### ISSUE TITLE
Morrrrre Live Examples

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vuejs.org#1]
JSFiddle links / PRs welcome.

**Comment by lepture** [comment]
The whole site is built with vue: https://python-china.org/

![python-china](https://cloud.githubusercontent.com/assets/290496/9175773/0992f308-3fba-11e5-8d9f-cc9b1c03016e.png)

**Comment by yyx990803** [comment]
@lepture wow 帅气！

**Comment by chrisvfritz** [comment]
Closing for now, since this thread has been inactive for over a year. 😃  We have added quite a few live examples since then, especially in the 2.0 docs!
