### ISSUE TITLE
What is a Vue answer to Fiber (new React reconciliation algorithm)?

### ISSUE THREAD

**Issue by slipdef** [vuejs/vuejs.org#1022]
https://github.com/acdlite/react-fiber-architecture

**Comment by LinusBorg** [comment]
We ar not working on anything like this, and personally I don't have a specific opinion about Fiber yet.

It seems like a great concept though.

WIll close this issue, because this is not related to the website.

If you want to discuss this, I suggest visiting forum.vuejs.org or chat.vuejs.org
