### ISSUE TITLE
Spanish Traslation "work-in-progress"

### ISSUE THREAD

**Issue by IsraelOrtuno** [vuejs/vuejs.org#1023]
We are using CrowdIn for the Spanish translation, which is a localisation management software and makes the translation versioning a breeze.

It can be found here: https://crowdin.com/project/vuejs/es-ES#

Project is actually translated to 14% and more work will be done in the upcoming weeks as I got some spare time.

Feel free to create a new profile and request access to the project!

cc @posva

**Comment by posva** [comment]
Hey, thanks for the initiative Israel, but there's already a team working on it #308 (https://github.com/vuejs-es/vuejs.org)
I suggest you join forces. I think they need reviewers. I don't know if it's finished but feel free to ping me or @chrisvfritz when it is, so we can add it to the list of translations
