### ISSUE TITLE
icons on forum.vuejs.org are not loaded properly

### ISSUE THREAD

**Issue by jkzing** [vuejs/vuejs.org#1029]
Sorry, I don't know where to put this issue because I cannot find the forum repo, maybe it's not public.

It seems the font icon of forum website is not being loaded properly, like:
![image](https://user-images.githubusercontent.com/2851517/28298682-46229a88-6ba7-11e7-9759-641bdf742344.png)

And, did a quick look in devtool, it may be caused by a not allowed CORS request for `fontawesome` icon file:
![image](https://user-images.githubusercontent.com/2851517/28298709-6db04fa0-6ba7-11e7-964d-bf90139e80dc.png)

And my chrome and platform version is here if it could help:
![image](https://user-images.githubusercontent.com/2851517/28298722-80050966-6ba7-11e7-8ce4-feef23dfb79e.png)

**Comment by chrisvfritz** [comment]
I can duplicate this on my end and am investigating. 🤔  Strangely, I'm not seeing duplicate headers with:

```
curl -Is https://forum.vuejs.org/ | grep Access-Control-Allow-Origin
```

**Comment by chrisvfritz** [comment]
Woohoo, I fixed it! 😄  🚀  🤜 💥 🤛  🎉  🥇

**Comment by jkzing** [comment]
@chrisvfritz Awesome! Thanks!🎉
