### ISSUE TITLE
A question about wrapper component example（vm.$emit('input', this.value)）

### ISSUE THREAD

**Issue by gemmi** [vuejs/vuejs.org#1030]
When a child component emit an event up to parent, there always be a  method or function called by parent component, but i can't find callback function "input" in the code section when select2 changes:
```
...
vm.$emit('input', this.value)
...
var vm = new Vue({
  el: '#el',
  template: '#demo-template',
  data: {
    selected: 2,
    options: [
      { id: 1, text: 'Hello' },
      { id: 2, text: 'World' }
    ]
  }
});
```
[source code](https://jsfiddle.net/fruqrvdL/456/?utm_source=website&utm_medium=embed&utm_campaign=fruqrvdL)
So why the event 'input' can be captured by 'vm'?  Is there any magic function called conventionally inside Vue?

**Comment by chrisvfritz** [comment]
This sounds more like a usage question, rather than an item about the docs specifically, so I'll refer you to the either [the forum](http://forum.vuejs.org/) or [the chat](https://chat.vuejs.org/).
