### ISSUE TITLE
"None of that would be possible with a computed property." Why? 

### ISSUE THREAD

**Issue by komali2** [vuejs/vuejs.org#1032]
In the Computed Page [docs](https://vuejs.org/v2/guide/computed.html) [github](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/computed.md), there is the following sentence at the end of the page: 

> In this case, using the watch option allows us to perform an asynchronous operation (accessing an API), limit how often we perform that operation, and set intermediary states until we get a final answer. None of that would be possible with a computed property.

Why is none of this possible with a computed property? I'm still learning vue so perhaps the answer will become clear later, but it remains unclear to me the difference between computed properties, and methods that set properties (and are called off watch functions).

**Comment by nickmessing** [comment]
@komali2, please use official [chat](http://chat.vuejs.org/) or [forum](https://forum.vuejs.org) to ask questions. Short answer is: `getters` **should** always `return` a value so they are synchronous, if you need to do some asynchronous stuff (like http request) and then use the result - getters cannot do that.

**Comment by gustojs** [comment]
As for "why" - because computed properties (and getters) return cached values.
