### ISSUE TITLE
Modal Component Example warning

### ISSUE THREAD

**Issue by puuridee-david** [vuejs/vuejs.org#1035]
Modal Component Example gives a warning by default.

```[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "showModal"```

**Comment by chrisvfritz** [comment]
Are you referring to [this example](https://vuejs.org/v2/examples/modal.html)? I'm not seeing an error there and `showModal` isn't passed as a prop.

**Comment by puuridee-david** [comment]
Had a wrong implementation; linked example is indeed working fine.
