### ISSUE TITLE
Menu translation links should direct to a related anchor of chosen translation. 

### ISSUE THREAD

**Issue by Piterden** [vuejs/vuejs.org#1037]
If be honest, I not thought I would notice somebody about it...

At least in API part hashes are similar, but I think there should be a system, which solves such of problem like translation key, or so...

I tried to make a PR, but sorry guys: https://github.com/vuejs/vuejs.org/blob/master/themes/vue/source/js/common.js

Is it possible to rewrite that ^ to vue.js? Did you hear about this framework? :)

Btw, Nuxt don't have this problem:
![image](https://user-images.githubusercontent.com/5930429/28489000-61a2c8fc-6ec0-11e7-9eeb-188dc6240474.png)

**Comment by chrisvfritz** [comment]
Great idea! Done. 🙂

**Comment by Piterden** [comment]
Man, you rock :+1: 
Thanks.
