### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by AndreyKozlovTomsk** [vuejs/vuejs.org#1040]
Ошибка, пропущена буква "х" - http://joxi.ru/Q2KGG3xT94ED12

этиХ

:)

**Comment by Alex-Sokolov** [comment]
Исправил в https://github.com/translation-gang/ru.vuejs.org/pull/199
Опубликую обновления вечером

**Comment by chrisvfritz** [comment]
It looks like this is fixed, so closing. 🙂
