### ISSUE TITLE
Directive hooks

### ISSUE THREAD

**Issue by mbraint** [vuejs/vuejs.org#1044]
**Case:**
When I create custom directives, I thinked that 'update' and 'componentUpdated' hooks of directive will be  call when component or children updated, but the hooks works only when updated vnode. I think will be useful add this informaition to docs.

**Actually  desctiption:**
[#Hook-Functions](https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions)
'update: called after the containing component has updated'
'componentUpdated: called after the containing component and its children have updated.'

**Expected desctiption:**
'update: called after _vnode_ of the containing component has updated'
'componentUpdated: called after _vnode_ of the containing component and _vnodes_ of his children have updated.'

**Comment by chrisvfritz** [comment]
Good idea. Just updated! 🙂

**Comment by mbraint** [comment]
Thanks)
