### ISSUE TITLE
Hebrew translation  

### ISSUE THREAD

**Issue by rakef** [vuejs/vuejs.org#1046]
Hi,

We're starting to translate the website into Hebrew here:
https://github.com/misterBIT/vuejs.org

Anyone who wants to join is very welcome :)

**Comment by chrisvfritz** [comment]
@rakef Fantastic! Let me know if you have any questions I can help with. 🙂

**Comment by rakef** [comment]
Thank you, @chrisvfritz  :)

Actually, there is a problem in the direction of the text.  Hebrew is an RTL language, but it seems as if MD only supports LTR.

I tried wrapping a paragraph and giving it direction. It did change the direction, but also caused the loss of MD styling.

**Comment by chrisvfritz** [comment]
Hmm, there's [someone here](https://github.com/hamecoded/oded-hexo/commit/3a5e047aca36bb046127347815006e1efbd8aaf1) who seems to have made hexo work with Hebrew and he's using the same markdown renderer as us. Is there anything there that helps?

**Comment by rakef** [comment]
Great, thank you, I'll try it 🌝

**Comment by rakef** [comment]
@chrisvfritz , thank you for the link. Unfortunately, it did't help :\  
We've decided to just keep on translating, hoping the solution will be found during the translation or  after it's completed.

**Comment by chrisvfritz** [comment]
@rakef Is it just the text editor that doesn't render the markdown correctly, or is it not being parsed correctly in hexo?

**Comment by rakef** [comment]
@chrisvfritz good news! We've got it! 💃

**Comment by eyalcohen4** [comment]
Hey @rakef, How can I help?
Do we have a list of what is already translated?

**Comment by rakef** [comment]
hi @eyalcohen4 and thank you!

could you please contact us on or@misterbit.co.il?

**Comment by phanan** [comment]
I'm closing this topic as an effort to tidy our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
