### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by MrZxSiye** [vuejs/vuejs.org#1049]
为什么我们react在实现组件化的过程中，我们的子组件模板可以嵌套在父组件中，而我们的vue必须在实例化的过程中定义childComponents

**Comment by chrisvfritz** [comment]
@MrZxSiye I'm sorry, I'm not able to understand this one with Google translate. 😕  @Jinjiang Can you help?

**Comment by Jinjiang** [comment]
Well this question is the different usage with react about sub components in template/render-function.

> In React we can directly use sub component names in `render()` function but in Vue we need to explicitly declare them in `components`.

**Comment by MrZxSiye** [comment]
我知道的这两个不同的实例化的方式，但是他们这么不同的设计的原理是什么。 vue中父组件中声明子组件的原理和有关的生命周期

**Comment by Jinjiang** [comment]
So your suggestion is telling the different design principles behind components system in comparisons guide. Right?

**Comment by nickmessing** [comment]
@Jinjiang, that's difference between JSX and vue templates. We can't compare all aspects, we try to compare only the libraries afaik.

**Comment by Jinjiang** [comment]
@nickmessing agree.

@MrZxSiye 组件相关的介绍有[单独的页面](https://cn.vuejs.org/v2/guide/components.html)可以查阅，可以通过这里了解和体会其中的设计理念。原理更多是框架实现层面的东西，有兴趣的话可以阅读我们的源码🤝
