### ISSUE TITLE
A printable version of API Reference/Guide?

### ISSUE THREAD

**Issue by hanfeisun** [vuejs/vuejs.org#105]
The current API reference and guide is nice. It would be great if they can be printed. 

Is it possible to export all the documents into a single PDF or HTML file to make it printable?

**Comment by hanfeisun** [comment]
This issue seems a little similar to  https://github.com/vuejs/vuejs.org/issues/38, but with different purpose.

As the documents is written in Markdown, maybe this tool (https://www.npmjs.com/package/markdown-pdf) could be used to compile Markdown files into a single PDF.

**Comment by yyx990803** [comment]
You can contribute a script to do this :)

**Comment by oleynikd** [comment]
Save the trees! Use one of dozen of your screens ;)

**Comment by yyx990803** [comment]
1.0 API reference is now in one page: http://rc.vuejs.org/api/
