### ISSUE TITLE
Filter scope

### ISSUE THREAD

**Issue by darrylhein** [vuejs/vuejs.org#1052]
In attempting to create my first filter, I had to hunt around the internet to figure out how to make a filter that was available in more than 1 component (I wanted component and children). I'm thinking this is correct: filters are only available in the component they're added to and not their children, but global filters can be added using `Vue.filter(...)`.

Let me know if you'd like me to make an attempt at adding this to the docs.

**Comment by chrisvfritz** [comment]
I think we already describe this behavior in the API for [`Vue.filter`](https://vuejs.org/v2/api/#Vue-filter) and the [`filters` option](https://vuejs.org/v2/api/#filters). Let me know if I've misunderstood what you mean though.

**Comment by darrylhein** [comment]
The problem I had was that I searched for "filters" on the Vue site and ended up on [this page](https://vuejs.org/v2/guide/syntax.html#Filters) which has no mention of where filters are available nor the global API.

**Comment by chrisvfritz** [comment]
This should be fixed soon. Since Filters aren't really an "Essential" feature, I'm thinking of consolidating all the info here into the API.

**Comment by sdras** [comment]
Filters have a dedicated page [here](https://vuejs.org/v2/guide/filters.html), as well as a place in the [API](https://vuejs.org/v2/api/#Vue-filter). Is this issue solved?

**Comment by chrisvfritz** [comment]
Yes, good catch. 🙂
