### ISSUE TITLE
Questions about Example Markdown Editor

### ISSUE THREAD

**Issue by caoxiaoshuai1** [vuejs/vuejs.org#1068]
In this example , '_' and marked is node defined, is there some other code needed first?

https://vuejs.org/v2/examples/index.html

**Comment by Jinjiang** [comment]
Yes, if you click the "Edit in JSFiddle" link ( https://jsfiddle.net/chrisvfritz/rdjjpc7a/ ), you can find them in "External Resources" in the sidebar.
