### ISSUE TITLE
HTTPS is not forced

### ISSUE THREAD

**Issue by wesdawg** [vuejs/vuejs.org#1073]
#### To reproduce:
In a clean browsing session on Chrome or Firefox, visit http://vuejs.org/ , http://vuejs.org/js/vue.min.js

TLS connection is not forced.

**Comment by chrisvfritz** [comment]
@wesdawg Hmm, I'm unable to reproduce this in the latest Chrome or Firefox on macOS Sierra. 😕  @atomaka Do you have any ideas/questions?

**Comment by atomaka** [comment]
I can replicate this and will look into it.

**Comment by atomaka** [comment]
@wesdawg Can you validate that TLS is now forced?

**Comment by wesdawg** [comment]
Yes, it seems to be fixed.

Thanks,
