### ISSUE TITLE
Modify the examples in the Introduction

### ISSUE THREAD

**Issue by wudb1993** [vuejs/vuejs.org#1076]
In the Introduction,the example of binding element attributes is not appropriate .
  var app2 = new Vue({
  el: '#app-2',
  data: {
    message: 'You loaded this page on ' + new Date()
  }
})

Here are my suggestions 

  var app2 = new Vue({
  el: '#app-2',
  data: {
    message: 'You loaded this page on ' + new Date().toLocaleString()
  }
})

I think that it fits most people's reading habits.what do you think of it?

**Comment by chrisvfritz** [comment]
@wudb1993 I'm fine with that if you'd like to make a pull request. 🙂

**Comment by chrisvfritz** [comment]
Resolved in #1077.

**Comment by greatgraphicdesign** [comment]
I have just tried this example in my browser, and I'm getting this message from Chrome 81 (Mac)...

`Uncaught TypeError: (intermediate value).tolocaleString is not a function`
