### ISSUE TITLE
Suggest to add a HTML div tag

### ISSUE THREAD

**Issue by CHWJ** [vuejs/vuejs.org#1080]
When I reading [Checkbox](https://vuejs.org/v2/guide/forms.html#Checkbox) chapter,I test it the example called "Multiple checkboxes".But it doesn't work.It looks like the following:
![image](https://user-images.githubusercontent.com/2307260/29308477-917a37ce-81d8-11e7-8656-85efb9e2dbe3.png)
So it is used to compare with the webpage source code,the difference is highlighting:
![image](https://user-images.githubusercontent.com/2307260/29308708-6877d22c-81d9-11e7-9f4d-c648c46802a3.png)
I only see "..." in the example,it makes me confused.So I suggest to add a HTML div tag.
PS:  Forgive me for my poor English.:blush:

**Comment by chrisvfritz** [comment]
The English was very good! I'll make the change soon. 🙂

**Comment by AllanOcelot** [comment]
@chrisvfritz was this included with #1086  ?

**Comment by chrisvfritz** [comment]
No, I still haven't gotten to it, but would accept a separate PR if someone wants to beat me to it. 😉

**Comment by AllanOcelot** [comment]
Hi @chrisvfritz Sadly I just tried to do a PR for this and keep getting a 403 :(

**Comment by sdras** [comment]
This looks like it's been merged, closing it out. Feel free to reopen if I'm mistaken :)
