### ISSUE TITLE
Separate search page

### ISSUE THREAD

**Issue by andreasvirkus** [vuejs/vuejs.org#1087]
Greetings!

I'd like to see a separate search page so we could add Vue.js' docs as a bang to duckduckgo.
The duck's bang requires a bang url, e.g. `https://vuejs.org/?q={{{s}}}`.

That way Vue's docs would be easily searchable with (for example) `!vue v-once`.

I could make a PR for this as well, would just like to know how you'd like this implemented
(I see we use Algolia's docsearch as the autocomplete wrapper).

**Comment by chrisvfritz** [comment]
I'd accept a PR for a dedicated search page. How about at `/v2/search`?

**Comment by chrisvfritz** [comment]
I'm going to close this since there doesn't seem to be much interest. Happy to reopen in the future. 🙂

**Comment by NoelDeMartin** [comment]
@andreasvirkus @chrisvfritz Hey just letting you know that duck duck go accepted the bang! so you can now search using it, for example "v-model !vue" and it'll take you to the vue docs :).
