### ISSUE TITLE
Demo in Website not working for 2.x version

### ISSUE THREAD

**Issue by Conrekatsu** [vuejs/vuejs.org#1089]

**Comment by chrisvfritz** [comment]
Can you be more specific, please? Which demo on which page?

**Comment by Conrekatsu** [comment]
https://vuejs.org/v2/examples/

all examples here are not working. but the lower versions are working.
I'm using google chrome.

**Comment by chrisvfritz** [comment]
Unfortunately, I'm not able to reproduce this. 😕  Using the latest version of Chrome on macOS, all the demos are working for me. Are you seeing any errors in the JavaScript console?

**Comment by kevinashworth** [comment]
Privacy Badger settings, or other Chrome extensions, could be the reason.

**Comment by Conrekatsu** [comment]
adblocker was the culprit..
