### ISSUE TITLE
Word error in page

### ISSUE THREAD

**Issue by cherubic** [vuejs/vuejs.org#1093]
in "/src/v2/guide/syntax.md" file, I think in the sentence below that under "**Attributes**" heading have a word error,The last second words "**falsy**" should be "falsely" or "false"?
> It also works for boolean attributes - the attribute will be removed if the condition evaluates to a falsy value

**Comment by LinusBorg** [comment]
https://developer.mozilla.org/en-US/docs/Glossary/Falsy
