### ISSUE TITLE
Improve docs for v-for with v-if 

### ISSUE THREAD

**Issue by hitautodestruct** [vuejs/vuejs.org#1108]
There seems to be a new vue warning when using `v-for` and `v-if` together on the same element.

Alas, it seems that the docs don't mention this warning and instead give a usage example of what is deemed by the warning as a "bad pattern" see [this page](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/list.md#v-for-with-v-if) for v-for with v-if.

It would be a good idea to point this out in the docs as well as give the warning and show an example of alternatives.

**Comment by chrisvfritz** [comment]
@hitautodestruct I'm [not seeing](https://jsfiddle.net/chrisvfritz/kjc12jaw/) the warning you're referring to. Can you demo it in a fiddle please?

**Comment by AllanOcelot** [comment]
Is this an issue, in what instance would a user be checking for and if?, surly it's one or the other?

**Comment by chrisvfritz** [comment]
@AllanOcelot You can use it to render only _some_ items in the `v-for`. It's a similar result to using a computed property to filter an array.

**Comment by AllanOcelot** [comment]
ahh got it @chrisvfritz , cheers, I'm still learning :)

**Comment by hitautodestruct** [comment]
@chrisvfritz Alas, it seems that I can not reproduce the error. I think this may be coming from an external package but I can't seem to find the source of the `[Vue Warn]` message.

For now I'm closing this issue.

Thanks for you time!
