### ISSUE TITLE
It seems to be an error in Vue instance's lifecycle diagram

### ISSUE THREAD

**Issue by leonisme** [vuejs/vuejs.org#1114]
In the lifecycle diagram, Vue created vm.$el and replace "el" with it after beforeMount hook, but in code Vue created vm.$el before beforeMount hook.

**Comment by yyx990803** [comment]
The diagram is correct. `$el` only exists before `beforeMount` if you are mounting to an existing node, but if mounting with a template or render fn, the DOM generation and replacement happens after `beforeMount`.

**Comment by leonisme** [comment]
I agree with what you said. But `el` refers to the existing DOM element to mount on and `$el` is replaced with the generated DOM after `beforeMount`, so I think using `created vm.$el and replace generated DOM with it` can be better.
