### ISSUE TITLE
Scoped slot

### ISSUE THREAD

**Issue by shinecorner** [vuejs/vuejs.org#1119]
About scoped slots:
please read this line in doc.

> A more typical use case for scoped slots would be a list component that allows the component consumer to customize how each item in the list should be rendered:

So inspired on above line I have create an example that try to allow consumer to customize how child data is listed. I use list-style. but as per your above comment I can also customize it to html table format.

Now suppose in list-style I am facing one issue. can you please suggest on it. check below code.

> <div id="my-example">
    <ul>
        <child-component :pass-items="itemList">
            <template slot="myItemSlot" scope="mscopevars">
                <li>{{mscopevars.currentitem}}</li>
            </template>        
        </child-component>
    </ul>
</div>

> `<script type="text/javascript">
Vue.component('child-component', {
    template: "<p><slot name='myItemSlot' v-for='item in passItems' :currentitem='item'></slot></p>",
    props: ["passItems"]
});
var vm = new Vue({
    el: '#my-example',
    data: {
        itemList: ['banana', 'orange', 'mango']
    }
});
</script>`

Here output of this example contain a p tag inside ul tag. this is because I have add p tag in component template. But I have no scope to render template without any parent tag or I can not just put only slot tag in above template. I must have to wrapper it with some tag so I put p tag. but basically it wrong to have p tag inside ul tag right? it must be li tag. so what is the proper solution for it?

**Comment by chrisvfritz** [comment]
For usage questions like this, I recommend posting your question on either [the forum](https://forum.vuejs.org/) or [Discourse chat](https://chat.vuejs.org/). We try to reserve issues for bugs and feature requests. To get you started on the right track though, check out the [`is` attribute](https://vuejs.org/v2/api/#is).

**Comment by shinecorner** [comment]
Hi Chris,
I already know about "is" attribute. but for above example "is" attribute not fit. I already have <child-component> tag that is used to pass itemList. so I can not define another component to <li> tag using is attribute.

Or can you please give me modified version of above example using "is" attribute?
Thanks for your reply.
