### ISSUE TITLE
Revise language that assumes ease ('simply', 'obviously', etc.)

### ISSUE THREAD

**Issue by robwierzbowski** [vuejs/vuejs.org#1120]
Vue **is** more easy, simple, and fun to use than other reactive frameworks 🎆.

But pointing out how 'simple', 'obvious', or 'easy' something is can have the opposite-of-intended effect. If a person doesn't understand the 'simple' code, the project can seem inaccessible. "If I don't understand this, what chance do I have to understand the rest?" There are plenty of articles on this effect, and I've observed it personally when working with junior co-workers.

To make the Vue documentation more friendly, I'd like to remove/revise some words that assume ease from the docs. Here's a list of potentially problematic words: https://css-tricks.com/words-avoid-educational-writing/. I can find more reference articles if you'd like. 

In most cases removing the word in question makes a sentence flow better; in some cases replacing the word with a more explicit one is a good option ('simple module' with 'small module', for example).

Would you be interested in a PR that revises one or two pages? If it looks good I could continue with the rest of the site.

**Comment by chrisvfritz** [comment]
@robwierzbowski That sounds great. PR more than welcome! 👍

**Comment by robwierzbowski** [comment]
All right! I'll give it a shot.

**Comment by wujekbogdan** [comment]
@robwierzbowski 
Obviously, you're right. Let's just remove these additional words as they don't add any value. However, everyone knows that a PR would be welcome. So, basically, make a PR and it will be merged. Easy!
