### ISSUE TITLE
js报错异常

### ISSUE THREAD

**Issue by TonyXY** [vuejs/vuejs.org#1132]
var xl;
alert(xl.length);
如上面的语句在vue 里面（vue2.0，vue-cli）不报错，后面的语句也不执行.
导致排查错误困难。

**Comment by Jinjiang** [comment]
看上去这不是针对网站或文档的讨论，建议去[聊天室](https://chat.vuejs.org/)、[论坛](https://forum.vuejs.org/)或各大技术社区讨论。
谢谢
