### ISSUE TITLE
Production mode is off in the documentation

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vuejs.org#1140]
On the guide (see [here](https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots) for instance), Vue production mode has not been activated, you can see that warning:
```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

**Comment by yyx990803** [comment]
This is intended, because we want to allow users to play with the devtool.

**Comment by AlexandreBonneau** [comment]
Ok but then why not just hide that noisy tip using `Vue.config.productionTip = false`?
This won't prevent the devtool right?

cf. [relevant documentation](https://vuejs.org/v2/api/#productionTip)

**Comment by chrisvfritz** [comment]
That'd be fine with me. 🙂 PR welcome!

**Comment by AlexandreBonneau** [comment]
I *would* create a PR if only I knew where the Vue initialization scripts were! :)
