### ISSUE TITLE
Brief info about how to deploy on server

### ISSUE THREAD

**Issue by FrancescoMussi** [vuejs/vuejs.org#1141]
What do you think about including a small but visible paragraph in the docs about how to deploy a stand-alone vue app on the server?

I passed two long days crashing my head against the monitor, looking disconsolate at the blank page online, looking for a solution everywhere, until I found something in a remote forum forgotten by God that said that I had to upload on the server only the content of the `/dist` folder.

And magically everything worked.

I checked again the docs to find where it is mentioned but I could not find it.

What do you think about making a paragraph where it is stated clearly how to deploy a stand-alone Vue app to the server?

It would save quite some time I think.

**Comment by chrisvfritz** [comment]
This isn't specific to Vue itself, but rather the template you're using, so those docs will be the best place for an update.

I really enjoyed the poetic description of your plight though! 😄
