### ISSUE TITLE
Styleguide: multiple style blocks

### ISSUE THREAD

**Issue by Christilut** [vuejs/vuejs.org#1150]
I didn't see anything about this in the styleguide so I wanted to ask.

I sometimes use 2 style blocks in my .vue components, one with `scoped` and one without.

The reason for this is that sometimes you need to include a third party library that dynamically alters the DOM which the `scoped` style has no access to. 
So I give my template a specific class (sometimes like `component-tooltip`) which is sure not to conflict with any libraries or my other components and reference that class name in the global style block.

Simplified example:
```
<template>
<div class="component-tooltip">
  <thirdparty-library></thirdparty-library>
</div>
</template>

<script>
// omitted
</script>

<style scoped>
 // scoped css, no classname needed
</style>

<style>
.component-tooltip {
  .thirdparty-library {
    // do stuff here that is specific to this component
  }
}
</style>
```

The styleguide says:
> For applications, styles in a top-level App component and in layout components may be global, but all other components should always be scoped.

But if a third party library is fully encapsulated by my custom component, I don't really want to split up this styling. Especially not if it is very little code. 

What do other people think about this?

**Comment by chrisvfritz** [comment]
In these cases, you can use either a [deep selector with `scoped`](https://vue-loader.vuejs.org/en/features/scoped-css.html#deep-selectors):

``` html
<style scoped>
.tooltip >>> .thirdparty-library {
  // ...
}
</style>
```

Or [`:global`](https://github.com/css-modules/css-modules#exceptions) with a [CSS module](https://vue-loader.vuejs.org/en/features/css-modules.html):

``` html
<style module>
.tooltip :global(.thirdparty-library) {
  // ...
}
</style>
```

I'll add notes about these strategies in the detailed explanation for this rule. 👍

**Comment by Christilut** [comment]
Woah, I didn't know about the deep selector. Mind blown!

Guess I'll be using that, should fix all my problems :)

**Comment by aghArdeshir** [comment]
Thanks 👍 I didn't know about that deep selector. It's for sure a cool thing.

But still, it does not solve the problem mentioned in the "tooltip" case. If the tooltips are attached to the end of the body (rather than the element), could it be a best practice to have two different `style` blocks in one SFC? one `scoped` and one non-scoped?
