### ISSUE TITLE
Style Guide: Keyed v-for (question)

### ISSUE THREAD

**Issue by dannyrb** [vuejs/vuejs.org#1161]
In instances when a good unique key does not exist for what you're iterating over, is:

```
<li
    v-for="(item, index) in items"
    :key="index"
  >
```

Considered good or bad practice?

**Comment by Akryum** [comment]
Yes, but you should ideally find a way to add a unique key on the items.

**Comment by chrisvfritz** [comment]
Great question! I'd like to add that using the index can cause some serious performance issues. For example, let's say the first item in the array is removed. if you use an index, Vue will assume the _last_ element was removed and update every remaining element as it shifts everything down, thinking they've _all_ changed. So you get the worst possible performance. 😢 

@dannyrb Does that make sense? And do you think it would be helpful to add more information in the description for the rule?

**Comment by dannyrb** [comment]
@chrisvfritz thanks for the extra information! 

It might be worth adding a small note in the "Detailed Explanation". I've used `index` as a key when an object does not have a clear property to use as a unique identifier (it feels like a natural fallback). I still like the suggested best practice, but its good to know in which situations `index` works (and doesn't work) well. My only hesitation is that the extra information muddies the currently "clear cut" rule. 

My guess would be that Vue would use `index` under the hood when no `:key` is specified? But I have no idea (and now I'm curious).

**Comment by chrisvfritz** [comment]
Another great question. 🙂  By default, Vue will simply optimize render efficiency, making the least expensive mutations possible to get the DOM up-to-date with the new state.

**Comment by chrisvfritz** [comment]
This has been addressed now. 👍
