### ISSUE TITLE
You're not good at memes

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vuejs.org#1163]
You are using the ["Not sure if X or just Y" image from Futurama](http://knowyourmeme.com/memes/futurama-fry-not-sure-if) as a stand in for "evil eye", which makes no sense at all.

Here are suitable replacements that make sense in context:

> "but other developers may give you the evil eye at conferences."

* https://i.giphy.com/7Heb8yPKfxS9i.gif
* https://i.imgur.com/aEtHUJL.gif
* https://i.giphy.com/n60aPuXZLJNiU.gif
* https://i.giphy.com/GjR6RPcURgiL6.gif

**Comment by chrisvfritz** [comment]
The original context in the show has nothing to do with "not sure if" so I think it's fine. 😉

**Comment by TheJaredWilcurt** [comment]
Okay, so you're wrong on every account. I'm trying to help here. I've even provided multiple alternatives.

1. The context in the original show [is shown here](https://www.youtube.com/watch?v=Wc4RFtZ-bXU

**Comment by TheJaredWilcurt** [comment]
Okay, so you're wrong on every account. I'm trying to help here. I've even provided multiple alternatives.

The context in the original show [is shown here](https://www.youtube.com/watch?v=Wc4RFtZ-bXU). As seen in the episode, the still was taken from, this image, in both it's original context and it's more well known internet form, have always been used to show **skepticisim**, not disgust/anger/contempt.

The meme version of it has been seen more than the original version of it, so much so that [the show *itself* referenced the "Not sure if..." meme](http://i0.kym-cdn.com/photos/images/original/000/334/418/041.gif). Meaning, although *both* versions represent skepticism, the version more associated with uncertainty is the predominate interpretation associated with it.

There has **never** been a usage or association of this imagery used in a context where it would make sense with the phrase "evil eye".

Pick an alternative, or remove the image altogether, I don't care, just stop misusing internet culture.
