### ISSUE TITLE
Inconsistency in set documentation.

### ISSUE THREAD

**Issue by waratah** [vuejs/vuejs.org#1172]
https://vuejs.org/2016/02/06/common-gotchas/
    https://vuejs.org/v2/guide/list.html#Array-Change-Detection

In common gotchas is says:  

Vue provides a convenience method arr.$set(index, value) which is syntax sugar for arr.splice(index, 1, value).

In the List page is says:

// Vue.set
Vue.set(example1.items, indexOfItem, newValue)

More importantly the second version works easily for Typescript type checking.

Can we include the Vue.set in the common gotchas page / or replace it.

**Comment by chrisvfritz** [comment]
The first link you referenced is not actually documentation, but a blog post from more than a year and a half ago, before Vue 2 was released. The API it references is not available in Vue 2.

**Comment by waratah** [comment]
@chrisvfritz I was looking around the documentation.   I really like the gotchas element of the blog documentation.  This was very helpful to me and other newbies to tell about what to watch out for, with array  details being in the middle of the list page (I would not have looked a that page otherwise.

I did try and figure out a better solution to the problem however it is not obvious to me.  Agree this should be closed.,
