### ISSUE TITLE
Enhancement idea: style guide as eslint rules

### ISSUE THREAD

**Issue by ijdickinson** [vuejs/vuejs.org#1175]
I'm just putting this out there as an idea: there are some really helpful suggestions in the [style guide](https://vuejs.org/v2/style-guide/index.html) for writing better Vue code. It would be great if these could be codified as an [eslint](https://eslint.org/) plugin.

**Comment by chrisvfritz** [comment]
Way ahead of you. 😄  The plugin is [in development](https://github.com/vuejs/eslint-plugin-vue#eslint-plugin-vue), hopefully to be released mid to late October when we remove the beta tag from the style guide.

**Comment by ijdickinson** [comment]
Excellent news - look forwards to trying it out!
