### ISSUE TITLE
Site broken, returns 404

### ISSUE THREAD

**Issue by peterhellberg** [vuejs/vuejs.org#1189]
https://vuejs.org/ currently doesn't work

<img width="616" alt="screen shot 2017-10-06 at 16 00 21" src="https://user-images.githubusercontent.com/565124/31281380-8ca222a2-aaaf-11e7-9a4b-7a9b5531d570.png">

**Comment by andreclemente** [comment]
Same here.

**Comment by holmberd** [comment]
yep.

**Comment by peterhellberg** [comment]
Seems to have been fixed now.
