### ISSUE TITLE
Style Guide: maybe problems in `Component name casing in JS/JSX`

### ISSUE THREAD

**Issue by wonderful-panda** [vuejs/vuejs.org#1194]
In `Component name casing in JS/JSX ` section:
https://github.com/vuejs/vuejs.org/blame/5756ffaa0de85303064b380b9ab56a9820783b8d/src/v2/style-guide/index.md#L916

```
- These applications always include many in-DOM components, where kebab-case [**must** be used](#Component-name-casing-in-templates).
```

1. I guess `in-DOM components` should be `in-DOM templates`. Right?
2. `#Component-name-casing-in-templates` is invalid anchor.
 `#Component-name-casing-in-templates-strongly-recommended` is valid.

**Comment by chrisvfritz** [comment]
Thanks! I just fixed both of these. 🙂
