### ISSUE TITLE
Guide: About "Tightly coupled component names"

### ISSUE THREAD

**Issue by ktquez** [vuejs/vuejs.org#1195]
Firstly, I need to thank you for this guide and congratulate you for this incredible teamwork.

About the "Tightly coupled component names"
```
components/
|- TodoList.vue
|- TodoListItem.vue
|- TodoListItemButton.vue
```

Would it also be good practice to structure this way?

```
components/
|- TodoList/index.vue
|- TodoList/Item.vue
|- TodoList/ItemButton.vue
```

Per-directory by reducing the number of components in the "components" directory.

Thanks,

**Comment by chrisvfritz** [comment]
Great question! I just pushed up an edit to address it. 🙂  I'd love to hear your thoughts.
