### ISSUE TITLE
Strong disagreement with Prop Name Casing

### ISSUE THREAD

**Issue by brianboyko** [vuejs/vuejs.org#1200]
Current: 

`Prop names should always use camelCase during declaration, but kebab-case in templates and JSX.`

Proposed: 

`Prop names should always use the same case both in declaration and in templates and JSX, either both camelCase or snake_case`

Reasoning: 

One of the big problems I'm having debugging this legacy Vue.js app we got from our outsourced team is that there are many, *many* instances of related items changing as it moves from template to component, and vice versa. 

One way to debug a file is to simply search where a particular prop, component, or method is being used - by forcing users to change the case from camelCase to kebab-case, it becomes impossible to search for. 

Additionally, hyphens cannot be used in JS variables, which forces you to refer to props like this: 
` this["kebab-case"] `

instead of 

`this.camelCase`

or 

`this.snake_case`

**Comment by chrisvfritz** [comment]
> forcing users to change the case from camelCase to kebab-case, it becomes impossible to search for

Quite the opposite is true actually. With our suggested conventions, you can search for props in any context you want:

- `myProp|my-prop` for references to a prop in _any_ context
- `myProp:` for only the prop definition
- `myProp([^:]|$) for only prop references
- `my-prop` for only prop passing

**Comment by chrisvfritz** [comment]
>  hyphens cannot be used in JS variables, which forces you to refer to props like this:
this["kebab-case"]

I think you might misunderstand here. If you're inside of an interpolation, binding, or directive value, you're back in JavaScript so would use camelCase.

**Comment by chrisvfritz** [comment]
@brianboyko Have I addressed your concerns? Is there a rewording that could make something more clear?

**Comment by sdras** [comment]
Closing this out because it's been unanswered for more than a month, feel free to reopen if there's more to discuss, though!
