### ISSUE TITLE
v-for="(todo, index) in todos"   not working in v-for with component exmaple

### ISSUE THREAD

**Issue by sm-ssntpl** [vuejs/vuejs.org#1207]
Here in the example of v-for with a component,   v-for loop is not working with two objects ie, todo and index.  While using two object fields, the text in list item is not getting displayed and only the list item with a button is being displayed. However if we use only one field ie v-for="todo in todos"   then the code runs properly and displays the prop field text as a list item.

Thus the code should be as below

[todo.txt](https://github.com/vuejs/vuejs.org/files/1374197/todo.txt)

**Comment by chrisvfritz** [comment]
It works properly on my end, so this sounds like a support question I recommend posting to the forum or chat.
