### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by 01abhishekjain** [vuejs/vuejs.org#1208]
https://vuejs.org/v2/guide/comparison.html#Performance

> In React, when a component’s state changes, it triggers the re-render of the entire component sub-tree, starting at that component as root.

Shouldn't this be "... starting at that **component's root.**" ?

**Comment by eddyerburgh** [comment]
I don't think so. 

If a child component's state changes, but a parent component's state does not change, the child component will re-render, while the parent component will not. 

Unless this has changed in 16?

**Comment by 01abhishekjain** [comment]
Not sure if it has changed, but seems like I misunderstood what that sentence meant.

Thanks for clarifying :)
