### ISSUE TITLE
The deprecation of `scope` prop should be addressed in guide

### ISSUE THREAD

**Issue by Justineo** [vuejs/vuejs.org#1223]
Since 2.5.0 we just replaced all `scope` with `slot-scope` in the guide, which may cause confusion among users. We should clearly address that `scope` is deprecated and `slot-scope` should be used instead.

**Comment by bison1994** [comment]
so efficiently. thanks

**Comment by BalGuldur** [comment]
Pls, write in documents info for users who don't update to 2.5.0 version. Becourse it's confusion users with Vue < 2.5, when they try implement slot-scope. 
Like "for Vue version < 2.5.0, use scope". 
Thx.

**Comment by chrisvfritz** [comment]
I agree. I'll try to get to this when I can, but a PR is welcome in the meantime.
