### ISSUE TITLE
Moving "Components" page into its own category

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vuejs.org#1230]
We are having more and more content in the component page, which itself is arguably one of the most important concept in the framework. However currently in the sidebar it only has a very low-profile link to the entire page. The page itself is also getting extremely long, making it difficult to navigate.

I think it's time that we break the page into multiple ones and make "Components" a category of its own. In the sidebar, we could have listing like below:

### Components
- Intro
- Props
- Events
- Slots
- Async
- Misc

For the new component composition page, I'm not entirely sure whether it should be included here or in the dedicated Reusability and Composition section. Thoughts?

**Comment by chrisvfritz** [comment]
Agreed - I plan to do this soon. I was thinking of keeping the components page, but changing it to more of an intro with only the basics of slots, props, and events. The reasoning is I still want to keep basic component usage in Essentials. 

Then all the more advanced content would be split between new pages in a new Advanced Components section (name TBD). The new component composition page would then be moved there.

How does that sound to you?

**Comment by yyx990803** [comment]
Sounds good!

**Comment by sdras** [comment]
This has been done for a while :)
