### ISSUE TITLE
Style Guide: Private property names rule

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vuejs.org#1231]
The `$_` prefix seems not suitable for mixin property naming as per  [doc](https://vuejs.org/v2/api/#data).
> Properties that start with `_` or `$` will not be proxied on the Vue instance

we **can't** access them with `this.$_myMixin_prop`.

**Comment by phanan** [comment]
Thanks for letting us know. I'm closing this ticket though, as it seems the problem has been addressed. If you think this is a mistake, please open another. Cheers!
