### ISSUE TITLE
Checkbox with v-model and v-on:click both attribute in the same control have different behaviors in IE and Chrome

### ISSUE THREAD

**Issue by ajajansari** [vuejs/vuejs.org#1233]
If you create a page with input type checkbox and have both the attribute as shown below, the behavior is different in IE and Chrome.

**Template**
<input type="checkbox" v-model="selected" v-on:click.stop="chkClicked()" />

**Method**
chkClicked:function(e){
    alert("State after click " +  this.selected);
    this.vResult += "<br/> checkbox clicked -" + this.selected;
}

By default I have kept **selected** as false, when you check in google chrome after check, it will return **false**, but in IE it will return **true**

For Demo, you can check the below fiddle.
https://jsfiddle.net/ajajansari/qzc3ury3/

**Comment by chrisvfritz** [comment]
Can you open this as a new issue on vuejs/vue? This repo is actually just for documentation.
