### ISSUE TITLE
Inaccuracy in Knockout comparison

### ISSUE THREAD

**Issue by n3ps** [vuejs/vuejs.org#1236]
For the addTodo function, it's unfair to say you need to capture the keyCode.

The correct approach is to wrap the textbox with a `<form data-bind="submit: addTodo">`. Then you wouldn't need to manually detect an "enter" keypress.

**Comment by phanan** [comment]
Thanks for letting us know. I can't seem to find the mentioned information though, so I'll go ahead and close this issue. If you think this is a mistake, feel free to open another. Cheers!

**Comment by n3ps** [comment]
I should've posted the link: https://vuejs.org/v2/guide/comparison.html#Knockout there's a reference to Chris' gist: https://gist.github.com/chrisvfritz/9e5f2d6826af00fcbace7be8f6dccb89
