### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by SteveALee** [vuejs/vuejs.org#1241]
First I'd like to say what an excellent comparison it is. I found it easy to read and highly informative.

My only minor quibble is that I feel a massive benefit of typescript is the excellent intellisense you get in editors such as VS code. 

This makes editing and error reduction much smoother and might even speed development. If only all JS libs provided typings or were written in TS.  :)

**Comment by chrisvfritz** [comment]
I agree that intellisense from type information is great. 🙂  What's the inaccuracy you noticed?

**Comment by SteveALee** [comment]
Apologies for lack of clarity. Not an innacurracy but a suggestion. I left the auto title unchanged.

Perhaps add intellisense to the advantages in 1st paragraph in typescript function.

In another note I did find a couple of assertions made in the text that said vue is better and which left me wondering what feature made that so. Sorry I can't recall details or find now with quick scan. I'd recall for one thinking perhaps because of the way you usr webpack.but I now see that is optional

Having now read the docs I love how you answer all the questions that came to mind. Like "why a DEL in templates". Vue has matured so much since I last looked. Then it eas just simple viees really. Am excited to start using I.

**Comment by chrisvfritz** [comment]
Ah, I see. TypeScript actually isn't necessary to take advantage of intellisense from type definitions, as VS Code makes them available for JavaScript as well. And either way, TypeScript can be used with Vue as well, so it's not really relevant to the comparison with other JavaScript frameworks.

Glad to hear you're enjoying Vue! 😄

**Comment by SteveALee** [comment]
Ok, np. 

But FYI code uses typescript for javascript and while tsc is awesome at type inference In JS it can only do so much unless you annotate your JS or use TS.

**Comment by LinusBorg** [comment]
Sure, but again: you can use Typescript with Vue, so we are not comparing Vue to Typescript - it's therefore not a topic to cover in that section of the guide.
