### ISSUE TITLE
Styleguide: Template / Options consistancy

### ISSUE THREAD

**Issue by Haeresis** [vuejs/vuejs.org#1246]
Hi @chrisvfritz.

In the Styleguide, the rules about options order said the correct order in a normal case is: 

```js
module.exports = {
    ...,
    data: function () {
        return {}
    },
    ...,
    template: `<div>
        <div></div>
    </div>`
}
```

but, the rules about top-level element order in SFC said:

> [Single-file components](../guide/single-file-components.html) should always order `template`, `script`, and `style` tags consistently, with `<style>` last.

So the way this sentence is written suggest that order:

```htm
<template>
    <div>
        <div></div>
    </div>
</template>

<script>
module.exports = {
    data: function () {
        return {}
    }
}
</script>
```

This is exactly the inverse of previous rules.

**So I suggest changing this sentence by:**

> [Single-file components](../guide/single-file-components.html) should always order `script`, `template`, and `style` tags consistently, with `<style>` last.

**and change good example order place:**

``` html
<!-- ComponentA.vue -->
<script>/* ... */</script>
<template>...</template>
<style>/* ... */</style>

<!-- ComponentB.vue -->
<script>/* ... */</script>
<template>...</template>
<style>/* ... */</style>
```

example before:

``` html
<!-- ComponentA.vue -->
<template>...</template>
<script>/* ... */</script>
<style>/* ... */</style>

<!-- ComponentB.vue -->
<template>...</template>
<script>/* ... */</script>
<style>/* ... */</style>
```

That not said the others order is not possible, but that bring consistency in rules

What is your thought? (Yeah I know is not a horrible problem, but if it's just little better, why not?)

**Comment by Haeresis** [comment]
I just read this

```
I go template -> style -> script
Because I often go back and forth between layout and styling
While the component definition itself rarely changes
```

**Comment by chrisvfritz** [comment]
Hm, I can see the logic here. You've convinced me. 😄 If you submit a PR to the Style Guide removing the part that recommends a specific order, it will be accepted.
