### ISSUE TITLE
Clarify "falsy" values

### ISSUE THREAD

**Issue by Justineo** [vuejs/vuejs.org#1250]
https://vuejs.org/v2/guide/syntax.html#Attributes

> It also works for boolean attributes - the attribute will be removed if the condition evaluates to a falsy value

In fact, binding an attribute to `0` or `NaN` won't result in removing the attribute. It's not a normal case but the doc should be more precise on this IMO.

via https://github.com/vuejs/cn.vuejs.org/issues/586

**Comment by chrisvfritz** [comment]
Interesting. I'm glad you brought this up, but I'm wondering if it's a documentation issue or a bug. @yyx990803 Is this intentional and if so, why the deviation?

**Comment by yyx990803** [comment]
Yeah we should be more precise here - it only removes the value if it is `null`, `undefined` or `false`: https://github.com/vuejs/vue/blob/dev/src/platforms/web/util/attrs.js#L41-L43

**Comment by chrisvfritz** [comment]
@yyx990803 Thanks! Can you share the reasoning for that? I'd like to provide a justification for the behavior in the more precise explanation.

**Comment by yyx990803** [comment]
Well, if the value is 0, most likely the user does want to display `0`. The case for `NaN` is subject to debate, but usually it is a result of error and probably better to have that shown in the output so the user can actually spot it.

**Comment by chrisvfritz** [comment]
I see. Thanks!

**Comment by sdras** [comment]
Fixed!
