### ISSUE TITLE
Persian translation

### ISSUE THREAD

**Issue by mrfarhadir** [vuejs/vuejs.org#1252]
hi there,
please give me permission to be able to create repo or  create fa.vuejs.org repo for me to be able to translate vuejs.org to Persian language

**Comment by chrisvfritz** [comment]
@mrfarhadir Glad to hear this! 🙂  Our current process for new translations is to create a personal fork of this repo. Then when it's ready, we can integrate it into the site and point the appropriate subdomain to your fork. That way, you have full control over the repo and contributors and don't have to go through us to add new people or make changes.

@pi0 may also be interested in this, so I'm tagging him here.

**Comment by mrfarhadir** [comment]
@chrisvfritz
 Thanks for your reply whoud u plz send url of the repo that I should fork 
Thanks.

**Comment by chrisvfritz** [comment]
[This one](https://github.com/vuejs/vuejs.org).

**Comment by pi0** [comment]
@mrfarhadir This is awesome for your interest 😍 I already made [this organization](https://github.com/orgs/vuejs-fa) to start translation of various vue projects into Persian :) Just sent you an invitation. I suggest talking more on this on telegram (My id is [@pooyaparsa](https://t.me/pooyaparsa)). There are some other people interested for translation too out there :)

**Comment by mrfarhadir** [comment]
@pi0 I joined to your org. but there wasn't any forked repo of so I forked it to start translating if you have willing to collaborate let me know.
Thanks

**Comment by pi0** [comment]
Just some updates on our progress: (Internally talked with @mrfarhadir)

- Made an official [org](http://github.com/vuejs-fa)
- Some of the most important repositories cloned
- We have a telegram [public group](https://t.me/joinchat/C6fePg4CQPKGFxMwI-mhHQ) for interested Persian users
- A [trello board](https://trello.com/b/fhVLQb49/vuejs-persian-doc) to track tasks.
