### ISSUE TITLE
UTF8 support for filtering

### ISSUE THREAD

**Issue by holubar** [vuejs/vuejs.org#128]
I have a problem with filtering data containing UTF8 characters, like names of people from Slovakia, for example Čechovič, Šipoš etc...

I want to find this name also by typing cechovic, sipos... Currently I have to add another set of data from backend with strings with removed special characters. to be able to do the filtering.

Is it possible to add support for this directyl in Vue?

**Comment by simplesmiler** [comment]
Please read https://github.com/vuejs/Discussion/issues/257

**Comment by yyx990803** [comment]
Please post questions to forum.vuejs.org instead.
