### ISSUE TITLE
Cloudflare interferes with tween.js source URL 

### ISSUE THREAD

**Issue by Perturbatio** [vuejs/vuejs.org#1282]
On https://vuejs.org/v2/guide/transitioning-state.html

In the section "Animating State with Watchers", the tween.js source URL contains an @ symbol which cloudflare picks up as an email address and obfuscates.

**Comment by chrisvfritz** [comment]
@Perturbatio Are you sure it's not a browser extension or something? I'm not seeing any obfuscation on my end.

**Comment by sdras** [comment]
I'm gonna PR to change this soon anyways, so whatever issue this is won't matter then (hopefully)

**Comment by Perturbatio** [comment]
@chrisvfritz I don't have any kind of cloudflare nor email obfuscation extension installed, the link it provided linked through to a cloudflare info page that said I needed to enable JS (which isn't disabled).

I do have: 
Privacy Badger
Test Pilot
Vue.js devtools
Wayback Machine

it's possible that privacy badger prevented cloudflare's JS from running, but cloudflare shouldn't be obfuscating the URL anyway.

**Comment by chrisvfritz** [comment]
Still not sure why this is happening for some people, but I've just disabled Email Obfuscation since I don't think we list emails anywhere.

**Comment by Perturbatio** [comment]
If it becomes an issue to have it disabled, you can insert `<!--email_off-->` unobfuscated code here `<!--/email_off-->`
to disable it for code blocks.

https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-
