### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by lucascv12** [vuejs/vuejs.org#1288]
O link que se encontra no trecho: **"Se você está interessado em números, pode dar uma olhada neste _comparativo independente_ que foca no desempenho bruto de renderização/atualização."** envia para uma página não existente (https://rawgit.com/krausest/js-_framework_-benchmark/master/webdriver-ts/table.html)

**Comment by Justineo** [comment]
It should be https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html.

**Comment by sdras** [comment]
Agreed, the link works in the english version so I'll close this out over here.
