### ISSUE TITLE
How to call a custom component by calling a custom directive

### ISSUE THREAD

**Issue by MaximeAubry** [vuejs/vuejs.org#1290]
Hello.
Today, i try to add a "copy" (in clipboard) button on an input using by a directive, which one calls a component i made.
I don't if it's a good way to customize a vue-material component. Maybe do you have a better idea ?
[Here](https://github.com/MaximeAubry/CallComponentWithDirective) is my code
Thanks a lot :)

**Comment by sdras** [comment]
Hi Maxime, 
This seems a little more imperative than it needs to be to me- you could do the same with one component with a method in less code (the console logging is so you can test and see that it's working)

https://codepen.io/sdras/pen/0b5104a8b20c7622d2a0b9432d52775f?editors=1011

Hope that helps!
