### ISSUE TITLE
Framework Comparison: Angular 5 faster

### ISSUE THREAD

**Issue by Jefftopia** [vuejs/vuejs.org#1291]
It looks like the benchmarks drawn and linked in the docs is outdated. I found a more recent version:

http://www.stefankrause.net/js-frameworks-benchmark7/table.html

That, if I'm reading correctly, shows Angular ahead in overall perf, possibly as well for memory allocation.

I think it would be nice to update the docs to reflect Angular's smaller memory footprint and marginally faster speed.

**Comment by shentao** [comment]
This doesn’t seem to be true especially in terms of memory allocation (less is better). As for perf, both libraries seem to perform similarly.
![screenshot 2017-11-23 10 12 04](https://user-images.githubusercontent.com/3737591/33165358-d3a54128-d036-11e7-9b18-dd1452472af3.png)

**Comment by Jefftopia** [comment]
In terms of memory allocation, Vue is mostly better than Angular, but Angular absent zone has  better allocation. 

For speed, the mean geometric slowdown favors Angular 5 any way you cut it. 

I grant that Vue and Angular are effectively the indistinguishable when it comes to perf, but the docs state (paraphrasing) Vue is at least as fast, which is a false statement. Vue is not faster. The docs should reflect this.

**Comment by chrisvfritz** [comment]
@Jefftopia Thanks for bringing this up. We definitely want to avoid making overly broad statements or overgeneralizing from a limited benchmark, so I've just updated the text. I agree that the runtime performance of Vue and Angular are now at a point where it's unlikely to be a deciding factor, apart from the one critical metric of time-to-interactive, which will be more a result of Angular's much larger size (which we already cover) in most environments than its slower startup time.

Let me know what you think of the new text. I'm happy to reopen if you still don't feel it treats Angular fairly. 🙂

**Comment by Jefftopia** [comment]
@chrisvfritz Personally, I think the copy change is 👍 . I can't speak for the wider community but if they care they can create a new ticket.
