### ISSUE TITLE
Add `<template functional>` syntax to section about functional components

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vuejs.org#1298]
Functional components are discussed [here](https://vuejs.org/v2/guide/render-function.html#Functional-Components) and according to [this](https://medium.com/the-vue-point/vue-2-5-released-14bd65bf030burl) announcement we can now do

`<template functional>` instead of `functional: true`.

I think the docs should include this. I can make this PR later this week if the team is happy with this idea.

**Comment by chrisvfritz** [comment]
A small note regarding SFCs on that page linking to [the vue-loader docs](https://vue-loader.vuejs.org/en/features/functional.html) would be welcome. 🙂

**Comment by lmiller1990** [comment]
Thanks Chris, I will do it in the next day or two!

**Comment by lmiller1990** [comment]
I looked into this, it feels really out of place on [this](https://vuejs.org/v2/guide/single-file-components.html) page. I feel like it fits better in [this section[(https://vuejs.org/v2/guide/render-function.html#Functional-Components) that talks about how to make a file `functional`. 

Is there any reason you felt it fits better in the SFC area @chrisvfritz ? The reason I think it goes best in the section section is because when I was making some functional components, I was referring to that area mostly, as opposed to the SFC page or vue-loader documentation, which I rarely use.

**Comment by chrisvfritz** [comment]
Just a misunderstanding. 🙂  we're on the same page actually (no pun intended). When I said "that page" I was referring to the one you linked to in your original post, which is the render functions page.

**Comment by lmiller1990** [comment]
Sure! Great to hear. I'll make the PR this weekend.

Thanks for your quick response, no wonder Vue has the best documentation of any framework I've used.

**Comment by lmiller1990** [comment]
It's done, closing
