### ISSUE TITLE
Update select2 example

### ISSUE THREAD

**Issue by printercu** [vuejs/vuejs.org#1299]
Hi!

There is an issue in select2 example: it does not refresh select2 state when value is updated from outside of component. It requires `.trigger('change')` after setting new value:

```js
      // update value
      $(this.$el).val(value).trigger('change')
```

Here is updated fiddle with option to set value from outside of component and with issue fixed:
https://jsfiddle.net/d131Lebj/167/

Should i prepare pr with updated link?

**Comment by phanan** [comment]
@printercu Thanks for reporting the issue (and sorry for the super late response). However, I think the current example is good enough for the intended purpose (to show case Vue/Select2 integration).

**Comment by printercu** [comment]
@phanan I find your decision strange. New vue.js users would like to see example, which they can just copy to their app and it should work. While finding such errors is disappointing.

**Comment by phanan** [comment]
@printercu Again, the purpose of the example, as well as others, is to provide a _minimal_ demonstration of the feature (in this case a wrapper component). It's never meant to be a complete product.
