### ISSUE TITLE
Add comparison to Ractive

### ISSUE THREAD

**Issue by PaulMaly** [vuejs/vuejs.org#1300]
I think these two frameworks are very similar. So, maybe it will be very interesting to find out what advantages of Vue against Ractive. Except popularity )))

Thanks!

**Comment by chrisvfritz** [comment]
Hmm, I don't think I'll have time to look at Ractive in-depth, but if someone with experience in both wants to start composing something, I'm willing to publish something approved by both communities.

**Comment by sdras** [comment]
Hey @PaulMaly, are you willing to PR for this? If not, no worries, but  I'm going to close it out because no one on this team has the requisite experience to write this up. Thanks!

**Comment by sdras** [comment]
Ok, I'm closing it out, but feel free to reopen if you decide you want to PR :)
