### ISSUE TITLE
Style Guide: is the beta fase finished?

### ISSUE THREAD

**Issue by ErickPetru** [vuejs/vuejs.org#1304]
Based on [this comment](https://github.com/vuejs/vuejs.org/pull/1160#issuecomment-333319128) from @chrisvfritz, the Style Guide would be considered in beta for about one month. We're past two months now and I'm think if it's time to start translating the Style Guide, but no one wants to translate a beta content. Any news about the official release of the style guide?

**Comment by chrisvfritz** [comment]
The beta stage won't be finished until @yyx990803 has had a chance to do a thorough review, but I think you can consider it stable enough to translate at this point. I don't _expect_ many more changes than other pages in the future.
