### ISSUE TITLE
Problem with margins in hackernews-example

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/vuejs.org#1308]
https://vuejs.org/v2/examples/hackernews.html:
![image](https://user-images.githubusercontent.com/4497128/33594252-3ee27584-d9a4-11e7-83eb-dc0a8d9554cf.png)

**Comment by sdras** [comment]
Thanks! That does look screwy. We'll take care of it soon.

**Comment by honzie** [comment]
@sdras: I opened a PR with a fix for this margin issue. Please let me know if there are any additional steps to help out. Hopefully this solution jibes well with the rest of the theme.

**Comment by chrisvfritz** [comment]
This is addressed now, so closing. 🙂
