### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by thilobillerbeck** [vuejs/vuejs.org#1327]
I'm starting to work on a german translation for the VueJS Docs. I forked this onto my private account, because I want to ask the developers first for permission to create a german vuejs organization. (This can be concidered as a question 😄 ).
If you want to help me, here is the repository: [Repo](https://github.com/thilobillerbeck/vuejs.org)

**Comment by chrisvfritz** [comment]
I don't mind you creating a vuejs-de organization. 🙂 Also tagging @LinusBorg, in case he'd like to help or has some tips.

**Comment by thilobillerbeck** [comment]
Ok, then I'll create an organization. :) Is there a special logo for that or can I just use the logo from your organization?

**Comment by thilobillerbeck** [comment]
I created the organization https://github.com/vuejs de. Feel free to help me. :)

**Comment by chrisvfritz** [comment]
A custom logo would be preferred to avoid confusion, similar to what [vuejs-br](https://github.com/vuejs-br) does. You don't necessarily have to change colors to incorporate the schwarz, rot, gold - just adding "DE", "Deutsch" etc to the normal logo would be fine.

**Comment by thilobillerbeck** [comment]
Ok. If anyone is at #34C3 and want to help me translate the docs, feel free to contact me :)

**Comment by bastian-w** [comment]
I could help with that.

**Comment by thilobillerbeck** [comment]
Hey @bwcgn, sorry for the delayed answer, I had to do some exams the past weeks. If you want to help  translating, I would add you to the VueJS Germany organization. :smile:

**Comment by stakx** [comment]
@thilobillerbeck - Could you please also send me an invite? I'd be willing to help, too. 😃

**Comment by thilobillerbeck** [comment]
done :)

**Comment by nekomajin** [comment]
Hello everyone.
Is there any "work-in-progress" that goes on? I want to help translate the german docs.

**Comment by thilobillerbeck** [comment]
Hey @nekomajin,

I am busy with my study at the moment, but this repo isn't closed or cancelled. Feel free to participate! 😉

**Comment by dpisarenko** [comment]
I also started to translate Vue.JS docs to German and just finished translating the [API page](https://github.com/dpisarenko/vuejs.org/blob/de/src/v2/api/index.md). The current version is located in branch `de` of [this repository](https://github.com/dpisarenko/vuejs.org/tree/de).

Suggestions and improvement proposals are welcome.

**Comment by maluio** [comment]
Hey,

Any updates on the current status? @dpisarenko, it seems you have translated [quite a bit](https://github.com/dpisarenko/vuejs.org/tree/de). @thilobillerbeck, are you planning to continue maintaining the vuejs-de organisation? Could both efforts be merged in some way?

**Comment by dpisarenko** [comment]
Hello, Martin! At the moment I cannot work on the translation. However, you can gladly use my existing translations as long as me and the other translator, Artjom Heinz, are credited. Best regards Dmitri Pisarenko 28.01.2019, 10:57, "Martin" <notifications@github.com>:Hey,Any updates on the current status? @dpisarenko, it seems you have translated quite a bit. @thilobillerbeck, are you planning to continue maintaining the vuejs-de organisation? Could both efforts be merged in some way?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by maluio** [comment]
Thanks @dpisarenko. If I will continue the translation I will credit you and Artjom and post an update here in case others are interested in joining in.

**Comment by thilobillerbeck** [comment]
Hey @maluio, I do not have enogh time at the moment to actively work on the translation, but I can give you and other devs access to the Vue.js DE organization so that you can work on the translation there. Maybe we can merge your, Dimitri's and my work into one repo and finish this off. :)

**Comment by phanan** [comment]
Closing in favor of #2015. Feel free to post a link there.
