### ISSUE TITLE
Vue.js Guide: Document use of "event parameters" in $emit(eventName, [...params]) for custom events

### ISSUE THREAD

**Issue by marko-knoebl** [vuejs/vuejs.org#1336]
I'm just learning vue.js and I noticed that https://vuejs.org/v2/guide/components.html#Custom-Events doesn't give any explanation/introduction about the optional event parameters that can be passed to a custom event.

The signature is given as just "$emit(eventName)".

Further down optional parameters are used in code but never introduced (first appearance in the section ".sync Modifier": "this.$emit('update:foo', newValue)").

I think this should be explicitly mentioned at the beginning of the section.

By the way, all in all the vue.js guide is amazing, thanks for the great work!

**Comment by sdras** [comment]
I've also noticed this area of the documentation is thin and could be explained in more detail. This is a good point, I'll try to put a PR in for it soon. Thanks!

**Comment by chrisvfritz** [comment]
One additional note: we don't have to explicitly explain this, but in our examples I think it'd be good to follow the convention of emitting a single payload, rather than multiple arguments. For example, instead of:

```js
$emit('some-event', 'foo', 3)
```

Doing this:

```js
$emit('some-event', { text: 'foo', count: '3' })
```

**Comment by sdras** [comment]
This is merged 🎉

**Comment by HarinderKaur11** [comment]
Hi, 

@sdras @chrisvfritz 
I am new to VueJs and I am doubtful about passing the optional payload
Could you please tell me how to pass the value returned by a computed function in the child component to the parent component using the optional payload.

I want to implement a separate search component which returns the search results to all other components. The computed function looks like this:

get computedSports () {
        if (!this.searchModel || this.searchModel.length === 0)
            return this.sports
        else
            return this.fuseSearch.search(this.searchModel)
    }


This is how I am trying to pass the value returned by computed function to its parent component:
@input="$bus.$emit('computed-sports', computedSports)"

In the parent component, this is how I want access the value of that function:
v-on:computed-sports="" <--- what value should come here?

**Comment by chrisvfritz** [comment]
Sounds like you're building a fun app. 🙂 I believe it should work if you remove the `$bus` part, then you can use a method as the value of the event listener in the parent. That method will receive the value of `computedSports` as the first argument.

**Comment by HarinderKaur11** [comment]
@chrisvfritz Thank you very much! It worked :)

**Comment by zarub2k** [comment]
@chrisvfritz Worked great!
