### ISSUE TITLE
Why Vue video not loading

### ISSUE THREAD

**Issue by octref** [vuejs/vuejs.org#1338]
![image](https://user-images.githubusercontent.com/4033249/34243728-03f01686-e5d7-11e7-9023-bf4384863466.png)

Clicking the button starts playing the video, but nothing is being shown on screen.
This is happening for at least Chrome, FF and Safari.

**Comment by chrisvfritz** [comment]
Thanks for reporting this! I have not yet been able to reproduce the problem, but I'll dig in a little deeper tomorrow. Since it's happening across all browsers, I wonder if it's OS-specific. What OS were you on when you noticed this?

**Comment by octref** [comment]
macOS. Umm..Let me see if I can trace the cause.

**Comment by octref** [comment]
More specifically, macOS 10.12.6 Sierra and Chrome 63.

**Comment by octref** [comment]
@chrisvfritz If you try clearing your cache and force refresh (Cmd+Shift+R) in Chrome, does it repro?

**Comment by chrisvfritz** [comment]
Very strange. 😅 I just tried that exact OS/browser combination, with a clear cache and force refresh, then also in incognito mode - but still no luck reproducing the problem. 😕

**Comment by octref** [comment]
One thing I forgot to add: When I hit the button, the video starts playing (I can hear the sound). However, nothing is shown on the screen.

I just tried connecting to LTE on my phone. Not working. So not network problem.

Tried using my work laptop (macOS with Chrome) too. Not loading. So not my computer specific setup problem.

Tried using Windows in Parallels in my work computer. Plays sound but no video.

**Comment by znck** [comment]
It didn't work for me in Safari for the first time, but it started working after a (normal) refresh.

**Comment by chrisvfritz** [comment]
One idea that just occurred to me is it could be a caching issue, where you're being served the new HTML and JS, but stale CSS for some reason. I just completely purged the CloudFlare cache, in case that might be happening. Let me know if you notice any difference.

**Comment by octref** [comment]
Was easy to debug:

![video](https://user-images.githubusercontent.com/4033249/34245769-54ebb6a4-e5e0-11e7-89fe-5e34a3d607bf.gif)

In this line:

https://github.com/vuejs/vuejs.org/blob/master/themes/vue/source/js/common.js#L165

```js
if (e.target !== modalButton && !videoModal.contains(e.target))
```

Should also check `!modalButton.contains(e.target)`.

What happened: Click on the play button toggled `open` class on Player, started playing video, but triggers the onclick meant for closing the window, thus removing the `open` class immediately.

The second onclick is meant for "Clicking outside the player closes the player". However, this should check if that's the click event on `modalButton`. (Or you can stop the event propagation too).

**Comment by Jinjiang** [comment]
Nothing wrong or JS error in my MacOS 10.13.1 + Safari 11.0.1 (13604.3.5).
But Vimeo is always blocked from the "Wall" unfortunately :-(

**Comment by chrisvfritz** [comment]
@octref Thanks for that thorough investigation! I just updated the button with a `stopPropogation` event handler and it should be live in about 10 minutes. Let me know if that resolves the issue. 🙂 

@Jinjiang That's too bad. 😞 Are you thinking of hosting with a different service for the Chinese translation?

**Comment by Jinjiang** [comment]
Yeah, will just try to register a Youku account for us.
So how could I get the source video and put translation in?
Thanks.

**Comment by octref** [comment]
@chrisvfritz Thanks for the quick turnaround! This has been fixed.
