### ISSUE TITLE
How/what to test when testing vue components

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vuejs.org#1344]
Hi,

I would like to contribute to the cookbook, regarding how and what to test when testing Vue components. 

I wrote [this](https://github.com/vuejs/vue-test-utils/pull/282) for the `vue-test-utils` documentation recently. I also write a lot about testing Vue components [here](https://medium.com/@lachlanmiller_52885), so maybe something based on those articles.

The main things I want to convey are

- what is in the scope of unit tests
- when to mock/stub
- common pitfalls

Edit: I do not know how to assign a label.

**Comment by sdras** [comment]
Sounds like a great addition! We'd love to have something like this in the cookbook. You probably already found it, but there's [a template](https://vuejs.org/v2/cookbook/cookbook-contributions.html) we ask people to work from in the cookbook section. Let me know if you need anything else to get started. 🎉

**Comment by lmiller1990** [comment]
Thanks @sdras . I will be working [here](https://github.com/lmiller1990/vuejs.org/tree/1344-cookbook-what-to-test), and ping you with a PR for feedback. Thanks!

**Comment by sdras** [comment]
You did it! Congrats! Thank you for your contribution 🙏
