### ISSUE TITLE
What does 'binding' mean in 'render-function' section?

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vuejs.org#1346]
At noon, I made a pr in [#629](https://github.com/vuejs/cn.vuejs.org/pull/629) , and the pr has succeed to being merged,
but there is also an existing  question  about 'What does 'binding' means here' ? It means the argument `binding` in  the directive hook arguments or it is meaningless but just a word `binding`? I want to know! Thanks!

**Comment by chrisvfritz** [comment]
You're correct that it refers to the `binding` referenced in the [directive hook argument](https://vuejs.org/v2/guide/custom-directive.html#Directive-Hook-Arguments). 🙂

**Comment by Justineo** [comment]
Okay then I think we should keep the parameter name untranslated in Chinese docs. Better to use <code>\`\`</code> to keep consistent with the other parts of the doc.

**Comment by chrisvfritz** [comment]
Sounds good to me!
