### ISSUE TITLE
Change the repo setting to allow only squash merge

### ISSUE THREAD

**Issue by re-fort** [vuejs/vuejs.org#1351]
Hi, I'm a member of [jp.vuejs.org](https://github.com/vuejs/jp.vuejs.org).
We have a bot that creates an issue automatically from the commit of `vuejs.org/master` to track the doc changes.
So when merging the PR with merge commits, our bot creates an extra issue because the commits on master branch include all commits on source branch.
For this reason, I want you to change the setting to allow only squash merge on this repo if possible.

Thanks :)

**Comment by chrisvfritz** [comment]
I'm good with that - I almost always do squash merges for this repo anyway. @yyx990803 If it sounds good to you too, can you update the setting on this repo?

**Comment by yyx990803** [comment]
done!

**Comment by re-fort** [comment]
Thanks @chrisvfritz and @yyx990803 :)
