### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by swamikevala** [vuejs/vuejs.org#1354]
Vue vs Angular.
In our organisation we were having this debate and one of the key factors was the availability of large, well-documented and well supported libraries of pre-built components for Angular, which the Vue ecosystem cannot match at this stage. 

Maybe that should also be pointed out in the comparison

**Comment by Elfayer** [comment]
I think vue has very good libraries of components. Here are the most known:
http://element.eleme.io/#/en-US
https://vuetifyjs.com/
http://quasar-framework.org/

And there are a looot more if you dig a little bit. (Just names I haven't tried: MintUI, Vue-strap)

You can find more on this topic on the forum:
https://forum.vuejs.org/t/best-frontend-design-library-for-vue2/23138
https://forum.vuejs.org/t/best-gui-framework-for-vuejs-i-guess-that-would-be-quasar/2349/40

**Comment by swamikevala** [comment]
@Elfayer - Thanks for the links. I would recommend that you update the docs and make it clear that these full featured component libraries exist. In our organisation, the decision to use Angular over Vue was strongly influenced by the assumption that there were none (to measure up to PrimeNG for example). Had we known about these, it may have gone differently. I imagine that in other organisations the same debate may be happening.

**Comment by Elfayer** [comment]
You can find/ask this information on the [forum](https://forum.vuejs.org/) or even the [Discord](https://discordapp.com/invite/HBherRA) which are very active and you're welcome to join ;)

**Comment by sdras** [comment]
In the ecosystem dropdown on the site, the last section is "Resource Lists" which includes official repos as well as [Awesome Vue](https://github.com/vuejs/awesome-vue) and [Vue Curated](https://curated.vuejs.org/), both of which are rich with components and resources. Thanks for stopping by! I think these do cover the use cases you're looking for.
