### ISSUE TITLE
Document how to dockerize a Vue app

### ISSUE THREAD

**Issue by fabriziocucci** [vuejs/vuejs.org#1357]
### Description

It would be nice to add a small section (maybe in the [Production Deployment](https://vuejs.org/v2/guide/deployment.html) page) which shows how to create a production-like docker image of a Vue app built out of an official template (e.g. webpack).

This comes out of my question in the `#need-help` channel:

> I'm trying to create a production-like docker image capable of serving my Vue.js app (built starting from the official Vue.js webpack template).
> 
> I came up with something like this:
> 
> ```
> FROM node:9.3.0-alpine
> 
> # install static server
> RUN npm install -g serve
> 
> # create a 'tmp' folder for the build and make it the current working directory
> WORKDIR /app/tmp
> 
> # copy only the package.json to take advantage of cached Docker layers
> COPY package.json .
> 
> # install project dependencies
> RUN npm install
> 
> # copy project files and folders to the working directory
> COPY . .
> 
> # build for production with minification
> RUN npm run build
> 
> # make the 'app' folder the current working directory
> WORKDIR /app
> 
> # clean up (i.e. extract 'dist' folder and remove everything else)
> RUN mv tmp/dist dist && rm -fr tmp
> 
> EXPOSE 5000
> CMD [ "serve", "--single", "--port", "5000", "dist" ]
> 
> ```
> 
> Considering I'm a Vue.js newbie:
> 1) is this the best approach (or even a correct one)?
> 2) all examples I've found googling around just copy the whole project folder inside the docker container and use the `npm run dev` command to serve the app with webpack. Is this a preferable approach? (although I guess in this case the non-minified app will be served)
> 3) is there an official documentation that clearly describe the best way to dockerize a Vue.js app? (apologies if there is and I missed it)

**Comment by sdras** [comment]
I think this a great idea. I have a dockerfile that I've been using for Vue applications as well, I could see it in the cookbook and linked to from deployment, as Dockerfiles can be set up many ways, and there is not one true way. Here is my nginx version:

```
FROM node:alpine

EXPOSE 80

RUN apk add --no-cache nginx

WORKDIR /app

COPY package.json .
RUN yarn install

COPY misc/nginx.conf /etc/nginx/nginx.conf

COPY . .

RUN yarn run generate

CMD ["nginx"]
```

The only thing I'd say is that the cleanup step adds an unnecessary layer to the image, but that might be something worth documenting and talking through in the cookbook example.

Unless you are interested in writing it, I can make the cookbook example.

**Comment by fabriziocucci** [comment]
@sdras thanks a lot for your prompt feedback!

> The only thing I'd say is that the cleanup step adds an unnecessary layer to the image, but that might be something worth documenting and talking through in the cookbook example.

I agree with you here, I wasn't particularly happy about that either. I guess my OCD kicked in and forced me to remove anything unnecessary. Maybe we could chain it to the `RUN npm run build` to avoid the unnecessary extra layer or maybe there is no point in doing any cleanup.

Also, as you said, there are probably infinite ways to write a Dockerfile for this purpose and I was actually thinking about using something a little bit more robust like nginx as a replacement for [serve](https://github.com/zeit/serve). Although, in the context of a cookbook, maybe that would mean spending a couple of words describing a (very simple) nginx configuration file.

Finally, unless you have something already, I'd be happy to contribute the cookbook! ❤️

**Comment by sdras** [comment]
Awesome! There's a [template here](https://vuejs.org/v2/cookbook/cookbook-contributions.html) that can help you get started. 🎉

**Comment by sdras** [comment]
Hey! Just a quick ping on this since it's March now, would you like me to do this recipe instead or are you still planning on putting in the PR? We're going to go to beta on the cookbook soon so I'd like to get it in before that, but I'm flexible in terms of who writes it :)

Cheers! 🍻

**Comment by fabriziocucci** [comment]
> We're going to go to beta on the cookbook soon

Really glad to hear that! ❤️ 

> Just a quick ping on this since it's March now

You are right, I've been pretty lazy on this, sorry. Let me try to give it a shot in the next couple of days and see what comes out.

**Comment by sdras** [comment]
Excellent! Thanks

**Comment by williamhallatt** [comment]
Hi @sdras, thanks for the Dockerfile example! Would you be willing to share the content of your nginx.conf here?

**Comment by fredderf204** [comment]
@williamhallatt I was able to get this working using @sdras Dockerfile example with some tweaks. Here are my nginx.conf and nginx.default files, which live the in misc folder;

misc\nginx.conf:
```
user nginx;
worker_processes 1;
pid /var/run/nginx.pid;
daemon off;

events {
  worker_connections 512;
  # multi_accept on;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" "$http_host"';

  access_log stdout main;
  error_log  stdout debug;

  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
}
```
misc\nginx.default:
```
server {
  listen 80 default_server;
  listen [::]:80 default_server ipv6only=on;

#  listen 443 default ssl;
#  ssl_certificate /etc/nginx/certs/server.crt;
#  ssl_certificate_key /etc/nginx/certs/server.key;

  root /app/dist;
  index index.html index.htm;

  server_name _;

  location / {
    try_files $uri $uri/ =404;
  }

  location /stats/nginx {
    stub_status on;
  }
}
```
DockerFile:
```
FROM node:8.9-alpine
RUN apk add --no-cache nginx
WORKDIR /app
COPY package.json .
RUN yarn install
ADD misc/nginx.default /etc/nginx/conf.d/default.conf
ADD misc/nginx.conf /etc/nginx/nginx.conf
COPY . .
RUN npm run build
EXPOSE 80
CMD ["nginx"]
```
PS I have crafted the nginx conf files from 2-3 samples I found on the web, so I am not the authority on the subject. But the above is working for me :)

Let me know if it helps?

**Comment by fredderf204** [comment]
@williamhallatt @sdras disregard to above solution...... as there is a much better way. [Docker mulit-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/ ). Please see new Dockerfile below;

```
FROM node:8.9-alpine as builder
WORKDIR /app
COPY package.json .
RUN yarn install
COPY . .
RUN npm run build

FROM nginx
COPY --from=builder /app/dist /usr/share/nginx/html
```

No need for custom nginx conf files and reduces my Docker image from 276MB to 110MB :)

**Comment by williamhallatt** [comment]
Hi @fredderf204, I managed to get my setup working, but the nginx files were the ones I was after (I cannot run Docker containers in my env). Going to use yours to see if there are any config improvements I can make on ours! 👍

**Comment by fabriziocucci** [comment]
@fredderf204 
There is [a pending PR](https://github.com/vuejs/vuejs.org/pull/1483/files) which actually shows how to dockerize a Vue.js app taking advantage of the Docker multi-stage builds as you suggested. I'd love to hear your feedback on that!

@williamhallatt 
As part of the same PR I mentioned above, one of the first commit actually required a [nginx configuration file](https://github.com/vuejs/vuejs.org/pull/1483/commits/a8f2f01e836b831e545e862b73cff01cda32e562#diff-7c54b5256e4bebd8c8b7ba3be8e0ab67L90). It was **very** basic but _maybe_ you could start from that and further customise it.

**Comment by gertjanwytynck** [comment]
@fabriziocucci Thanks for the cookbook Helped me a lot.

Just updating here that I had an issue with the cookbook. It stopped on `RUN npm install` with this error:

```
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

Not using the `alpine` image version worked or  adding this before `npm install`:

```
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
```

Founded this solution [here](https://github.com/nodejs/docker-node/issues/586)

**Comment by fabriziocucci** [comment]
> @fabriziocucci Thanks for the cookbook Helped me a lot.

@gertjanwytynck  I'm really glad to hear that! 😊 

Regarding the issue, I've just tried to go through the cookbook one more time, replaying both the simple example and the real-world example but, for some reason, I can't seem to replicate the issue you mentioned.

Could you please help me figure out what's going on here? 😕 

1. what's your dev environment (OS and Docker version)?
2. did that happen on the simple example or the real-world one?
3. did you happen to change any of the base images used in the cookbook?

Thanks in advance.

**Comment by gertjanwytynck** [comment]
Well,

OS version: `10.13.4`
Docker version: `18.03.1-ce, build 9ee9f40`
NPM version: `6.1.0`

It happend on a real-world example. I have a fixed version in my package file (`"webpack-s3-plugin": "git+https://github.com/eyupci/s3-plugin-webpack.git#master"`). Maybe that is the reason?

No, only thing I've changed is the apk...

```
# build stage
FROM node:9.11.1-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:1.13.12-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by fabriziocucci** [comment]
@gertjanwytynck thanks for your prompt feedback.

I was kind of hoping you deviated from the cookbook by changing the base images but it doesn't seem the case based on what you posted:

```docker
# build stage
FROM node:9.11.1-alpine as build-stage
...

# production stage
FROM nginx:1.13.12-alpine as production-stage
...
```

So, if you remove this:

```
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
```

 from your `Dockerfile` you get the error posted above, correct?

**Comment by gertjanwytynck** [comment]
@fabriziocucci you're welcome.

That is correct. Just removed those lines, and the error is raised again.

**Comment by fabriziocucci** [comment]
@gertjanwytynck thanks again.

My only (wild) guess at this point is that the issue could be related to one of the dependencies of your project.

May I ask you to clone [this](https://github.com/fabriziocucci/vuejs-cookbook-test) repository and try to build the Docker image using the Dockerfile of the real-world example? i.e.

```bash
docker build -f Dockerfile.real-world-example -t vuejs-cookbook/dockerize-vuejs-app .
```
