### ISSUE TITLE
"Filter as you type" cookbook example

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/vuejs.org#1358]
A cookbook entry showing computed properties and a "filter as you type" demo. You have a list of names and a simple field. As you type in the field, the list filters based on the input. This is rather trivial, but it seems like the kind of thing that would be good for a cookbook. 

Also - maybe show a second example where the data is more complex. So the first example is based on an array of names. A second example could show an array of simple objects where you have to check a `.name` property. (Or maybe we even include 2 input fields, one for name and one for age.)

**Comment by sdras** [comment]
Hm, I think this might be too simple for the cookbook. We show a number of examples like this in the guide, as well as the examples section. I could see it being part of another cookbook entry though. The cookbook is meant for larger patterns- I know that it's more complicated to implement this in other frameworks, but in Vue it's pretty trivial to implement. Thanks for the suggestion though!
