### ISSUE TITLE
Cookbook entry for table sorting

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/vuejs.org#1360]
Simple - demonstrate how to sort a table with Vue. Here is a codepen example of this - https://codepen.io/pespantelis/pen/ojwgPB. I'd be willing to reach out to the author of that pen and see if they mind me using it in an entry.

**Comment by cfjedimaster** [comment]
Also - perhaps show adding/removing items from a table.

**Comment by cfjedimaster** [comment]
Also - maybe show pagination. (Although this may be pushing it a bit and perhaps could be a second cookbook entry.)

**Comment by cfjedimaster** [comment]
Oh - and heh - maybe show filtering too. I made another entry for that, but it could be good here too.

**Comment by sdras** [comment]
Hi Raymond! Happy new year :)

We already have example that is like this: https://vuejs.org/v2/examples/grid-component.html
Would this be different from that?

**Comment by cfjedimaster** [comment]
I'm ashamed to say this - I never noticed that link before. Well, ashamed, but dang happy I know it about now. Closing this as I don't think it would be different. (Maybe the intro page to the cookbook should include a link to the examples too?)

**Comment by sdras** [comment]
Good idea! Yeah, they should probably link to eachother. Thanks Raymond!
