### ISSUE TITLE
Missing example on deep watcher

### ISSUE THREAD

**Issue by Elfayer** [vuejs/vuejs.org#1362]
Hello guys,

I come here from a question on the Discord and couldn't find an example on the doc on this.
Here is the question: __How to watch a unique deep key?__

As you can see [here](https://vuejs.org/v2/api/#watch), the example provides this:

```js
var vm = new Vue({
  data: {
    a: 1,
    b: 2,
    c: 3,
    d: 4
  },
  watch: {
    a: function (val, oldVal) {
      console.log('new: %s, old: %s', val, oldVal)
    },
    // string method name
    b: 'someMethod',
    // deep watcher
    c: {
      handler: function (val, oldVal) { /* ... */ },
      deep: true
    },
    // the callback will be called immediately after the start of the observation
    d: {
      handler: function (val, oldVal) { /* ... */ },
      immediate: true
    }
  }
})
vm.a = 2 // => new: 2, old: 1
```

But no mention of the following is presented:
```js
watch: {
  'a.b.c': function (val, oldVal) {

  }
}
```

I think it would be nice to make a little improvement here. This syntax is mentioned nowhere.

**Comment by M-Porter** [comment]
It's mentioned in the API docs for vm.$watch https://vuejs.org/v2/api/#vm-watch
