### ISSUE TITLE
Turkish (TR) Translation "work-in-progress"

### ISSUE THREAD

**Issue by myazarc** [vuejs/vuejs.org#1368]
hi everyone.
i starting made translation Turkish.
~~my repo: https://github.com/myazarc/vuejs.org~~

> https://github.com/vuejs-tr/vuejs.org
> there's been no repo activity for a long time.
  
**## Edit:**
repo: https://github.com/vuejs-turkce/vuejs.org

**Comment by chrisvfritz** [comment]
Sounds great @myazarc! Let us know if you have any questions. 🙂

**Comment by med177** [comment]
bu gün bende aynı niyetle repoyu kopyalamış bulundum aslında araştırmam lazımdı ancak baktığımda küçük bir çalışma gördüm ciddi anlamda çeviri yapmak istersen birlikte yapabiliriz seni de davet ettim gruba myazarc

**Comment by myazarc** [comment]
Tamamdır birlikte devam edelim benim içinde çok iyi olur.

**Comment by med177** [comment]
merhaba çeviri takımı kurup çeviri planlamasını ekledim bitenleri Done kısmına atadım üzerinde çalışılanları InProgress kısmına ve iki adet yapılacaklar kısmı koydum ToDo Primary ve ToDo Secondary, bi incele yapılması gereken şeyler varsa eklersin ya da önceliği değişmesini düşündüğün bir şey varsa da, yönetici yetkilerini verdim şu an sende owner rolündesin katılımın için teşekkür ederim.

**Comment by phanan** [comment]
I'm closing this issue as an effort to tidy up our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
