### ISSUE TITLE
It is not clear in the introduction of the guide that a Component must be registered before the root instance

### ISSUE THREAD

**Issue by yurimalheiros** [vuejs/vuejs.org#1370]
Add some explanation to make this clear. It is confusing and frustrating for a newcomer to add the code and not see the correct result.

**Comment by sdras** [comment]
True! I got stuck on this at one point, too. This seems like a good one to add.

**Comment by sdras** [comment]
Actually, upon revisiting this section, this is already stated in the components section of the guide, in bold, no less :) I guess we both just read it too fast.
