### ISSUE TITLE
Inaccuracy in comparisons guide (ownership of weex)

### ISSUE THREAD

**Issue by HyndexCoder** [vuejs/vuejs.org#1382]
Weex has been transferred from Alibaba group to Apache foundation.

**Comment by chrisvfritz** [comment]
@Jinjiang Can you confirm this?

**Comment by Jinjiang** [comment]
Exactly, Weex is just incubating from Alibaba Group to Apache Foundation. This requires a time course. I think we can update the doc when the incubation success. Or add a explanation if necessary.

Thanks :-)

**Comment by chrisvfritz** [comment]
@Jinjiang Whichever you think is best sounds good to me. 🙂

**Comment by Jinjiang** [comment]
@chrisvfritz I have create a PR for this. And @Hanks10100 please have a review.
Thanks.

**Comment by Hanks10100** [comment]
+1. I think we should update the document to explain the relationship between Weex and ASF for now, then update it again when Weex finished the incubating.
