### ISSUE TITLE
DNS update for Brazilian Translation on Netlify

### ISSUE THREAD

**Issue by ErickPetru** [vuejs/vuejs.org#1385]
As suggested in the new README instructions, we moved our deploy to Netlify too: [br-vuejs-org.netlify.com](https://br-vuejs-org.netlify.com/).

@yyx990803 can you update the DNS, please?

**Comment by yyx990803** [comment]
I've updated DNS - it seems you haven't set the custom domain to `br.vuejs.org` in Netlify - make sure to do that and enable HTTPS!

**Comment by ErickPetru** [comment]
Unfortunately I receive the message "Another site is already using this domain" when I try to set the custom domain.

**Comment by chrisvfritz** [comment]
Hmm, I wonder if Netlify won't allow linking to a domain once it's been validated as belonging to another account. @ErickPetru If that might be the case, it could be worth [contacting Netlify support](https://www.netlify.com/support/) to see if we can make an exception.

**Comment by yyx990803** [comment]
Ok, if that's the case here's what we need to do:

- I'll create a vuejs-br team on Netlify under my account (I have free open source team plans) since the vuejs.org domain is linked to my account now.
- @ErickPetru I'll add you to the vuejs-br team, which will need your email address. Is the one in your GitHub profile ok?
- You should then be able to deploy the site under vuejs-br on Netlify and be able to setup the custom domain.

I've temporarily switched the DNS back to github for now.

**Comment by ErickPetru** [comment]
@yyx990803 yes, the e-mail is the same from GitHub. Waiting your feedback to perform the deploy.

**Comment by ErickPetru** [comment]
@yyx990803, unfortunately the _"Another site is already using this domain"_ message remains, even with the deploy performed under the new **vuejs-br** team. Thinking about that, we're talking about the same domain already configurated for the main vuejs repo so Netlify will not allow a subdomain of that domain configurated in another repo. For now, I can't think on a workaround.

**Comment by yyx990803** [comment]
@ErickPetru I've contacted Netlify support and they will manually set the domain for us. I'll let you know once we have that fixed.

**Comment by ErickPetru** [comment]
@yyx990803 I took a look at the settings now and I saw that the Netlify staff has already set up the domain [br.vuejs.org](https://br.vuejs.org/). Please, can you update the DNS again to see if everything will work out this time?

**Comment by yyx990803** [comment]
@ErickPetru done! It's on Netlify now.
