### ISSUE TITLE
Getting started instructions (versions)

### ISSUE THREAD

**Issue by rubydesign** [vuejs/vuejs.org#1390]
Hi,
getting started is great in general, and it did just that.

The issue i would like to raise is about the versions. The script, and in fact all the links in that page, point to a *latest* version.  And while that maybe seems good, it does have serious pitfalls. Which is why i feel it should not be encouraged.

Production apps can be extremely fiddly as to which versions actually work and which don't. **Implicit** update is setting oneself up for midnight calls and angry users.
What if 2.6 comes out. Or 3.0. And (small or large) incompatible changes break the app.

So the suggestion is to put explicit version numbers into the download links. Get people started off on the right foot.

**Comment by chrisvfritz** [comment]
That sounds good to me. 🙂 A PR would be welcome to update the `pre-deploy.js` script to keep each CDN link up-to-date.

**Comment by rubydesign** [comment]
fair enough, i dug that hole, so there it is
