### ISSUE TITLE
文档页面中，任意位置点击时控制台报错。

### ISSUE THREAD

**Issue by zhaozhe0831** [vuejs/vuejs.org#1400]
![image](https://user-images.githubusercontent.com/12945873/35428134-6cd39b94-02a8-11e8-9b2d-23fa72e58cb6.png)

click anywhere, console prints error.

**Comment by Jinjiang** [comment]
Reproduced. I will fix it asap. Thanks.

**Comment by sdras** [comment]
This looks to be fixed, thanks! I'm closing it out but feel free to reopen if I'm mistaken.
