### ISSUE TITLE
Improve unit testing page in docs

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vuejs.org#1402]
https://vuejs.org/v2/guide/unit-testing.html

This page leaves a lot to be desired. How do we simulate events on DOM elements, for example? Is there a more in-depth guide on unit testing in Vue?

**Comment by sdras** [comment]
We've got a unit testing cookbook article that's almost ready, so this will be done and linked to soon.

**Comment by ffxsam** [comment]
Thanks Sarah! I actually just discovered `vue-test-utils` which is the 💣 😄

**Comment by sdras** [comment]
Totally! I'll be sure to add a link to that too.
