### ISSUE TITLE
Translate Docs to Czech - work in progress

### ISSUE THREAD

**Issue by graveto** [vuejs/vuejs.org#1413]
Hi,
I would like to start translating the docs to Czech. How much should be translated before I make any pull requests?

**Comment by chrisvfritz** [comment]
Great to hear! 🙂 We actually recommend creating team for the translation, such as `vuejs-cz`, then managing the translation there. That way, you'll have the ability add new translators and manage the process however you'd like. When enough of the document is translated that you feel it's ready to be published, we can add it to our list of translations on the main site.

Let me know if you have any other questions!

**Comment by graveto** [comment]
Thanks @chrisvfritz. I am excited about learning Vue and contributing to the project. I am a bit confused by the creation of a team. Should I create an organization called vuejs-cz and fork the main repo there? So the path would be vuejs-cz/vuejs.org instead of graveto/vuejs.org.

**Comment by graveto** [comment]
I have created a new repo for the translation.
https://github.com/vuejs-cz/vuejs.org

**Comment by chrisvfritz** [comment]
Beautiful! That's exactly right. 🙂
