### ISSUE TITLE
Docs refer to old test-utils package

### ISSUE THREAD

**Issue by amochohan** [vuejs/vuejs.org#1417]
The Vue test utils documentation ([testing SFC with Jest](https://vue-test-utils.vuejs.org/en/guides/testing-SFCs-with-jest.html)) refers to the following command:

```bash
$ npm install --save-dev jest vue-test-utils
```

which is the non-scoped package, resulting in the following warning.

```bash
vue-test-utils@1.0.0-beta.11: VUE-TEST-UILS WARN: vue-test-utils has moved to a scoped package. The new repository is available @vue/test-utils. To install the new package, run npm install --save-dev @vue/test-utils
```

**Comment by phanan** [comment]
Thanks, but this is a vue-test-utils issue and should be reported there instead.
