### ISSUE TITLE
Renaming Vue.js Cookbook

### ISSUE THREAD

**Issue by robaxelsen** [vuejs/vuejs.org#1418]
First off, thanks a lot for working on the Vue.js Cookbook. I am excited to see it take shape and eager (as an impatient kid waiting for xmas) to see the first version completed :tada: :smiley: 

I've noticed an increasing amount of mentions to the upcoming [Vue.js Cookbook](https://github.com/vuejs/vuejs.org/blob/master/src/v2/cookbook/index.md). Last time I saw it mentioned [today in this tweet](https://twitter.com/sarah_edo/status/960532467961622528), and I remember first reading about it in [this medium article](https://medium.com/@kevin_peters/what-happened-to-vue-js-in-2017-aeaaa69c2c6f).

But anytime I google it, I either come across [Vue.js 2 Cookbook by Andrea Passaglia](https://www.packtpub.com/web-development/vuejs-2-cookbook), or [this demo app project](http://vuecookbook.com/).

As I am sure I'm not the only one who has been curious and googled myself into confusion, and Andrea already has written a published book with the (almost) same name, would it maybe be better for both the contributors and the Vue.js community if this project was renamed?

@sdras @chrisvfritz

**Comment by sdras** [comment]
Hi @robaxelsen, 
Thanks for stopping by. The project is still in the first stages, though in March/April I plan to get a few more entries in and bring it to the next level. Part of the reason it isn't indexed well is because we haven't formally introduced and announced it yet. I'm positive that when we're ready for it to be more visible, we can get it there. There are a number of platforms we'll use to announce it.

Thanks for concern!

**Comment by robaxelsen** [comment]
Hi @sdras,

Thanks a lot for launching The Cookbook. It's an amazing resource, and I am grateful for all the work you and other contributors have put into this :tada: 

It now appears as the number one search result for "vue.js cookbook" in google, which is awesome. It does not appear in the search results over at vuejs.org though, but I guess that is deliberate as it's available under "Learn":
![screenshot from 2018-03-28 11-33-07](https://user-images.githubusercontent.com/13132899/38021061-2693f300-327c-11e8-9c10-e293a4b42c64.png)
