### ISSUE TITLE
赞助页面，进入编辑页面后，内容为空

### ISSUE THREAD

**Issue by dear-lizhihua** [vuejs/vuejs.org#1422]
[Sponsor Vue.js Development](https://vuejs.org/support-vuejs/) 页面最下面的 Caught a mistake or want to contribute to the documentation? [Edit this page on GitHub!](https://github.com/vuejs/vuejs.org/blob/master/src/support-vuejs/index.md)
点击 `Edit this page on GitHub!` 后，进入 https://github.com/vuejs/vuejs.org/blob/master/src/support-vuejs/index.md 页面，看到的 markdown 文档为空。

赞助页面被移至：https://github.com/vuejs/vuejs.org/blob/master/themes/vue/layout/sponsors-page.ejs

**Comment by Jinjiang** [comment]
因为赞助页面和首页都需要展示赞助商的信息，所以为了避免重复维护，这两个页面都是经过特殊模板生产的，并且赞助商的数据放到了 yml 配置文件中。

所以这个页面直接编辑 markdown 已经存在一定的难度和认知成本了，一个我暂时能够想到的改进建议是在 `support-vuejs/index.md` 中加入一段注释做个简单的说明。

**Comment by dear-lizhihua** [comment]
好的，收到
