### ISSUE TITLE
Revue link is dead

### ISSUE THREAD

**Issue by nesk** [vuejs/vuejs.org#1427]
[The link to Revue is dead](https://github.com/vuejs/vuejs.org/blob/38f492e6ff0deb194df98a3d0180da73b0f43ed4/src/v2/guide/state-management.md#information-for-react-developers) and it seems we cannot find the repository anymore on Github, does the project still exist?

**Comment by 01abhishekjain** [comment]
I can't find any mention of Revue on the `State management` page. Can you check again?

**Comment by nesk** [comment]
See the "simple bindings" link :)

**Comment by 01abhishekjain** [comment]
Gotcha. Why don't you raise a PR for this?

**Comment by nesk** [comment]
Because I cannot find Revue on Github anymore, so I don't know with which URL I could replace the original one. I could provide the [NPM URL](https://www.npmjs.com/package/revue) but the fact that the Github repository is down is very strange, and I don't want to provide a URL for a potentially dead project.

**Comment by 01abhishekjain** [comment]
Maybe the hyperlink should be removed altogether considering how Vuex has become kinda the de-facto state management solution for Vue. And if someone really wants to, s/he can set up bindings with Redux themselves.

Someone higher up might be able to take a decision.

**Comment by phanan** [comment]
@nesk Thanks for letting us know. Do you want to create a PR with the link changed into https://yarnpkg.com/en/packages?q=redux%20vue&p=1?

**Comment by nesk** [comment]
@phanan Yep, done!

**Comment by phanan** [comment]
Cheers!
