### ISSUE TITLE
Add mention to v-bind directive documentation that v-bind.sync="{...}" is possible

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vuejs.org#1431]
This capability was added here: https://github.com/vuejs/vue/issues/5937

**Comment by chrisvfritz** [comment]
Thanks! This would be in the component documentation and a contribution is welcome. 🙂

**Comment by davidkhess** [comment]
Done.

https://github.com/vuejs/vuejs.org/pull/1459

**Comment by chrisvfritz** [comment]
Merged! 😄
