### ISSUE TITLE
Can I contribute a blog example?

### ISSUE THREAD

**Issue by jakelumetta** [vuejs/vuejs.org#1432]
I'd like to contribute a serverless blog example to https://github.com/vuejs/vuejs.org/tree/master/src/v2/examples

It would use ButterCMS API for the blog backend. Similar to this Firebase example: https://vuejs.org/v2/examples/firebase.html

Let me know your thoughts! Thanks

**Comment by sdras** [comment]
Sounds like a nice idea! I'm sure it will be useful to people.

If you decide you would like to do a write up of the example, let me know! We can add it to the [cookbook](https://vuejs.org/v2/cookbook/index.html).

Thanks!

**Comment by sdras** [comment]
You can open a PR- is it an example or a cookbook recipe? I can label it appropriately here.

Examples go in the directory you pointed at, while cookbook entries are [linked up here.](https://github.com/vuejs/vuejs.org/tree/master/src/v2/cookbook)

Thanks!

**Comment by jakelumetta** [comment]
@sdras Sounds good - I think it's a fit for cookbook but you tell me :)

PR is here: https://github.com/vuejs/vuejs.org/pull/1457

**Comment by sdras** [comment]
Excellent! I'll have a look and get back to you! On my way to a conference but I'll review as soon as I can.

**Comment by sdras** [comment]
Done!
