### ISSUE TITLE
Translate Docs to Polish - work in progress

### ISSUE THREAD

**Issue by anushhka** [vuejs/vuejs.org#1436]
Hi! 
I would like to start translation into polish and I have seen Your recommendation for a translator from Czech Republic saying that the best way is to create a new organization (vuejs-pl) and fork the main repo there, which I did. Is it ok that I did it? 

There is another person already willing to help me with that, but I would like to invite more people for this team. Is there a chance the organization can be added on the translations list on README to confirm we are the part of the project so others can be sure and more willing to join us?

**Comment by chrisvfritz** [comment]
Hi @anushhka - sorry for the delay in getting back to you. What you did is perfect and we look forward to your translation! We usually like to wait a little while for progress before adding a note to the README, but you can feel free to link back to this issue for now, to confirm that you've been officially invited to translate. 🙂

**Comment by wbankowski** [comment]
Hi @anushhka - with pleasure, I will contribute to the community of Vue.js and make a translation for Polish users. Let me know how you're doing with the stuff so I can join the efforts.

**Comment by wbankowski** [comment]
Hi @chrisvfritz - it seems that nothing was done in this issue and there is no contact with @anushhka 
Is there a chance to take control over vuejs-pl organization or should I set up a new one, like pl-vuejs. Is it ok for you?

**Comment by chrisvfritz** [comment]
I'd recommend giving @anushhka a little more time to respond to your comment, then trying to contact her via email/Twitter. If you still can't get in touch, you could technically contact GitHub to try to get control, but I think it would be easier to just create a new one and that'd be fine with me. 🙂

**Comment by Triloworld** [comment]
Is there some progress going on? Where is this "vuejs-pl" organization?
This one? : https://github.com/vuejs-pl/vuejs.org
No sync with main repository ;(

**Comment by wbankowski** [comment]
Hi @Triloworld. I had tried to contact @anushhka but with no response. Even GitHub stuff tried to do it. There is a group "Translation Gang" that you can contact.

**Comment by Triloworld** [comment]
Ok. Can you (@wbankowski) create new organization as you described?
And add me so we can work together. Or I can do that if you need?

**Comment by wbankowski** [comment]
Due to lack of contact possibilities with @anushhka we have set a new organization for Polish translation, i.e. pl-vuejs
We kindly inform about it @chrisvfritz and @sdras

**Comment by Triloworld** [comment]
Can you add me to it? You don't have any contact information on your profile

**Comment by wbankowski** [comment]
@Triloworld I sent an invitation for you already. My email: w.bankowski@me.com and mobile +48 533 95 25 95

**Comment by JakeTvvv** [comment]
@wbankowski How do you progress? I would like to join and help in the creation of Polish translation

**Comment by dam-orzel** [comment]
@anushhka and how are the works on the Polish translation going?

**Comment by kasiawrz** [comment]
hey guys!
@wbankowski @chrisvfritz  @anushhka how is it going? 
Is there any progress on it? 
i have quite a lot of time (especially over the next month) and would like to contribute

**Comment by JakeTvvv** [comment]
Hi!
@dam-orzel @kasiawrz 
I'm from the VUE.JS Polska team.
Send me an email to kontakt@jakubgrzywacz.pl and we will add you to the organization and send an invitation to Discord.

**Comment by Triloworld** [comment]
Hello all 
We communicate on https://discord.gg/gggQsTD
Join us and help translate. 

As we write, there was some change ongoing to the link: https://github.com/pl-vuejs
(we get acceptance from github staff to claim the right name: vuejs-pl so there is little delay on work to be started)
I'am working daily as frontend developer and getting better hands-on with original documentation.
Our goal is to bring not only "Polish" version but detailed so more people enjoy using it.
I will try hard to do everyday progress but project is big for only one person

**Comment by phanan** [comment]
Closing in favor of #2015. Feel free to post a link there.
