### ISSUE TITLE
Inaccuracy in comparisons guide - Directives-vs-Components section

### ISSUE THREAD

**Issue by broql** [vuejs/vuejs.org#1443]
Is statement below up to date?

"Vue has a clearer separation between directives and components. Directives are meant to encapsulate DOM manipulations only, while components are self-contained units that have their own view and data logic. In AngularJS, there’s a lot of confusion between the two."

Source: [https://vuejs.org/v2/guide/comparison.html#Directives-vs-Components](https://vuejs.org/v2/guide/comparison.html#Directives-vs-Components)

According to [https://docs.angularjs.org/guide/component](https://docs.angularjs.org/guide/component) there is clear distinction when and where not to use components and what are their advantages over plain directives.

**Comment by chrisvfritz** [comment]
I wouldn't say there's a clear distinction, since AngularJS components _are_ directives, but I've just updated the comparison to better reflect what's communicated in the AngularJS doc and avoid the word "confusing", which I think was overly judgemental language.
