### ISSUE TITLE
Is this an error in example? How do <comp v-bind.sync="{ foo: 1, bar: 2 }"> work?

### ISSUE THREAD

**Issue by bingtimren** [vuejs/vuejs.org#1485]
In this page: https://vuejs.org/v2/guide/components.html, there's a sample for v-bind.sync:

```
 The .sync modifier can also be used with v-bind when using an object to set multiple properties at once:
 <comp v-bind.sync="{ foo: 1, bar: 2 }"></comp>
 This has the effect of adding v-on update listeners for both foo and bar.
```
 

What do foo and bar syncs to? In the previous example foo syncs to bar by declaring :foo.sync="bar", in this example, foo syncs to a number "1" and bar syncs to number "2"? If child components emits an event "update:foo' with value 3, how to update 1 to 3? 

Is this an error in the example or I misunderstood something?

**Comment by chrisvfritz** [comment]
Try the example in a JSFiddle. 🙂 You should see that the `update:foo` event does update 1 to 3, without having to do anything else. 1 and 2 are the initial values, just as `bar` contained the initial value for the previous example. Does that make sense?

**Comment by bingtimren** [comment]
https://jsfiddle.net/nzpxr8t2/39/

I tried the example in a JSFiddle. I can sync with :foo.sync="pfoo" syntax but cannot make it right with the "v-bind.sync=" syntax. Can you look at the example please? Thanks!

**Comment by chrisvfritz** [comment]
It looks like referencing a dynamic object works (e.g. `v-bind.sync="$data"`), but you're correct that referencing a literal object (e.g. `v-bind.sync="{ foo }"`) does not. We've corrected this in our soon-to-be-merged rewrite of the Components docs and will investigate further in Vue core. Thanks! 👍
