### ISSUE TITLE
video link in Introduction of getting started guide opens a blank tab on Firefox

### ISSUE THREAD

**Issue by jnizet** [vuejs/vuejs.org#1490]
I just started reading the introduction section of the getting started page at https://vuejs.org/v2/guide/.

Clicking on the "created a video" link, in Firefox 58.0.2, opens a blank new tab and switches to the tab, and starts a video in the previously opened tab. Not a big deal, but not very reassuring when the documentation of a view-centric framework has a bug in the first link you click when learning about it ;-)

**Comment by chrisvfritz** [comment]
Thanks for reporting the problem! I just fixed it, but don't worry, the docs aren't built with Vue. 😉 This was actually a bug with the static site generator we use interpreting `javascript:;` as an external site and adding `target="_blank"`.
