### ISSUE TITLE
[Cookbook] Use of slot-scope

### ISSUE THREAD

**Issue by voluntadpear** [vuejs/vuejs.org#1513]
It would be nice to have some examples of how powerful slot-scopes can be. There are many use cases for this, like having a component that gives you the current cursor position and let you render whatever you want.

Given how popular the render props pattern is in the React world and how many of those things can be achieved with slot-scopes, having a recipe with some examples would be nice.

**Comment by sdras** [comment]
Great! Sounds like a wonderful addition

**Comment by NataliaTepluhina** [comment]
Closing this because now we have a great example of scoped slots in https://github.com/vuejs/vuejs.org/pull/1754
