### ISSUE TITLE
[Cookbook] Vue PWA 🎉🎉

### ISSUE THREAD

**Issue by matteo-hertel** [vuejs/vuejs.org#1518]
There are a lot of talks, tutorials, screencasts about building a PWA with VUE, there are also a lot of tools, it can all get daunting for people so if an official section of the cookbook is dedicated to PWAs it'll give people a place where to start explore PWAs

I think a base example can show how to spin up a PWA with Vue CLI and just highlight some of the key concepts like`manifest.json` and service worker, then move on to the tooling around a PWA, how to test with Lighthouse and finally some production tips (for instance a PWA must be served from https)

As a bonus or advanced section, how to build a PWA from scratch using Workbox can be shown.

Summary:
- Basic example
  - Use Vue CLI to set up a PWA
  - Key concepts `manifest.json` and service workers
- Tooling
  - Lighthouse
- Advanced 
  - Use workbox to build a Vue PWA

I'm currently building a PWA (actually several PWAs 😄 ) with Vue and I built a ton of them for personal projects and production with Polymer (both 1.x and 2.x) and React and I'd be honoured to add this section to the Vue official docs

cc @sdras (you must be getting tons of notifications, sorry about that 😅 )

**Comment by sdras** [comment]
This sounds great but you already filed two other recipes- it might be good to file one at a time so you don't overwhelm yourself :) Let me know if you want to close this out for now until you make traction on the other two.

**Comment by matteo-hertel** [comment]
That's true, I've created the top 3 I had on my list of "I wish this was in the official doc" and follow a logical order Development (Storybook), Production (deploy to CDN), Enhance (PWA)

I also wasn't sure I it was ok for me to tackle the ideas straight off or need some discussion upfront, so I raised them all in one go, feel free to close this one, once the other two are done, I'll come back to this one 😄

**Comment by sdras** [comment]
We definitely do require some discussion upfront- and to be clear, we're really excited about these additions! I just don't want you to feel like you've bitten off more than you can chew. Ok I'll close this one, but let me know when you're ready to reopen it! It sounds like a great idea.
