### ISSUE TITLE
Translate Docs to Indonesian- work in progress

### ISSUE THREAD

**Issue by donnisnoni95** [vuejs/vuejs.org#1522]
Its very nice for me to contributing translating The official documentation site for   ###Vue.js to indonesian

**Comment by chrisvfritz** [comment]
Great to hear! Let me know if you have any questions. 🙂

**Comment by gustialfian** [comment]
I am from indonesia and i love to help, is there anything that i can do?

**Comment by adi88nugroho** [comment]
I think another person was begin the project earlier https://github.com/jefrydco/id.vuejs.org

**Comment by isatrio** [comment]
Hi guys, can I help you with translation. I wan to start to translate also, but if you guys have started it out, let me join. 
@adi88nugroho look like the repo is not active, and feels like forking from someone that not active also. still far from finish.

**Comment by isatrio** [comment]
Hi @chrisvfritz,

May we retake this. look like not active anymore. We are at gresikDev (developer community in Gresik) has a program to translate for some framework documents. We will start with this if we can take over.

**Comment by cloudsbird** [comment]
Hi everyone looks like no one would like to start translate again. So, I am trying to start and translate it from today. you can fork or see my progress at https://github.com/cloudsbird/vuejs.org if you interest in it.

**Comment by aftarfadilah** [comment]
Hi @cloudsbird , it seems your translation repositories is inactive. I would like to continue your translation by forking your repository.
@isatrio There is already a translation repository for indonesia [vuejs-id](https://github.com/vuejs-id/docs) but it's already stale and inactive for a long period of time. I was searching this repository and can't find any Bahasa Indonesia translation work in progress. As you're currently speaking as a community, can you create `a little` bit official version for the translation?

**Comment by phanan** [comment]
I'm closing this issue as an effort to tidy up our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
