### ISSUE TITLE
'currencyValidator is not defined' on Components page.

### ISSUE THREAD

**Issue by tbtalbottjr** [vuejs/vuejs.org#1523]
FYI

**Comment by chrisvfritz** [comment]
Hm, I wasn't able to reproduce this, so I think it may have been a temporary CDN issue. This example will also be replaced on Monday, so even if there's something else going on, it won't be a problem for long. 🙂

**Comment by tbtalbottjr** [comment]
My bad.  Privacy Badger was blocking the CDN.
