### ISSUE TITLE
Docs: Need clarification on data referenced for functional components

### ISSUE THREAD

**Issue by bencodezen** [vuejs/vuejs.org#1527]
In the docs for Functional Components in the [Render Functions](https://vuejs.org/v2/guide/render-function.html) section, `data` is referred in two different places that is initially confusing:

> In cases like this, we can mark components as functional, which means that they're stateless (no data) and instanceless (no this context).

>Everything the component needs is passed through context, which is an object containing:
>    ...
>    data: The entire data object passed to the component

From talking with @chrisvfritz, these refer to two different things. So, this issue is to track how it is either defined or clarify it for future readers.

**Comment by LinusBorg** [comment]
Just for reference:

* the former ``data` refers to this: https://vuejs.org/v2/api/#Options-Data
* the latter refers to this: https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth


Maybe a small change such as this might be enough:

```diff
- which means that they're stateless (no data)
+ which means that they're stateless (no reactive component [data](https://vuejs.org/v2/api/#Options-Data))

- - data: The entire data object passed to the component
+ - data: The entire [data](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth) object of the passed to the component by the parent's render function.
```
