### ISSUE TITLE
Question of detail description of vm.$refs  

### ISSUE THREAD

**Issue by LiuwqGit** [vuejs/vuejs.org#1529]
first, show my opinion:

An object that holds child components and **DOM element** that have ref registered.

Explanation:

![image](https://user-images.githubusercontent.com/7065327/37957765-5a254e44-31e1-11e8-9731-75d6962fb0b7.png)
Form this property description, I see that `vm.$refs.p` is represented as a DOM node.

![](https://user-images.githubusercontent.com/7065327/37953408-68210ab2-31d5-11e8-9100-4c4d75c026b8.png)

![](https://user-images.githubusercontent.com/7065327/37953562-d2f94e26-31d5-11e8-8ea6-6391b1c6d3bf.jpg)
so, I think that `vm.$refs`  represents:
An object that holds child components and **DOM element** that have ref registered.

please correct me.

[中文说明](https://github.com/vuejs/cn.vuejs.org/issues/696)

**Comment by donnysim** [comment]
As far as I used it, the documentation is correct. If you put `ref` on non-component element, the value is an HTMLElement, if `ref` is put on component element - it is a component object.

When put on component, you can access the components data and methods, and it's `$refs` etc. - `this.$refs.modal.close()`, `this.$refs.modal.$refs.closeButton.style.display = 'none'` etc..

**Comment by chrisvfritz** [comment]
@LiuwqGit Please forgive me, but I'm unclear on what the question is. 

> so, I think that vm.$refs represents: An object that holds child components and DOM element that have ref registered.

Yes, that's exactly right. 🙂 Did the current text suggest something different to you?

**Comment by LiuwqGit** [comment]
![image](https://user-images.githubusercontent.com/7065327/38180700-23ef0930-3661-11e8-90dc-a76007e22034.png)


vm.$refs  
Details:

> An object that holds child components that have ref registered.

My thinking is whether I need to add element components，Details：

> An object that holds child components `and DOM element `that have ref registered.

**Comment by chrisvfritz** [comment]
I see - thanks for clarifying! I just pushed up a fix. 🙂
