### ISSUE TITLE
Adding nextTick information in v-for

### ISSUE THREAD

**Issue by a1626** [vuejs/vuejs.org#1536]
A lot of time user might want to do some action after `v-for` is finished rendering. This can be done via `Vue.nextTick` function. I think vue docs can explicitly point this out to user.

**Comment by a1626** [comment]
I'll be more than happy to do the edit if collaborators think that this is a valid request

**Comment by chrisvfritz** [comment]
Thanks for the suggestion! 🙂 Could you give an example of the kind of use case you'd like to see better described?

**Comment by a1626** [comment]
In my case i was dynamically adding data to a `v-for` which would have scrolled my `input` element out of view. So to scroll input into view i had to use `nextTick` so as to make sure that the loop is rendered beforehand.

**Comment by chrisvfritz** [comment]
Thanks for explaining. 🙂  In this case, the `updated` hook should have been able to solve the same problem, so I don't think there's actually a need to add `nextTick` this early.

**Comment by a1626** [comment]
Thanks for pointing that out. I was actually looking for something like `updated` hook, but ended up using `nextTick`. 
But, will we know what got updated in the hook? I know it's not required in my case but just out of curiosity.

**Comment by chrisvfritz** [comment]
No, in cases where you need to react to some specific changes, I recommend watchers.

**Comment by a1626** [comment]
oh! Right. Thanks for the help.
