### ISSUE TITLE
Missing object syntax example for v-on API

### ISSUE THREAD

**Issue by znck** [vuejs/vuejs.org#1555]
The `v-on` API docs (https://vuejs.org/v2/api/#v-on) does not have object syntax example.

**Comment by chrisvfritz** [comment]
Actually, I do see both a note and example about `v-on`'s object syntax, so this seems to be covered.

**Comment by znck** [comment]
Oh! I don't know how I missed it. Sorry!

**Comment by chrisvfritz** [comment]
No worries. 🙂
