### ISSUE TITLE
Make cookbook available in search results

### ISSUE THREAD

**Issue by robaxelsen** [vuejs/vuejs.org#1561]
The first times I wanted to check out the cookbook again (after initially learning about it's existence), my first impulse when looking for it was to:
1. ...go to the main page
2. click the search field
3. enter keyword and search for it

If I got no results in the search, my next impulse was to google for it, only to realize when I found it that it was located at vuejs.org after all. Took me a little time to realize and remember that it was available only via the "Learn" menu.

As I see that "Guide" and "API" is available both in the "Learn" menu and in the search results, I propose to also add "Cookbook" to the search results.

[Posted recently about this here,](https://github.com/vuejs/vuejs.org/issues/1418#issuecomment-376824564) but decided it was a good idea to follow up here with an actionable suggestion for how to improve the UX.

Illustrative screenshot:
![](https://user-images.githubusercontent.com/13132899/38021061-2693f300-327c-11e8-9c10-e293a4b42c64.png)

**Comment by chrisvfritz** [comment]
Great idea. 🙂 While we're at it, I just noticed the Style Guide is also not being indexed. @maxiloc How should we go about adding the [Style Guide](https://vuejs.org/v2/style-guide/) and [Cookbook](https://vuejs.org/v2/cookbook/) to the index?

**Comment by s-pace** [comment]
👋 @robaxelsen @ @chrisvfritz ,

I am working [on DocSearch](https://community.algolia.com/docsearch/documentation/docsearch/introduction/) with @maxiloc.

I have updated your DocSearch configuration and populate your index in order to encompass the ressources you point out. Change are live.

Let us know if you have any feedback. Btw, please note that we have a v2 for our Search-UI.

Cheers

**Comment by robaxelsen** [comment]
@s-pace Awesome, thanks! Have a great weekend :tada:

**Comment by s-pace** [comment]
@robaxelsen You are welcome.

Just to give you a quick idea of it: http://vuejs-docsearch-v2.surge.sh/

**Comment by robaxelsen** [comment]
@s-pace That link takes me to https://vuejs.org/v2/guide/. Was that intentional?

**Comment by s-pace** [comment]
Yes it is only the front end part that matters. It introduces the Serach-UI, the global behaviour stay the same
