### ISSUE TITLE
Production Deployment: Using webpack on production mode?

### ISSUE THREAD

**Issue by bloggervista** [vuejs/vuejs.org#1580]
In docs it says to use webpack in production we should do 

```
var webpack = require('webpack')

module.exports = {
  // ...
  plugins: [
    // ...
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    })
  ]
}
```

but we think we can do it simply using mode property only, isn't it?

```
module.exports = {
  mode: 'production'
};
```

Or is it due to webpack version? 

Links:
https://vuejs.org/v2/guide/deployment.html#With-Build-Tools
https://webpack.js.org/concepts/#mode
Thank you .

**Comment by CubeLuke** [comment]
Setting the mode to `production` was something that was new for webpack 4, so the vuejs docs weren't updated to reflect that. Just having the mode should be enough.
