### ISSUE TITLE
Introduction not clear for beginner

### ISSUE THREAD

**Issue by paddyjo** [vuejs/vuejs.org#1584]
Examples are easy to follow using jsfiddle but I can't see where it says to place the html and JS (from examples) if I want to use vue from a html file locally. I am a beginner but I would like to get up and going quick without having to google this.

**Comment by sdras** [comment]
Hi @paddyjo!

Though I do appreciate your position, the Vue guide is meant for people new to Vue, not really for beginning web development as a whole. I believe what you're describing falls more into the latter category. We can't teach all of web development here, we have to retain some focus. I actually think it's _great_ to google this! Whether you're a beginner or seasoned programmer, google will be your best friend in finding your way around the web landscape. That said, we do outline how to include Vue in a script tag from a CDN in your index file:

[https://vuejs.org/v2/guide/#Getting-Started](https://vuejs.org/v2/guide/#Getting-Started)

You could add another script tag that references a local main.js file where you then write your Vue code :)

Also, here are some resources that might help get you going with web dev in general:
- [https://www.codecademy.com/](https://www.codecademy.com/)
- [https://www.codeschool.com/](https://www.codeschool.com/)
- [https://css-tricks.com/guides/beginner/](https://css-tricks.com/guides/beginner/)

Hope that helps!
