### ISSUE TITLE
[Cookbook] Basic deployment to firebase hosting

### ISSUE THREAD

**Issue by WillowHQ** [vuejs/vuejs.org#1585]
I'd like to contribute a quick recipe to describe the simplest way to deploy vue-cli to firebase hosting. 
This is introductory level, the purpose of it is to help new users quickly deploy. It is not meant to be a best practice in industry standard production deployments.

**Comment by sdras** [comment]
I think this is a great idea for a recipe, but the recipe linked doesn't follow cookbook format. Looking forward to your revision!

**Comment by WillowHQ** [comment]
Sorry for the delay. Instead of writing out a recipe, I added a deployment section to the vue-cli docs/README.md . I felt that was more appropriate. Thanks !
