### ISSUE TITLE
Question about modify the length of the array

### ISSUE THREAD

**Issue by byog** [vuejs/vuejs.org#1594]
The way of modifying the length of the array In Vue's guide is

``` vm.items.splice(newLength) ```

but it is not effective immediately I found in practice, my main code is
```
      ... 
      <li v-for="(item,index) in items">{{ index }} : {{ item }}</li>
    
      var app = new Vue({
         el: '#app',
         data: {
            items: [1, 2, 3]
         }     
      }
      ...
```

When I execute in chrome console 
``` 
     app.items.splice(10)       // UI didn't changed
     app.items.length           // 3, modification did not succeed
     app.items.length = 10      // or app.items[9] = 10, UI didn't changed
     app.items.length           // 10
     app.items.splice()         // or other array’s mutation methods(eg. sort(),shift() ...), UI changed
``` 

As described above, I think **vm.items.splice(newLength)** is invalid.

**Comment by chrisvfritz** [comment]
It will work for _decreasing_ the number of items in array, but increasing the size and an array and filling in the extra indices with empty items. Could you provide more context for the use case?

**Comment by byog** [comment]
Sorry, reply to you now. **[Here](https://jsfiddle.net/728wu5eL/2/)** is my whole code.

**Comment by chrisvfritz** [comment]
@byog I think the code example you linked to may be incomplete, because I didn't see `splice` used there.

**Comment by byog** [comment]
@chrisvfritz I didn't use splice in code, it used in chrome console.
``` 
     app.items.splice(10)       // UI didn't changed
     app.items.length           // 3, modification did not succeed
     app.items.length = 10      // or app.items[9] = 10, UI didn't changed
     app.items.length           // 10
     app.items.splice()         // or other array’s mutation methods(eg. sort(),shift() ...), UI changed
```

**Comment by chrisvfritz** [comment]
I think I'm still not sure what the use case is for increasing the length of the array without adding items to the array.

**Comment by byog** [comment]
You mean it will work for decreasing the number of items in array, but increasing the size with empty item(eg. app.items.splice(10)) doesn't work, app.items.splice(3,0,'d','e','f','g','h') will work.

**In other words, use splice() to  increasing the size of array must provide non-empty item.**

**Comment by chrisvfritz** [comment]
Yes, the way `splice` works, you can only increase the size of the array by adding items to the array. 👍
