### ISSUE TITLE
Computed docs demo for watch suggests it cannot be done with computed - but it can

### ISSUE THREAD

**Issue by chrisbruford** [vuejs/vuejs.org#1598]
[Doc in question](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/computed.md)

> In this case, using the watch option allows us to perform an asynchronous operation (accessing an API), limit how often we perform that operation, and set intermediary states until we get a final answer. None of that would be possible with a computed property.

But I believe I have a [fiddle](https://jsfiddle.net/cbruford/aa3L8n9e/) showing that this is not true 

So I believe it is possible, but should be avoided; the computed property needs to reference a data property which is a little inelegant but also could be changed directly without triggering the API lookup

Perhaps a reword along the lines of

> In this case, using the watch option allows us to perform an asynchronous operation (accessing an API), limit how often we perform that operation, and set intermediary states until we get a final answer. While this is _possible_ with computed properties; it is not recommended as it leads to convoluted and brittle code.

**Comment by chrisvfritz** [comment]
I think it's fine the way it is. _Technically_, a computed property can be involved, you can't accomplish this with a computed property alone - this is a hack that also requires a proxied data property and a method. The computed property is little more than a getter and setter at this point.
