### ISSUE TITLE
xfive logo pixelated/incorrect on Sponser Vuejs Development

### ISSUE THREAD

**Issue by ansipes** [vuejs/vuejs.org#1603]
https://vuejs.org/support-vuejs/

The xfive logo looks incorrect:

<img width="601" alt="xfive-error" src="https://user-images.githubusercontent.com/25012869/39384413-ba0ea104-4a3a-11e8-82e4-0e1fdd8a2dcc.png">

Should look more like this:

![xfive-correct](https://user-images.githubusercontent.com/25012869/39384514-13a3073c-4a3b-11e8-9ce0-e0dd07d996af.jpg)

**Comment by chrisvfritz** [comment]
Thanks for reporting this! Unfortunately, there isn't much we can do from our end, as we pull these images directly from Open Collective. If you work at xfive or happen to know someone who does, they should be able to upload a different image to Open Collective. Within a few days, it will have updated on our site. 🙂
