### ISSUE TITLE
Good example of child emitting to a parent

### ISSUE THREAD

**Issue by sdras** [vuejs/vuejs.org#1612]
Someone brought up to me that they didn't think the docs had a good, simple example of a child emitting to the parent component. I looked around a few times and think this might be true. It's possible that I missed it, but if I did after looking, and this person did as well, if it does exist we might want to make it more prominent. @chrisvfritz you're probably the one that knows best.

**Comment by chrisvfritz** [comment]
If you both looked for a simple example and didn't find what you were looking, I agree there's definitely a problem. 🙂 

The first example we provide is [this blog post example](https://vuejs.org/v2/guide/components.html#Sending-Messages-to-Parents-with-Events) on the Components Basics page. Is there a way you think we can/should simplify it? Or were you thinking of first moving away from the blog post example to show something simpler like:

```js
Vue.component('base-button', {
  template: `
    <button v-on:click="$emit('click')">
      <slot></slot>
    </button>
  `
})
```
```html
<div id="example">
  <base-button v-on:click="sayHi">
    Click me
  </base-button>
</div>
```
```js
new Vue({
  el: '#example',
  methods: {
    sayHi: function () {
      alert('Hi!')
    }
  }
})
```

then coming back to the blog post example? 

We could also possibly replace it with an expansion of the `<button-counter>` example:

```js
Vue.component('button-counter', {
  data: function () {
    return {
      count: 0
    }
  },
  methods: {
    addOne: function () {
      this.count++
      this.$emit('add-one')
    }
  },
  template: `
    <button v-on:click="addOne">
      You clicked me {{ count }} times.
    </button>
  `
})
```

```html
<button-counter v-on:add-one="total++"></button-counter>
<button-counter v-on:add-one="total++"></button-counter>
<button-counter v-on:add-one="total++"></button-counter>

<p>The counters were clicked a total of {{ total }} times.</p>
```

This is a bit simpler, but one potential issue is we could hurt the flow of the page this way, since we don't get to just expand on the previous example. I feel like the `<button-counter>` example is also a bit more contrived. (Then again, I was never 100% happy with the button to increase text size either.)

What are your thoughts?

**Comment by sdras** [comment]
Ah, yeah I see it- actually I had read through it before but since it wasn't exactly just "showing how to emit" I didn't think of it when it was brought up. This particular example didn't come up in search for me, either, and when I looked at the API, [it did seem a bit scarce](https://vuejs.org/v2/api/#vm-emit). So maybe in order to not interrupt the flow of the page we could add the simplest possible example to the API docs? That way we could link off to it without disrupting the flow of the page.

I started making a [codepen collection](https://codepen.io/collection/db363299f0318f24902ad5f8494248ed/) of some examples of different ways to emit. They're still a little rough yet, but do you think it would be helpful to move the pens to the Vue account and put them somewhere for people to explore? I can give you access to our codepen account if I haven't already done so, so that you could edit them, too. If not, I'll just use the materials for my workshops or an article or something.

**Comment by dasjestyr** [comment]
The wording is a bit confusing as well. In the component example, it says that $emit will send the event to the parent. However, when I created two separate blocks that had a <blog-post> repeater in it, button clicks would emit the event to both blocks. It is unclear as to what "parent" really means in this context.

**Comment by dasjestyr** [comment]
<div id="app">
    
    <div :style="{ fontSize: postFontSize + 'em' }">
        <blog-post 
            v-for="post in posts"
            v-bind:key="post.id"
            v-bind:title="post.title"
            v-bind:content="post.content"
            v-on:enlarge-text="postFontSize += 0.1">
        </blog-post>
    </div>
    
    <div :style="{ fontSize: postFontSize + 'em' }">
            <blog-post 
            v-for="post in posts"
            v-bind:key="post.id"
            v-bind:title="post.title"
            v-bind:content="post.content"
            v-on:enlarge-text="postFontSize += 0.1">
        </blog-post>
    </div>
</div>

**Comment by dasjestyr** [comment]
In the component example, it says that $emit will emit the event to the "parent" but it is unclear what the "parent" is, in this context. For example:

```
<div id="app">
    <!-- what I thought was the 1st 'parent' -->
    <div :style="{ fontSize: postFontSize + 'em' }">
        <blog-post 
            v-for="post in posts"
            v-bind:key="post.id"
            v-bind:title="post.title"
            v-bind:content="post.content"
            v-on:enlarge-text="postFontSize += 0.1">
        </blog-post>
    </div>
    <!-- what I thought was the 2nd 'parent' -->
    <div :style="{ fontSize: postFontSize + 'em' }">
            <blog-post 
            v-for="post in posts"
            v-bind:key="post.id"
            v-bind:title="post.title"
            v-bind:content="post.content"
            v-on:enlarge-text="postFontSize += 0.1">
        </blog-post>
    </div>
</div>
```

If I click *any* of the buttons, then *everything* gets updated. I realize they're both sharing the same view model, however, based on how the example is written, I would assume that if I clicked a button inside of the 2nd "parent" then the event would only be scoped to that 2nd parent and the 1st parent would never receive the event and thus not be updated.

**Comment by chrisvfritz** [comment]
@sdras 

> So maybe in order to not interrupt the flow of the page we could add the simplest possible example to the API docs?

I like that! Should I use the button example I posted above or did you have any idea for another example?

> do you think it would be helpful to move the pens to the Vue account and put them somewhere for people to explore?

Yeah, sounds good. 🙂 

> it is unclear what the "parent" is, in this context

In this case, that shared view model (`new Vue` instance) is the parent. Does this explanation make sense: "A component's parent is the Vue or component instance that uses it." Would that clarify things if we added it?

**Comment by dasjestyr** [comment]
> Does this explanation make sense: "A component's parent is the Vue or component instance that uses it."

I think so. So if inside of a component definition "ComponentA" I used components called "ComponentB"  and "ComponentC" -- and inside of ComponentB, I emit an event called "DidThing" then it would be ComponentA that receives the event and also disseminates that back down to all child components, including CompnentB **and** ComponentC? And to that effect, any siblings or ancestors of ComponentA would still be unaware of this event occuring (i.e. out of scope)?

**Comment by sdras** [comment]
I think the button example is a good one! I'll move the pens to the Vue account this week.

**Comment by dasjestyr** [comment]
@chrisvfritz Ok so that's where the confusion is because that's not what I was experiencing. When I find a moment, maybe this weekend, I'll put together a test project that shows what I'm talking about. But basically, I was going through the exercise where the user is able to change the font size for a component. I added two of those components  to the page but the control to increase the font size was being applied to both instances of the component.

**Comment by dasjestyr** [comment]
@chrisvfritz Oh you know what I think it is...

Both components are using the same view model, so the font size is bound to the same value. If sibling A causes an update to that value, then sibling A and B will be updated. It's because of the value binding, not the event. Derp. Thanks :)

**Comment by chrisvfritz** [comment]
@dasjestyr I'm glad we got that figured out. 🙂 Are there any other clarifications you think could improve the experience of other readers?

**Comment by dasjestyr** [comment]
@chrisvfritz No I think your suggestion works, unless you wanna add a diagram. Diagrams are always welcome particularly when dealing with messaging :)

**Comment by chrisvfritz** [comment]
Thanks! We have another issue for adding a reference diagram, so I'll close this then. 🙂
