### ISSUE TITLE
JS snippet should be HTML

### ISSUE THREAD

**Issue by Elfayer** [vuejs/vuejs.org#1617]
Here: https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model

The second snippet below is written in HTML but the code highlight is using JS:
![image](https://user-images.githubusercontent.com/15869149/39794268-0915f5c8-537c-11e8-9cd6-aeccbd2e3353.png)

**Comment by hmatalonga** [comment]
Well spotted! :+1:

I submitted a PR to fix it :wink:
