### ISSUE TITLE
Transition-group mode is not supported

### ISSUE THREAD

**Issue by emileber** [vuejs/vuejs.org#1619]
The following has no effect.

```
<transition-group mode="out-in">
...
</transition-group>
```

Also confirmed in the [`transition-group.js` component source](https://github.com/vuejs/vue/blob/5e3823a5766da1df60481e1e7a20f36d08e716ce/src/platforms/weex/runtime/components/transition-group.js#L9):

```
const props = extend({
  tag: String,
  moveClass: String
}, transitionProps)

delete props.mode
```

As [Evan You said](https://github.com/vuejs/vue/issues/3974#issuecomment-316372415):

> This is unlikely to happen due to the sheer complexity - it will likely introduce too much extra code for a relatively non-critical use case, and the behavior of the transition modes on multiple items can be vague and hard to define. Even if we were to implement it, we'd probably ship it as a separate plugin instead of as part of core.

I feel like this should be explicitly mentioned in the [list transition documentation](https://vuejs.org/v2/guide/transitions.html#List-Transitions). It's easy to assume that it should work, but it won't.

**Comment by sdras** [comment]
Excellent point. I'll try to add a note about that. Pull request to fix also welcome.

**Comment by emileber** [comment]
I could definitely make a pull request for this. I could even translate it to french and pull on vuejs-fr/vuejs.org

I'll setup the project and propose something shortly.

**Comment by chrisvfritz** [comment]
@emileber Doing a chunk of docs work today, so just added a fix for this, but would love to hear your thoughts on it. 🙂

**Comment by emileber** [comment]
@chrisvfritz exactly what I had in mind!

Maybe mentioning the `mode` attribute explicitly in addition to the current message would help as well?
