### ISSUE TITLE
Promote good accessibility practices in example code

### ISSUE THREAD

**Issue by chipit24** [vuejs/vuejs.org#1624]
I came across the following code block in the Vue docs, from https://vuejs.org/v2/guide/list.html#v-for-on-a-lt-template-gt:

```html
<ul>
  <template v-for="item in items">
    <li>{{ item.msg }}</li>
    <li class="divider"></li>
  </template>
</ul>
```

To help promote good accessibility practices, I think these examples could be updated to include any relevant aria attributes, roles, etc.:

```html
<ul>
  <template v-for="item in items">
    <li>{{ item.msg }}</li>
    <li class="divider" role="presentation"></li>
  </template>
</ul>
```
See https://www.w3.org/TR/wai-aria-1.1/#presentation.

Once the accessibility guide (https://github.com/vuejs/vuejs.org/pull/1002) is finished, references to such attributes can link to explanations in the guide.

This is one example, but I'm sure there are others, and I would like to get your thoughts on this :) I could go through the rest of the docs and get a PR put together.

**Comment by sdras** [comment]
This would be fantastic! Even if you wanted to do it a little at a time, I think we would all be super appreciative.

There is also an older PR in to create an accessibility section. The PR has become a bit cumbersome for the original author given his schedule and he's looking for someone to help pick it up again. That's another way to contribute if it interests you. Thanks!
