### ISSUE TITLE
[Cookbook] Normalizing Data in Your Vuex Store

### ISSUE THREAD

**Issue by mattrothenberg** [vuejs/vuejs.org#1636]
I'd like to contribute a cookbook on the merits & process of normalizing the data in your Vuex store. I took a _super_ high-level stab at an introduction + base example – would this topic be relevant for the docs?

**Introduction**
Working with deeply nested data can be downright painful, particularly so in the context of a Vuex store where you often need to traverse an array to find/update an element given its ID. Luckily, there are techniques for making this data easier to work with, namely "normalization." This post aims to demonstrate how normalizing your Vuex store makes for simpler and clearer mutation/flow of data.

**Base Example**

1.  Nested data can be cumbersome and hard to work with.
2.  Flattening this data (and grouping the respective entities within by ID, aka normalization) can make it easier to reason about and manipulate.
3.

Imagine a Vuex mutation where we want to update a user's name. Assuming our store has an array of `User` objects, we might do something like:

```js
state: {
  users: [
    id: 2,
    name: "Matt"
  ]
},
mutations: {
  UPDATE_USERNAME (state, {id, name}) {
    const matchingUser = state.users.find(user => user.id === id)
    matchingUser.name = name;
  }
}
```

Were our data normalized, we could do something like this instead:

```js
state: {
  users: {
    2: {
      id: 2,
      name: Matt
    }
  }
},
mutations: {
  UPDATE_USERNAME (state, {id, name}) {
    state.users[id].name = name
  }
}
```

4.  Notice how our mutations become more terse and likely more efficient (in that we're not iterating over an array to find the item we want to change)

_more to come_ 😱

**Comment by mattrothenberg** [comment]
@sdras Thanks for both the feedback and your consideration. On second thought, I'm going to abandon this cookbook entry in favor of something like a technical blog post. Cheers!

**Comment by sdras** [comment]
Sounds good, thanks!
