### ISSUE TITLE
Avoid the use of unnecessary images, particularly for code

### ISSUE THREAD

**Issue by cannona** [vuejs/vuejs.org#1650]
As a totally blind developer, the use of images for some of the code samples in the docs is rather annoying, to say the least. Is there a benefit to doing things this way? Would folks be open to considering alternatives? Or could there be a way to give access to the raw code, perhaps by turning the images into links, which lead to the code in a text format?

For an example of what I'm talking about, see the introduction section of https://vuejs.org/v2/guide/single-file-components.html

**Comment by cannona** [comment]
I would not recommend putting the code in the alt attribute. It's really only intended for short snippets of text, and would most likely not preserve linebreaks and so forth. 

The longdesc attribute is also something I wouldn't recommend, since it is not well understood by many screen reader users, and has some limitations that make it a poor choice in general.

I think the best option is to make the code available behind a link/button. You could cause this button to toggle between showing the code as text or as a screenshot, or it could just show/hide the code as text.  Either way, this would be nice, since it wouldn't require that the user leave the page. Alternatively, you could just link to a page that only has the code on it.

You could also simply embed the code as screen reader only text, as you mentioned, but the problem with doing that is that having access to the raw code could be helpful for folks who might wish to copy/paste, and for users who require a high degree of magnification, or who perhaps use custom fonts to make text easier to read.  So, if we can make the code available in text to more people than just screen reader users, that would be preferable IMHO.

Hopefully this all makes sense. If not, let me know, and I'll be happy to clarify, or discuss other alternatives.

I very much appreciate your willingness to address this.

**Comment by chrisvfritz** [comment]
Thanks! I followed your suggestion to create text versions of the images. I'd love to hear what you think. 🙂

**Comment by chrisvfritz** [comment]
To provide more information, another reason we started using images here was because highlight.js didn't offer good syntax highlighting for `.vue` files. If someone were able to write that syntax highlighter or was even willing to manually write syntax-highlighted HTML for these two code examples, I'd be willing to remove the images altogether.

**Comment by chrisvfritz** [comment]
Glad to hear it! 😄 I'll close then, but happy to reopen pending new information or if we realize there's a case we still don't handle. Further discussion in this issue is also still welcome.

**Comment by goelrohan6** [comment]
If highlighter.js doesn't work well can we not just embed the gist in the page directly @chrisvfritz?

**Comment by chrisvfritz** [comment]
I believe VuePress (which those docs are using) uses Prism underneath and it looks like an adequate syntax highlighter might exist for that. In that case, I'm open to switching to Prism for these docs, using [hexo-prism-plugin](https://github.com/ele828/hexo-prism-plugin). PR welcome is someone wants to take that on. 🙂

**Comment by chrisvfritz** [comment]
The hexo-prism-plugin docs should give you a good place to get started. Feel free to reach out if you get stuck though. 🙂

**Comment by sustained** [comment]
I know this is a really old issue but I [opened this issue](https://github.com/highlightjs/highlight.js/issues/2062) to request support for Vue SFCs on the highlight.js repo, since I use it anyway for my personal website and could/would make use of it myself.

If you guys are still using highlight.js and still desire `.vue` support then perhaps you could take a moment to give it a :+1:.

**Comment by phanan** [comment]
I believe this issue can be closed now.
