### ISSUE TITLE
[Question] What is the theme used in code blocks?

### ISSUE THREAD

**Issue by robcresswell** [vuejs/vuejs.org#1654]
Hi!

Sorry for the question here, I know it isn't ideal (have tried the Discord, and Google, and no luck.)

What is the theme used in the example code blocks, such as <https://github.com/vuejs/vuejs.org/blob/master/src/images/vue-component.png>? It's quite pleasant and the contrast seems solid too.

Thanks!

**Comment by chrisvfritz** [comment]
The question is actually very specific to this repo, so this is the perfect place for it. I believe Evan made it up very early on in Vue's history. You can see some styles for general code blocks defined [in `_common.styl`](https://github.com/vuejs/vuejs.org/blob/master/themes/vue/source/css/_common.styl), with styles for syntax-highlighting [in `_syntax.styl`](https://github.com/vuejs/vuejs.org/blob/master/themes/vue/source/css/_syntax.styl). You're very welcome to use them yourself if you'd like!

**Comment by robcresswell** [comment]
Awesome, I will do that. Was putting together a highlighting theme for Pygments / Chroma (to be used in Hugo); a lot of themes, pretty as they are, fail the WCAG contrast guidelines. So I think I'll pinch this because it looks like a good start, and I can adjust as required. Thanks @chrisvfritz

**Comment by robcresswell** [comment]
@chrisvfritz https://github.com/vuejs/vuejs.org/pull/1666 - had a go at feeding back some tweaks.
