### ISSUE TITLE
Router lazy loading page is 404

### ISSUE THREAD

**Issue by Narretz** [vuejs/vuejs.org#1656]
I searched for "vue webpack code splitting" with Google and the following link was the second result:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjf6YHW6KrbAhWFsaQKHRpuBqcQFgg1MAE&url=https%3A%2F%2Frouter.vuejs.org%2Fen%2Fadvanced%2Flazy-loading.html&usg=AOvVaw1Tev6PekQWN6-hmsurPn7D

However, the link is 404. So it should either be restored or not indexed at all.

**Comment by chrisvfritz** [comment]
Thanks for reporting this! 🙂 I just opened up an issue for this on the Vue Router repo.
