### ISSUE TITLE
vuejs site running in development mode

### ISSUE THREAD

**Issue by mkastner** [vuejs/vuejs.org#1659]
### Reproduction link
[https://vuejs.org](https://vuejs.org)

### Steps to reproduce
enter https://vuejs.org in browser address bar, check console in browser development tools

### What is expected?
vuejs site running in production mode

### What is actually happening?
vuejs is running in development mode

---
Or is it supposed to run in development mode?
![vue-js-dev-mode](https://user-images.githubusercontent.com/287486/40718517-99db590a-6410-11e8-8d1c-84ed5ac28bf4.png)

**Comment by chrisvfritz** [comment]
It looks like Evan beat me to this. 🙂 Should be fixed now.

**Comment by leopiccionia** [comment]
Isn't it a "feature", as of #1140?

**Comment by chrisvfritz** [comment]
Yes, we just turned off the warning so people don't have to worry about it.
