### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by osipovvictor** [vuejs/vuejs.org#1667]
Секция: [Масштабирование-вниз](https://ru.vuejs.org/v2/guide/comparison.html#%D0%9C%D0%B0%D1%81%D1%88%D1%82%D0%B0%D0%B1%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2%D0%BD%D0%B8%D0%B7)
Именно так — в простейшем случае достаточно просто добавить тег скрипта на **HMTL**-страницу.

**Comment by chrisvfritz** [comment]
I like the suggestion. 🙂 I just updated the page in English, so it should be updated in Russian soon too.
