### ISSUE TITLE
Class and style page in classObject, active should be string

### ISSUE THREAD

**Issue by goelrohan6** [vuejs/vuejs.org#1672]
active is not a defined variable, it should be a string

![image](https://user-images.githubusercontent.com/14099191/41021730-14e6b1d4-6985-11e8-921d-709815cc920d.png)

**Comment by goelrohan6** [comment]
#1673 I have created a pr, can someone please review :)

**Comment by goelrohan6** [comment]
Yes @leopiccionia it can be written as [active] but the point is there is no variable active defined as 'some class'.

**Comment by chrisvfritz** [comment]
Thanks, but the quotes are indeed unnecessary. Either will work, so we've opted for the shorter syntax. 🙂
