### ISSUE TITLE
the grid-template example could be made sortable via the keyboard easily

### ISSUE THREAD

**Issue by YordanGeorgiev** [vuejs/vuejs.org#1677]
Sorry for not doing this the official way ... not ready to get familiar with the whole process , install proj etc. , yet the grid-component could be done sortable via the keyboard by adding the ` tabindex="1" v-on:keyup.enter="sortBy(key)"` : 

```
      <!-- component template -->
      <script type="text/x-template" id="grid-template">
        <table tabindex="1">
          <thead>
            <tr>
              <th v-for="key in columns"
                @click="sortBy(key)"
                :class="{ active: sortKey == key }" tabindex="1" v-on:keyup.enter="sortBy(key)">
                {{ key }}
                <span class="arrow" :class="sortOrders[key] > 0 ? 'asc' : 'dsc'">
                </span>
              </th>
            </tr>
          </thead>
```

Of course the following css could be added tooo ... 
```
th:focus {
   color: #fff;
}
```

In this way both the whole table is navigable with the arrows , and each column is sortable by hitting the Enter ...

**Comment by YordanGeorgiev** [comment]
Also sorting does not properly work for floats : 
```
           a = a[sortKey]
           b = b[sortKey]
          return (a === b ? 0 : a > b ? 1 : -1) * order
```
Change to : 
```
          if ( (!isNaN(parseFloat(a)) && isFinite(a)) && (!isNaN(parseFloat(b)) && isFinite(b)) ) {
            return (a-b) * order
          } else {
            return (a === b ? 0 : a > b ? 1 : -1) * order
          }
```

seems to fix it ...

**Comment by YordanGeorgiev** [comment]
https://jsfiddle.net/YordanGeorgiev/3bpkyc1v/9/

**Comment by phanan** [comment]
Thanks for the PR. However, while I would consider myself a big proponent of accessibility, I believe this change would fall beyond the scope of the example and make it more complex than it should be.
