### ISSUE TITLE
Meetups List Link

### ISSUE THREAD

**Issue by rdytogokev** [vuejs/vuejs.org#1678]
I recently learned about [https://www.vuemeetups.org/](https://www.vuemeetups.org/).

It might be helpful to the community if this were listed on the website menu.
It might fit under the **Ecosystem** tab > **Help** section.

Just an idea.

Thanks for your time, and definately thanks for vue.

**Comment by chrisvfritz** [comment]
I like that! PR welcome. 🙂

**Comment by sdras** [comment]
Thanks for this!
