### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by Gavriliuk** [vuejs/vuejs.org#1684]
In the Russian version of this document (https://ru.vuejs.org/v2/guide/comparison.html) there are two versions of the same paragraph placed one by one, the old and the new one.

The topic is "Модульный (компонентный) CSS" ("Component-Scoped CSS")

The 1st paragraph looks as the prior verison of its English analog. It begins from the statement:
> "За исключением случаев разделения компонентов на несколько файлов (например, посредством CSS-модулей), для ограничения области видимости CSS в React обычно используется подход CSS-in-JS."

The 2d paragraph is very similar, it looks as the newer verison of its English analog. It begins from the statement:
> "За исключением случаев разделения компонентов на несколько файлов (например, посредством CSS-модулей), для ограничения области видимости CSS в React обычно используется подход CSS-in-JS (например, styled-components, glamorous и emotion)."

The English analog begins from the statement:
> "Unless you spread components out over multiple files (for example with CSS Modules), scoping CSS in React is often done via CSS-in-JS solutions (e.g. styled-components, glamorous, and emotion)."

I guess the 1st paragraph of this topic in the Russian version of the document has to be removed.

Thanks!

**Comment by chrisvfritz** [comment]
Thanks for the notice! @gbezyuk

**Comment by gbezyuk** [comment]
@Alex-Sokolov
