### ISSUE TITLE
Become a sponsor button not working

### ISSUE THREAD

**Issue by AlejandroMut** [vuejs/vuejs.org#1687]
The "Become a sponsor" buttons are linking to a broken page: https://opencollective.com/vuejs/tiers/gold-sponsors/7/website

**Comment by cukejianya** [comment]
This is is a problem with open collective and is being worked on. https://github.com/opencollective/opencollective/issues/1127

**Comment by phanan** [comment]
Closing as the issue is no longer valid. Thank you!
