### ISSUE TITLE
Translate Docs to Thai - work in progress

### ISSUE THREAD

**Issue by iphayao** [vuejs/vuejs.org#1689]
Hello Everyone,

I would like to start translate vuejs.org site to Thai and forked vuejs.org to th.vuejs.org project in vuejs-th organisation.

https://github.com/vuejs-th/th.vuejs.org

Welcome to contribute this translation.

Thank you,
Phayao

**Comment by iphayao** [comment]
@sdras How many % of translation that Vue team will be create sub-domain for translation?

**Comment by chrisvfritz** [comment]
@iphayao There's not a definitive rule, but we like people to be near completion when we publish, so that a clear commitment to keeping up the translation has been demonstrated. 🙂

**Comment by phanan** [comment]
I'm closing this issue as an effort to tidy up our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
