### ISSUE TITLE
Nativescript marked as not ready in comparision with other frameworks

### ISSUE THREAD

**Issue by nklayman** [vuejs/vuejs.org#1696]
In the [native rendering](https://vuejs.org/v2/guide/comparison.html#Native-Rendering) section of the comparison with other frameworks, nativescript is said to be coming soon.
> Another option Vue developers will soon have is NativeScript, via a community-driven plugin.

This should be updated to show that it is ready for use in production.

**Comment by jamesgeorge007** [comment]
Shall I proceed?
