### ISSUE TITLE
[Cookbook] Practical use of scoped slots with GoogleMaps

### ISSUE THREAD

**Issue by mateuszRybczonek** [vuejs/vuejs.org#1698]
The base idea is to make it more clear for the developers how/why we can use scoped slots. As I noticed the idea behind the scoped slot is know for many devs, but there is a lack of practical examples on how we could use it. This example helped me and few other persons to understand this concept deeper, so I would like to share it with others :)

Details about the Value
This example shows a bit more clearly how we can use the scoped slots to create a wrapper that initialises a specific object based on external API and expose that object, that is pre-configured and ready to be used.

Real-World Example:
- https://github.com/mateuszRybczonek/v-tracker-vue/blob/master/src/components/GoogleMapLoader.vue
- https://github.com/mateuszRybczonek/v-tracker-vue/blob/master/src/components/VesselDashboardGoogleMap.vue

The example extracts the map initialisation and configuration to a separate component and return the `google` and `map` that is ready to be used in the template to inject any further object into the map (Marker / Line, etc.)

When To Avoid This Pattern:
It might be tempting to create a very complex solutions based on the example, but at some point we can get to the situation where this abstraction becomes an independent part of the code living in our codebase. If we get to that point it might be worth considering extraction to an add-on.

**Comment by sdras** [comment]
This is s a great use of scoped slots! We'd love an entry like this.

**Comment by NataliaTepluhina** [comment]
Closing this as related PR was merged
