### ISSUE TITLE
Wrong documentation for .sync modifier

### ISSUE THREAD

**Issue by tobiasbeck** [vuejs/vuejs.org#1721]
There is an error in the vue.js documentation for the .sync modifier you can find here: 
https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

It states, that you should use a kebab-case event name for the .sync event:

> That’s why instead, we recommend emitting events in the pattern of `update:my-prop-name.` `

This is not correct. because the event must be camelCased to work properly.

**Comment by lordfuoco** [comment]
Also discussed here https://github.com/vuejs/vue/issues/6428
and here: https://github.com/vuejs/vue/issues/8244

**Comment by chrisvfritz** [comment]
Just updated for now, but once [this is merged](https://github.com/vuejs/vue/pull/8297) and released, I'll be changing it back. 🙂
