### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by CoffeeandTea** [vuejs/vuejs.org#1726]
我就觉得官方文档中 “深入响应式原理”一章中，对于数据绑定的解释那里表达的不够清楚，明白。文档上是这么说的：当你把一个普通的 JavaScript 对象传给 Vue 实例的 data 选项，Vue 将遍历此对象所有的属性，并使用 Object.defineProperty 把这些属性全部转为 getter/setter。

什么是getter/setter？   翻阅书籍，书中说是访问器属性的其中两个特性。意思是他是一个属性的特性，而不是属性本身。（因为访问器属性还有另外两个跟数据属性相同的特性，configbale  evaluable）,所以你们想表达的是不是：当你把一个普通的 JavaScript 对象传给 Vue 实例的 data 选项，Vue 将遍历此对象所有的（数据）属性，并使用 Object.defineProperty 把这些（数据）属性全部转为访问器属性。   这个意思？

**Comment by chrisvfritz** [comment]
@Jinjiang Would you say this is an issue with the Chinese docs or does this apply to the English docs as well?

**Comment by chrisvfritz** [comment]
@Jinjiang Thanks! Just added the link. 🙂
