### ISSUE TITLE
[HTML/CSS] cli.vuejs.org Navbar Search Unusuable in Certain Window Widths

### ISSUE THREAD

**Issue by njwest** [vuejs/vuejs.org#1728]
## Navbar Search Position Issue

In the [cli.vuejs.org](https://cli.vuejs.org) subdomain, a bit below 1100px browser width (once the nav search starts to cover the nav brand logo, another usually undesirable behavior) and within the Md breakpoint, the Search results are unseeable (as they start to the left off-screen)

Screenshots:

<img width="1010" alt="screen shot 2018-07-29 at 11 06 05 am" src="https://user-images.githubusercontent.com/3742496/43362583-a7417ea0-9320-11e8-9f87-7b564317e3dd.png">

<img width="302" alt="screen shot 2018-07-29 at 11 09 52 am" src="https://user-images.githubusercontent.com/3742496/43362585-abe51034-9320-11e8-8d7a-a3db5d070289.png">

Browser: Google Chrome

**Comment by chrisvfritz** [comment]
This is actually an issue in VuePress, which we're [working on here](https://github.com/vuejs/vuepress/pull/266) so I'll close this since there's nothing we can do from this repo. 🙂

**Comment by ulivz** [comment]
Fixed it at https://github.com/vuejs/vue-cli/pull/2116.
