### ISSUE TITLE
[中文文档]组件注册中组件名大小写，使用 PascalCase翻译错误

### ISSUE THREAD

**Issue by Gxw521** [vuejs/vuejs.org#1744]
当使用 PascalCase (驼峰式命名) 定义一个组件时， 
应该改为PascalCase (帕斯卡命名)

**Comment by JerryYuanJ** [comment]
@Gxw521 `PascalCase` 又称为大驼峰命名，这不是翻译错误。

**Comment by Justineo** [comment]
中文翻译的问题可以发到 vuejs/cn.vuejs.org 项目。谢谢！
