### ISSUE TITLE
Google gives results on user language, not the requested language

### ISSUE THREAD

**Issue by enomado** [vuejs/vuejs.org#1752]
What i've got:
![image](https://user-images.githubusercontent.com/707007/44101849-01d9078e-9ff1-11e8-8bfa-42508a6e8d60.png)

What was expected:
Page in requested language e.g. in English [https://vuejs.org/v2/guide/components.html](https://vuejs.org/v2/guide/components.html)

Possible caused by
![image](https://user-images.githubusercontent.com/707007/44101711-b6a0880a-9ff0-11e8-9c9e-80cee4beccd0.png)

Looks like this behavior was introduced accidentally by https://github.com/vuejs/vuejs.org/pull/1027

Many people like it but for most people its easier to read in English. 

For search engines and SEO its right to show page on users language for any content, but English is superior in our business IMO

**Comment by phanan** [comment]
Thanks for letting us know, but I wouldn't consider this a problem. It's only natural that we receive results tailored to our browser's locale.
