### ISSUE TITLE
Documentation advises to use deprecated keyCode attribute

### ISSUE THREAD

**Issue by deltragon** [vuejs/vuejs.org#1765]
The documentation on Event Handling, specifically on [key modifiers](https://vuejs.org/v2/guide/events.html#Key-Modifiers) advises to use the
[deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) keyCode attribute to detect pressed keys. Only as an afterthought/convenience method it mentions that the KeyboardEvent.key aliases can be used as well.

Ideally the documentation would present the .key alias as the default usage, and mention that usage of keyCode is deprecated.

**Comment by mrmowji** [comment]
It'd be good to mention what's the alternative way to trigger events for keys with no [standard key values](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values), for example alphanumeric keys.
