### ISSUE TITLE
vetur support for type definitions

### ISSUE THREAD

**Issue by csigmanek** [vuejs/vuejs.org#1772]
Hello, as far as I know the official supported library is vetur in VSCode. I want to see type definitions of modules in the editor. So perhaps you can add it to vetur or recommend an extension to install.
I wrote
```
this.$router.push({
  to: 'quiz/single-choice',
});
```

And got the error message: Argument of type '{ to: string; }' is not assignable to parameter of type 'RawLocation'.  Object literal may only specify known properties, and 'to' does not exist in type 'RawLocation'.

The error message is fine. I just want to see the definitions of RawLocation in the IDE. Can you do that?
https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts
is leading to
```
export type RawLocation = string | Location;
export interface Location {
  name?: string;
  path?: string;
  hash?: string;
  query?: Dictionary<string | string[]>;
  params?: Dictionary<string>;
  append?: boolean;
  replace?: boolean;
}
```
I want to see that in my IDE as browsing node_modules or GitHub or google is not very comfortable.

**Comment by LinusBorg** [comment]
This is the repository for the vuejs.org website. 

It's not the right place to ask for support. 

Please use forum.vuejs.org or chat.vuejs.org
