### ISSUE TITLE
Conditional Rendering starts with comparison to unrelated technology

### ISSUE THREAD

**Issue by electric-skeptic** [vuejs/vuejs.org#1780]
From: https://vuejs.org/v2/guide/conditional.html#v-if

Beginning an explanation of functionality by comparison with unrelated, possibly unfamiliar technology may lead to more mystification than it alleviates.
Direct description of the operating principle, perhaps followed by a salient comparison with a related technology to mention any distinguishing behaviour may be more helpful

**Comment by ErickPetru** [comment]
I believe that the comparison makes any sense in this case, since many new users come from templating systems based on handlebars. But I agree that the order matters here, and the comparison could come after the explanation of Vue way like @electric-skeptic suggested.

**Comment by phanan** [comment]
Agreed. Apparently, Handlebars was much bigger and more relevant back when we started the doc, enough to be set as the de-facto example. I doubt it's still the case now :)
