### ISSUE TITLE
Suggestion: place download link on introduction page

### ISSUE THREAD

**Issue by webnard** [vuejs/vuejs.org#1782]
Downloading Vue requires navigating through three pages: from the home page to _Get Started_, and from _Get Started_ to _Installation_.

It would be nice to have a download link and the URL of a CDN right there on the home page, similar to what other JS library hosts are doing (e.g., Bootstrap, JQuery, Rivets).

**Comment by kashwa** [comment]
### Totally agree,
 i had to download it to work on my project. but as a UX i gained from that situation,
 there is no 'manage for clicks', it took me three navigation and some time to get where i want.

**Comment by jamesgeorge007** [comment]
@webnard @kashwa Anybody working on this?

**Comment by phanan** [comment]
Agreed. I think a Download/Install button can be added in place of the current GitHub one – IMHO GitHub the link is less important to the average user and can be put at the top right corner (similar to how most of the other libraries are doing). I can work on such a UI change if the proposal is agreed. Pinging @yyx990803 @chrisvfritz @sdras.

**Comment by sdras** [comment]
As per the comments in #2014, we're going to add a button for installation on the introduction page in leu of replacing the github link.
