### ISSUE TITLE
Change ecosystem's submenu "Webpack Template" to "Vue CLI"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs/vuejs.org#1783]
With the new [Vue CLI 3](), what's the relevance of Webpack Template in the ecosystem menu?

https://github.com/vuejs/vuejs.org/blob/a9af183c91fee41ba4ebcbbf36c011f01dfa24f2/themes/vue/layout/partials/ecosystem_dropdown.ejs#L14

I suggest this menu item changes to:

``` html
<li><a href="https://cli.vuejs.org/guide/" class="nav-link" target="_blank">Vue CLI</a></li>
```

**Comment by LinusBorg** [comment]
Done with #1763
