### ISSUE TITLE
Discrepancies in CDN use between "Installation.md" and "Comparison.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs/vuejs.org#1784]
The `installation.md` recommends linking to a specific version when using Vue from a CDN:

https://github.com/vuejs/vuejs.org/blob/49ffe8eafa38ba59033bbe50efb29b0bd3abd29b/src/v2/guide/installation.md#L40

But `comparison.md` still shows the URL without versioning:

https://github.com/vuejs/vuejs.org/blob/49ffe8eafa38ba59033bbe50efb29b0bd3abd29b/src/v2/guide/comparison.md#L114

I believe it can confuse beguiners about the best approach. Would be better to update the URL at `comparison.md`, wouldn't?

**Comment by phanan** [comment]
The mentioned section in Comparison is only meant to show how simple getting started with Vue is, so I don't see this as a huge problem honestly. t If you believe it is, a PR is always welcome :)
