### ISSUE TITLE
The example given for "Disabling Attribute Inheritance" doesn't work

### ISSUE THREAD

**Issue by estyh** [vuejs/vuejs.org#1787]
The docs show an example for how to disable attribute inheritance (https://vuejs.org/v2/guide/components-props.html#Disabling-Attribute-Inheritance) - I tried, and it doesn't work!
In this example, the placeholder is passed to the input, but class is not, it is applied to the root-element, label. Are the docs wrong, or is something broken in Vue?
As a side note, the example uses a label prop for the child component, but doesn't pass it in as an attribute.
Here is my js-fiddle example, almost straight out of the docs (with some css for clarity)
https://jsfiddle.net/estherh/y12eb6xg/

**Comment by leopiccionia** [comment]
From [docs](https://vuejs.org/v2/api/#inheritAttrs):
> Note: this option does **not** affect `class` and `style` bindings.

Perhaps this note could appear in guide, too?

**Comment by LinusBorg** [comment]
Indeed. And the example should not use `class`, of course.

**Comment by phanan** [comment]
@leopiccionia Any progress on this one?

**Comment by leopiccionia** [comment]
@phanan I've closed my original PR, I'll open an improved one yet today.
