### ISSUE TITLE
Styleguide: Priority A Rules: Private Property Names

### ISSUE THREAD

**Issue by alrdytaken** [vuejs/vuejs.org#1789]
https://vuejs.org/v2/style-guide/#Private-property-names-essential

This rule isn’t completely clear to me, probably because it revolves around the term **custom private properties**, for which no defintion can be found on vuejs.org

So basically it’s straight forward. Applying mixins is simply merging two objects so we need to take care that properties/methods are not overwritten unpredictably. Therefore it advises us to prefix it.

But what exactly is the method ```$_myGreatMixin_update ``` in the example?

a) Is it one to be used by the component consuming the mixin?
So somewhere in the component’s code I'll be writing ```_myGreatMixin_update````

b) Or is ```_myGreatMixin_update``` a computed property which is only used in the mixin itself?

**Comment by LinusBorg** [comment]
> This rule isn’t completely clear to me, probably because it revolves around the term custom private properties, for which no defintion can be found on vuejs.org

Since there are no truly private properties in Javascript, people mostly "simulate" them by using prefixes, usually an underscore. You will find quite some of those private properties on your component instances, Vue's own internal private properties. (i.e. `_vnode`).

A "custom" private property then, is one that *you* are adding to the component instance, not *Vue*.

> But what exactly is the method $_myGreatMixin_update in the example
> a) ...
> b) ....

b)  (but it's a method, not a computed property).

**Comment by alrdytaken** [comment]
Putting a function in the module scope will make them kind of like private.

myGreatMixin.js
```
module.exports = {
  mounted() {
    update();
  }
}

function update(){
  …
}
```
So I think the example is irritating for people using ES6/Node modules. Changing it to an example with a public computed property using a non-public computed property would fit all.

**Comment by LinusBorg** [comment]
That's true, totally agree. 

Would you be up for a PR?

**Comment by alrdytaken** [comment]
Sure.

**Comment by sdras** [comment]
Still interested in submitting a PR for this or should we take it from here?

**Comment by thedamon** [comment]
I still found this rule quite confusing (based mainly on the reasoning that private properties are very poorly defined).

We have had team members interpret this rule to mean that internal computed properties should not begin with `$` where others have argued it doesn't apply in that scenario.. but I don't see any other rules about naming of computed props either and can think of reasons for and against prepending a computed prop with `$`
