### ISSUE TITLE
Can i use vuejs  safely in my project ?  (need to support IE 7,8)

### ISSUE THREAD

**Issue by caibinterry** [vuejs/vuejs.org#179]
Hi, I want to know can i use vuejs safely in my project which is need to support Internet Explorer 7, 8.
I know that vuejs just supports es5 , so I am also going to use es-shims/es5-shim (I think this will help).
I am also know that es5-shim is not support all features of es5, so i ask this issues. : )

**Comment by yyx990803** [comment]
Sorry, Vue uses features that **cannot** be shimmed. The browser must support ES5 natively.
