### ISSUE TITLE
Cookbook/Client-side Storage example description doesn't correspond to the example

### ISSUE THREAD

**Issue by maxirozay** [vuejs/vuejs.org#1793]
At the end of the base example it says:
> You could also store a date representing when the values were stored. With that metadata, the mounted method could make a logical call on whether or not to store the values again, such as in this version below. You can try this version below.

But in the example the mounted method only do:
```
if(localStorage.name) this.name = localStorage.name;
if(localStorage.age) this.age = localStorage.age;
```
The mounted method only check if the values exist, it never "make a logical call on whether or not to store the values again".

**Comment by LinusBorg** [comment]
Would you be so kind and link to the section that you are talking about? We don't haven't memorized very section of the documentation, and I have no idea what you are talking about right now.

**Comment by maxirozay** [comment]
Sure it's in the cookbook/client-side storage https://vuejs.org/v2/cookbook/client-side-storage.html. Go at the last paragraph of the base example.

**Comment by maxirozay** [comment]
@cfjedimaster should you change your CodePen example or should we change the description?

**Comment by maxirozay** [comment]
Ok I can do that.

**Comment by maxirozay** [comment]
Done in #1797
