### ISSUE TITLE
VNode is used in the Guide before it is defined

### ISSUE THREAD

**Issue by cxw42** [vuejs/vuejs.org#1799]
Brand-new to Vue, and I'm reading the Guide front to back.  The term `VNode` is used in the [Custom Directives](https://vuejs.org/v2/guide/custom-directive.html) page.  However, it is not defined until later in the Guide, in the [Render Functions & JSX](https://vuejs.org/v2/guide/render-function.html) page.  I see that was mentioned in [#319 (comment)](https://github.com/vuejs/vuejs.org/issues/319#issuecomment-237098016).

Would someone who actually knows Vue :) be willing to update the Guide so that `VNode` is not used without explanation on the Custom Directives page?  I don't claim to know what would be the best way to accomplish that :) .  Thank you!

**Comment by phanan** [comment]
Would a link e.g. [VNode](https://vuejs.org/v2/guide/render-function.html#The-Virtual-DOM) suffice?

**Comment by cxw42** [comment]
It would certainly be better than nothing :) .  Again, as a rank newbie, I think I would benefit from both the link and a brief intro at the top of the section.  How about something like the below?  (I'm happy to submit a PR if you wish.)

> ### Hooks
>
> A directive definition object can provide several hook functions (all optional).  The hooks fall at various points along the path from a template or render function, through [Virtual DOM](https://vuejs.org/v2/guide/render-function.html#The-Virtual-DOM) nodes ("VNodes"), to real DOM nodes that are presented in the browser.  We'll cover VNodes in more detail later, when we discuss [render functions](https://vuejs.org/v2/guide/render-function.html).  For now, all you need to know is that Vue processes the Virtual DOM, then updates the real DOM based on the Virtual DOM.
>
>  * `bind`...

**Comment by phanan** [comment]
I would actually prefer a `p.tip` after the `update` hook (where we first mention the term), which may simply say

```
We'll cover VNodes in more detail later, when we discuss [render functions](link).
```

**Comment by cxw42** [comment]
You're the expert, so I defer to your judgment.  Thanks!

**Comment by cxw42** [comment]
@phanan Have you had a chance to look at #1855?  I just rebased it onto the latest master.  Thanks!

**Comment by phanan** [comment]
@cxw42 Indeed, this slips my watch :) Thanks!
