### ISSUE TITLE
Example for Shared Store Doesn't work.

### ISSUE THREAD

**Issue by arre-qp-db** [vuejs/vuejs.org#1809]
http://jsfiddle.net/50wL7mdz/752294/

**Comment by Justineo** [comment]
Hi, can you point out where does this fiddle appear in the docs?

**Comment by leopiccionia** [comment]
You should use `{{ sharedState.message }}` instead ([see fiddle](http://jsfiddle.net/leopiccionia/q5mL7xo6/)).

@Justineo It appears in docs here: https://vuejs.org/v2/guide/state-management.html#Simple-State-Management-from-Scratch
