### ISSUE TITLE
Change event not triggered for multi-select box on your site.

### ISSUE THREAD

**Issue by a2zbits** [vuejs/vuejs.org#181]
I have noticed a minor issue with multi-select-box script on your site today. I don't know if this is some bug in VueJS or may be a browser issue. Please have a look at the attached error-screen first. Today, I was testing VueJS on following page of your site:
http://vuejs.org/guide/forms.html

<b>Steps to Reproduce:</b>
- cilck the above link
- select "A" in multi-select. this works and outputs "[A]".
- Finally try to select all values by clicking "A" and drag the mouse far below "C". Release the mouse outside the boundary of multi-select. Now all values are selected, but VueJS could not realize the change event. VueJS will not realize this change even if you change the focus to some other field. It will realize this change only when you click the multi-select once again.

Not sure if this is VueJS bug or browser didn't fire change event. but whatever the case is, it will lead to unwanted results in back-end.

regards,

Ahmed Khan
a2zBits,
Lahore, Pakistan.
![issue](https://cloud.githubusercontent.com/assets/11661091/11091982/7ce11dbe-88a1-11e5-9c59-15a3e1d00058.jpg)

**Comment by yyx990803** [comment]
Thanks for reporting this. I've tested this in Chrome, Firefox, Safari and IE11 and it seems Safari is the only browser with this behavior. This is indeed because Safari is not firing the `change` event when the user releases the mouse outside of the select box. I think this is a Safari bug and you probably should report it at https://bugs.webkit.org/ .

**Comment by a2zbits** [comment]
Thank you for your prompt reply. I faced this issue in Google Chrome Version 46.0.2490.80 m. And amazingly I faced this issue only on your own site. when I copied the same script to a local test file this worked fine even in the same browser. so I think some CSS property of surrounding elements on your site may have caused this.

It is not a big issue. and yes we can close it.
