### ISSUE TITLE
.

### ISSUE THREAD

**Issue by raslan3333** [vuejs/vuejs.org#1810]
https://vuejs.org/v2/examples/
https://codepen.io/renaudtertrais/pen/hwrqH

**Comment by LinusBorg** [comment]
I don't see any benchmarks? What specifically are you referring to?

Also, how does that relate to this repository, which is about Vue's documentation?

**Comment by leopiccionia** [comment]
That specific Vue example seems slow because it's using a 300ms debounce.

**Comment by LinusBorg** [comment]
...which is a good thing to do in many situations.
