### ISSUE TITLE
why can't i use camelCase in html (or as you say 'Non-string template')?

### ISSUE THREAD

**Issue by CoffeeandTea** [vuejs/vuejs.org#1818]
in your doc you just tell me since html is not sensitive about Capitalization, so you should turn all the 

camelCase props into kebab-case......What??  i am just confused about this. and i'v found many people 

are confused with this too.    i can't find any logic in this pice of statement.  as i understanding, since the html is not sensitive about the Cap, so we can write it any way~😂

**Comment by Justineo** [comment]
> since the html is not sensitive about the Cap, so we can write it any way~

The tag names and attributes you declared in your in-DOM template will always be converted to lowercase by the browser no matter which case you write in.

```html
<MyComponent fooBar="1"/>
```

From JavaScript you will only see a `mycomponent` element with a `fooBar` attribute. So a component expecting a prop `fooBar` will never get the value you provide.
