### ISSUE TITLE
v-for alternative

### ISSUE THREAD

**Issue by AlexPitigin** [vuejs/vuejs.org#1823]
Hi all. In most of all case this directive work fine. But i have 10k+ elements. And v-for has frieze. I'll tried to create custom directive with same functional.  But this is not possible with the current directive functionality.

What i guess: add some property to 'v-for' for asynchronous appending to DOM.
P.S. Sorry for my English =) TY.

**Comment by phanan** [comment]
Please use our [forum](http://forum.vuejs.org) or [Discord](https://vue-land.js.org/) for questions like this.
