### ISSUE TITLE
Updated code examples to ES2015, is this relevant?

### ISSUE THREAD

**Issue by samuelgozi** [vuejs/vuejs.org#1829]
Without thinking too much I updated all the documentation to ES2015(es6) and changed the code style to use semicolons and fixed some typos that could cause errors if copy-pasted, however only after finishing all of it I realized that it would cause many conflicts.

Is this relevant or should I forget about it?

**Comment by sdras** [comment]
Hey! Thanks for doing that! I think it would be better for us if you could submit smaller PRs with the typos first so that we can take a look at one thing at a time. Massive PRs tend to get stalled, as you noted, it becomes harder to manage the conflicts.

Re: ES6, @chrisvfritz and I have talked about this a few times, more recently we thought it might be a good direction, though that was a casual conversation so I might be mistaken. We really should hear his take before moving forward. Again, this would probably be best as a smaller PR that's separate from the typos so we can get a clean review. Thanks!

**Comment by samuelgozi** [comment]
@sdras Thanks for replying, when I wrote typos I meant code errors, not grammar. In some cases, there are missing commas and other small errors that would break the code.
At this point, it will be very hard for me to separate those from the other changes.

Overall I made the code more consistent, In many cases, you could find in the same document es6/next syntax and in the next example es5 syntax, as well as different coding styles.

A summary of the most common changes is:
- Anonymous functions into arrow functions(I did check for binding differences, so don't worry).
- In object literals, I changed function properties into methods, for example:
```js
render: function(h) { /* ... */ }

// into
render(h) { /* ... */ }
```
- Inconsistencies in coding styles within the same topic(just to be clear, I wasn't very opinionated, I only made changes when you could find different coding styles within the same document, in the same topics, but there are other cases in which I did use the same syntax all over, for example in render functions.), example:
```js
render: (h) => { /* ... */ }
// Changed into:
render(h) { /* ... */ }
```
- Replaced all the `var` declarations with `const`(I didn't find even one case where `let` was needed).
- Added semicolons everywhere. This one(Is seems...) is an opinionated change, but I feel like it made the code more readable in many cases, for example when chaining objects with indentation, and you are trying to find when does the line end, and when It is a different object, which happened 
a lot in the animations tutorials.

In addition, there were other small changes as I explained above, like missing commas (and other stuff that I can't remember) that would break the code. **And I never touched code within {% raw %} blocks.** This means that the code in the examples is different in syntax to the code in the demos.

**Comment by samuelgozi** [comment]
@phanan I agree with most of your point, and as I said, I didn't think much before doing it so I don't expect this to even be considered, however, I do think that converting the code to es6 should be strongly considered in addition to enforcing a coding style on the examples.

The reason I assumed that this might be a good idea is that most of the docs that I read(i think its safe to say the majority of them) has mixed ES5 and ES6 and mixed use of semicolons.

And I also agree that ideally, the code within `{% raw %}` blocks should be identical to the examples but In the real world its never the case, however, I do understand that it can be a nightmare to maintain(although it might be easier than thought to just automate it, then it adds maintenance concerns again).

Putting that aside for a sec, If it wasn't obvious yet, Im new to contributing to open source projects and I would really like to contribute to Vue, what would be a good place to start doing that(If needed at all)?

And thanks for your time!

**Comment by sdras** [comment]
@samuelgozi a great place to start would be to consider some of those small changes you mentioned where you think the code is actually broken- but in small PRs please. The docs has it's own coding style so please keep that in consideration. If we do move to ES6 for all code samples, it will likely be a larger undertaking that will be decided on with the team and particularly @chrisvfritz. For that reason I will close this issue out but it doesn't mean we aren't considering it.

Another way to contribute would be to check out the other issues in this repo- there are a few that are "low-hanging fruit". In other words, smaller changes that you could make and submit a pull request for.

Thanks!
