### ISSUE TITLE
scoped style with dynamic added DOM

### ISSUE THREAD

**Issue by elaijuh** [vuejs/vuejs.org#184]
I am using jquery-ui which might introduce some DOM in run time. The scoped style will not be applied to the new DOM, any solution on this?

**Comment by azamat-sharapov** [comment]
This repo issue tracker is for vuejs.org website issues. You should ask you _question_ in forum.vuejs.org

As for question, you might want to read about `Vue.nextTick()` or `vm.$nextTick()` and check if it's what you looking for.

**Comment by elaijuh** [comment]
@azamat-sharapov thanks!
