### ISSUE TITLE
[Proposal] Add Marko JS into the comparisons

### ISSUE THREAD

**Issue by VSJ** [vuejs/vuejs.org#1840]
Can you guys also add markojs to the comparisons?

**Comment by sdras** [comment]
I'm not sure anyone here has a lot of experience with it, what in particular would you like to highlight? We could accept a pull request if you're willing to write up the comparison.

**Comment by phanan** [comment]
As the issue's title and context are quite unrelated to each other, I've taken the liberty to change the title – hope you don't mind.

**Comment by sdras** [comment]
@VSJ since we didn't hear back, I'm going to close this out unless you want to contribute. We don't have the background to do this ourselves. Please feel free to reopen, we'd love to add to the guide. Thanks!
