### ISSUE TITLE
Vuejs.org PWA: Save the site into local storage

### ISSUE THREAD

**Issue by OgierM** [vuejs/vuejs.org#1851]
Vuejs.org is already a PWA. It would be nice if it saves the whole website into local storage, so I can use the PWA as an offline documentation.

**Comment by phanan** [comment]
@OgierM Personally I'd use [DevDocs](https://devdocs.io/) for the purpose :)

**Comment by OgierM** [comment]
@OgierM I see that, but the Vue docs can also be used as a tutorial, especially the beginning. It shouldn't be too hard to implement, but it might be a big win for people with sketchy internet connections.
