### ISSUE TITLE
Clarify behavior with null values on prop validation

### ISSUE THREAD

**Issue by afontcu** [vuejs/vuejs.org#1874]
Hi! 👋 This issue (https://github.com/vuejs/vue/issues/9023) reminded me of a discussion we had in our team regarding the [Prop Validation](https://github.com/vuejs/vuejs.org/blob/53b11fbbef932f3ba2cf0596fe198d6be8d70e23/src/v2/guide/components-props.md#prop-validation) doc, where people who started working with Vue found hard to understand the following statement:

```js
Vue.component('my-component', {
  props: {
    // Basic type check (`null` matches any type)
    propA: Number,
//...
```

Does the comment mean that defining the prop as `propA: null` will match any type of prop?
Or that passing `:prop-a=null` in the template would work, no matter the type we define in the prop declaration?

I know it is a small nuance :)

If you find this is an issue worth solving, I'd happily submit a PR.

Thanks for your work!

**Comment by phanan** [comment]
@afontcu Looking forward to you PR :)

**Comment by afontcu** [comment]
Great @phanan! :) 

I noticed that both `null` and `undefined` values won't raise any warning (if the prop is not required, obvs).

Should the new message warn about both edge cases? Or is there a reason to only mention `null` and not `undefined`?

My suggestion would be to reword the comment:

"// Basic type check (`null` and `undefined` values will pass any type validation)"
