### ISSUE TITLE
syntax object in array in v-bind

### ISSUE THREAD

**Issue by IronDos** [vuejs/vuejs.org#1877]
Hey!
I tried to make this:
v-bind:class="{ 'is-invalid': errors.payments[0][index]['selectedMethod']}"
and it doesnt work.
Data structure:
object/array => array => array => object
I tried all the combination with ' " and  + 
in every single place I could.
Maybe I am doing something wrong.
BUT,
If I use laravel blade @{{ errors.payments[0][index]['selectedMethod']}" }}
it works fine but in "" when its need to be v-bind or v-if... no success
If someone have a solution i will be happy to hear before I convert one array to many arrays :(

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) for questions like these. Thanks!
