### ISSUE TITLE
[cookbook] Packaging SFC for NPM: Give more explanation on how to leverage package-browser-field-spec when creating own library

### ISSUE THREAD

**Issue by renoirb** [vuejs/vuejs.org#1879]
In [Cookbook / Packaging SFC for NPM][cookbook-packaging-sfc] ([docs link][cookbook-packaging-sfc-read]) we get an explanation that if we add a `"browser"` object from the library's *package.json*.

```json
{
  "name": "foo",
  "browser": {
    "./bar": "src/bar.vue"
  }
}
```

So that, when in another project, we can add that module as a dependency, then import it using `import`.

```js
import FooBarComponent from 'foo/bar'
Vue.component('foo-bar', FooBarComponent)
```

After some reading, it seems that's planned in tleunen/babel-plugin-module-resolver#41 and looks pretty bleeding edge.

I'm assuming it's been documented here because it is possible.
If it is, a few questions:

* Could we have an example available?
* How about a package (e.g. from a monorepo `@monorepo/foo`) that has more than one component (e.g. a group of component for the same purpose)
* Is that limited to globally available packages, and not namespaced? (example is too vague in docs) Can we do (e.g. `import FooBar from '@monorepo/foo/bar'`)?

[cookbook-packaging-sfc]: https://github.com/vuejs/vuejs.org/blob/master/src/v2/cookbook/packaging-sfc-for-npm.md
[cookbook-packaging-sfc-read]: https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#How-do-I-make-multiple-versions-of-my-component
[babel-plugin-module-resolver-issue]: https://github.com/tleunen/babel-plugin-module-resolver/issues/41

**Comment by renoirb** [comment]
Pinging @chrisvfritz related to demo work in [chrisvfritz/hello-vue-components][hello-vue-components]. Maybe this issue should be moved elsewhere.

[hello-vue-components]: https://github.com/chrisvfritz/hello-vue-components

**Comment by sdras** [comment]
Thanks for the issue! I'm not sure this is necessary for this cookbook entry, we don't require examples for them. (Though I wouldn't be adverse to someone making one if they would like to PR). I think the rest of the questions are good ones but probably out of the scope of the recipe.
