### ISSUE TITLE
RSS for news.vuejs.org

### ISSUE THREAD

**Issue by rightaway** [vuejs/vuejs.org#1888]
http://news.vuejs.org/feed.xml is outdated, and the other RSS link there is updated but only for the podcasts. The RSS feed should contain the actual news.vuejs.org entries as shown on the website.

**Comment by phanan** [comment]
Pinging @shentao.

**Comment by shentao** [comment]
Thanks for bringing this up! The RSS feed was supposed to be updated whenever the build task finishes. Gotta look why it doesn’t.

Let’s move it to the news repo. https://github.com/vuejs/news.vuejs.org/issues/15
