### ISSUE TITLE
example page contains error on ipad

### ISSUE THREAD

**Issue by ZaynJarvis** [vuejs/vuejs.org#1889]
When double tap to enlarge the view on iPad, the example page "example header" position changes and is not clickable.
![image](https://user-images.githubusercontent.com/31875147/48994496-9010e600-f17e-11e8-982e-7b082bd3f44a.png)

**Comment by phanan** [comment]
Thanks for reporting the issue. I can't reproduce it though, and would argue that it would be an edge case anyway, so I'm closing this. Feel free to open another if you don't think so.
