### ISSUE TITLE
Styleguide Priority D v-if/v-else-if/v-else without key Example

### ISSUE THREAD

**Issue by pribilinskiy** [vuejs/vuejs.org#1896]
At https://vuejs.org/v2/style-guide/#v-if-v-else-if-v-else-without-key-use-with-caution
there's a link to a fiddle with an example about side effects https://jsfiddle.net/chrisvfritz/bh8fLeds/
which is very confusing.

In the example both buttons are of type `submit` thus when clicking either the page is reloaded.
Here's a fixed version https://jsfiddle.net/zkywct0j/
But now it's unclear where are the unintended side effects here.

**Comment by phanan** [comment]
Thanks for letting us know. I believe @chrisvfritz has fixed the issue, so I'm closing this ticket. Please feel free to open another if it's not the case. Cheers!
