### ISSUE TITLE
Declarative Rendering

### ISSUE THREAD

**Issue by ebakirmak** [vuejs/vuejs.org#1899]
Hi guys, i have a problem related declarative rendering. 

I am adding value (numbers) to <td> tags . <td> tags are editable.
![p1](https://user-images.githubusercontent.com/11062124/49377404-244cf100-f71b-11e8-90be-63ecadd677a7.png)

and then i send to database. When it saves, i change the date at datepicker.
![p2](https://user-images.githubusercontent.com/11062124/49377537-7ee64d00-f71b-11e8-94dc-2a7561aa6255.png)

After date changed, Planned data is come on the page with AJAX request. This data is show with {{ ... }} 
But data that i add on the page, some td tags can't change with data that come.
![p3](https://user-images.githubusercontent.com/11062124/49377828-32e7d800-f71c-11e8-9c4b-0aecc1d7005a.png)

My code is below. I'm waiting your answers.
![p4](https://user-images.githubusercontent.com/11062124/49377661-d2589b00-f71b-11e8-938b-a841dffa85e2.png)

![p5](https://user-images.githubusercontent.com/11062124/49377933-77737380-f71c-11e8-88c4-829f44b20214.png)

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Discord](https://vue-land.js.org/) for questions like this.

**Comment by ebakirmak** [comment]
Okay.
