### ISSUE TITLE
How are you creating these beautiful architectural diagrams across Vue repositories?

### ISSUE THREAD

**Issue by cb109** [vuejs/vuejs.org#1905]
I do like the look and feel of the diagrams that can be found in the VueJS documentation as well as in its sibling packages like vuex or vue-cli. They all seem to follow the same style guide. Here are a couple of examples:

## From vuejs
![](https://github.com/vuejs/vuejs.org/blob/master/src/images/mvvm.png?raw=true)
## From vue-cli-ui
![](https://cli.vuejs.org/vue-cli-ui-schema.png)
## From vuex
![](https://vuex.vuejs.org/vuex.png)

Since they are usually stored as .png I wasn't yet able to find out how they have been created. **If there is a library that you are using (something like [PlantUML](http://plantuml.com/) or [Mermaid](https://mermaidjs.github.io/)) I'd love to know which?** If they are manually drawn using something like [draw.io](https://www.draw.io/), how do you maintain the same look and feel, is there a template to use?

I really tried to find this information myself and have asked in VueLand, but to no avail, so I hope it's okay to post my question here. Thank you for your time.

**Comment by Justineo** [comment]
Last time I asked, Evan told me he drew these charts manually with [Adobe Illustrator](https://www.adobe.com/products/illustrator.html).

**Comment by cb109** [comment]
Alright, thanks for clarifying :+1:
