### ISSUE TITLE
JQuery conflict with Vuejs 

### ISSUE THREAD

**Issue by DBARUNNER** [vuejs/vuejs.org#1916]
I'm using Metronic  Data-table when I call a Vue function inside of the Table content it's not working. but, when I call outside of the Table content it's working it means that Vue has conflict with jQuery. How should I solve it ?

**Comment by phanan** [comment]
Please ask your question on [our forum](https://forum.vuejs.org) or [Discord](https://discordapp.com/invite/HBherRA).
