### ISSUE TITLE
Explanation of Different Builds doesn't mention browser builds

### ISSUE THREAD

**Issue by StevenLiekens** [vuejs/vuejs.org#1919]
I'm a first-time user following the installation guide and I noticed that the NPM package contains bundles that aren't mentioned anywhere.

 - vue/dist/vue.esm.browser.js
 - vue/dist/vue.esm.browser.min.js

Don't these files deserve a mention here?
https://github.com/vuejs/vuejs.org/blob/a32e1567979aff0b0f7736c6901958b202d4afc9/src/v2/guide/installation.md#explanation-of-different-builds

**Comment by Phinome** [comment]
from `vue` build script: https://github.com/vuejs/vue/blob/dev/scripts/config.js#L96 . we will see, it should more clear at docs.

**Comment by Justineo** [comment]
See https://github.com/vuejs/vue/pull/7110#issuecomment-453686795.
