### ISSUE TITLE
Error on Vue website home page

### ISSUE THREAD

**Issue by David263** [vuejs/vuejs.org#1938]
Copied here from: https://forum.vuejs.org/t/error-on-vue-website-home-page/53856 .

When visiting https://vuejs.org/ 1 and playing the video, the top line of the video is cut off by the web page header. So when the host announces success, you can’t actually see the successful output.

My suggestion would be to test your homepage on a variety of browsers and make sure that the video pane is moved down a bit to clear the header pane.

My environment: 11" laptop, Windows 10 Home, Firefox 64.0.2 (64).

David Spector
Springtime Software

**Comment by Lukyhenson** [comment]
@yyx990803 @David263 i create this PR to solve this => https://github.com/vuejs/vuejs.org/pull/2021

**Comment by phanan** [comment]
Closing via #2021.
