### ISSUE TITLE
Live Demo of Example

### ISSUE THREAD

**Issue by berkansivri** [vuejs/vuejs.org#1947]
You need to check live demo of hackernews example.
https://vuejs.org/v2/examples/hackernews.html

**Comment by phanan** [comment]
Oh wow, this is bad 🤦‍♂️ Thanks for letting us know.

**Comment by dominikstraessle** [comment]
May this issue has been resolved by the following pull request: [#1951](https://github.com/vuejs/vuejs.org/pull/1951)
