### ISSUE TITLE
Myanmar (Burmese) Translation

### ISSUE THREAD

**Issue by hnhtag** [vuejs/vuejs.org#1948]
Hello,

I would like to start translating vuejs.org doc to Myanmar (Burmese).
I forked vuejs.org to mm.vuejs.org project in Vue.js Myanmar.

https://github.com/vuejs-mm/mm.vuejs.org

Welcome to contribute.

Thank you,

**Comment by phanan** [comment]
I'm closing this issue as an effort to tidy up our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
