### ISSUE TITLE
Specify list of built-in events directives

### ISSUE THREAD

**Issue by d8vjork** [vuejs/vuejs.org#1962]
Hi guys ✋,

I was trying to implement some events on my app but as I saw in https://vuejs.org/v2/guide/events.html is no any `@blur` event (even the API docs doesn't explain that we've this since 2.3.x update), maybe more events missing

I think is a good To Do for a little improvement on the docs site, just tell the developer all the possibilities.

And apologies if this is repeated somewhere.

**Comment by Justineo** [comment]
`v-on` on native HTML elements supports all events. `blur` events is only triggered on focusable elements. Please make sure you are applying `@blur` on a focusable element (interactive elements like `<button>`, `<a>`, etc. or with a positive `tabindex` value).

**Comment by d8vjork** [comment]
@Justineo Missed that, I was imagined that those events are limited because of the release of the blur

**Comment by phanan** [comment]
As your issue seems to have been clarified, I'm closing this :) Feel free to open another, or better yet, ask on Discord or our forum.
