### ISSUE TITLE
Clarify v-model in the docs

### ISSUE THREAD

**Issue by yamsellem** [vuejs/vuejs.org#1965]
### What problem does this feature solve?
On multiple occasions, the docs clearly stated that `v-model on a component uses value as the prop and input as the event` ([here](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model) and [there](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components)).

On standards inputs, the documentation ([here](https://vuejs.org/v2/guide/forms.html)) don't explain what can be expected from `v-model`, and how to replace its default behavior (when writting wrappers, for example). I have found that:

* on `input[type=text]` and `textarea`, v-model uses `value` as the prop and `input` as the event
* on `input[type=radio]` and `input[type=checkbox]`, v-model uses `checked` as the prop and `input` as the event — but seems to collide with `value` ([#8379](https://github.com/vuejs/vue/issues/8379))
* on `select`, v-model uses `value` as the prop and `change` as the event

Some issues are related to this:
* dynamic input value with radio buttons don't work in IE11 [#8379](https://github.com/vuejs/vue/issues/8379) — related to [this section of the docs](https://vuejs.org/v2/guide/forms.html#Radio-1) which breaks the default IE9+ compatibility
* <select @input="..."> doesn't work in IE11 but works with v-model [#4701](https://github.com/vuejs/vue/issues/4701)

May you please consider detailing for each control (input, radio, checkbox, select, textarea) what is the  expected behaviour of v-model? This would be of great help!

### What does the proposed API look like?
--

Related to [#9370](https://github.com/vuejs/vue/issues/9370)

**Comment by phanan** [comment]
@yamsellem Thanks for reporting the issue. I see that it's almost an exact copy from https://github.com/vuejs/vue/issues/9370, which has been explained/clarified by @yyx990803. Do you think his clarification doesn't answer your question?

**Comment by yamsellem** [comment]
@phanan I think @yanxyz clarification is:
* the issue is not related to vue but to its docs: I copied it here
* the issue is not related to component but to standard inputs: I've tried to clarify the point here

_In a nutshell_: the expected behavior of `v-model` is not documented for standard inputs, and it would be of great help if it was.

(_so no, @yyx990803 don't answer my question, sorry_)
