### ISSUE TITLE
Doesn't show accurate line number at web browser

### ISSUE THREAD

**Issue by Even-Lau** [vuejs/vuejs.org#1975]
Hello,

I console.log( a ) in my webstorm at 1408, but the browser shows that it is at 1366. 

![image](https://user-images.githubusercontent.com/23427420/52097683-fd217b80-2606-11e9-9d98-744523a6c761.png)

![image](https://user-images.githubusercontent.com/23427420/52097718-16c2c300-2607-11e9-95fc-5c9b8bfe354a.png)

**Comment by Even-Lau** [comment]
dependancies are below:


"dependencies": {
    "axios": "0.18.0",
    "echarts": "^4.2.0-rc.2",
    "element-ui": "2.4.6",
    "js-cookie": "2.2.0",
    "js-file-download": "^0.4.4",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "vue": "2.5.17",
    "vue-count-to": "^1.0.13",
    "vue-router": "3.0.1",
    "vuex": "3.0.1",
    "xlsx": "^0.14.1"
  },

**Comment by LinusBorg** [comment]
This is not related to our website / documentation.
