### ISSUE TITLE
 Visible {% raw %} on styleguide page

### ISSUE THREAD

**Issue by jimutt** [vuejs/vuejs.org#1977]
There are some visibile `{% endraw %} {% raw %}` tags in the styleguide. In the "Prop name casing" and "Multi-attribute elements" sections (https://vuejs.org/v2/style-guide/#Prop-name-casing-strongly-recommended):
![Image of unwanted tags](https://user-images.githubusercontent.com/1392559/52106888-7bc0ed80-25f4-11e9-9b19-db9d2449de98.png)

**Comment by NataliaTepluhina** [comment]
For some reason it happens every time we have one-line code snippet as the last one inside `style-example` block
