### ISSUE TITLE
v-slot directive is not documented in API

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vuejs.org#1989]
We introduced the new `v-slot` directive with Vue 2.6, and we documented it's usage in the Guide. 

But the API page is missing an entry about it.

**Comment by NataliaTepluhina** [comment]
@LinusBorg hmmm maybe a cache issue? I can see `v-slot` entry in the API: https://vuejs.org/v2/api/#v-slot

**Comment by LinusBorg** [comment]
Yeah, seems my cache on mobile didn't update properly.

Thanks.
