### ISSUE TITLE
Visible {% raw %} and {% endraw %} in Components

### ISSUE THREAD

**Issue by supergrecko** [vuejs/vuejs.org#1992]
There's currently a visible raw/endraw block in the components example.

https://vuejs.org/v2/guide/components.html#Base-Example

![image](https://user-images.githubusercontent.com/42585241/52641264-b5d59d80-2ed8-11e9-932a-2a61d042d704.png)

**Comment by NataliaTepluhina** [comment]
Created a workaround here: https://github.com/vuejs/vuejs.org/pull/1979

**Comment by sustained** [comment]
You can also see raw tags here: https://vuejs.org/v2/guide/components-dynamic-async.html

Was just about to report this issue.
