### ISSUE TITLE
examples for each directive

### ISSUE THREAD

**Issue by BrandonPierce** [vuejs/vuejs.org#20]
Had a little idea to create comprehensive fiddle examples for each of the directives to give people a reference point for their projects and clear up any gotchas or quirks. A very quick and crude example for v-text and v-html as an example: 

v-html
http://jsfiddle.net/brandonpierce/rT5LE/

v-text
http://jsfiddle.net/brandonpierce/fzCBJ/

v-show
http://jsfiddle.net/brandonpierce/zKedk/

v-class
http://jsfiddle.net/brandonpierce/zePz9/

v-attr
http://jsfiddle.net/brandonpierce/hD6EV/

v-style
http://jsfiddle.net/brandonpierce/Uf26z/

These fiddles could then be either linked or embedded in the docs page.

**Comment by yyx990803** [comment]
Closing since this is no longer relevant after 1.0 docs revamp
