### ISSUE TITLE
Error on CLI website with Firefox Developer Edition

### ISSUE THREAD

**Issue by Valegar** [vuejs/vuejs.org#2008]
The website https://cli.vuejs.org/ is broken into the browser https://www.mozilla.org/en-US/firefox/developer/.
It seems to be related to the scripts call :
`<script src="/assets/js/app.aa71c60b.js" defer=""></script>`
Firefox DE try to read the content as "text/html", maybe using the attribute `type="text/javascript"` will fix that.

**Comment by Justineo** [comment]
It's working on my side (with Firefox DE 66.0b8). And I didn't find an `app.aa71c60b.js` being loaded. Can you clear your cache and try again?

**Comment by Valegar** [comment]
So strange, I updated Firefox DE 66.0b8 (macOS Mojave) and cleared the cache.
When hard refresh `⌘ + ⇧ + R` the website all is fine, the browser load last assets version :
`<script src="/assets/js/app.152d3e31.js" defer=""></script>`
but once I refresh `⌘ + R` the browser try to reload broken js files :
`<script src="/assets/js/app.aa71c60b.js" defer=""></script>`
I don't figure out why Firefox DE behave this way but the bug clearly come from the browser, not the website (even if I notice that only for cli.vuejs.og).
I close the issue, thanks for your time.
