### ISSUE TITLE
Translating Official Documentation to Bahasa Indonesia

### ISSUE THREAD

**Issue by adityapurwa** [vuejs/vuejs.org#2011]
Hi,

We are trying to help Indonesian developers learning Vue by translating the official documentation to Bahasa Indonesia. I am adityapurwa, a native Indonesian, and together with:

- https://github.com/fahmi-idris
- https://github.com/cyberid41
- https://github.com/rohmad-st

We are trying to translate this documentation. Currently, we finished translating the homepage, installation, and introduction page. We will try to keep the velocity of translating one page per day and doing a repository sync every Friday.

We are inviting others to contribute, you can find the repository at https://github.com/adityapurwa/id.vuejs.org/ (please read the contributing.md file on guide for how to contribute). We might move the repository to a dedicated organization account later if it was necessary.

Our current roadmap is to translate the pages listed below, this list will be updated to reflect the progress of our translation.

- [x] Halaman Awal / Homepage
- [x] Pemasangan / Installation
- [x] Pengenalan / Introduction
- [x] Instan Vue / The Vue Instance
- [ ] Sintaks Templat / Template Syntax
- [ ] Properti Terkomputasi dan _Watchers_ / Computed Properties and Watchers
- [ ] Kelas dan _Style Bindings_ / Class and Style Bindings
- [ ] Rendering Kondisional / Conditional Rendering
- [ ] Rendering Daftar / List Rendering
- [ ] Penanganan _Event_ / Event Handling
- [ ] _Binding_ Masukan Formulir / Form Input Bindings
- [ ] Dasar-dasar Komponen / Component Basics

- [ ] Pendaftaran Komponen / Component Registration
- [ ] Props / Props
- [ ] Event Kustom / Custom Event
- [ ] Slot / Slots
- [ ] Komponen Dinamis dan Asinkronus/ Dynamic & Async Components 
- [ ] Penanganan Kasus-kasus Tertentu / Handling Edge Cases

- [ ] Transisi Masuk dan Keluar / Enter and Leave Transitions
- [ ] Transisi State / State's Transitions

- [ ] Mixins / Mixins 
- [ ] Direktif Kustom / Custom Directives
- [ ] Fungsi Render & JSX / Render Functions and JSX

- [ ] Plugins / Plugins
- [ ] Filter / Filters
- [ ] Komponen Satu Berkas (KSB) / Single File Components (SFC)
- [ ] Unit Testing / Unit Testing
- [ ] Dukungan TypeScript / TypeScript Support
- [ ] Peluncuran Produksi / Production Deployment

- [ ] Routing / Routing
- [ ] Manajemen State / State Management
- [x] Rendering di Sisi Server / Server Side Rendering
- [ ] Lebih Dalam Tentang Reaktifitas / Reactivity in Depth

- [ ] Migrasi dari Vue 1.x / Migrating from Vue 1.x
- [ ] Migrasi dari Vue Router 0.7.x / Migrating from Vue Router 0.7.x
- [ ] Migrasi dari Vuex 0.6.x ke 1.0 / Migrating from Vux 0.6.x to 1.0
- [ ] Perbandingan dengan Framework Lainnya / Comparison with Other Frameworks
- [ ] Gabung dengan Komunitasi Vue.js / Join the Vue.js Community!
- [ ] Berkenalan dengan Tim / Meet the Team

We are asking @yyx990803 to help us set the Netlify membership and DNS for the domain id.vuejs.org.

Thank You! Looking forward to help fellow Indonesian to learn Vue.js!

**Comment by phanan** [comment]
Closing in favor of #2015.
