### ISSUE TITLE
Add contributing steps on readme.md

### ISSUE THREAD

**Issue by Lukyhenson** [vuejs/vuejs.org#2022]
### Description

@yyx990803  @NataliaTepluhina what do you think to add contributing steps to new contributors on readme.md?

**Comment by NataliaTepluhina** [comment]
@Lukyhenson thanks for the proposal! I think these steps are more or less sinilar for any OSS contributions.
@phanan what do you think?

**Comment by phanan** [comment]
I agree. Thanks and looking forward to your next PRs though, @Lukyhenson 🙌
