### ISSUE TITLE
Document all options for object-based props definition in API

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vuejs.org#2027]
This issue is a consequence of a conversation I had on the forum:

https://forum.vuejs.org/t/where-are-prop-options-documented/56692/3?u=linusborg

The user raised valid points, namely that the API docs in that area don't acually document the options that are avaliable except for the brief example that's given. For details about these options, the reader is forwarded to the Props Guide, but information here is spread across multiple sections in the guide, making it hard to get the full picture of what options are available and what their syntax is.

So we should clearly and still briefly document all options that are available in the API docs section:

* type
* default
* required
* validator

**Comment by phanan** [comment]
It seems the "See also" link in the props API section also needs an update. Right now it's pointed to https://vuejs.org/v2/guide/components.html#Props which is no more, and then redirected to https://vuejs.org/v2/guide/components.html#Passing-Data-to-Child-Components-with-Props. The correct URL should be https://vuejs.org/v2/guide/components-props.html I believe.
