### ISSUE TITLE
The "Why vue.js video" still play after popup closing

### ISSUE THREAD

**Issue by marataziat** [vuejs/vuejs.org#2034]

**Comment by Justineo** [comment]
Cannot reproduce here. Is it reproducible from your side and what is your browser & version?

**Comment by NataliaTepluhina** [comment]
Can't reproduce as well.

**Comment by marataziat** [comment]
<img width="700" alt="2019-02-14 13 56 42" src="https://thumbs.gfycat.com/SoupyFriendlyAmericancrow-size_restricted.gif">

**Comment by phanan** [comment]
Can't reproduce (same subdomain, MBP, Chrome 72.0.3626.109). Are you sure you've given the browser enough time to "cool down?" It takes me several second for the icon to disappear.
