### ISSUE TITLE
API navigation is slow due to smoothScroll configuration

### ISSUE THREAD

**Issue by sdouglas** [vuejs/vuejs.org#2037]
Navigating to different [API](https://vuejs.org/v2/api/) entries via the anchor links on the left-hand table of contents (TOC) can be extremely slow.

For example, try clicking one of the top links in the left column, e.g. [#Global-Config](https://vuejs.org/v2/api/#Global-Config), and then scroll to the bottom of the TOC and click a link near the bottom, e.g. [#Server-Side-Rendering](https://vuejs.org/v2/api/#Server-Side-Rendering). I clocked the scroll time at nearly _30 seconds_.

Personally I'd favor just dropping smoothScroll entirely. However, if you wish to keep it, [according to the docs](https://github.com/cferdinandi/smooth-scroll#scroll-speed) you might reconfigure it with the option `speedAsDuration: true` so all scrolls will take the same amount of time.

https://github.com/vuejs/vuejs.org/blob/0d9b754b2f31eb77b2c7767aac2b943a2f8775bd/themes/vue/source/js/common.js#L412

**Comment by NataliaTepluhina** [comment]
@sdouglas thank you so much for spotting this :+1:  ! It definitely worsen user experience on navigation.

Created a PR to fix it

**Comment by phanan** [comment]
😅😅😅
