### ISSUE TITLE
Improve typescript documentation to show how to use vue without imports that would require module bundler

### ISSUE THREAD

**Issue by realmerx** [vuejs/vuejs.org#2042]
Since currently type definitions for vue need to be exported, you have to use import:

```typescript
//ItemComponentl.ts
import Vue from 'vue'

const ItemComponent = Vue.extend({
})
```

To get them work without import you can create custom type definition with declare global:

```typescript
//global.d.ts - name does not matter
import { VueConstructor } from 'vue'

declare global {
    const Vue: VueConstructor
}
```

**Comment by phanan** [comment]
Sorry, I'm lost. What part of the documentation are we looking at?

**Comment by realmerx** [comment]
I am Sorry for not being clear enough :) https://vuejs.org/v2/guide/typescript.html

**Comment by phanan** [comment]
Right, thanks! Still, I'm not very sure what change(s) you want to see there. Do you think a PR would explain your intention better?

**Comment by realmerx** [comment]
Sure, I'll create a pull request for this.

**Comment by realmerx** [comment]
Finally got time to do that :)

https://github.com/vuejs/vuejs.org/pull/2137

**Comment by NataliaTepluhina** [comment]
Thank you for spotting this issue and for your work on the related PR!

Closing this now as https://github.com/vuejs/vue/pull/9912 got merged and now we can use global `Vue `without any additional setup required.
