### ISSUE TITLE
Translate docs to Mongolian - work in progress

### ISSUE THREAD

**Issue by tortuvshin** [vuejs/vuejs.org#2050]
We are would like to start translating vuejs.org docs to the **Mongolian** language.

Translation Repo [vuejs-mn](https://github.com/vuejs-mn/mn.vuejs.org)

Contributors: @doljko @ebatgerel and anyone is welcome to contribute to this translation.

https://vuejs-mn.netlify.com/

Thank you,

Turtuvshin Byambaa

**Comment by phanan** [comment]
Please see #2015.
