### ISSUE TITLE
Proposal: make clear what means "your browser's JavaScript console"

### ISSUE THREAD

**Issue by solatch** [vuejs/vuejs.org#2052]
### Summary

The guide document should make clear what means "your browser's JavaScript console" for each execution environment.

### Expected behavior

I executed the contents of "Getting Started" of guide document by using JSFiddle. 
(Browser: Google Chrome)
https://jp.vuejs.org/v2/guide/

### Actual behavior

In "Conditionals and Loops" section, it was written as 

> In the console, enter app4.todos.push({ text: 'New item' }). You should see a new item appended to the list.

So I did in the following steps; 
1. Open the Chrome DevTools, show Console tab
1. Input `app4.todos.push({ text: 'New item' })`

Then I saw the following error in DevTools' console: 
```
VM258:1 Uncaught ReferenceError: app4 is not defined
    at <anonymous>:1:1
```

### Proposal

For JSFiddle, does "your browser's JavaScript console" mean the lower-left area on the screen?
If that is the case, I supporse the guide document should make clear what means "your browser's JavaScript console" for each execution environment.
For example:
- JSFiddle: the lower-left area on the screen
- Local index.html: Chrome DevTools

**Comment by phanan** [comment]
The "browser console" means just that: your browser's console. As you were looking at the [Guide](https://vuejs.org/v2/guide/), just open the Chrome DevTools when you're there. We even emphasize in the Guide that:

> Open your browser’s JavaScript console (right now, on this page)

So I don't see how this can be confusing.
