### ISSUE TITLE
Render Functions docs refer to use of slots attributes

### ISSUE THREAD

**Issue by aantipov** [vuejs/vuejs.org#2058]
In "Render Functions & JSX" section https://vuejs.org/v2/guide/render-function.html there is a statement

> In this case, you have to know that when you pass children without a `slot` attribute into a component, like the `Hello world!` inside of `anchored-heading`, those children are stored on the component instance at `$slots.default`.

It refers to use of a `slot` attribute which is deprecated. Instead we need to refer to use of the new `v-slot` directive

**Comment by aantipov** [comment]
The same problem in https://vuejs.org/v2/api/#vm-slots:

> Used to programmatically access content distributed by slots. Each named slot has its own corresponding property (e.g. the contents of `slot="foo"` will be found at `vm.$slots.foo`). The `default` property contains any nodes not included in a named slot.

`slot="foo"` is a deprecated syntax

**Comment by phanan** [comment]
Indeed, thanks for pointing this out. I'd suggest we opt for a more graceful change though, with the new `v-slot` directive as the main reference and a note about `slot` for the previous version. Do you think you can work on such PR?

**Comment by aantipov** [comment]
@phanan Done!
