### ISSUE TITLE
Suggestion: use shorter method definition syntax

### ISSUE THREAD

**Issue by rdhelms** [vuejs/vuejs.org#2059]
Currently in the Vue docs, methods are defined using the `methodName: function () {}` syntax, such as for the `data` method below:

**Current Example**: https://vuejs.org/v2/guide/components.html
```
// Define a new component called button-counter
Vue.component('button-counter', {
  data: function () {
    return {
      count: 0
    }
  },
  template: '<button v-on:click="count  ">You clicked me {{ count }} times.</button>'
})
```

But it is very common in tutorials, articles, and other Vue apps to use the shorter method definition syntax, described by MDN here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

It would improve readability and minimize context-switching if the Vue docs could also use this newer syntax. Outside of the Vue documentation, it seems more and more rare to find methods with the older syntax.

**Proposed Example**:
```
// Define a new component called button-counter
Vue.component('button-counter', {
  data () {
    return {
      count: 0
    }
  },
  template: '<button v-on:click="count  ">You clicked me {{ count }} times.</button>'
})
```

I understand that it may be intentional to keep the older syntax for those who are not yet familiar with the newer shorter syntax...but if that were truly a concern then the docs shouldn't really be using arrow functions either. If we're comfortable with arrow functions, I would argue that it's time to be comfortable with the shorter method definitions as well.

**Comment by phanan** [comment]
> I understand that it may be intentional to keep the older syntax for those who are not yet familiar with the newer shorter syntax...but if that were truly a concern then the docs shouldn't really be using arrow functions either.

Indeed, the doc shouldn't use arrow functions (or any ES5 feature in that sense), with the sole exception of cookbooks where readers are expected to be more familiar with the language/framework. If you find any example that's not the case, it's most likely an oversight from us, and a PR is welcomed :)
