### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by MickaMx** [vuejs/vuejs.org#2067]
In the paragraph https://vuejs.org/v2/guide/comparison.html#Flexibility-and-Modularity you are using webpack template but it's deprecated thanks to Vue CLI 3. 
 
Maybe talking about Vue CLI 3 is best.

**Comment by phanan** [comment]
Indeed, thanks for pointing out. Are you interested in working on a PR?

**Comment by MickaMx** [comment]
Why not, that could be interesting.

**Comment by phanan** [comment]
@MickaMx Any updates?

**Comment by MickaMx** [comment]
I've been busy the last week, i'll do it today or tomorrow.

**Comment by sdras** [comment]
Fixed! Closing it out.
