### ISSUE TITLE
Firefox Debugging Config

### ISSUE THREAD

**Issue by nicoweber** [vuejs/vuejs.org#2070]
The Firefox debugging configuration does not work.

The first error message was:
![image](https://user-images.githubusercontent.com/11292742/54686941-b4704400-4b1a-11e9-9e2a-d6365fefee96.png)

My launch.json is

```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
        "type": "firefox",
        "request": "launch",
        "name": "vuejs: firefox",
        "url": "http://localhost:8089",
        "reAttach": true,
        "webRoot": "${workspaceFolder}/src",
        "pathMappings": [{
            "url": "webpack:///src/",
            "path": "${webRoot}/"
        }]

    }]
}
```

then i added the 
`        "firefoxExecutable": "C:/Users/{first.last}/AppData/Local/Mozilla Firefox/firefox.exe",`
to the launch.json firefox configuration, but the behavior was not as expected. Every letter in the textfield triggered a method of a button.

https://vuejs.org/v2/cookbook/debugging-in-vscode.html

**Comment by phanan** [comment]
Sorry, but "doesn't work" doesn't help. Unless you can give us more details, I'm going ahead and close this issue.

**Comment by nicoweber** [comment]
With this firefox-config i also get this error
Config
` {
      "type": "firefox",
      "request": "launch",
      "name": "vuejs: firefox",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src",
      "pathMappings": [{ "url": "webpack:///src/", "path": "${webRoot}/" }]
    }
`

error:
![image](https://user-images.githubusercontent.com/11292742/54696385-01104b00-4b2c-11e9-9f13-0de00d9b32ad.png)

**Comment by phanan** [comment]
Have you tried setting `"firefoxExecutable"` in your `launch.json`'s configuration?

**Comment by phanan** [comment]
Anyway this is not a documentation issue. I've just configured my env and it works just fine.

![image](https://user-images.githubusercontent.com/8056274/54699595-9d891c00-4b31-11e9-85af-68484de7b100.png)

**Comment by nicoweber** [comment]
i`ve edited my intial post. with the example configuration my and the env of my coworker does not work.

**Comment by phanan** [comment]
Can you try using backslashes instead? Anyway, like I said above, the config works just fine for me so it's not a documentation issue. You're welcome to ask for help on our [Discord](https://vue-land.js.org/) or [forum](https://forum.vuejs.org) instead.
