### ISSUE TITLE
Azerbaijani translation.

### ISSUE THREAD

**Issue by saidfagan** [vuejs/vuejs.org#2072]
Hi people!
I am going to translate the documentation to Azerbaijani language (Azərbaycan Türkçəsi). Will gladly accept assistance from anyone who wants. The repo is here: [github.com/saidfagan/vuejs.org](https://github.com/saidfagan/vuejs.org)

**Comment by Justineo** [comment]
See #2015.

**Comment by saidfagan** [comment]
Closing the issue as suggested.
