### ISSUE TITLE
Header is translucence

### ISSUE THREAD

**Issue by SuhwanCha** [vuejs/vuejs.org#2073]
![image](https://user-images.githubusercontent.com/16171447/54703072-77886980-4b7b-11e9-8ba0-7b6e45168a94.png)

The header is translucence when ```min-width: 1590px```.
I think to remove translucence is better. 
Is there a particular reason why have to use translucence header?
Under 1590px, `background-color: #fff` but over 1590px `background-colro: rgba(255,255,255,0.4)`

**Comment by phanan** [comment]
I agree, this looks kind of weird (maybe a leftover from some UI decision in the past). Do you want to create a PR for this?

**Comment by SuhwanCha** [comment]
@phanan
I'll create PR soon 😊
