### ISSUE TITLE
improve v-slot documentation

### ISSUE THREAD

**Issue by dholth** [vuejs/vuejs.org#2074]
The slots documentation is confusing.

When you look for slots, it points you to the RFC for v-slot, and tells you it replaces the slot and slot-scope attributes. Two things a newcomer shouldn't have to know about. https://vuejs.org/v2/guide/components-slots.html#ad

Instead, it should immediately tell you that you declare a slot with `<slot/>`, fill a slot by putting content between the tags of your custom component, and fill a named slot by using `<template v-slot:named>content</template>`. I'd like to see an example like 

### Declare slot

````
<template>
    <div class="...">
      <slot></slot>
    </div>
    (<slot name="comment"></slot>)
</template>
````

### Use slot

```
<template>
<a-component>I was thinking about slots
<template v-slot:comment>I like them lots!</template>
</a-component>
</template>
```

(Why doesn't `v-slot="named"` with an equals sign `=` work?)

The docs could consider the old way at the bottom.

**Comment by phanan** [comment]
> When you look for slots, it points you to the RFC for v-slot, and tells you it replaces the slot and slot-scope attributes. Two things a newcomer shouldn't have to know about. 

These two things are marked with `>`, indicating "side notes" and are not meant to be the main content (which actually starts with the "Slot Content" section).

**Comment by dholth** [comment]
That may be true, but it is still the first and most prominent part of the documentation.

**Comment by sdras** [comment]
I think it's a good thing to link off to where things are headed here. It's pretty important information that even a beginner should take note of. We'll be refactoring this section in the Vue 3 release coming up, it's not too far away :)
