### ISSUE TITLE
Rename filters to pipes before it's too late

### ISSUE THREAD

**Issue by EvAlex** [vuejs/vuejs.org#208]
The feature is great itself, but its name may lead to misunderstanding. Imagine view where you have list of items with filtering and sorting. And when you render item, you use filter in binding expression. Filter and filter, but these are very very very different things. 

If you ask people with huge bash/cmd experience, they will tell you, that "|" in vue.js is very similar to what pipes do and look like. 

Besides, angular 2 renamed filters to pipes opposed to angular 1.

**Comment by yyx990803** [comment]
It's already too late ;)
Renaming means breaking changes to the API, which means 2.0, and there's no plan to do it anytime soon. People have been ok with the name since Angular 1, it's fine.
