### ISSUE TITLE
adding tips about custom events will not broadcasting now

### ISSUE THREAD

**Issue by Misaka-0x447f** [vuejs/vuejs.org#2083]
As a vue begineer, I was having a stereotype about event system, that is "event system will broadcast my custom events, not only tell parents". So a tip about that could be useful for users that not starting from vue 1.x.

* Costed over one week to debug this, finally found that it is a feature.

**Comment by NataliaTepluhina** [comment]
@Misaka-0x447f could you please point out on what part of the documentation was unclear? I am looking at https://vuejs.org/v2/guide/components.html#Listening-to-Child-Components-Events and it's explicitly saying about parent/child communication 🤔

**Comment by Misaka-0x447f** [comment]
@NataliaTepluhina At debugging time I just goes to read [https://vuejs.org/v2/guide/components-custom-events.html](https://vuejs.org/v2/guide/components-custom-events.html) ... And there's no tips about "event will only catchable by the parent, not all components" so.

**Comment by phanan** [comment]
@Misaka-0x447f Your linked page assumes that you've read @NataliaTepluhina's, which talks about parent-child communication in multiple places. Thank you for your feedback, but I don't think repeating information is a good idea here. Closing.

**Comment by Misaka-0x447f** [comment]
@phainv 

ok but wait... how about add a tip to the more basic one, [/guide/components.html#Listening-to-Child-Components-Events](https://vuejs.org/v2/guide/components.html#Listening-to-Child-Components-Events) ?

This section only says "you can listen to child", not "you can only listen to child"(not including child of child), also nothing about "any two component communication"... These info are actually available at [/guide/migration.html#dispatch-and-broadcast-replaced](https://vuejs.org/v2/guide/migration.html#dispatch-and-broadcast-replaced)

Begineers needs to learn why was able to do this and why better not to do this. So a link to that migration guide could be useful for them.
