### ISSUE TITLE
Reloading Vue instance after ajax response received

### ISSUE THREAD

**Issue by parthbhagat** [vuejs/vuejs.org#2087]
I am new to Vuejs and using Vuejs 2.0. This is an evaluation phase for us as we are trying feasibility of Vue with our existing project.

What I am trying to achieve is on click event of a button the page makes an Ajax call and receives HTML content. This HTML content includes normal HTML tags as well as Vue components. After the end of the content, I have added Vue instance creation script so that the content received via Ajax request does recognize it and mark it as Vue component. But the thing is the response does loaded and set to the page correctly but Vue instance script does not sounds to work. It does not loads component like it should be.

I have found several issue somewhat similar to what I am looking for. But the solution provided in them are not fit for my case or not working out.

Here is the Vue content from Ajax response:
```
<input-element name="experimentCommandObj.name" id="name" 
               label="Name"
               cssclass="form-group"></input-element>
  <checkbox-element name="experimentCommandObj.enabled" id="checkboxItem"
                    label="Tracking?"
                    cssclass="form-group"></checkbox-element>
```

Vue component:
```
Vue.component('input-element', {
	props: {
		id: String,
		name: String,
		label: String,
		cssclass: String,
		value: String
	},
	template: `<div :class="cssclass" :id="id + 'Container'"> <label v-bind:for="name" class=" ">{{ label ? label : name | capitalize }}</label >
		  <input autocomplete="off" :title="label ? label : name | capitalize" class="text-property form-control" type="text"   :id="id"  :name="name" :value="value" /></div>
	</div>`,
	filters: {
	  capitalize: function (value) {
		if (!value) return ''
		value = value.toString()
		return value.charAt(0).toUpperCase() + value.slice(1)
	  }
	}
});
Vue.component('checkbox-element', {
	props: {
		id: String,
		name: String,
		label: String,
		value: String,
		cssclass: String
	},
	template: `<div :class="cssclass" :id="id + 'Container'"> <label v-bind:for="name" class=" ">{{ label ? label : name | capitalize }}</label >
		  <input type="hidden" :name="name" />
		  <input type="checkbox" :name="name" :id="id" :title="label ? label : name | capitalize" />
	</div>`,
	filters: {
	  capitalize: function (value) {
		if (!value) return ''
		value = value.toString()
		return value.charAt(0).toUpperCase() + value.slice(1)
	  }
	}
});
```

HTML page in which Vue instance is been loaded:
```
<div id="vueComponent">
<input type="button" onclick="javascript: makeAjaxReq()" value="Submit" />
</div>
<script>
       var e = new Vue({
           el: "#vueComponent"
       });
</script>
```

Any input/hint greatly appreciated.

**Comment by pranayaryal** [comment]
Why do you want to get your component with Ajax and how have you defined your `makeAjaxReq()` method? Why can you not use conditional rendering to show or hide your component based on ajax response?

**Comment by parthbhagat** [comment]
Current structure we are having is completely HTML. On `makeAjaxReq()`, it creates ajax request with get/post method and send it to the server, which returns HTML response. That response is set/update to one of the container on the page. Mostly ajax request is to validate form data and show error messages (in case data is invalid) or submit the form and show next step which may be another form or another page in the container. 

About conditional rendering, it is I think ok if impact to the form/ajax response is small. In my case it is completely new form as ajax response or error messages to each form field. 

Please correct me if my approach is wrong.

**Comment by pranayaryal** [comment]
Why can't the button which makes the ajax request be inside the Vue instance instead of outside? Why would you need a separate javascript file to make the request?

**Comment by parthbhagat** [comment]
The reason there is separate javascript file is we have created a common js library which performs some task prior to make request and handling of response. This javascript library also handles some data validations, performs session checking operations. These are all done in our custom javascript library. 

As far as I have understood Vuejs (which is at a beginner level), we can do ajax request inside method section of Vue instance. To perform ajax call from Vue's method we will need ajax request handling on each and every Vue instance. And there are hundreds of ajax calls being made in entire applications.  And there may be chance that to perform ajax request we may have to switch on and off some html elements which are out of Vue instance's scope.

Thank you.

**Comment by parthbhagat** [comment]
Any input on this please @pranayaryal ?

**Comment by pranayaryal** [comment]
You can use Vue's lifecycle hooks to subscribe to a service or to unsubscribe from a service. https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks

**Comment by phanan** [comment]
@parthbhagat Please use our [forum](https://forum.vuejs.org/) or [Discord](https://vue-land.js.org/).

**Comment by PabloRN** [comment]
Perhaps this can help https://vuejs.org/v2/guide/components-dynamic-async.html
