### ISSUE TITLE
Better documentation for stylelint

### ISSUE THREAD

**Issue by rdhelms** [vuejs/vuejs.org#2095]
This is a request to add better information here:
https://vue-loader.vuejs.org/guide/linting.html#stylelint

Currently, the docs simply say "Make sure that your stylelint config is right", and the link takes you to the general stylelint config docs, which say nothing specific about linting vue files.

And the second option listed in the docs is `stylelint-webpack-plugin`, which does not support the latest version of stylelint, has not been updated in almost a year, and seems to no longer be maintained.

Currently, my solution for using stylelint in vue is to use `@ascendancyy/vue-cli-plugin-stylelint`, but then to install `stylelint@^8.0.0` to avoid the npm warning that comes from `vue-cli-plugin-stylelint` trying to use `stylelint@^9.0.0`.

I would love to have better instruction for getting stylelint up and running in a Vue app without having to track down the docs for 7 packages.

**Comment by phanan** [comment]
Please report this issue in [vue-loader repo](https://github.com/vuejs/vue-loader) instead.

**Comment by rdhelms** [comment]
Sorry - is this because there IS not currently a good known way to use stylelint with vue components as the docs suggest? Because if that's the case I would still say this is an issue in the docs.

The docs communicate a sense that "you can use stylelint easily!". If that's not true, it should say so.

On the other hand, if there IS already a way to easily use stylelint, that seems to just be a docs issue and not an issue with vue-loader.

**Comment by phanan** [comment]
@rdhelms This repository is for vuejs.org docs. Your issue belongs to vue-loader docs. They are different.
