### ISSUE TITLE
404 error for docsearch.min.js.map

### ISSUE THREAD

**Issue by co16353sidak** [vuejs/vuejs.org#2105]
I noticed that there seems to be a 404 error for the resource `docsearch.min.js.map` in the browser console when I loaded the website:
<img width="1280" alt="Screenshot 2019-04-07 at 5 24 07 PM" src="https://user-images.githubusercontent.com/35738138/55683136-fb9f6700-5959-11e9-885c-c354f5342736.png">

Would love to find a way to contribute on this and remove this console error.

**Comment by phanan** [comment]
Strange, I don't seem to receive this error.

**Comment by co16353sidak** [comment]
This could be a platform specific problem, i tested the above on Safari (latest edition), on Firefox I am not able to find this error. 🍎

**Comment by NataliaTepluhina** [comment]
Confirmed. On Safari we have `https://cdn.jsdelivr.net/docsearch.js/1/dist/cdn/docsearch.min.js.map` link (and it's broken) and on all other browsers we have `https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js`.

**Comment by phanan** [comment]
I believe the culprit is in https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js:

```js
//# sourceMappingURL=dist/cdn/docsearch.min.js.map
```

There's a (closed) issue here: https://github.com/algolia/docsearch/issues/245.

As there's nothing we can do about it and this is not a severe problem, I'm closing this issue as a "won't fix."
