### ISSUE TITLE
can i add buttons and radio buttons or checkbox or combobox to grid

### ISSUE THREAD

**Issue by migz7** [vuejs/vuejs.org#2106]
`var demo = new Vue({
  el: '#demo',
  data: {
    searchQuery: '',
    gridColumns: ['LinkTest', 'PartNumber', 'Lnominal', 'Ipeak', 'IDC', 'Price'],
    gridData: [
      { LinkTest:'<a href="#">Test</a>', PartNumber: 'XFL4015-122', Lnominal: 1.2, Ipeak: 0.96, IDC: 1.1, Price: '$' + 18.79 },
      { LinkTest:'<a href="#">Test</a>', PartNumber: 'XGL4020-332', Lnominal: 3.3, Ipeak: 2.7, IDC: 2.9, Price: '$' + 21.50 },
      { LinkTest:'<a href="#">Test</a>', PartNumber: 'XGL4020-472', Lnominal: 4.7, Ipeak: 3.8, IDC: 4.1, Price: '$' + 15.17 },
      { LinkTest:'<a href="#">Test</a>', PartNumber: 'XFL4020-222', Lnominal: 3.3, Ipeak: 2.7, IDC: 3.1, Price: '$' + 17.10 }
    ]
  }
})`

can you show me a code of how i could add radio button or checkbox or button or maybe img with different source. <img src="#"></img> please do i'm new in VueJS and want to learn more

**Comment by phanan** [comment]
Please use our [forum](https://forum.vuejs.org/) or [Discord](https://vue-land.js.org/) for questions like this. Thanks.
