### ISSUE TITLE
Multi-word built-in components

### ISSUE THREAD

**Issue by afontcu** [vuejs/vuejs.org#2114]
Hi! The docs state that:

_"Component names should always be multi-word, except for root App components."_ ([source](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential)).

However, built-in components such as `<component>` or `<transition>` break that rule. 

Is it something worth mentioning in the docs? My team had some doubts about it (the docs are enforcing a rule that Vue itself isn't following).

However, given the reason to apply this rule (avoid name collision with existing and future HTML elements), one could argue that built-in components should become multi-worded. If that's the case, I'd be more than happy to open an issue to the Vue repo.

Thanks! 🙌

**Comment by sdras** [comment]
I don't think the answer here is to update Vue itself. The Styleguide needs some caveat in the wording like, 

_"Component names should always be multi-word, except for root App components, and built-in components provided by Vue, such as `<transition>`."_

Open to a PR but I can also fix it up.

**Comment by afontcu** [comment]
Makes sense :) I’ll submit the PR!


El 12 abr 2019, a les 11:26, Sarah Drasner <notifications@github.com> va escriure:
