### ISSUE TITLE
Design inconsistencies in navbar design across different pages

### ISSUE THREAD

**Issue by co16353sidak** [vuejs/vuejs.org#2125]
urls:
1. https://vuejs.org
2. https://vuejs.org/v2/guide/

screenshots:
<img width="1280" alt="Screenshot 2019-04-16 at 10 30 01 AM" src="https://user-images.githubusercontent.com/35738138/56183198-21e89500-6033-11e9-9aa2-4a843b0ecc74.png">
<img width="1278" alt="Screenshot 2019-04-16 at 10 29 55 AM" src="https://user-images.githubusercontent.com/35738138/56183200-23b25880-6033-11e9-99f7-64a27db39f51.png">

On observing the website I found that while most pages follow the same style for the navbar (relatively smaller in size and a slight border at the bottom), the main front-page follows a different style format (slightly larger size and no border at the bottom) (also no logo) (not-sticky on top)

This could be intentional but if it isn't then I feel that the design should be consistent throughout,
it could be a easy fix and I would like to work on this 🥇

**Comment by phanan** [comment]
Thanks for the suggestion, but I'm not sure how you get the different font sizes - both look exactly the same on my browser(s). WRT logo and bottom border: yes, they're intentional. So let's leave them as-is :)

**Comment by phanan** [comment]
Oh, maybe you mean the _logo_'s font size. In that case, it's intentional too.
