### ISSUE TITLE
nextTick: Changed the order of compatibility

### ISSUE THREAD

**Issue by Mayness** [vuejs/vuejs.org#2132]
page: https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue
code: https://github.com/vuejs/vue/blob/dev/src/core/util/next-tick.js
the compatibility order in nextTick is changed：`Promise.then`、`MutationObserver`、`setImmediate`、`setTimeout`

**Comment by phanan** [comment]
I'm not sure I get what you mean. What exactly is wrong with the current doc?

**Comment by Mayness** [comment]
yeah,the previous compatibility priority were `Promise.then` and `MessageChannel`. But now, the `MutationObserver` replaced `MessageChannel`, and `MutationObserver` is a micro-task.

**Comment by phanan** [comment]
Oh right, sorry I missed that yesterday. Do you want to send a PR over? Something like this will work fine I guess:

>  Internally Vue tries native `Promise.then`, `MutationObserver`, and `setImmediate` for the asynchronous queuing and falls back to setTimeout(fn, 0).

**Comment by Mayness** [comment]
Ok,thank you

**Comment by NataliaTepluhina** [comment]
Closing this issue as #2134 is merged.
