### ISSUE TITLE
Typo of src in JSFiddle

### ISSUE THREAD

**Issue by PlusoneWang** [vuejs/vuejs.org#2156]
[JSFiddle](https://jsfiddle.net/chrisvfritz/1Leb7up8/) in this [section](https://vuejs.org/v2/guide/components-edge-cases.html#Programmatic-Event-Listeners) has typo in the script src of Pikaday.

![Image 2](https://user-images.githubusercontent.com/37727068/57514696-a03f0b00-7343-11e9-8ba0-114261e0d1dc.png)

The correct is Pikaday, not Pickaday.

**Comment by phanan** [comment]
Pinging @chrisvfritz

**Comment by PhilipJohnBasile** [comment]
@PlusoneWang is correct. It is Pikaday.

[Proof](https://unpkg.com/browse/pikaday@1.7.0/)

**Comment by ianfabs** [comment]
Forked the JSFiddle with typo-correction [here](https://jsfiddle.net/09jvu65m/). Will add into docs now.

**Comment by NataliaTepluhina** [comment]
Closing as related MR is merged
