### ISSUE TITLE
Sidebar overflow, scrollbar broken

### ISSUE THREAD

**Issue by fayazara** [vuejs/vuejs.org#2157]
Getting this scrollbar overflowed in vuejs docs site.

![vuejs](https://user-images.githubusercontent.com/15716057/57522962-3e7da180-7341-11e9-996a-754412a22f68.png)

**Comment by fayazara** [comment]
OS: Ubuntu 18.04
Browser: Chrome Version 74.0.3729.131

**Comment by gustojs** [comment]
The issue still persists on Windows 10 (both Chrome and Firefox)

![Screenshot (105)](https://user-images.githubusercontent.com/25644507/57526656-4122cb80-732e-11e9-9476-b1d1743e721d.png)

**Comment by phanan** [comment]
@gustojs Apparently you're looking at vuejs.org? It should be the Netlify preview instead.

**Comment by sdras** [comment]
thanks for the PR!

**Comment by Attaulla9** [comment]
Thanks @fayazara for this issue.
