### ISSUE TITLE
Licenses for Diagrams/Images

### ISSUE THREAD

**Issue by rlafranchi** [vuejs/vuejs.org#2176]
Are the diagrams free to use (ex. lifecycle diagram)? Do they fall under the MIT license or some other license?

**Comment by phanan** [comment]
Hey! They're licensed under MIT, as you can see in the README file 💚.

**Comment by factotumchris** [comment]
Hi, phanan. Can we use the lifecycle diagram in a book that rlafranchi and another person are writing for Apress? I looked at the MIT license and think it might be okay, but we wanted to ask as a courtesy and to make sure. Thanks!
