### ISSUE TITLE
 https://jsfiddle.net在国内访问404

### ISSUE THREAD

**Issue by evilThought** [vuejs/vuejs.org#2178]
嗯...无法访问此页面
尝试此操作
请确保你已获取正确的网址: https://jsfiddle.net

刷新页面

**Comment by phanan** [comment]
请用英语。

**Comment by huanghe2015** [comment]
我给他翻译一下吧。
Because the website of demo storage 'JSfiddle' is blocked by(You know). How about the future plan to migrating existing demo to another REPL website?

**Comment by phanan** [comment]
Oh, thanks for the explanation. TBH we don't have a specific plan to migrate from JSFiddle, as we don't have a clear idea how China's internet censorship does/will look. I think the idea of having our own REPL popped out in one of our internal discussions though, but still, there's nothing concrete about it.

**Comment by evilThought** [comment]
thanks for the explanation
