### ISSUE TITLE
Algolia search for Spanish translation

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vuejs.org#2181]
@maxiloc We'd like to go live soon with a Spanish translation that will be at `es.vuejs.org`. Would it be possible to set up an Algolia key for that translation?

**Comment by s-pace** [comment]
Hi @chrisvfritz , 

Congratulations, your search is now ready! 
I've successfully configured the underlying crawler and it will now run every 24h. 

You're now a few steps away from having it working on your website: 

- Copy the following CSS/JS snippets and add them to your page 
```html
<!-- at the end of the HEAD --> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 

<!-- at the end of the BODY --> 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript"> docsearch({ 
apiKey: 'fd19a0f4b0ab402d2b6f9f95e9003e3b', 
indexName: 'vuejs-es', 
inputSelector: '### REPLACE ME ####', 
debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script> 
```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field. 
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/styling.html) 
- You can also check your configuration in our GitHub repo (https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs-es.json). 
- info@pionect.nl has already an Algolia account. Analytics available from the Algolia dashboard by selecting the application DOCSEARCH (access granted) 
Please open a pull request if want to leverage your configuration! 

Feel free to get back to us if you have any issues or questions regarding the integration. 

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it. 

Have a nice day :)

**Comment by chrisvfritz** [comment]
Thanks! 😄

**Comment by Davidcreador** [comment]
@sdras @chrisvfritz is that the algolia key you are requesting?
