### ISSUE TITLE
The Vuejs.org/guide causing Safari Service Worker using 100% CPU

### ISSUE THREAD

**Issue by zrfrank** [vuejs/vuejs.org#2188]
The Vuejs.org/guide webpages, for instance 'router.vuejs.org', has caused Safari Service Worker using 100% CPU. It's happened a few time since last few days. When this happens, the webpage is always out-focused.

macOS Mojave 10.14.5
Safari 12.1.1

**Comment by phanan** [comment]
Sorry, I don't really get what you mean. vuejs.org(/guide) and router.vuejs.org are two very different web sites.

**Comment by phanan** [comment]
I've left my Safari open on router.vuejs.org for several hours now to no such problem at all. Most likely it's some problem with your machine.
