### ISSUE TITLE
Docs improvements suggestion

### ISSUE THREAD

**Issue by stratboy** [vuejs/vuejs.org#2195]
Hi! I’d like to suggest you to improve the group/list transition docs by specifying that the css transition classes will be applied to inner elements and not to the group/container itself. Took me a while to get it.

**Comment by phanan** [comment]
We're open to a PR 👐

**Comment by krishnanandula** [comment]
@stratboy or @phanan  which section would you like to suggest to make this change? 
[Transition-classes](http://localhost:4000/v2/guide/transitions.html#Transition-Classes)  or[ List-Transitions](http://localhost:4000/v2/guide/transitions.html#List-Transitions) ?

**Comment by NataliaTepluhina** [comment]
Closing this as related PR has been merged.
