### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by mikekangts** [vuejs/vuejs.org#2199]
https://kr.vuejs.org/v2/guide/comparison.html

자바 스크립트 세계가 빠르게 움직이기 때문에 이 문서를 최신 상태로 유지하는 당신의 도움을 받길 바랍니다. 

to

자바 스크립트 세계가 빠르게 움직이기 때문에 이 문서를 최신 상태로 유지하기 위해 당신의 도움을 받길 바랍니다.

**Comment by Justineo** [comment]
I believe this issue belongs [here](https://github.com/vuejs-kr/kr.vuejs.org).
