### ISSUE TITLE
Adding a"see source" link next to each API methods

### ISSUE THREAD

**Issue by ayamflow** [vuejs/vuejs.org#22]
I'm using Pixi.JS at the moment ans I find it pretty neat, for a small/young library to give the user the possibility to easily check the source if needed: [pixi docs](http://www.goodboydigital.com/pixijs/docs/classes/DisplayObjectContainer.html).

Do you find it useful? Would that be possible with hexo?
I guess it would require to insert some kind of documentation in the current code so that may not be ideal (given that there is not doc in the code).

**Comment by chrisvfritz** [comment]
A naive implementation of this is now live. I've just linked to a GitHub search referencing the API in the Vue source. It may be the best we'll be able to manage unfortunately, since many of our entries aren't distinct methods or pure functions.
