### ISSUE TITLE
Italian translation.

### ISSUE THREAD

**Issue by ludo237** [vuejs/vuejs.org#220]
Hello everyone.

I know this is not the place for this kind of messages, but since I don't think this could rely on "pull requests" at the moment I think it's a good idea to place it here.

Anyways I'm translating the site into italian. You can check the progress [directly on my repo](https://github.com/ludo237/it.vuejs.org) the project is the most updated one, old project are still incomplete and they aren't updated.

The current state of the translation is roughly at 33% 

I've opened this issue not only to let you know that there's this implementation coming but also because I've few questions about it

1) How can I submit the entire work when it's finished?

2) Do I have to translate the `_*_old` content? Like `_api_old` ?

3) How can this project became the official translation for this language?

**Comment by yyx990803** [comment]
Hey @ludo237 - thanks for your hard work! For your questions:

1. Ideally we would want to move the repo into the `vuejs` organization - however, GitHub doesn't allow a repo and its fork to coexist in the same organization, so we will have to create a fresh repo and let you push your version to it.

2. You can ignore the `*_old` stuff :)

3. I'm more than happy to accept it as the official Italian translation. I'm not sure if you've talked with @chrispecoraro who has been working on a translation previously, but you should probably coordinate on that. Once you're done, setup a preview somewhere so I can make sure everything looks right (I can't read Italian, so it's just making sure the styling/etc. looks ok).

**Comment by yyx990803** [comment]
Ok, I've invited you to the vuejs organization and given you admin rights to https://github.com/vuejs/it.vuejs.org - let's continue the work over there :)

**Comment by chrispecoraro** [comment]
@yyx990803 Yes, I've been in touch with @ludo237 and he's the right man to do the job so we'll use his repo going forward.

**Comment by yyx990803** [comment]
@chrispecoraro :+1:

**Comment by ludo237** [comment]
Thanks for the repository, I'll get to work after the 25th I think the first ETA is for 31 of December.
