### ISSUE TITLE
Vue 3.0 release date

### ISSUE THREAD

**Issue by woothu** [vuejs/vuejs.org#2204]
I cannot find any current information about the planned date of 3.0 version release. It would be very helpful to have some idea about the current approximate time of the release. 

Regards

**Comment by NataliaTepluhina** [comment]
Sorry, but it's definitely not related to Vue documentation issues.

**Comment by woothu** [comment]
Which repo os apropriate?

śr., 19 cze 2019, 17:26 użytkownik Natalia Tepluhina <
notifications@github.com> napisał:
