### ISSUE TITLE
Missing Spanish options in Translations dropdown

### ISSUE THREAD

**Issue by Davidcreador** [vuejs/vuejs.org#2211]
I noticed that there is no option for the Spanish version of the site, I speak Spanish as a native language and it would be nice to have that option as well. I see that if I go directly to https://es.vuejs.org/ it works but most of us don't do that. So, I am making a PR to add that option. Is that Ok? Do we have an issue related to this or not? Please let me know, in the meantime, I am making the PR.

**Comment by Davidcreador** [comment]
https://github.com/vuejs/vuejs.org/pull/2212 for reference

**Comment by posva** [comment]
closed in https://github.com/vuejs/vuejs.org/pull/2353
