### ISSUE TITLE
can not find demo of Template Compilation

### ISSUE THREAD

**Issue by Syntax-J** [vuejs/vuejs.org#2214]
https://vuejs.org/v2/guide/render-function.html#Template-Compilation
<img width="782" alt="demo" src="https://user-images.githubusercontent.com/29221509/60228861-9f980f00-98c6-11e9-9d69-f849d240a207.png">

**Comment by NataliaTepluhina** [comment]
Thank you for creating this issue! I can see the mentioned demo in docs:
<img width="770" alt="Screen Shot 2019-06-27 at 07 40 52" src="https://user-images.githubusercontent.com/18719025/60235005-fe518e80-98ae-11e9-8587-33ac2f5f98c6.png">

This probably means JSFiddle is blocked/unavailable at your location (we are aware there are some issues with JSFiddle in China). Could you please check the console to verify it's JSFiddle error?

I think as a docs team we should work on moving or duplicating our examples to the platform available everywhere.

**Comment by Syntax-J** [comment]
@NataliaTepluhina 
Thank you for your replay. and
Yes indeed ,the JSFiddle is blocked/unavailable in china.
here is the log error:
<img width="1652" alt="a" src="https://user-images.githubusercontent.com/29221509/60240437-90738a00-98e3-11e9-9e32-b1f27a706551.png">

**Comment by phanan** [comment]
This (kind of) issue has been reported before, and discussed among the team as well. Even if we replace JSFiddle with another provider, we can't be sure if the replacement will work _or_ continue to work in the future. 

In a next version of the docs, we hope to solve this problem by implementing our demo "system," so to say.

**Comment by NataliaTepluhina** [comment]
I am closing an issue because we're not able to resolve the JSFiddle problem on our side 😞

**Comment by wizardpisces** [comment]
Same issue ! Seems like [jsFiddler](http://www.jsfiddle.net/) is broken for a long time
