### ISSUE TITLE
Why not use VuePress?

### ISSUE THREAD

**Issue by zhaojh329** [vuejs/vuejs.org#2216]

**Comment by NataliaTepluhina** [comment]
Thank you for your question 😅 We have a migration to VuePress planned.

**Comment by samajammin** [comment]
Hey @NataliaTepluhina - just curious, is a migration still planned? If so, any sense of the priority on it?

Cheers

**Comment by batbayar-su** [comment]
Yeah, if it is started, some people might would like to contribute since it is hacktoberfest.
