### ISSUE TITLE
[CookBook] The "data" option should be a function in unit-testing-vue-component-real-world-example

### ISSUE THREAD

**Issue by re4388** [vuejs/vuejs.org#2220]
In this page, [unit-testing-vue-component-real-world-example](https://github.com/vuejs/vuejs.org/blob/master/src/v2/cookbook/unit-testing-vue-components.md#real-world-example), if you run the code, will produce below message:
```bash
console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
[Vue warn]: The "data" option should be a function that returns a per-instance value in component definitions.
```

Problem I found could be here:

```javascript
const factory = (values = {}) => {
  return shallowMount(Foo, {
    data: { ...values  }
  })
}
```

Based on the error message, modified as below and the no error

```javascript
const factory = (values = {}) => {
  return shallowMount(Foo, {
    data(){
      return {
        ...values
      }

    }
  })
}
```

**Comment by phanan** [comment]
You're right, `data` should be a function (even though in this case it doesn't affect the outcome). Are you interested in working on a PR or this?

**Comment by NataliaTepluhina** [comment]
Closing this as a relevant PR was merged
