### ISSUE TITLE
VueJS docs need a list of events

### ISSUE THREAD

**Issue by vincentntang** [vuejs/vuejs.org#2228]
There's a few events missing from the documents

- @change 
- @blur

Possibly more events. 

I didn't find it in the documents and had a hard time finding the difference between @input and @change (input fires immediately, change fires off when user clicks on a different target)

It would be nice to see a table side by side diagram, showing the conventions used in vue compared to HTML Dom events found here

https://www.w3schools.com/jsref/dom_obj_event.asp

**Comment by Justineo** [comment]
They *are* just native [DOM events](https://developer.mozilla.org/en-US/docs/Web/Events#Standard_events). But be aware that different events are triggered on different elements and you should make sure to check what events are supported on the specific element you are using.
