### ISSUE TITLE
error in docs?

### ISSUE THREAD

**Issue by aranmohyeddin** [vuejs/vuejs.org#2233]
I can't read the line 215 of [this](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/events.md) I mean I don't understand what it means exactly. I think I know what the whole part means tho.

**Comment by phanan** [comment]
The comments are meant to be read as a whole block ;)

**Comment by aranmohyeddin** [comment]
so we have: 

> the scroll event's default behavior (scrolling) will happen immediately, instead of waiting for `onScroll` to complete in case it contains `event.preventDefault()`   

In case what contains  event.preventDefault? what will happen in that case?
The way I understand this sentence it means:
> If the scroll event contains `event.preventDefault()`, the scroll event's default behavior (scrolling) will happen immediately, instead of waiting for `onScroll` to complete.

But AFAIK preventDefault and passive should never be used together. And also AFAIK the consequent here is true regardless of the antecedent.
