### ISSUE TITLE
[cookbook] Packaging Vue Components for npm

### ISSUE THREAD

**Issue by kartsims** [vuejs/vuejs.org#2240]
After following the "Packaging Vue Components for npm" cookbook page, I got stuck with the following error:

```
src/wrapper.js → dist/mfwebtk.esm.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
src/components/mfwebtk.vue: (25:9)
[!] Error: 'default' is not exported by node_modules/vue-runtime-helpers/dist/normalize-component.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module-
src/components/mfwebtk.vue (25:9)
```

This is happening for each build type. It turns out the recent versions of `rollup-plugin-vue` require to include  `rollup-plugin-commonjs`... [Source](https://github.com/vuejs/rollup-plugin-vue/commit/fd3dfb9a4440b13b220fb2dc535506274280fa0c).

I'll just leave this information here for reference but can also do a PR on the cookbook if you want just let me know.

### Update to the `package.json`

_If you did a recent install for the package.json (like I did) you already have the latest versions of those packages_
```
    "rollup": "^1.17.0",
    "rollup-plugin-buble": "^0.19.8",
    "rollup-plugin-commonjs": "^10.0.1",
    "rollup-plugin-vue": "^5.0.1",
    "vue": "^2.6.10",
    "vue-template-compiler": "^2.6.10"
```

Note that `rollup-plugin-commonjs` has been added. These are the latest version at time of this writing.

### Update `rollup.config.js`

```javascript
import vue from 'rollup-plugin-vue'; // Handle .vue SFC files
import commonjs from 'rollup-plugin-commonjs'; // ??
import buble from 'rollup-plugin-buble'; // Transpile/polyfill with reasonable browser support
export default {
    input: 'src/wrapper.js', // Path relative to package.json
    output: {
        name: 'mfwebtk',
        exports: 'named',
    },
    plugins: [
        commonjs(),
        vue({
            css: true, // Dynamically inject css as a <style> tag
            compileTemplate: true, // Explicitly convert template to render function
        }),
        buble(), // Transpile to ES5
    ],
};
```

`commonjs()` is called before `vue()` to prevent the error from happening

**Comment by NataliaTepluhina** [comment]
Thank you for spotting this! As you've mentioned you don't mind creating a PR, can I ask you to do so? :slightly_smiling_face:

**Comment by kartsims** [comment]
You got it, thanks for all the good work you guys are doing!

**Comment by NataliaTepluhina** [comment]
Closing this issue as related PR was merged

Thank you one more time for working on it!
