### ISSUE TITLE
Fastclick not required anymore

### ISSUE THREAD

**Issue by BlueskyFR** [vuejs/vuejs.org#2245]
On the Vuejs.org website, I can see that fastclick is used. However, according to the project's readme:

"As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and risks introducing bugs into your application. Consider carefully whether you really need to use it."

I think that fastclick should be removed. The website will load faster because one less library has to be loaded.
Tell me what you think!

**Comment by phanan** [comment]
I agree :) Would you mind working on a PR?

**Comment by BlueskyFR** [comment]
Sorry, I was busy :-/
Thanks for doing it :)
