### ISSUE TITLE
Please explain that "hook:<>" events exist and they allow to subscribe to the Vue component lifecycle events

### ISSUE THREAD

**Issue by WillAvudim** [vuejs/vuejs.org#2247]
# What problem does this request solve?
I've just recently learned from the 3rd sources that

vue_component.$once('hook:beforeDestroy', function () { ... } )
can be used to subscribe to the lifecycle events of individual components.

In my case this is very convenient, it enables me to automatically shut down the no longer necessary websocket connection that is used to receive real-time updates on a certain page of my SPA.

Would it be possible to mention this great fact in the official documentation? I couldn't find any reference to it anywhere. There are several mentioning of the word hook in the documentation and they all seem to connote some other unrelated things.

# What will the proposed change look like?
A documentation enhancement.

# What is the use case and what needs to be covered?
A sample write up is provided at https://github.com/vuejs/vue/issues/10312.

**Comment by phanan** [comment]
As @posva commented in the linked issue, this feature is internal and shouldn't be relied on – especially with Vue 3 approaching.

**Comment by sirlancelot** [comment]
It's worth pointing out that the `hook:` syntax is documented appropriately under [Handling Edge Cases: Programmatic Event Handlers](https://vuejs.org/v2/guide/components-edge-cases.html#Programmatic-Event-Listeners).

**Comment by lobo-tuerto** [comment]
An example is documented, but there is no list of all the existing `hook:X` events.
Even though it'll be safe to assume every lifecycle hook will fire a `hook:X` event, it's not noted anywhere I think.
