### ISSUE TITLE
Markdown example - Marked deprecated sanitizer parameters

### ISSUE THREAD

**Issue by jenstornell** [vuejs/vuejs.org#2248]
https://github.com/vuejs/vuejs.org/blob/master/src/v2/examples/index.md

When using the latest version of Marked:
https://github.com/markedjs/marked/blob/master/lib/marked.js

I get this:

>marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options

Just remove the param and it works fine.

**Comment by phanan** [comment]
Thanks for letting us know. As the fiddle uses a specific version of marked (0.3.6) which doesn't have this issue, I guess we can live with it :)
