### ISSUE TITLE
Outdated docs. Automatic Global Registration of Base Components is not working

### ISSUE THREAD

**Issue by Mehdi-Hp** [vuejs/vuejs.org#2255]
[Automatic Global Registration of Base Components](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/components-registration.md#automatic-global-registration-of-base-components) doesn't work with new core-js@3, but works fine with @2.x.  
the error got thrown is:
```js
These dependencies were not found:

* core-js/modules/es6.regexp.replace in ./src/main.js
* core-js/modules/es6.regexp.split in ./src/main.js
* core-js/modules/web.dom.iterable in ./src/main.js
```

**Comment by sodatea** [comment]
It's not related to the code snippet, but to Vue CLI.

`@vue/babel-preset-app` v3 only works with `core-js@2`
`@vue/babel-preset-app` v4 beta works with `core-js@3`.
