### ISSUE TITLE
Dynamic arguments with upper case doesn't work

### ISSUE THREAD

**Issue by mmiyahara** [vuejs/vuejs.org#2256]
Dynamic arguments will not work when being specified by a data property with upper case.
Ref: [Dynamic arguments upper case problem · Issue #9528 · vuejs/vue](https://github.com/vuejs/vue/issues/9528)

In the example of Dynamic Arguments below, however, the name of the data property is `attibuteName` and `eventName`.
Ref: [Template Syntax — Vue.js](https://vuejs.org/v2/guide/syntax.html#Dynamic-Arguments)

I know that there is a description at `Dynamic Argument Expression Constraints` section saying that using uppercase keys should be avoided, but it's still confusing that the example with `attibuteName` and `eventName` don't work.

I think we can change the name of the data property from `attributeName` to `attribute` and from `eventName` to `event`. What do you think?

**Comment by phanan** [comment]
While I hear your concern, having the argument as mere `attribute` or `event` wouldn't be as expressive and may actually cause another confusion, as they more than often refer to the _objects_ (the attribute or event themselves) and not the names. What do you think about this alternative:

```html
<!-- 
Note that there are some constraints to the argument expression, as explained
in the "Dynamic Argument Expression Constraints" below.
-->
<a v-bind:[attributeName]="url"> ... </a>
```

**Comment by mmiyahara** [comment]
@phanan 
Thanks for replying back soon. I agree with the alternative! 
Just to clarify, but what I understand from [this report](https://github.com/vuejs/vue/issues/9528) is that the `attributeName` get lowercased to `attributename` and Vue will see if there is `attributename` data. Please let me know if I didn't get it right.
If my understanding is right, I think we should also edit the following sentences as follows.

> For example, if your Vue instance has a data property, attributeName, whose value is "href", then this binding will be equivalent to v-bind:href.

For example, if your Vue instance has a data property, **attributename**, whose value is "href", then this binding will be equivalent to v-bind:href.

> Similarly, when eventName‘s value is "focus", for example, v-on:[eventName] will be equivalent to v-on:focus.

Similarly, when **eventname‘s** value is "focus", for example, v-on:[eventName] will be equivalent to v-on:focus.

I am not sure if the lowercased, not camel cased variable name is proper as an example though...

**Comment by phanan** [comment]
@mmiyahara Can you please check the PR linked above and see if it suffices.

**Comment by mmiyahara** [comment]
@phanan 
Thank you for creating PR. I just want to make sure if you check https://github.com/vuejs/vuejs.org/issues/2256#issuecomment-516743300. Except for the things I mentioned in https://github.com/vuejs/vuejs.org/issues/2256#issuecomment-516743300, everything looks fine.
