### ISSUE TITLE
Problem with transitions using sync

### ISSUE THREAD

**Issue by WisdomEye** [vuejs/vuejs.org#2280]
I have read the documentation many times, and can't get an simple text rotator working with transtions.

The issue I have notice about is not working probaly is because the key work as async.

From data I have:

```json
	rotateindex: 0,
	rotate: [
		{
			item: 0,
			text: 'Some item 1',
			name: 'zoom',
			enter: 'zoomIn',
			out: 'zoomOut',
			color: '',
			duration: 4000
		},
		{
			item: 1,
			text: 'Another item 2',
			name: 'zoom',
			enter: 'zoomIn',
			out: 'zoomOut',
			color: '',
			duration: 4000
		},
		{
			item: 2,
			text: 'There more items',
			name: 'zoom',
			enter: 'zoomIn',
			out: 'zoomOut',
			color: '',
			duration: 3500
		},
		{
			item: 3,
			text: 'Was think is about (parentesis) and seems is not... - not show this one',
			name: 'zoom',
			enter: 'zoomIn',
			out: 'zoomOut',
			color: '',
			duration: 4000
		},
		{
			item: 4,
			text: 'This show without animation',
			name: 'zoom',
			enter: 'zoomIn',
			out: 'zoomOut',
			color: '',
			duration: 4000
		},
		{
			item: 5,
			text: 'Another Curious thing is use / then / seems / not / working',
			name: 'zoom',
			enter: 'zoomIn',
			out: 'zoomOut',
			color: '',
			duration: 4000
		}
	]
};
```

As Method I have did:

```javascript
textRotate() {
	this.rotateindex += 1;
	if (this.rotateindex >= this.rotate.length) {
		this.rotateindex = 0;
	}
	// For debug
	console.log(this.rotateindex);
	console.log(this.rotate[this.rotateindex].text);
```

And call it on mounted:

```javascript
	setInterval(() => {
		this.textRotate();
	}, this.rotate[this.rotateindex].duration);
```

Timer come from Json becoming dynamic., for template on first approach, have did:

```javascript
	<transition appear :name="rotate[rotateindex].name" :enter-class="rotate[rotateindex].enter"  :leave-active-class="rotate[rotateindex].out" mode="out-in">
		<p class="caption" :key="rotateindex">{{ rotate[rotateindex].text }}</p>
	</transition>
```

With the code above using the package:

[Vue Animate](https://github.com/asika32764/vue2-animate)

Got some animations, since the key skip (read variable and show blank) some data (at first time was think is issue with / and ( but not is), or in another words have skipped the json 3 and 5 (no idea why)...

Using the .sync then data is read but there's no animation, example:

```javascript
	<transition appear :name="rotate[rotateindex].name" :enter-class="rotate[rotateindex].enter"  :leave-active-class="rotate[rotateindex].out" mode="out-in">
		<p class="caption" :key="rotateindex.sync">{{ rotate[rotateindex].text }}</p>
	</transition>
```

With .sync all data from json is read and show correctly, but without animations...
(Does not occours the enter / leave class added events on <p>)

Someone can point me where I am doing something wrong?

PS.: Have tested using nuxt.
PS2.: Using Animate.css too

**Comment by phanan** [comment]
Please use our [forum](https://forum.vuejs.org/) or [Discord](https://vue-land.js.org/) for questions like this. Thanks.

**Comment by WisdomEye** [comment]
> Please use our [forum](https://forum.vuejs.org/) or [Discord](https://vue-land.js.org/) for questions like this. Thanks.

Its not only an question, let me remake:

Do not show random items from array is the desired behavior from Vue?

Or its a bug?

Show all items only using .sync and losing the transitions make transitions useless and its the desired behavior?
