### ISSUE TITLE
v-else is invalid with v-show together

### ISSUE THREAD

**Issue by chenjieshun** [vuejs/vuejs.org#2287]
The English translated by @Jinjiang :

> ## v-else
> > A v-else element must immediately follow a v-if or a v-else-if element - otherwise it will not be recognized.
>
> Actually put **v-show** after **v-else** would cause an error.

The original Chinese issue:

> > v-else 元素必须紧跟在 v-if 或 v-show 元素的后面——否则它不能被识别。 
> 
> 实际上在 **v-show**后面跟**v-else**会报错

**Comment by phanan** [comment]
Where does it say "`v-else` must follow `v-show`" on vuejs.org? I remember fixing this issue a long time ago when v2 was released. Now it even says

![image](https://user-images.githubusercontent.com/8056274/64491656-6cc9aa00-d26b-11e9-87c1-f348a80e6af0.png)

**Comment by Jinjiang** [comment]
Oh, yes I realised this is an outdated issue. So close it.
Thanks.
