### ISSUE TITLE
Late firing of watch/$watch - call *before* dom updates

### ISSUE THREAD

**Issue by tomcon** [vuejs/vuejs.org#229]
Clicking on the span below toggles the filtered data value. This will cause the passFilterTest() function to be called before the watcher so the filtercnt var cannot be updated until after the tr's have been rendered.

```javascript
watch : {
   filtered: function(newVal, oldVal) {
      this._filtercnt = 0;
}
 methods: {
      passFilterTest : function(row){
         var ok;

         ok = ( !this.filtered || .... || .... );

         if (ok) this._filtercnt++;
         if (row.recno===this._totalrecs)
            this.numrecs=this._filtercnt;

         return (ok);
      }
   },
```

```html
<div v-show="numrecs">{{numrecs}} Reports</div>
...
<span @click="filtered=!filtered" >Filter</span>
...
<tr v-for="row in rs" v-show="passFilterTest(row)">
```

**Comment by yyx990803** [comment]
All internal watchers are fired after related DOM updates have been applied, this is the designed behavior. It seems a bad idea to have this shared state dependency between a watcher and a filter. You should use just use a method that toggles `filtered` and resets `_filtercnt` at the same time.
