### ISSUE TITLE
Hamburger menu hidden on mobile

### ISSUE THREAD

**Issue by bencodezen** [vuejs/vuejs.org#2297]
On mobile, the hamburger icon is covered by the sidebar.

![Screen Recording 2019-09-13 at 03 50 PM](https://user-images.githubusercontent.com/4836334/64890719-4a0a0d80-d63e-11e9-8510-f6a3262469fe.gif)

Hat tip to @phanan for discovering the bug!

**Comment by NataliaTepluhina** [comment]
Closing as related PR was merged
