### ISSUE TITLE
Reference to npn guide seems to be wrong.

### ISSUE THREAD

**Issue by dragz** [vuejs/vuejs.org#2301]
The reference to the npn intro in 

https://vuejs.org/v2/guide/single-file-components.html#For-Users-New-to-Module-Build-Systems-in-JavaScript

points to 

https://docs.npmjs.com/getting-started/what-is-npm

but it isn't any chapter 10 in there.

**Comment by phanan** [comment]
Indeed! Would you mind fixing it with https://docs.npmjs.com/uninstalling-packages-and-dependencies#uninstalling-global-packages?

**Comment by dragz** [comment]
I can, but wouldn't it be better to ask new users to read through the whole section about getting packages from the registry?

https://docs.npmjs.com/packages-and-modules/getting-packages-from-the-registry

**Comment by phanan** [comment]
Oh, you're right. Sorry, for some reason I only focused on the "Uninstalling…" part.

**Comment by dragz** [comment]
Ok, created a pull request.
