### ISSUE TITLE
Markdown Editor Example,  deprecated sanitize feature.

### ISSUE THREAD

**Issue by AMTazi** [vuejs/vuejs.org#2302]
According to [Marked.js Documentation](https://marked.js.org/#/USING_ADVANCED.md#options) the `sanitize: true`  is deprecated and it should NOT be used as it cannot be considered secure.

**Comment by phanan** [comment]
Thanks for opening the issue. We're aware of the deprecation, but for the sake of the demonstration, the current implementation is believed to be good enough.
