### ISSUE TITLE
Russian docs subdomain ip is blocked

### ISSUE THREAD

**Issue by Mihail0v** [vuejs/vuejs.org#2325]
$ dig
;; ANSWER SECTION:
ru.vuejs.org. 237 IN A 104.18.49.43
ru.vuejs.org. 237 IN A 104.18.48.43

[Roscomnadzor Block list ](https://blocklist.rkn.gov.ru/)check result:
ip: 104.18.49.43
Запись 1661273 ip 104.18.49.43 решение № 27-31-2018/Ид2971-18 от 16.04.2018, Генпрокуратура; дата включения: 31.07.2019 15:12
Запись 1686897 ip 104.18.49.43 решение № 27-31-2018/Ид2971-18 от 16.04.2018, Генпрокуратура; дата включения: 13.08.2019 20:25

The problem is that Roscomnadzor thinks that its Telegram's ip addresses. The only way to fix it is to change the ip of russian node.

**Comment by sdras** [comment]
This seems resolved, is it?

**Comment by Mihail0v** [comment]
> This seems resolved, is it?

No, the ip of subdomain is still same.

**Comment by phanan** [comment]
Thanks for reporting the issue, but there's little we can do about this. The IP is assigned by Netlify, which is not under our control 🙂.

**Comment by bravik** [comment]
@phanan change the hosting... or contact Netlify support to reassign the IP's...
There is no point in mantaining Russian docs if it's hosting is blocked in Russia.
The issue shouldn't be closed (
 forum.vuejs.org, chat.vuejs.org  are also blocked...

**Comment by myfbone** [comment]
It's still blocked
