### ISSUE TITLE
Update documentation to compare with knockout

### ISSUE THREAD

**Issue by milimetric** [vuejs/vuejs.org#233]
This seems like a great library that's bringing a lot of reactive programmers from different backgrounds together. But in all the intro writings I didn't find any mention of Knockout.js which it seems most similar to. I think a paragraph on how Vue compares with Knockout would be very useful.

If the authors aren't familiar with knockout, I'm happy to learn Vue while teaching someone Knockout so we can write something together that makes sense :)

**Comment by biggyspender** [comment]
Yep. I'll second that. As one of the only other frameworks that does dependency tracking, a comparison with knockoutjs is very obviously missing.

**Comment by ludo237** [comment]
I think that vuejs.org has already a lot of comparisons. Take a look at http://vuejs.org/guide/comparison.html

We cannot add every js framework out there otherwise that page will be too long.

**Comment by milimetric** [comment]
I agree that vue.js should not be compared to every framework. The reason to compare it to knockout is because of all the frameworks out there, it's by far the most similar. And since knockout was around for years and vue is new, addressing what exactly it's trying to accomplish that's different from knockout seems important. Unless of course it's trying to just steal knockout's ideas and wrap them up in a sexier package. In which case of course it shouldn't write documentation about that, it would be silly. I'm just pointing out that in the absence of that documentation people will draw their own conclusions.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Claudio LudovicoSent: Saturday, March 12, 2016 06:22To: vuejs/vuejs.orgReply To: vuejs/vuejs.orgCc: Dan AndreescuSubject: Re: [vuejs.org] Update documentation to compare with knockout (#233)I think that vuejs.org has already a lot of comparisons. Take a look at http://vuejs.org/guide/comparison.html

We cannot add every js framework out there otherwise that page will be too long.

—Reply to this email directly or view it on GitHub.

**Comment by yyx990803** [comment]
@milimetric the obvious difference is components, I'm not sure if it needed pointing out. FYI when Vue was launched (Feb 2014), Knockout didn't have the concept of components at all, it landed in Knockout 3.2 almost half a year later.

**Comment by milimetric** [comment]
Sure, but it was announced publicly by the knockout community in Jan 2014, and talked about before that. modern knockout development always uses them, but it's a very non-opinionated library. I think that might be one of the major differences, the general approach. I see vue as knockout with a few lightweight opinions                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Evan YouSent: Saturday, March 12, 2016 10:00To: vuejs/vuejs.orgReply To: vuejs/vuejs.orgCc: Dan AndreescuSubject: Re: [vuejs.org] Update documentation to compare with knockout (#233)@milimetric the obvious difference is components, I'm not sure if it needed pointing out. FYI when Vue was launched (Feb 2014), Knockout didn't have the concept of components at all, it landed in Knockout 3.2 almost half a year later.

—Reply to this email directly or view it on GitHub.

**Comment by ludo237** [comment]
@milimetric I don't know how Knockout works, I am open to any pull request about `Knockout vs Vuejs`

**Comment by milimetric** [comment]
Ok, thanks, I'll have to first learn Vue better and I'll submit a PR if someone doesn't beat me to it.

**Comment by chrisvfritz** [comment]
This is now addressed in [the 2.0 comparison guide](https://github.com/vuejs/vuejs.org/blob/2.0/src/guide/comparison.md#knockout). Would love any feedback from Knockout fans!

**Comment by milimetric** [comment]
The comparison looks great, thank you.  As a longtime knockout user, I actually agree with development slowing a bit.  I'm excited to try Vue on my next project, the component system looks really fun.

**Comment by chrisvfritz** [comment]
@milimetric Very glad to hear we did it justice! 🙂

**Comment by Solanar** [comment]
I'm looking into trying out vuejs and I'm not familiar with it yet, but in the todo list gist that is linked in the comparison, it references 

> Vue instances are scoped to a specific element, while
Knockout will parse the entire DOM.

Knockout can also be scoped to a specific element, as seen in the docs [here (Observables -> Activating Knockout)](http://knockoutjs.com/documentation/observables.html)

`ko.applyBindings(<model>, <element>);`

I've worked with knockoutjs before and it seems like vuejs definitely has less boilerplate, which is awesome.

**Comment by chrisvfritz** [comment]
Thanks for pointing this out! We'll update the doc.
