### ISSUE TITLE
Repeated reactivity explanations

### ISSUE THREAD

**Issue by opl-** [vuejs/vuejs.org#2352]
I noticed that both [Reactivity in Depth (section Change Detection Caveats)](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) and [List Rendering (section Object Change Detection Caveats)](https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats) mention the caveats of creating object properties and reactivity. They use slightly different, but fundamentally the same examples.

While this is certainly an important thing to mention, its repetition on both of those pages strikes me as odd and slightly confusing as a user coming back to the guides. I had a brief moment of uncertainty when I realized that it felt as though I've already read that section.

I'm not sure if this is significant enough to be worth correcting. Personally I feel like linking to the Reactivity in Depth page would be an easier to maintain and less confusing solution, though the importance of this explanation, as well as the name of the Reactivity in Depth guide in the section Internals suggesting it's an advanced topic and it's low position on the sidebar menu make me slightly hesitant to change it.

Thoughts?

**Comment by phanan** [comment]
I agree, linking (with a short introductive message perhaps) is a better option and more in-line with our documentation convention.

**Comment by rabbitwerks** [comment]
i also agree and would be willing to update the docs to reflect this.
