### ISSUE TITLE
bug: 'partials/blog' doesn't exist

### ISSUE THREAD

**Issue by JinsYin** [vuejs/vuejs.org#2355]
> https://github.com/vuejs/vuejs.org/blob/master/themes/vue/layout/layout.ejs#L101
> https://github.com/vuejs/vuejs.org/tree/master/themes/vue/layout/partials

**Comment by phanan** [comment]
Hmm indeed. Would you like to work on a PR to remove the logic?

**Comment by phanan** [comment]
Closed by #2362.
