### ISSUE TITLE
feature request, can we have a v-for fallback?

### ISSUE THREAD

**Issue by dotku** [vuejs/vuejs.org#2408]
each time we have to repeating writing v-else statement, which is annoying.
If we can have default fallback component, which would be perfact
 
```
<element v-for="item in items" loading="loadingComponent" default="noItemComponent" >
{{item.name}}
</element>
```

**Comment by NataliaTepluhina** [comment]
I think this feature request should go to core repository, not to the documentation one 😅 

Could you please create it on https://github.com/vuejs/vue ?
