### ISSUE TITLE
custom directive locally - where?

### ISSUE THREAD

**Issue by nerdoc** [vuejs/vuejs.org#2412]
Using vue 2.6.10.

The [docs](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/custom-directive.md) say: "If you want to register a directive locally instead, components also accept a directives option:"

```
directives: {
  focus: {
    // directive definition
    inserted: function (el) {
      el.focus()
    }
  }
}
```

Now, i think it is not clear where this code should go. What I read, is that if I have a ComponentA, and this component has a 'directives' attribute, the template **of this component** can use this directive. Complete component:

```
Vue.component("extension", {
  name: "extension",
  directives: {
      hook: {
          bind: (el, binding) => {
              console.log(binding.arg)
          }
      }
  },
  template: '<div class="extension">extension placeholder...</div>'
})
```

So I suppose I can use '<extension v-hook:foo/>' anywhere I can use the component. But this is not the case:

```[Vue warn]: Failed to resolve directive: hook```

Am I supposed to add this directive to the parent component? This makes no sense, I just want to have the `extension` component to accept that directive...

    <extension v-hook:foo/>

Is this a bug, or is there a better way of achieving this, or am I wrong assuming I can use directives for just one component?

**Comment by nerdoc** [comment]
Or is that better served with a prop?

**Comment by phanan** [comment]
It's not a bug. By registering a directive in a component, the directive is available _within_ the component. In your case, this is how it's supposed to work:

```js
Vue.component("extension", {
  name: "extension",
  directives: {
      hook: {
          bind: (el, binding) => {
              console.log(binding.arg)
          }
      }
  },
  // notice the v-hook attribute
  template: '<div class="extension" v-hook:foo>extension placeholder...</div>'
})
```

You're right that in this case, a prop should be preferred.
