### ISSUE TITLE
v-model for Radio Button array

### ISSUE THREAD

**Issue by nhugh406** [vuejs/vuejs.org#2417]
I have a v-for within a v-for that renders options per group. these radio buttons should only allow one choice per group (native radio button behavior), but i need any radio button within each group to add to an array. Example being:

Group 1:
    Opt1
    Opt2
    Opt3

Group 2:
    Opt1
    Opt2
    Opt3

I should be able to select an option from group 1 AND group 2. These options should then map to an array that i use in another function. Using v-model easily passes/updates the variable i'm trying to affect but does not "pass" each radio option from each group respectively.  Using CHeckboxes work, but I have to be able to prevent multiple options within a respective group from being selected.

here's an example;

```
<template v-for="(choices, group_name) in grouping">
    <div class="uk-width-1-1 me-choice">
        <h5 class="groupingHdr">
            {{ group_name }} Plans
        </h5>
        <div class="uk-child-width-auto uk-grid-small" uk-grid>
            <template v-for="item in choices">
                <div>
                    <div>
                        <input :id="item.Plan_ID+item.Tier_ID" type="radio" :value="item.Plan_ID+item.Tier_ID"
                            v-model="compChoicesSel" @change="loadContributions()">
                        <label :for="item.Plan_ID+item.Tier_ID">
                            {{ item.Option }} -
                            {{ item.Tier }}
                        </label>
                    </div>
                </div>
            </template>
        </div>
    </div>
</template>
```

**Comment by NataliaTepluhina** [comment]
You need to have two different `v-model`s for two different groups.

Please, don't use issues in this repo for Vue-related questions. If you look for help, please refer to [Vue Forum](https://forum.vuejs.org/) or [VueLand Discord channel](https://discordapp.com/invite/HBherRA).
