### ISSUE TITLE
Translation links lead to external sites. 

### ISSUE THREAD

**Issue by Den2016** [vuejs/vuejs.org#2424]
Is it a bug or feature? 
Is there a Russian version of offline documentation? ru.vuejs.org opens so long... 16-17 seconds per page.

**Comment by NataliaTepluhina** [comment]
Opens literally 1s for me, probably the connectivity issue.
You can find Russian translation repo [here](https://github.com/translation-gang/ru.vuejs.org)

**Comment by Den2016** [comment]
О, спасибо ))
