### ISSUE TITLE
Does it support conditional render html attribute?

### ISSUE THREAD

**Issue by libertyAlone** [vuejs/vuejs.org#243]
v-if can conditional render html element, but I want to conditional render html attribute.How can I do that?
I prefer it like this:
`
<input :diabled="v-if {{flag}}" type="text">
`
if flag == true, rendered result is 
`
<input diabled type="text">
`
if flag == false, rendered result is 
`
<input type="text">
`
ps:diabled="false" is the same as disabled="true" :)

**Comment by simplesmiler** [comment]
`:disabled="flag"`

**Comment by hootlex** [comment]
You can bind `disabled` attribute directly to your expression, in your case `flag`.

```HTML
<input :disabled="flag" type="text"> 
```

You can see a live example [here]().

**Comment by ludo237** [comment]
@hootlex and @simplesmiler have already answered. I close this.

**Comment by deckar01** [comment]
That solution does not work for all HTML attributes. The one I am having trouble with is the `<progress>` element. The mere presence of the `value` attribute, regardless of its value, changes the behavior of the element. Without this feature I have to duplicate the entire tag and all the other attribute bindings just to toggle the presence of of the attribute.

**Comment by disapamok** [comment]
If you want to put attribute with a value.
`:your-attr="flag ? 'attr-value' : false"`

**Comment by kuige** [comment]
In some situations, the ability of conditional rendering of html attributes is still needed, for example, the breadcrumb, `<el-breadcrumb-item :to="{ path: '/' }">home</el-breadcrumb-item>`, if the "to" attribute isn't needed, it cannot be `<el-breadcrumb-item :to="false">home</el-breadcrumb-item>`, the "to" attribute is the same as `<router-link>`.

Yes, I can do this in another way, but it's much straightforward if there is a conditional rendering directive.
