### ISSUE TITLE
In comparison page, Glamorous now deprecated

### ISSUE THREAD

**Issue by samuelpath** [vuejs/vuejs.org#2430]
In the [comparison page](https://vuejs.org/v2/guide/comparison.html), it says:

> React is often done via CSS-in-JS solutions (e.g. styled-components, glamorous, and emotion)

However, [Glamorous](https://github.com/paypal/glamorous) is now deprecated and unmaintained, so maybe it should not be mentioned here anymore?

**Comment by phanan** [comment]
That makes perfect sense! Would you want to work on a PR?

**Comment by NataliaTepluhina** [comment]
Closing this as related PR was merged 👍
