### ISSUE TITLE
index.md guide importing Vue is a bit confusing

### ISSUE THREAD

**Issue by nickycutesc** [vuejs/vuejs.org#2440]
I'm a bit confused about what's the proper way to import Vue. 

On this page: https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/index.md

I see that in the default index.html and in JSFiddle Hello World example, Vue is imported using the following: <script src="https://unpkg.com/vue"></script>

whereas the guide recommends to use the following: <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

Are there any differences between the two import statements?

**Comment by NataliaTepluhina** [comment]
Not really, it's just a different CDN (it's mentioned in the [Installation](https://vuejs.org/v2/guide/installation.html#CDN))

Both will give you Runtime + Compiler UMD build that can be used directly in the browser via a `<script>` tag.

**Comment by nickycutesc** [comment]
Oh wow, it was staring right at me lol. Thx @NataliaTepluhina !
