### ISSUE TITLE
Sidebar scrollbar

### ISSUE THREAD

**Issue by ksdev-pl** [vuejs/vuejs.org#245]
Hi

As in: https://github.com/vuejs/vue-devtools/issues/60, a scrollbar for the sidebar menu would be great. Especially when you're on the http://vuejs.org/api page - the sidebar is quite long; at first look you don't even know that you can scroll it.

**Comment by ludo237** [comment]
If you hover the mouse on the sidebar you will be able to scroll the API menu on http://vuejs.org/api

**Comment by ksdev-pl** [comment]
Yes, with middle mouse button. I was writing about scrolling _without_ middle mouse button, with normal scrollbar.

**Comment by ludo237** [comment]
That would break the aesthetics of the template itself

**Comment by ksdev-pl** [comment]
Possibly, yes. 

My reasons are three: 
1. At first look you don't know that you can scroll this part of the page, it looks broken with long list, 
2. Mouse without / with broken scroll, 
3. RSI (with which you should not use mouse scroll).

There is indeed a scrollbar showing up in firefox (when you scroll the main scrollbar slightly) - so the aesthetics is already broken ;) but it doesn't work in Chrome.

**Comment by ludo237** [comment]
The last decision must came from @yyx990803 if he agree with this I can fix it quite easily, or if you have a pull request you will be able to do it.

**Comment by ksdev-pl** [comment]
I've made a pull request fixing (or changing - it looks like Evan really doesn't like scrollbars) the Firefox - Chrome difference. I still propose to show the sidebar scrollbar always. If Evan will agree with it I can prepare another pull request if it will be needed.
