### ISSUE TITLE
All <code class="hls are html but some should be "js" | free video

### ISSUE THREAD

**Issue by RichBernhardt** [vuejs/vuejs.org#2474]
Hello Guys

A few notes regarding page https://vuejs.org/v2/guide/components-slots.html

All <code class="hls are 'html' but some should be 'js'. As a beginner I couldn't understand the concept of slots as both JS and HTML templates are called templates and couldn't identified which code source is the HTML and which one is the JS.
Making explanation even more understandable, putting 
Vue.component('whatever-id', {
				template: `...
would greatly improve the understanding, I think.

In the end this free video helped me to understand the concept. I think putting a link of the vid onto the top of the page as done on other pages would also be a great help.
https://vueschool.io/lessons/component-slots

The following snippet would also make a big help:

`<!DOCTYPE html>
<html>
	<body>
		<div id="app">
			<slot-example-container>
				<p>This has been inserted</p>
			</slot-example>
		</div>

		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
		
		<script type="text/javascript">
			Vue.component('slot-example-container', {
				template: `
					<div>
						<slot></slot>
					</div>`
			})

			new Vue({ el: '#app' })
		</script>
	</body>
</html>
`

Many thanks for all your effort.
I really appreciate it.

Cheers
Rich

**Comment by phanan** [comment]
Thanks for opening the issue, but to be honest I'm having a hard time trying to get what you want to convey. Would you mind open one PR for each of the problems you see, and we'll start from there one by one?
