### ISSUE TITLE
Open Collective avatars are broken

### ISSUE THREAD

**Issue by talkor** [vuejs/vuejs.org#2482]
<img width="780" alt="Screen Shot 2020-02-15 at 13 11 37" src="https://user-images.githubusercontent.com/18269880/74608136-4eec5500-50e7-11ea-950e-79a4f9aad431.png">

**Comment by NataliaTepluhina** [comment]
Thank you for the report! However, they appear to be fine for me:

![Screenshot_5](https://user-images.githubusercontent.com/18719025/74608727-434f5d00-50ec-11ea-87a7-5c4b08ef7aec.png)

Might be a connectivity issue
