### ISSUE TITLE
Some code example indication should be JS instead of HTML

### ISSUE THREAD

**Issue by RichBernhardt** [vuejs/vuejs.org#2483]
Hi Phan

Thanks for your comments regarding #2243 
Please see code snippet snapshots below which should be indicated as JS not HTML on page https://vuejs.org/v2/guide/components-slots.html

Many thanks
Rich

![Screenshot from 2020-02-17 09-46-22](https://user-images.githubusercontent.com/8362126/74637847-18581e00-516b-11ea-97de-4665a7db8f35.png)
![Screenshot from 2020-02-17 09-46-59](https://user-images.githubusercontent.com/8362126/74637851-19894b00-516b-11ea-945c-2bcc5f84d5ad.png)
![Screenshot from 2020-02-17 09-47-07](https://user-images.githubusercontent.com/8362126/74637853-1a21e180-516b-11ea-8322-308741dbcd4e.png)
![Screenshot from 2020-02-17 09-47-35](https://user-images.githubusercontent.com/8362126/74637854-1aba7800-516b-11ea-98ef-eb6ab41bb110.png)
![Screenshot from 2020-02-17 09-48-09](https://user-images.githubusercontent.com/8362126/74637855-1aba7800-516b-11ea-98d4-5e393028807d.png)
![Screenshot from 2020-02-17 09-48-18](https://user-images.githubusercontent.com/8362126/74637857-1b530e80-516b-11ea-8e34-e762e95daced.png)

**Comment by phanan** [comment]
Thanks. The way I see it, all of the snippets above are HTML. Or did I miss anything here?

**Comment by RichBernhardt** [comment]
As I see, the full code for this particular snippet:
![Screenshot from 2020-02-17 09-47-07](https://user-images.githubusercontent.com/8362126/74665494-25433480-51a0-11ea-8df4-6187e9e3f0cf.png)
...would be something like this:

```
<!DOCTYPE html>
<html>
	<body>
		<div id="slot-demo">
			<submit-button>
				Save
			</submit-button>
		</div>

		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

		<script type="text/javascript">
			Vue.component('submit-button', {
				template: `
					<div>
						<button type="submit">
							<slot>Submit</slot>
						</button>
					</div>
				`
			})

			new Vue({
				el: '#slot-demo'
			})
		</script>
	</body>
</html>
```
Is this correct?
If so, then the following isn't the same scenario?
![Screenshot from 2020-02-17 16-13-58](https://user-images.githubusercontent.com/8362126/74665756-9387f700-51a0-11ea-84c3-c917efda5c17.png)
https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots

Cheers

**Comment by phanan** [comment]
Ah. The former is HTML code (or the `template` section inside single file components) when the latter is JS. So the documentation is correct here.

**Comment by RichBernhardt** [comment]
Thanks Phan for clarifying this.
Just one more question.
What a beginner is supposed to learn first, slots or single file components?
The way this guide is built is that slots are far earlier discussed than single file components.
So I understand that the code is correct, but I am wondering if this the most digestible presentation order?
Or did I miss anything here?

**Comment by NataliaTepluhina** [comment]
@RichBernhardt @phanan sorry for jumping in 😅 

I would say slots and SFC are orthogonal things: you can learn them independently. Single-file component is just a pattern created for better developer experience so the component could be placed withing `.vue` file. In fact, even if `template` part is written as a string in `template` component property or with [x-template](https://vuejs.org/v2/guide/components-edge-cases.html#X-Templates), it's still a HTML-code (slightly extended with Vue-related properties). Also, marking this as HTML helps us with the proper highlighting.

**Comment by RichBernhardt** [comment]
@NataliaTepluhina @phanan 

Hi Natalia, thanks for your thoughts.

The thing is that Slots is the first chapter in the Guide where familiarity with SFC is a prerequisite and nothing informs about this. I've started the whole Guide from the beginning and suddenly I did not understand what's going on :)

What about completing the first note of the Slots page:

> This page assumes you’ve already read the Components Basics. Read that first if you are new to components.

With SFC?:

> This page assumes you’ve already read the Components Basics **and Single File Components**. Read that first if you are new to components.

**Comment by NataliaTepluhina** [comment]
Slots do not require SFC knowledge, as I've mentioned above. These two chapters are independent.

**Comment by RichBernhardt** [comment]
I'm with you Natalia regarding Slots do not require SFC knowledge.

The presentation of Slots however does require SFC. The presentation could have been written either with or without SFC.
It has been written with SFC.

Therefore, however, Slots itself does not require SFC knowledge, their presentation does require at its current form.

Consider an analogy with English. The Guide is in English. Why? Because English is the default world language. Slots doesn't care what language its presentation is written, it operates in the same way regardless the presentation's language.
But the user, who the Guide is for, might not understand. Although that would be the whole point of the Guide.

The Guide is not for the Slots but the Users. And users won't know that the presentation is based on SFC. They won't even know that there is such a thing that SFC. So they won't even know what should they know once they reach the chapter of Slots. Such like I did not have a clue...

I hope this makes my point a bit clearer.

PS: the prerequisite on the top of the page notifies about component basics which is a chapter that preveils Slots, while SFC is a latter one. I think the prerequisite note would be more related to SFC than Composit basics.

Cheers
Rich

**Comment by phanan** [comment]
I'm sorry but this (closed) issue is not really the best place to discuss SFC/components. Better mediums would be our forum or Discord, or even StackOverflow. Cheers.
