### ISSUE TITLE
Documentation: Examples for v2 are missing

### ISSUE THREAD

**Issue by maratumba** [vuejs/vuejs.org#2484]
All examples on https://vuejs.org/v2/examples/ throw "sandbox not found" error.
e.g:
https://vuejs.org/v2/examples/index.html
https://vuejs.org/v2/examples/commits.html
https://vuejs.org/v2/examples/grid-component.html

**Comment by NataliaTepluhina** [comment]
@maratumba hmm it works fine for me (tested also with incognito mode and with VPN changing a few locations).

Could you please provide more details about the error?

**Comment by maratumba** [comment]
Now it works for me too. Must have been some temporary connection problem. Sorry for the false alarm.

**Comment by NataliaTepluhina** [comment]
Np! Thank you for reporting it anyway! 👍
