### ISSUE TITLE
<component /> preserves state of locally registered components

### ISSUE THREAD

**Issue by rp-pedraza** [vuejs/vuejs.org#2485]
In https://vuejs.org/v2/guide/components-dynamic-async.html#keep-alive-with-Dynamic-Components it is shown that the component is reinstantiated everytime the tab is switched, but this is not the case when the components are registered locally. The selection is preserved.

Please see this modified version of the example which doesn't use `Vue.component()`: https://codesandbox.io/s/pensive-dream-x27mf.  Vue version used is 2.6.11.

I like this behavior and I hope it gets documented and explicitly declared official.

**Comment by phanan** [comment]
That's because in your example, you're already using `keep-alive`. Once it's removed, the behavior will be reverted back to as documented.

**Comment by rp-pedraza** [comment]
Well this was a blunder.  I didn't check the keep-alive and presumed that it wasn't there.  But I do have a component that keeps a persistent state.  I'll try to examine it further and see if I can replicate it.  Maybe it's got something to do with component wrapping.
