### ISSUE TITLE
Allow cross origin access error

### ISSUE THREAD

**Issue by Ask149** [vuejs/vuejs.org#2495]
Hi, I'm am working on integrating a vuejs template in spring boot admin, and I was successful in integrating the same. As per the project requirement, I was required to make a GET request to a specific URL which is in the same service ( http://localhost:8080/... ). However, the url of the service varies as per the environment it is running on. But, when the GET call is requested through axios along with the headers for CORS ( Allow Cross Origin... ), I'm getting an error specifying Allow cross origin headers not present. To make sure I try every other alternatives, I've even added the required Bean in Spring Java Code for CorsConfiguration and also added properties for CORS in application.properties file. Could you help me with this issue?

**Comment by phanan** [comment]
Please use our [forum](https://forum.vuejs.org/) or [Discord](https://vue-land.js.org/) for questions like this. Thanks.
