### ISSUE TITLE
[Proposal] Content linting

### ISSUE THREAD

**Issue by sarahdayan** [vuejs/vuejs.org#2499]
Hi there!

In the VuePress documentation, we've set up [content and Markdown linting](https://github.com/vuejs/vuepress/tree/master/packages/docs) with [textlint](https://github.com/textlint/textlint) and [remark-lint](https://github.com/remarkjs/remark-lint). This is helpful to ensure consistency over natural language style, Markdown formatting, and help to enforce rules that have been decided upon.

Similarly to ESLint, textlint lets you add and configure rules as plugins, and create your own. These can be checked in the CI or as a pre-commit hook and allow reviewers to focus on meaning instead of style.

Examples of rules that we've activated in VuePress:

- `textlint-rule-apostrophe`, to use consistent apostrophes (instead of a mix of straight and curly)
- `textlint-rule-common-misspellings`, to catch common typos from [this curated list](https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines)
- `textlint-rule-terminology`, to consistently spell terms, brands and technologies spelling (no more "npm" and "NPM" across docs!)
- `textlint-rule-write-good`, to improve English prose and make the Vue docs even more enjoyable to read (if such a thing is even possible)

Here's a more exhaustive list: https://github.com/textlint/textlint/wiki/Collection-of-textlint-rule

If this is something that interests you, I'm willing to take care of setting it up, install and configure the rules that you want to activate, and start the process of running it through the documentation.

Let me know what you think!

**Comment by NataliaTepluhina** [comment]
As we're moving to VuePress for Vue 3 docs, we set up rules there 👍

If you're willing to work on Vue 2 documentation linting, please do so but my concern is it might be wasting your time and effort

**Comment by sarahdayan** [comment]
@NataliaTepluhina Great news! Indeed, if this is happening on the Vue 3 docs, it's probably overkill to add it on the Vue 2 docs which will lose viewership with time anyway.

Thanks for your prompt reply! I'm closing this then 🙂

**Comment by NataliaTepluhina** [comment]
@sarahdayan as soon as we open Vue 3 docs  - would you mind helping us with linters? 😅

**Comment by sarahdayan** [comment]
@NataliaTepluhina Of course, I would love to!
