### ISSUE TITLE
[docs] inform that props stack

### ISSUE THREAD

**Issue by imaia** [vuejs/vuejs.org#250]
Please, add to the documentation that props stack when extending.
http://jsfiddle.net/avekyjzt/2/

**Comment by chrisvfritz** [comment]
It is specified that `Vue.extend` creates something like a sub-class, so I feel it would be expected that options merge intelligently (not only props, but also data, computed, watchers, etc). I'll think I'll close this for now, as I haven't seen a great deal of confusion around this behavior and no one else has chimed in with similar concerns in 4 months.
