### ISSUE TITLE
Example missing

### ISSUE THREAD

**Issue by tobyjoiner** [vuejs/vuejs.org#2509]
[https://vuejs.org/v2/examples/modal.html](https://vuejs.org/v2/examples/modal.html) is missing the example in the middle of the page.

**Comment by phanan** [comment]
Can you try disabling/clearing cache and refreshing the page?

**Comment by phanan** [comment]
Update: https://twitter.com/siddharthkp/status/1234883523510784001.
I think we can close this now 🙂

**Comment by Rambone** [comment]
Yes, I know this issue is close, but the CodeSanbox links are still broken …
Doesn't matter which browser, if cache and cookies are cleared or not.

**Comment by CarbonCollins** [comment]
Seems to be no longer working again. CodeSandbox is saying that it is not found
