### ISSUE TITLE
CodeSandbox links are broken

### ISSUE THREAD

**Issue by HZooly** [vuejs/vuejs.org#2510]
Documentation about [Dynamic Components](https://vuejs.org/v2/guide/components.html#Dynamic-Components) get two broken links:
- https://codesandbox.io/s/github/vuejs/vuejs.org/tree/master/src/v2/examples/vue-20-dynamic-components-with-binding
- https://codesandbox.io/s/github/vuejs/vuejs.org/tree/master/src/v2/examples/vue-20-dynamic-components

**Comment by phanan** [comment]
We're encountering some hiccup with CodeSandBox. Let's merge this issue with #2509.
