### ISSUE TITLE
documentation and the tutorials are incomplete for a new guy.

### ISSUE THREAD

**Issue by dgoelhs** [vuejs/vuejs.org#2553]
There isn't a single place where it is mentioned that the Vue only application will be visible at localhost:8080. I just found a video in which I figured that I have to open the localhost and then only my app will be visible.

**Comment by NataliaTepluhina** [comment]
@dgoelhs Vue application is not availabe by default on `localhost:8080`.  You probably have seen a tutorial using [Vue CLI](https://cli.vuejs.org/guide/) that by default runs a dev server on `localhost:8080` indeed. However, core documentation doesn't assume you have a building step.
