### ISSUE TITLE
Documentation: reference to `Guide` in #v-model is not clear

### ISSUE THREAD

**Issue by geoidesic** [vuejs/vuejs.org#2565]
On this page: https://github.com/vuejs/vuejs.org/blob/master/src/v2/api/index.md
On line 2253: "Create a two-way binding on a form input element or a component. For detailed usage and other notes, see the Guide section linked below."

It is not clear what is meant by "the Guide section linked below".

**Comment by Jinjiang** [comment]
That means the 2 links below: "Form Input Bindings" and "Components - Form Input Components using Custom Events". They all come from the "Guide" part.
