### ISSUE TITLE
Request for example: A sortable list

### ISSUE THREAD

**Issue by nileshtrivedi** [vuejs/vuejs.org#2574]
A very common use-case seems to be really tricky to implement in Vue, the docs don't cover these aspects very well and the community seems to lack the know-how and best practice for this with modern versions of Vue.

Say, you want to build a custom list component with re-arrangable list-items and offer this as a reusable component to sites without module bundlers.

This is a minimal example of what should be possible:

```
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-sortable-list.js"></script>

<vue-sortable-list>
  <vue-list-item>Arbitrary HTML here</vue-list-item>
  <vue-list-item>Second item</vue-list-item>
</vue-sortable-list>
```
with controls on each list-item to push it up or down.

This requires using slots, setting up communication between child components and parent components, keeping the order of slots and children in sync, producing the right build (library or webcomponent) with a good number of gotchas.

A working example that demonstrates the correct way of doing all of these (slots/events/$children) is sorely needed. Closest example of similar functionality is https://github.com/SSENSE/vue-carousel however this does not work as a UMD library or a WebComponent. Questions on StackOverflow are mostly unanswered. In the forums too, there seems to be no consensus on what's the right way of wiring this up is. `vue-web-component-wrapper` has [open issues](https://github.com/vuejs/vue-web-component-wrapper/issues/60) but the docs for using slots in this manner are non-existent.

Adding this example will help VueJS beginners a lot as this pattern of nested components with slots seems to be quite common.

**Comment by bencodezen** [comment]
Thanks for sharing your concerns @nileshtrivedi.

Component design patterns are complicated as their complexity is dependent on the requirements set for them (even in the sortable list use case that you mention). While your situation may call for slots, events, and such, others may only need a computed property that updates the rendered list order.

In terms of the desire to "produce the right build," this knowledge is separate from the Vue framework itself and not required for a developer to be productive with Vue. As a result, it wouldn't be a good fit for the docs.

Finally, whether or not a solution is "right" or "best practice" is often heavily contingent on the context and requirements that the developer is working in. 

To help in your search for an answer to your situation, I'd recommend breaking up your question into two separate issues for the forums:

1. **Show a reproducible example of your sortable list and the problems you are having with it.** This will allow for more fruitful discussions regarding what is going on.

2. **Share a repo that contains your attempts at the library build you've created and share the problems you are having.** By doing this, hopefully there will be others who can share their experience with you and help you out.

Best of luck on your journey with this component!
