### ISSUE TITLE
Lack of definition in the component tag.

### ISSUE THREAD

**Issue by chumager** [vuejs/vuejs.org#2590]
Hi, for a couple of years I was using Vue.component to load components dynamically, that's the way your documentation shows, because I don't know at first what I'm going to load.

That's bothers me a lot because I can produce names overload and others problems.

Yesterday after reading some comments and questions I realize the **is** attribute supports Strings and Objects, even Functions. So I create a component who uses "component" tag to automagically load components.

I'll be really nice to add other examples to the documentation so everyone will know the fantastic of the "component with is attribute".

Best regards.  

PS: the URL is https://vuejs.org/v2/guide/components-dynamic-async.html

**Comment by bencodezen** [comment]
Thanks for your suggestion @chumager! I'm glad that you were able to discover the `is` attribute. We will be sure to take a look at how to best highlight this in the docs post 3.0. Thanks again!

**Comment by chumager** [comment]
Hi @bencodezen, I use the "is" attribute since the beginning, what I didn't know and isn't explained in the docs is that you can pass, besides a component name already declared via Vue.component, a function for lazy load and an object definition.

That's why I first declared a component via Vue.component in created or mounted hook and then use the "is" attribute in the template section.

It's a very powerful tool the "is" attribute, but the lack of documentation avoids the full use of the potentiality it has.

Best regards.

**Comment by bencodezen** [comment]
@chumager You bring up a great point. We can certainly provide better documentation to expose the full potential of the component import methodologies. Thank you for opening the issue and providing the feedback!
