### ISSUE TITLE
Show the shorthand for defining a function inside a method

### ISSUE THREAD

**Issue by ConnorIngold** [vuejs/vuejs.org#2599]
In the Vue documentation under [methods ](https://vuejs.org/v2/api/#methods) it gives the following example: 
```
var vm = new Vue({
  data: { a: 1 },
  methods: {
    plus: function () {
      this.a++
    }
  }
})
vm.plus()
vm.a // 2
```

It's noted why you shouldn't use arrow functions but doesn't note the shorthand for defining functions (or at least I can't find where it talks about it 😅) so for the above example, you could do: 

```
var vm = new Vue({
  data: { a: 1 },
  methods: {
    plus() {
      this.a++
    }
  }
})
vm.plus()
vm.a // 2
```

Is this documented? If so where? There's an entire section dedicated [Event Handler Shorthands  ](https://vuejs.org/v2/guide/syntax.html#Shorthands). 

I propose another note be added underneath to explain it although what most important is that it is explained. Hopefully, this hasn't been brought up already I had a quick search and couldn't see anything.

**Comment by NataliaTepluhina** [comment]
Thank you for opening the issue! This shorthand is not something Vue-specific, it's common ES6 feature known as [object method shorthand syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions).

In Vue3 upcoming documentation, all the examples will use this syntax, so we won't need a dedicated section explaining it.
