### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by ameesters** [vuejs/vuejs.org#260]
Hello,

I want to translate the website to dutch, so my fellow dutch-man can read it in their native language.
Now i have been thinking on how to approach this, i could just fork the repository into my own GitHub repository but that way doesn't seem to invite community support for it, and also will fragment ownership.

I have seen that for other translations you have a repository in the vuejs organisation, could this also be done for the dutch translation?

I don't mind cloning it to my own repository and work on it there, i just don't know if that is wise and desired?

**Comment by yyx990803** [comment]
Yes - forking is the best way to start. In general we expect to see some initial work just to confirm your commitment before moving the repo into the organization - the moving isn't that complicated though.

**Comment by ameesters** [comment]
sure thing, will get started tonight!

**Comment by oscaralexander** [comment]
Let me know if you need any help @ameesters!

**Comment by chrisvfritz** [comment]
@ameesters @oscaralexander Is there still interest in making this happen? If so, it may be worth starting with the 2.0 docs at this point. If you do want to try, I can read Dutch and would be happy to review any especially tricky parts.

**Comment by ameesters** [comment]
i did get started on the 1.0 docs, but at this point its better to do the 2.0 first... I am sorta busy at the moment, starting a new job on friday, recording screencasts on vue and es6, so i dont know exactly when i will come around to do it...

**Comment by sdras** [comment]
Hey hey! It's been more than a year since we last talked. Are you still interested in creating this. If so, great! If not, it would be nice to close out the issue in case someone else wants to take up the charge. Thanks!

**Comment by sdras** [comment]
Closing this out due to inactivity. Please feel free to reopen :)
