### ISSUE TITLE
Change example with 3rd party JS Animation library to anime.js or GSAP

### ISSUE THREAD

**Issue by johlug** [vuejs/vuejs.org#2603]
for v3 docs. 

### Transitions
https://vuejs.org/v2/guide/transitions.html

As a 3rd party Animation library Velocity.js is mentioned (also with example code). In former days Velocity.js was a good alternative to jQuery's animations (think because old jQuery didn't use requestAnimationFrame). But nowadays jQuery is as fast as Velocity and Velocity is not used by many. I would make instead an example with anime.js or GSAP.

**Comment by phanan** [comment]
According to [this](http://libscore.com/#$.Velocity) I wouldn't say "Velocity is not used by many." Nevertheless, I personally don't think this is worth a change—the point we're trying to make should be library-agnostic.

**Comment by phanan** [comment]
Sorry, I didn't mean to close the issue. Let's keep it for post 3-0 discussions.

**Comment by johlug** [comment]
Okay. 
I am not sure if your link (http://libscore.com/#$.Velocity) is working well. On the first three listed sites i could not detect $.Velocity and when i query a site on this page it says 
"No libraries or scripts were detected!"
I think the example should be with an active maintained library, otherwise the docs seems also not active maintained.

**Comment by sdras** [comment]
I ran benchmarks a while ago and this is salient. I rewrote the new docs to use gsap for the examples anyways, primarily because jumping around from library to library in every example is cumbersome to the person learning, which is the most important part. Thanks!
