### ISSUE TITLE
Add missing "the" article

### ISSUE THREAD

**Issue by brunodevel** [vuejs/vuejs.org#2623]
A very tiny issue for post-v3. It seems like there is an article "the" missing in the following sentence on the [API > Special Attributes > ref](https://vuejs.org/v2/api/#ref) page:

> If used on a plain DOM element, the reference will be that element; if used on a child component, the reference will be **the** component instance:

**Comment by bencodezen** [comment]
Thank you for catching this @brunodevel! We will be sure to fix this soon. Appreciate it!

**Comment by sdras** [comment]
This is done :)
