### ISSUE TITLE
Forums not sending Validation email

### ISSUE THREAD

**Issue by kubacode** [vuejs/vuejs.org#264]
Hey there, just wanted to give you a heads up that the forums aren't sending a validation email at the moment. When trying to send the validation email, I get the error 'ERROR spawn sendmail ENOENT' returned.

I'm not able to post this issue in the forum (or chat with you about it) as my email isnt validated - doh!

**Comment by yyx990803** [comment]
Ah, the emailing plugin was missing after a reinstall. Should be fixed now - can you try asking it to send the verification email again?

**Comment by kubacode** [comment]
That seems to have fixed it - thanks for the quick response!
