### ISSUE TITLE
change tabs

### ISSUE THREAD

**Issue by zhytang** [vuejs/vuejs.org#2668]
Web address: https://vuejs.org/v2/guide/components-dynamic-async.html
Keep going up until you can't see.

![QQ20200819-153533-HD](https://user-images.githubusercontent.com/16872071/90606015-c6837400-e231-11ea-913a-3462b5133bf7.gif)

**Comment by bencodezen** [comment]
Thanks for finding and reporting the bug @zhytang!

**Comment by Justineo** [comment]
Fixed by #2700.
