### ISSUE TITLE
v3 API docs link broken

### ISSUE THREAD

**Issue by ricardobeat** [vuejs/vuejs.org#2707]
After visiting vuejs.org and reaching the [API page](https://vuejs.org/v2/api/), if you switch to v3, it redirects to https://v3.vuejs.org/api/ which is a 404 + a broken `<[object Object]>` tag at the top.

A working link is https://v3.vuejs.org/api/application-config.html, it seems there is no index page defined for `/api`.

**Comment by bencodezen** [comment]
Thanks for filing this @ricardobeat! We'll make sure to take care of that ASAP!
