### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by hthabet** [vuejs/vuejs.org#271]
Hello,

I just started translating the website in french. It is in progress at [hthabet/vuejs.org:lang-fr](https://github.com/hthabet/vuejs.org/tree/lang-fr)

Of course, if anyone wants to join, help is more than welcome :)!

**Comment by yyx990803** [comment]
Very cool! Thanks for the effort!

**Comment by hthabet** [comment]
**Translations**
- [ ] Guide 
- [x] API
- [ ] Examples **in progress**
- [ ] Other

**Review**
- [ ] Guide 
- [ ] API
- [ ] Examples
- [ ] Other

**Comment by lionel-bijaoui** [comment]
@hthabet How can I help ? I love VueJS and I would like to help.

**Comment by hthabet** [comment]
Hi @lionel-bijaoui! So I started translating the **Guide** page of VueJs documentation. As you can see, there are so many sections :) (Installation, Getting Started etc...). I started by the first section but feel free to fork https://github.com/hthabet/vuejs.org and pick any section you want to translate and you feel comfortable with.
Thank you for your help!

**Comment by lionel-bijaoui** [comment]
I'm starting with **Comparison with Other Frameworks**, will see how productive I can get :)

**Comment by chrisvfritz** [comment]
@hthabet @lionel-bijaoui It looks like progress on this has stalled a bit. If you're still interested in continuing, it might make more sense to start fresh with the 2.0 branch at this point. What do you think?

**Comment by lionel-bijaoui** [comment]
Yeah, sorry about that. It make more sense to go with 2.0, you are right !
I'm working on [vue-form-generator](https://github.com/icebob/vue-form-generator/) lately but once I'm done, I will get to work (for real this time, sorry :sweat_smile:)

**Comment by chrisvfritz** [comment]
Pas grave. 😄

**Comment by hthabet** [comment]
@chrisvfritz yes it makes more sense to go straight with 2.0. I was free the last few months and I have done more translation for 1.x (I did not push them yet though). but lately, I started being full time on another project using a different framework.

**Comment by sylvainpolletvillard** [comment]
Hi there, bonjour à vous. I would be glad to help with the French translation of Vue.js starting from 2.0. I already maintain the translation of [Riot.js french docs](http://riotjs.com/fr/) so I have a few experience. 

@hthabet @lionel-bijaoui vous en êtes où sur la 2.0 ? comment peut-on se répartir le travail ?

**Comment by lionel-bijaoui** [comment]
@sylvainpolletvillard J'ai rien commencé, je suis trop pris en ce moment. J'essaye de libérer un peu de temps.
La documentation de la 2.0 est fini en anglais ?

**Comment by chrisvfritz** [comment]
The English version of the guide is about as "ready" as frequently-updated docs ever are. 🙂 We just pushed up the new migration guide last yesterday, which was the last remaining item. The API is still being added to however.

**Comment by lionel-bijaoui** [comment]
@chrisvfritz Thank you for your hard work!

**Comment by sylvainpolletvillard** [comment]
https://github.com/hthabet/vuejs.org has not been updated in 6 months and does not have any 2.0 docs. Should I continue on this repo or restart from the latest 2.0 docs ?

**Comment by amouillard** [comment]
I'd like to help, is the translation still going on ?

**Comment by sylvainpolletvillard** [comment]
I think @hthabet repo is too old, we should start from a new one. I have started one myself but I am too busy at the moment to continue. Maybe if we share tasks and find 1-2 more people, it would be feasible

**Comment by Haeresis** [comment]
Hi Everybody,

I think it's maybe the good thread. I already send this message via Gitter to Evan You but maybe it's more easy for all to do that here.

« Hi Evan You !
I heard you come to a Meetup this Saturday https://www.meetup.com/fr-FR/Vuejs-Paris/

I'm french and I see there is a CN and JP translation for Vue Official Website : (https://github.com/vuejs/cn.vuejs.org and https://github.com/vuejs/jp.vuejs.org)

My question:

> Could you open a https://github.com/vuejs/fr.vuejs.org repository to allows me and other french people to contribute to Vue.js French Translation ?

I already traduce the page that compare Vue.js and others MVVM https://blog.lesieur.name/vuejs-versus-angular-versus-react-versus-les-autres-mvvm/ to allows french people to discovered Vue but I think it's better to traduce all directly into official Website.
And maybe ask Saturday to others if they want help to translate too. »

So, what is the status of French translation? I think it's a better choice to work from « https://github.com/vuejs/vuejs.org » now.

**Comment by zyhou** [comment]
Any news @Haeresis about fr.vuejs.org ?

**Comment by yyx990803** [comment]
Hi all - to reduce admin overhead, the recommended workflow for future community translations are:

- Create an organization dedicated to translation purposes, e.g. `vuejs-fr`. All contributors can then be invited into that organization.
- Fork `vuejs/vuejs.org` in that organization, and work in that fork.
- When it's done:
  - update `src/CNAME` to point to the desired subdomain (e.g. `fr.vuejs.org`)
  - update the deployment section in `_config.yml` to use the git URL of the fork
  - deploy with `hexo deploy` (this will deploy the site via github pages)

Then all I need to do is pointing the subdomain's DNS CNAME to GitHub and the site will be live!

**Comment by Haeresis** [comment]
Ok all.

Vue.js FR organization is created : https://github.com/vuejs-fr and
fr.vue.js repository is forked https://github.com/vuejs-fr/vuejs.org

**I invite all users who want participate to the translation to say that here! All work already done could be integrate in this repository.**

Currently:
- src/CNAME request fr.vuejs.org
- _config.yml is setted like this:
  - description: "Le Framework JavaScript Évolutif" (This sound more french which « Le Framework JavaScript Progressif » but share your comment!).
  - url: http://fr.vuejs.org
  - date_format: D MMM YYYY

I have removed the CNAME from `https://github.com/vuejs-fr/vuejs.org/tree/gh-pages` so the website run here for moment:
- https://vuejs-fr.github.io/vuejs.org/

I see some CSS/JS path not work so I guess some parameters are not fully translated for `https://github.com/vuejs-fr/` url, so I will try to check that, but if you have already the solution... ;)

**Comment by Haeresis** [comment]
I have setted a <base> for `https://vuejs-fr.github.io/vuejs.org/`.

The front page is in french (Thx @zyhou), and all page have a `Cette page est en cours de traduction française. Revenez une autre fois pour lire une traduction achevée ou participez à la traduction française ici.` message at top (That say french translation is in progress) so it's ok for CNAME redirection when @yyx990803 would set DNS redirection.

**Comment by Haeresis** [comment]
I add an upstream from `git@github.com:vuejs/vuejs.org.git`

after I do

```
git fetch upstream
git rebase upstream/master
```

from `git@github.com:vuejs-fr/vuejs.org.git` and all is ok!

So I will do a `rebase` from upstream one time by week from now.

**Comment by Haeresis** [comment]
I have some questions for @yyx990803 or @chrisvfritz 

- What is the Google Analytics Code we will use ?
- It's ok for CNAME redirection from https://vuejs-fr.github.io/vuejs.org/ to https://fr.vuejs.org
/ (CNAME is just removed while waiting for redirection).

I think for help, promote and set an official status for Vue.js's translation: it's a good thing to set CNAME while website is under translation but not add it into language dropdown list. That allows search engine to refer gradually the correct french page.

**Comment by yyx990803** [comment]
- Please just use the same Google Analytics ID with the main site.
- I have pointed `fr.vuejs.org` to GitHub pages, adding `CNAME` should make it work now.

**Comment by Haeresis** [comment]
Thx @yyx990803. All is ok. French website is under translation at https://fr.vuejs.org/.

**So, if someone want translate or have already translate some pages, share them on https://github.com/vuejs-fr/vuejs.org/ even if it's a page already translated. We compare it with file already translate and see if some point could be 
improved. Thx for your help!**.

**Comment by sdras** [comment]
Thank you for creating this translation! Reading through the issue, it seems to me that this translation is complete and added to our official translations about a year ago, so I'm closing out this issue. Please feel free to reopen if I'm mistaken. Thanks for the contribution 🎉

**Comment by Haeresis** [comment]
Thank a lot @sdras! And welcome amongst Vue.js team!

Courage to review all community issues!
