### ISSUE TITLE
尤大 vuejs ready 函数中 触发不了 onscroll 事件

### ISSUE THREAD

**Issue by yangfeiloveG** [vuejs/vuejs.org#272]
在ready 函数中 给某个元素绑定 scroll 事件却 不生效
<img width="571" alt="screen shot 2016-04-02 at 9 33 17 am" src="https://cloud.githubusercontent.com/assets/8132779/14223692/25554266-f8b6-11e5-9749-8f967a8dff32.png">

**Comment by yyx990803** [comment]
请带着重现链接去 vuejs/vue 开 issue
