### ISSUE TITLE
Fulltime?

### ISSUE THREAD

**Issue by taoeffect** [vuejs/vuejs.org#274]
> As of now I am exploring the possibility of working on Vue.js fulltime

So it's unclear to me, is this an outdated statement and you are working fulltime, or ...?

**Comment by yyx990803** [comment]
It means I am trying to see if it is sustainable to work on it fulltime, but not fully committed yet.

P.S. issues are not the best place to ask questions like this.

**Comment by taoeffect** [comment]
Oops my mistake! I think I misunderstood your original tweet as being committed fulltime; thought this might've been outdated text. Sorry for the misunderstanding!
