### ISSUE TITLE
v-for example not works as expected

### ISSUE THREAD

**Issue by DevDengChao** [vuejs/vuejs.org#2748]
![QQ截图20201217105421](https://user-images.githubusercontent.com/16363180/102438155-bd2adc80-4056-11eb-83a5-7e6fce7331f7.png)

**Comment by DevDengChao** [comment]
I'm using Chrome 87.0.4280.88 Release x64 edition.

And the console shows no error.
![QQ截图20201217110559](https://user-images.githubusercontent.com/16363180/102438761-e4ce7480-4057-11eb-90d7-d2dfb02f593a.png)

**Comment by DevDengChao** [comment]
Similar with https://github.com/vuejs/vuejs.org/issues/2685

**Comment by DevDengChao** [comment]
When I type `app4.todos.push({text: 'New item'})` in the console, it shows:

>Uncaught TypeError: Cannot read property 'todos' of undefined at <anonymous>:1:6
(anonymous) @ VM364:1

**Comment by Alex-Sokolov** [comment]
Seems work to me / Google Chrome  87.0.4280.88

![image](https://user-images.githubusercontent.com/4497128/102450616-e42de200-4047-11eb-86ce-012ea33da5dd.png)
