### ISSUE TITLE
请问一下这个是什么功能

### ISSUE THREAD

**Issue by caihai123** [vuejs/vuejs.org#2751]
![_16088867881910](https://user-images.githubusercontent.com/47770861/103129165-bc3b2000-46d2-11eb-9c1f-e3f607894cbf.png)

**Comment by Justineo** [comment]
PWA.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
