### ISSUE TITLE
v-for example with tr/td component

### ISSUE THREAD

**Issue by daniely** [vuejs/vuejs.org#276]
I'm not sure if it's just me but it took me awhile to figure out how to use a component to repeat the tr/td sections in a table body.

This is slightly different from the grid example.

Would an example of a component repeating tr/td in table body be useful? If so I'd be happy to submit a pull request.

**Comment by ludo237** [comment]
Yea you can submit the pull request for this and we will look into it.

**Comment by chrisvfritz** [comment]
@daniely Thanks for bringing up this issue! Would you mind providing more information on what you stumbled over? I think I'm unclear on what additional considerations are required for this use case. It [seems to work](http://jsfiddle.net/chrisvfritz/467ps9bv/) similar to other elements.

**Comment by daniely** [comment]
I'm not sure if the syntax changed but it does look pretty straight forward now. But thanks for asking.

Closing.
