### ISSUE TITLE
v-for绑定列表的时更改item信息的问题

### ISSUE THREAD

**Issue by liujb** [vuejs/vuejs.org#278]
#### 问题描述

尤大好，当我用array绑定列表的时候，更改其中某元素的属性的时候，出现了以下问题

#### 可以work的方式

```
var curr = me.list[index]
curr = {propA: false, propB: curr.propB, propC: curr.propC, ...}
me.list.$set(index, curr)
```

但是当只需要更改`propA`属性的值的时候，我需要将原来的属性全部重新写一遍，如果该对象属性特别多的话简直就是灾难。从代码的简洁考虑我期望。

```
var curr = me.list[index]
curr.propA = false
...
me.list.$set(index, curr)
```

用的vuejs1.0.17，是我用的不对，还是框架本身有所限制。请指教。

**Comment by yanxyz** [comment]
现在这个问题解决了吗？提问时在 fiddler, codepen 上写一个示例，这样别人也能看明白你的问题。

**Comment by stormhouse** [comment]
不知这样可否呢
`var curr = me.list[index]
curr = Object.assign({}, curr, {propA: false}
me.list.$set(index, curr)`

**Comment by stormhouse** [comment]
不知这样可否呢
```
var curr = me.list[index]
curr = Object.assign({}, curr, {propA: false}
me.list.$set(index, curr)
```

**Comment by yanxyz** [comment]
我的测试 `list[0].propA = false` 是可以的，但是不知道他具体是什么情况。

**Comment by liujb** [comment]
@yanxyz 感谢你的提醒和回答，问题得以解决。我再一次测试的时候发现

```
var curr = me.list[index]
curr.propA = false
...
me.list.$set(index, curr)
```
以及您提供的方式

```
list[0].propA = false
```
都是可以的，应该是我最开始的某个地方弄错，汗！
再次感谢。

**Comment by liujb** [comment]
@stormhouse 您提供的方式也是可以的。最初的方式也是可行的，应该是我某个地方弄错了，再次感谢。
