### ISSUE TITLE
Search isn’t working

### ISSUE THREAD

**Issue by halostatue** [vuejs/vuejs.org#2810]
I’m getting this error in the console, but the docsearch isn’t working:

```
Refused to execute https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
```

**Comment by NataliaTepluhina** [comment]
Unfortunately, I cannot reproduce this in any browser (including incognito mode). Would you mind trying incognito mode too to exclude browser plugins affecting the issue?

**Comment by halostatue** [comment]
This appears to have been a transient issue as I cannot reproduce it any longer.
