### ISSUE TITLE
vue3引入之前用vue2写的组件，报错Uncaught (in promise) TypeError: selfHook.bind is not a function

### ISSUE THREAD

**Issue by jingleding** [vuejs/vuejs.org#2812]
vue2的这个组件，之前是用webpack4打包后发布到npm私服上的，但是在vue3项目里面引入的时候报如下错误：Uncaught (in promise) TypeError: selfHook.bind is not a function
![image](https://user-images.githubusercontent.com/12590768/115978632-5644a380-a5b3-11eb-92f9-a0d1a141b809.png)

**Comment by Justineo** [comment]
Vue 2 的组件并不能无缝迁移到 Vue 3。
