### ISSUE TITLE
Hand cursor for the Subscribe button

### ISSUE THREAD

**Issue by ArunRaj6** [vuejs/vuejs.org#2826]
**What is the current behavior?**
The cursor icon is not changing when the user hovers over the Subscribe button on the home page.

**Changes suggesting?**
Change the cursor icon into a hand when the user hovers over the Subscribe button like other buttons on the page for consistency.

![Screenshot 2021-05-26 at 19 13 06](https://user-images.githubusercontent.com/22270737/119670517-94eda800-be56-11eb-970a-b4aa23ee137e.png)

**Comment by NataliaTepluhina** [comment]
Closing this issue as the PR that fixes it was merged
