### ISSUE TITLE
vue router 界面切换动画问题

### ISSUE THREAD

**Issue by chenjie-cnooc** [vuejs/vuejs.org#288]
vue router 界面切换，界面切出时，vue的transition和$destroy 之间是如何控制的，如果有切出动画， destroy的执行会在transition结束之后么？

**Comment by yanxyz** [comment]
文档说了， $destroy() 触发 beforeDestroy 和 destroyed 钩子，destroyed 钩子在过渡完成之后调用。如果你遇到的情况与这个描述不符，可以写一个示例。

**Comment by chenjie-cnooc** [comment]
非常感谢，问题已经解决了。是使用vue-router界面切回的时候，滚动条位置归0（不同浏览器情况不同）导致过渡效果没看到
