### ISSUE TITLE
VSCode Debugger for Chrome / Firefox Extension Has Been Deprecated, This Document Need To Be Update.

### ISSUE THREAD

**Issue by criticalsoft** [vuejs/vuejs.org#2903]
https://github.com/vuejs/vuejs.org/blob/master/src/v2/cookbook/debugging-in-vscode.md

**Comment by criticalsoft** [comment]
Does Anybody Know How To Debug Vue With VSCode BuildIn JavaScript Debugger? (Not In The Browser DevServer Overlay)

**Comment by wenliangzhou** [comment]
https://github.com/vuejs/vuejs.org/pull/2926
