### ISSUE TITLE
run ``npm run build``, size of file is 0B

### ISSUE THREAD

**Issue by huoher** [vuejs/vuejs.org#2914]
After I run ``npm run build``, some file in folder name ``public``, but the size is 0B.
There is show terminal output
```bash
INFO  Caching static resource "public/v2/guide/transitions.html" (0 B)
INFO  Caching static resource "public/v2/guide/typescript.html" (0 B)
INFO  Caching static resource "public/v2/search/index.html" (0 B)
INFO  Caching static resource "public/v2/style-guide/index.html" (0 B)
INFO  Total precache size is about 0 B for 360 resources.
```

OS: Windows 10
Node: v14.17.4
npm: 6.14.14

I look forward to your help！

**Comment by bencodezen** [comment]
Could provide more clarification on the issue? This seems like it may be an issue that's a different project from docs.

**Comment by huoher** [comment]
> Could provide more clarification on the issue? This seems like it may be an issue that's a different project from docs.
Thanks for your reply, the problem I have resolved by change my version of Node.js to 12！
