### ISSUE TITLE
Vue router 4 document doesn't support Korean language.

### ISSUE THREAD

**Issue by jsw3363** [vuejs/vuejs.org#2916]
<img width="438" alt="오픈_2-1" src="https://user-images.githubusercontent.com/91763903/144624533-c83d9cfb-459b-4a3b-9480-c2eb420b175c.PNG">

https://router.vuejs.org/
In the "View-Router 3" document, there's a Korean page in "Language"
but, in "View-Router 4" document, Korean does not exist in "Language".

https://github.com/vuejs-kr/vue-router-next
I know that most of the translation progress of "vue router next4"  has been completed in the github Korean translation project, but there is no Korean in the document.

So, Could you add Korean to the "vue router 4" document?

**Comment by bencodezen** [comment]
Thanks for the PR! This issue would be better filed in https://github.com/vuejs/vue-router-next for tracking. Could you refile the ticket there and tag me? Happy to help update this once you do.

**Comment by jsw3363** [comment]
> Thanks for the PR! This issue would be better filed in https://github.com/vuejs/vue-router-next for tracking. Could you refile the ticket there and tag me? Happy to help update this once you do.

https://github.com/vuejs/vue-router-next/issues/1229
I creat new PR thanks
