### ISSUE TITLE
Rename "api" to "docs"

### ISSUE THREAD

**Issue by pedzed** [vuejs/vuejs.org#303]
It's more of a standard to call the api "docs". I propose to have it renamed.

I usually just type https://example.com/docs, but that doesn't work, because it's currently not /docs, but /api.

**Comment by yanxyz** [comment]
In my own view,  docs is more related to API while guide is not which is more friendly to beginners.

**Comment by simplesmiler** [comment]
http://redux.js.org/docs (404)
https://angularjs.org/docs (redirects to https://angularjs.org/)

Maybe we can redirect from `/docs` to `/api` then.

**Comment by pedzed** [comment]
> Maybe we can redirect from /docs to /api then.

Fair enough.

**Comment by pedzed** [comment]
@yyx990803 I understand that you're busy, but could you at least say why you closed it?

**Comment by yyx990803** [comment]
API is API (reference), docs can include both API reference and guides.

Also, you are basically proposing to break an existing URL that many others may have bookmarked/cached for your own preference, which I don't find making much sense.
