### ISSUE TITLE
es.vuejs.org

### ISSUE THREAD

**Issue by zorobabel** [vuejs/vuejs.org#308]
Hi folks,

I think that Vue.js is great tool (well, I did a lot of research, found it and think it's amazing). And to give my two cents, I would like to contribute supporting the spanish version of the website.

Warm regards.

**Comment by yyx990803** [comment]
Thanks for your interest! The usual way to start a translation is forking this repo and just start translating the files. Once you've got some progress (to show some commitment), ping me again and I will be happy to move the repo into the vuejs organization and call for more contributors to help you out.

**Comment by zorobabel** [comment]
Evan, thanks for you quick response. I will follow your instructions and will ping you again with a progress.

**Comment by zorobabel** [comment]
@yyx990803 I did my first commit: fab29d6

**Comment by chrisvfritz** [comment]
@zorobabel That's great! Sorry for the late response - there's been a lot of work getting ready for 2.0. Unfortunately, we look for a bit more progress though before we pull in a translation. What we usually find unfortunately, is that a few pages are translated and then people lose steam. 😕  Are you still interested in continuing? And if so, would you like to start fresh with the 2.0 branch at this point?

**Comment by zorobabel** [comment]
@chrisvfritz @yyx990803 Hey guys! Yes, of course. Just now I'm working on the translation. Btw, I know v2.0 is coming, so I can help on it, too.

**Comment by zorobabel** [comment]
> Sorry for the late response - there's been a lot of work getting ready for 2.0. 

Np, I know you have a lot of work =)

**Comment by miljan-aleksic** [comment]
@chrisvfritz, I have the impression the docs are still in development and that Evan expressed the intention to focus on them next week. Shouldn't we wait a while longer?

@yyx990803, I know there are a few folks in the Spanish forum section willing to contribute translation, beside @zorobabel or me. I think keeping the spanish repo in Vuejs organization is a good idea, one way or another the project will be completed, you can count on it.

**Comment by chrisvfritz** [comment]
@miljan-aleksic Evan was mostly referring to docs for companion libraries such as vue-router and vuex. For the Vue core docs, people can see what's ready for translation [here](https://github.com/vuejs/vuejs.org/issues/319). I'm still doing a tiny bit of tweaking of the __Comparison with other Frameworks__ page, then will be adding an __Upgrade Guide__ and finishing up the API doc. The vast majority of it is in a good state though. 😃

**Comment by zorobabel** [comment]
@miljan-aleksic I don't need help in translation but in the review and won't wait for others 😃

> I'm still doing a tiny bit of tweaking of the Comparison with other Frameworks page, then will be adding an Upgrade Guide and finishing up the API doc.
@chrisvfritz Great, I'm aware of it!

> The vast majority of it is in a good state though
@chrisvfritz I agree!

**Comment by chrisvfritz** [comment]
@zorobabel Excellent! Sounds like you're on top of things. 😃  I can read Spanish as well, so if there are parts that you're having trouble translating or you aren't sure if you're correctly capturing the meaning of some sentence, please don't hesitate to ping me.

**Comment by zorobabel** [comment]
> I can read Spanish as well, so if there are parts that you're having trouble translating or you aren't sure if you're correctly capturing the meaning of some sentence, please don't hesitate to ping me.

@chrisvfritz Ooh, thank you so much!

**Comment by miljan-aleksic** [comment]
Hw many languages can you read, @chrisvfritz?

@zorobabel, ping me as well when ready.

**Comment by chrisvfritz** [comment]
@miljan-aleksic 😄  I can unfortunately read very few of the most popular languages within the Vue community (no Chinese, Japanese, or Russian), but I grew up in Belgium and was a linguist before I coded professionally, so I can read/speak a handful of western European languages with varying degrees of fluency. Since so many of the young/educated residents in those countries also speak English though, it's not actually that useful. 😅

**Comment by miljan-aleksic** [comment]
Awesome! Well seems useful now :)

**Comment by posva** [comment]
@chrisvfritz I absolutely forgot to tell, but I'm Spanish so I can review the PR 😄

**Comment by chrisvfritz** [comment]
@posva Excellent! 😄

**Comment by gbezyuk** [comment]
Being a native speaker and an amateur linguist, I would be more than happy to help with Russian translation. Is it, by any chance, already in progress?

**Comment by zgudino** [comment]
@posva @zorobabel @miljan-aleksic on [thread](https://forum.vuejs.org/t/spanish-category/363/11) we are talking this very same topic.
There are a couple of people willing to help, __including myself__. Do you mind tell me which repo we should submit PR?

Or maybe you guys can pass by thread, say hi and work on this together? 😎

**Comment by joelTorrejon** [comment]
Hi guys, @zorobabel, @chrisvfritz, i'm an Bolivian student, obviously i speak native spanish :smile:  and i want to contribute to the spanish translation, so i will send my pull requests in the next days, :+1:

**Comment by chrisvfritz** [comment]
Closing this in favor of the more recently active #1004.

**Comment by panietoar** [comment]
I can take ownership of this translation

**Comment by t4r0** [comment]
hey guys! I would like to help on this translation too. Please let me know how I can help

**Comment by miljan-aleksic** [comment]
@t4r0, join us at https://github.com/vuejs-es/vuejs.org/. Right now we are [syncing](https://github.com/vuejs-es/vuejs.org/pull/25) the translations with the new content and help is much appreciated

**Comment by t4r0** [comment]
perfect may I email you to know more about of the progress and tasks to be taken?

**Comment by miljan-aleksic** [comment]
@t4r0, get in touch at https://github.com/vuejs-es/vuejs.org/issues/2 :)

**Comment by phanan** [comment]
I'm closing this issue as an effort to tidy up our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
