### ISSUE TITLE
[Suggestion] Add an expo/showcase/cookbook section

### ISSUE THREAD

**Issue by YerkoPalma** [vuejs/vuejs.org#316]
Like the [expo section](http://expo.getbootstrap.com/) in bootstrap page, Vue could have a curated list of the best websites/apps built with Vue. I think that some of the [websites](https://github.com/vuejs/awesome-vue#appswebsites) and [interactive experiences](https://github.com/vuejs/awesome-vue#interactive-experiences) of the awesome vue list are a good place to start. This wouls need to define some method of selection of vue projects, but I think it could be a good way to expose Vue capabilities

**Comment by sdras** [comment]
It's in beta! 🎉
