### ISSUE TITLE
I founded a bug on vuejs forum, what can i do?

### ISSUE THREAD

**Issue by ricardovigatti** [vuejs/vuejs.org#318]
The bug is related with the verification email and the github authentication.

Where can i report or try to solve it?

**Comment by yyx990803** [comment]
You can share more details here if that's ok. The forum is using [NodeBB](https://github.com/NodeBB/NodeBB) and its [GitHub social plugin](https://github.com/julianlam/nodebb-plugin-sso-github).

**Comment by ricardovigatti** [comment]
Ok, i'll explain, it's quite a bit simple...

I've registered my account using the github connector and i received a warning saying that i need validate my email address, but the confirmation never reached my email box.

I checked my registered e-mail on the "Profile Edit" page in the Forum application and realized that my email was registered using a strange account from github, something like: "myname@no-reply.github.com"

For some reason it failed to obtain the email address from my github account . The reason could be the privacy settings from the github, cause i had the email configured as private at the time of registration. 

After i manually updated my email address, i was able to receive the confirmation. Anyway, this needs more tests to confirm the real cause of the problem.

**Comment by nerdyglasses** [comment]
I just wanted to create an issue for that. It didn't come to my mind that the email address would be something else then my own one.

**Comment by ricardovigatti** [comment]
@nerdyglasses, my privacy settings on github was setted as "private", so my e-mail was hidden. I have almost sure this is the cause. 

It's not a problem with vue site itself, this problem came from the GitHub social plugin. Here's one related issue from their repo: https://github.com/julianlam/nodebb-plugin-sso-github/issues/4

**Comment by chrisvfritz** [comment]
I'm glad that we've documented a solution here, but I'll close for now, since there's nothing we can do to fix it ourselves. 😕
