### ISSUE TITLE
docs example not working

### ISSUE THREAD

**Issue by dciccale** [vuejs/vuejs.org#320]
http://vuejs.org/guide/overview.html#example-1
<img width="630" alt="screen shot 2016-06-17 at 21 15 23" src="https://cloud.githubusercontent.com/assets/539546/16161996/ca3c3f2c-34d0-11e6-804d-64befcfd6447.png">

opening devtools and trying to change `exampleData.name` fails.

thx, awesome lib

**Comment by chrisvfritz** [comment]
@dciccale I just tested this and it does appear to be working for me. Can you provide more information about what you mean by "fails"? Are you getting an error? And what exactly are you typing?

**Comment by dciccale** [comment]
now is working.... i swear yesterday it was giving me `VM153:1 Uncaught ReferenceError: exampleData is not defined` and I actually now used the the autocompleted code I wrote yesterday

**Comment by chrisvfritz** [comment]
@dciccale 😄  No worries. I don't think you're crazy!
