### ISSUE TITLE
Suggestion to add link in Home Page

### ISSUE THREAD

**Issue by SusanthCom** [vuejs/vuejs.org#321]
Hi @yyx990803,  

This is a humble suggestion to add link / button  in [Home Page](http://vuejs.org) to the page [Comparison with Other Frameworks](http://vuejs.org/guide/comparison.html).

My recommendation is to add button / link Just above "GET STARTED" button found at bottom of home page. 

**Every new to Vue developer must reach this detailed comparison document as early as possible. Which will increases User base**

Thank you

**Comment by yyx990803** [comment]
Thanks for the suggestion - this link is mentioned right at the start of the Overview section: http://vuejs.org/guide/overview.html

I don't think it's necessary to put it on the homepage.
