### ISSUE TITLE
Missing docs how to declare transitions in separate components files.

### ISSUE THREAD

**Issue by mariaczi** [vuejs/vuejs.org#327]
I was looking for that and I really can't find it. 
I tried to put it into data:
```
data: function() {
return {
foo: {
                    enterClass: 'fadeIn',
                    leaveClass: 'fadeOut'
                }
}
}
```
but it's not working.

Nowhere in docs anything about it how should it be done in VUE files.

**Comment by LinusBorg** [comment]
It's in the API documentation: http://vuejs.org/api/#transitions
```js
export default {
  data() { ... },
  transitions: {
    foo: {
      enterClass: 'fadeIn',
      leaveClass: 'fadeOut'
    }
  }
}
```

**Comment by LinusBorg** [comment]
Hello!
Thank your for your interest in this project.

However, this is a usage question, and we encourage you to ask it on [forum ](http://forum.vuejs.org) or [gitter](http://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

**Comment by mariaczi** [comment]
@LinusBorg I am so sorry but it does not work properly. Please see this fiddle.
https://jsfiddle.net/mariaczi/v0svhsk0/2/

Vue is assigning class - `foo-enter-active` and `vue-leave-active` instead of 
```
transitions: {
            foo: {
                enterClass: 'fadeIn',
                leaveClass: 'fadeOut'
            }
        },
```

**Comment by chrisvfritz** [comment]
@mariaczi The example you provided is using Vue 2.0 alpha, which is why it is not working as described by the 1.x docs.
