### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs/vuejs.org#335]
Hello, I just finished translate in Korean.

https://github.com/ChangJoo-Park/vuejs.org

please add http://kr.vuejs.org :)

**Comment by ChangJoo-Park** [comment]
Translation

 Guide
- [ x]  Installation
- [ x]  Getting Started
- [x]  Overview
- [x]  The Vue Instance
- [x]  Data Binding Syntax
- [x]  Computed Properties
- [x]  Class and Style Bindings
- [x]  Conditional Rendering
- [x]  List Rendering
- [x]  Methods and Event Handling
- [x]  Form Input Bindings
- [x]  Transitions
- [x]  Components
- [x]  Reactivity in Depth
- [x]  Custom Directives
- [x]  Custom Filters
- [x]  Mixins
- [x]  Plugins
- [x]  Building Large-Scale Apps
- [x]  Comparison with Other Frameworks
- [x]  API
- [x]  Examples
- [x]  Other
- [x] Review
- [ ]  API
- [ ]  Examples
- [ ]  Other


 Guide (Reviewing)

- [ ]  Installation
- [ ]  Getting Started
- [ ]  Overview
- [ ]  The Vue Instance
- [ ]  Data Binding Syntax
- [ ]  Computed Properties
- [ ]  Class and Style Bindings
- [ ]  Conditional Rendering
- [ ]  List Rendering
- [ ]  Methods and Event Handling
- [ ]  Form Input Bindings
- [ ]  Transitions
- [ ]  Components
- [ ]  Reactivity in Depth
- [ ]  Custom Directives
- [ ]  Custom Filters
- [ ]  Mixins
- [ ]  Plugins
- [ ]  Building Large-Scale Apps
- [ ]  Comparison with Other Frameworks
- [ ]  API
- [ ]  Examples
- [ ]  Other

**Comment by kazupon** [comment]
@ChangJoo-Park 
Thanks for your translation!
Oh Great !! 💯 

Do you mistake the above checkboxes ?

I checked your translation repository.
I think your translation is perfect if you can translate `src/api/index.md`.

@yyx990803 
We should be added the korean translation repository, if @ChangJoo-Park can maintaine the korean translation repository. 😉

**Comment by ChangJoo-Park** [comment]
@kazupon thank you :) translate api now in progress!

**Comment by ChangJoo-Park** [comment]
API has translated!

**Comment by kazupon** [comment]
Perfect !! 💯

**Comment by ChangJoo-Park** [comment]
too busy to add korean repository? ;)

**Comment by yyx990803** [comment]
Currently too busy - will take a look after 2.0.

**Comment by ChangJoo-Park** [comment]
It so sad ;) but understand. I'll wait and ready for 2.0

**Comment by devjin0617** [comment]
good! : )

**Comment by ChangJoo-Park** [comment]
Translate 2.0 version to Korean in progress.
please check below.
https://github.com/ChangJoo-Park/vuejs.org 


old (1.0) version is here 
https://github.com/EndlessCreation/old.vuejs.org

**Comment by kazupon** [comment]
@ChangJoo-Park 
awesome!

Can you maintain korean translation repository continue from now?
If possible, I hope that want to join to you as maintainer.

@chrisvfritz @yyx990803 What do you think?

**Comment by ChangJoo-Park** [comment]
@kazupon  Yes, I hope many Korean user enter Vue world easily :)

**Comment by ChangJoo-Park** [comment]
Almost everything has been translated. Except `Example` and `Other`.

Now I start a review for Guide and API.

**Comment by ChangJoo-Park** [comment]
@kazupon Everything is done! (Actually without dropdown.)
this is my repo.
https://github.com/ChangJoo-Park/kr.vuejs.org

**Comment by yyx990803** [comment]
Looks like you have setup a custom domain for your github.io site - can you try adding `src/CNAME` with `kr.vuejs.org` and redeploy?

**Comment by ChangJoo-Park** [comment]
@yyx990803 I remove custom domain from my github.io site. and redeploy with CNAME.

**Comment by yyx990803** [comment]
@ChangJoo-Park thanks! The site should now be live at `kr.vuejs.org` - wasn't obvious at first sight because the homepage was still English ;) Maybe you'd want to translate the homepage as well?

**Comment by yyx990803** [comment]
@ChangJoo-Park btw, thanks for your hard work! When you feel that it is ready, you can submit a PR to add a link to the Korean docs here: https://github.com/vuejs/vuejs.org/blob/master/themes/vue/layout/partials/language_dropdown.ejs

**Comment by ChangJoo-Park** [comment]
@yyx990803  thank you! Evan 👍 

When I am ready, I'll create PR.

**Comment by ChangJoo-Park** [comment]
Create PR for dropdown.

**Comment by ChangJoo-Park** [comment]
Translated **TypeScript Support** in Korean.

**Comment by ChangJoo-Park** [comment]
[Question] Can I change this line?

[Original](https://github.com/vuejs/vuejs.org/blob/master/themes/vue/layout/page.ejs#L30)
to
[Korean](https://github.com/ChangJoo-Park/kr.vuejs.org/blob/master/themes/vue/layout/page.ejs#L30)

I think this is not my **own** project. I am just contributor, not owner.
So, It does not make sense for my account to be exposed.

 @kazupon , @yyx990803 .
I want to hear your opinion.

**Comment by kazupon** [comment]
@ChangJoo-Park 
Yeah! In this context, due to this sentence makes sense for this repository, You can change Korean translation repo.

ref: [japanese](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/themes/vue/layout/page.ejs#L31)

**Comment by yyx990803** [comment]
@ChangJoo-Park if you are concerned about exposing your personal account, you can create an organization e.g. `vuejs-kr` and move the forked repo into that organization.

**Comment by ChangJoo-Park** [comment]
Thank you for response. I create vuejs-kr organization ! github organization link is [here](https://github.com/vuejs-kr).  I hope `kr.vue.org`  managed by commnuity. Thanks @kazupon @yyx990803

**Comment by ChangJoo-Park** [comment]
add automatic build kr.vuejs.org using travis-ci.

**Comment by ChangJoo-Park** [comment]
Add algolia docsearch. @kciter 감사합니다.

**Comment by ChangJoo-Park** [comment]
Add Production deployment tip.
modify single file component

**Comment by ChangJoo-Park** [comment]
Add [Vue in 2016](https://medium.com/the-vue-point/vue-in-2016-8df71d98bfb3#.delpt96ok) , change google analytics.

I started collecting statistics for users of Korean pages.

**Comment by ChangJoo-Park** [comment]
Updated for 2.2.0

**Comment by sdras** [comment]
It seems to me reading through this that this translation was complete about a year ago, so I am closing out this issue. Please feel free to reopen if I'm mistaken. Thank you so much for the contribution! 🎉

**Comment by ChangJoo-Park** [comment]
@sdras, docs in Korean has maintained in https://github.com/vuejs-kr/kr.vuejs.org/ this repo.

:)
