### ISSUE TITLE
In ios vue ready is not in normal （vue ready周期方法问题）

### ISSUE THREAD

**Issue by heiliuer** [vuejs/vuejs.org#336]
在ios Safari 微信浏览器中vue ready方法执行时机有问题，dom并未插入到document中。在chrome，android正常。
In ios Safari，Weixin explorer，vue ready function is not executed in normal time when the dom did not be inserted into the document。All is fine in chrome or android webkit。
![vue template ready](https://cloud.githubusercontent.com/assets/6746060/16836023/0661df0c-49ee-11e6-89d2-555c697f27ce.png)
jq对象A 应该 和 B是同一个，或者包含同一个成员。
A and B should be the same but not。
vue version is v1.0.22

**Comment by prog-rajkamal** [comment]
@heiliuer This repo is for vuejs.org site. Please create an issue at github/vuejs/vue for reporting bugs.

**Comment by heiliuer** [comment]
Sorry!
