### ISSUE TITLE
Use v-else for empty v-for

### ISSUE THREAD

**Issue by Kolorbon** [vuejs/vuejs.org#341]
It would be nice if one could use a simple `v-else` to display an "empty data" message, when a `v-for` is empty. Although it is anyway easy to check the size of an array/object, the HTML just looks cleaner without it.

**Comment by chrisvfritz** [comment]
This is the repository for the website, not the core library, which is at [vuejs/vue](https://github.com/vuejs/vue). Either way though, this doesn't sound like a feature we'd be interested in adding. While a `v-else` would be shorter, it would be less expressive. With `v-if="array.length === 0"` or `v-if="!array.length"`, it's much more obvious when that element appears.
