### ISSUE TITLE
Working on some transition examples

### ISSUE THREAD

**Issue by rajibahmed** [vuejs/vuejs.org#344]
Hi @chrisvfritz,

As I wanted to help ... I am going through the examples on 

https://github.com/vuejs/vuejs.org/blob/2.0/src/guide/transitions.md

When I am done with updating the examples on JSbin will try to update the doc with pull requests.

https://jsbin.com/pecupo/edit?html,js,output

//Best

**Comment by chrisvfritz** [comment]
@rajibahmed Thanks for sharing these! I'm actually almost done updating the transitions guide already and will be pushing it up later today. 😅  Would you mind looking it over when it's done?

**Comment by chrisvfritz** [comment]
@rajibahmed The new transitions guide is up! Would love to hear your thoughts [at the main repo](https://github.com/vuejs/vuejs.org/issues/319). 😄  I'm going to close this for now just to consolidate the 2.0 docs discussion.
