### ISSUE TITLE
Children in slot not rerendering

### ISSUE THREAD

**Issue by blocka** [vuejs/vuejs.org#351]
Let's say I have I have a render function like this:

```
render (h) {
    return this.inner1 ? h(Outer, null, () => ['Inner1']) : h(Outer, null, () => ['Inner2'])
}
```

where `Outer` is defined as 

```
const Outer = {
  render (h) {
    return h('div', null, () => this.$slots.default);
  }
};
```

I would expect that when `this.inner1` gets set to `false`, that I would see `Inner2` on the screen. However, this doesn't happen.

Am I missing something?

**Comment by chrisvfritz** [comment]
@blocka Thanks for reporting this issue! Can you post it to the [main Vue repo](https://github.com/vuejs/vue)? This one is just for the website. When you do, please also include [this reproduction](https://jsfiddle.net/chrisvfritz/rpmce1v8/), as it will help us diagnose and fix the problem quickly.
