### ISSUE TITLE
Vue.js comparison against other frameworks

### ISSUE THREAD

**Issue by b44rd** [vuejs/vuejs.org#353]
Hi!

Really happy to see how well vue.js makes progress these days. 👍 

I noted Vue.js will be using virtual DOM in version 2.0, which means the React section on this this page could need an update? https://vuejs.org/guide/comparison.html 

Also came to think of if it could be worth mentioning Aurelia in this comparison? Just an idea.

**Comment by chrisvfritz** [comment]
We're actually updating the entire guide in the 2.0 branch. We might add a section for Aurelia after release, but 2.0 likely won't ship with one.
