### ISSUE TITLE
Vue.js visual intro guide

### ISSUE THREAD

**Issue by MarcTe** [vuejs/vuejs.org#366]
Hi, I made a visual version of the doc. (PDF) But github does not recognize it as a pdf!
It contains many ovale bubbles showing lacks in actual doc, that should be addressed.
Not shure how we could work together for improving it. Of course github. But I do not know how much I can use it and it is not exactly a textbased doc. 

The original is in Open Office Draw.

Is there a way to submit it? It could be a good way to accelerate Vue.js adoption.

It helps to follow along reading the official guide.

A reply would be appreciated before I move on another way of communication, etc.

Marc
vue.js.schema@wiseshift.com

**Comment by yyx990803** [comment]
Are you generating the pdf from the docs source?

**Comment by MarcTe** [comment]
I try to stay as close to original as possible, that is why I consider it a schematic version of the original doc, today I got the idea to explain that even more, in the intro. I do it manually. It think it can be understood faster, especially if read along the original doc, but adding a visual grouping, and splitting code and comments, and highlighting what to focus in the code, with comments. 

Ultimately, it would help - IMPOV - if it inducts a different format for any doc. I already have a version for Vue-router, and working on one about Vuex. I do it first for my own understanding, but if I can share it for the good of faster acceptance of Vue.js...

If you have any concern, or comments, let me know.
Marc

      De : Evan You <notifications@github.com>
 À : vuejs/vuejs.org <vuejs.org@noreply.github.com> 
Cc : Marc Tetreault <github@wiseshift.com>; Author <author@noreply.github.com>
 Envoyé le : Dimanche 14 août 2016 17h06
 Objet : Re: [vuejs/vuejs.org] Vue.js visual intro guide (#366)
   
Are you generating the pdf from the docs source?—

**Comment by chrisvfritz** [comment]
@MarcTe Can you post the PDF somewhere and link here so we can take a look?

**Comment by MarcTe** [comment]
https://drive.google.com/file/d/0B_kQr3l7tmlWS2hMU21JaENiUFU/view?usp=sharing
Still not perfect and, beginning to experiment, I see lacks in the doc (things we should explain, especially things that are in the API side of the doc).Marc

      De : Chris Fritz <notifications@github.com>
 À : vuejs/vuejs.org <vuejs.org@noreply.github.com> 
Cc : Marc Tetreault <github@wiseshift.com>; Mention <mention@noreply.github.com>
 Envoyé le : samedi 27 août 2016 15h26
 Objet : Re: [vuejs/vuejs.org] Vue.js visual intro guide (#366)
   
@MarcTe Can you post the PDF somewhere and link here so we can take a look? —

**Comment by chrisvfritz** [comment]
Interesting! Thanks for sharing. 😄  I'll go through the PDF and will be making updates in the next week using your oval comments. If there are larger changes to make, I'll open separate issues for them. There are sometimes things _intentionally_ left out of the guide though, then only covered in the API page - for a variety of reasons, but especially if they're more niche features.

Again, thanks for sharing! When you're done with these, I think posting links on [the forum](http://forum.vuejs.org/) and [Gitter chat](https://gitter.im/vuejs/vue) would be really helpful for others. In the meantime, I'll close this for now.

**Comment by MarcTe** [comment]
Not shure the best way to email to you (I suppose this will re-open the issue)
One idea would be to define several guidelines in order to help people grasp things ASAP. Some of them: 

-Group topics in one page with a title (or a title in code side bar comments)-Group ideas in rectangles
-Clean code, getting comments out, in a side bar comment-Rectangled words showing the focus elements in code text,
-Arrows (I have several guidelines about which direction the arrow should be) One of them: 
from existing assets (such as a function) to the one using it.-Useful comments in small boxes with arrows pointing to the related code.

- In fact, my 1st vue.js project is an app that can be used for writing such document (viewable in both web and PDF), easily updatable)
I suppose it would be better to clean this doc before posting it.I could put the Open Office Draw file somewhere, so you can edit it directly.But only one can do it at once. (I still do not know well how to manage a github, and it cannot be edited just with text editor)

Marc




      De : Chris Fritz <notifications@github.com>
 À : vuejs/vuejs.org <vuejs.org@noreply.github.com> 
Cc : Marc Tetreault <github@wiseshift.com>; Mention <mention@noreply.github.com>
 Envoyé le : samedi 27 août 2016 21h50
 Objet : Re: [vuejs/vuejs.org] Vue.js visual intro guide (#366)
   
Interesting! Thanks for sharing. 😄 I'll go through the PDF and will be making updates in the next week using your oval comments. If there are larger changes to make, I'll open separate issues for them. There are sometimes things intentionally left out of the guide though, then only covered in the API page - for a variety of reasons, but especially if they're more niche features.Again, thanks for sharing! When you're done with these, I think posting links on the forum and Gitter chat would be really helpful for others. In the meantime, I'll close this for now.—
