### ISSUE TITLE
Source Sans Pro legibility on Win/Chrome

### ISSUE THREAD

**Issue by simshaun** [vuejs/vuejs.org#392]
The docs currently have the font stack `'Source Sans Pro', 'Helvetica Neue', Arial, sans-serif`.

I'm finding Source Sans Pro fairly difficult to read. Take a look at the following comparison images between Source Sans Pro & Arial (I don't have Helvetica Neue to try out.)

# Source Sans Pro
![source-sans-pro](https://cloud.githubusercontent.com/assets/379519/18219210/ee8bf5b0-7135-11e6-8c2b-953da3a3412d.png)

--

# Arial
![arial](https://cloud.githubusercontent.com/assets/379519/18219209/ee897db2-7135-11e6-8b14-60db2860c5c9.png)

**Comment by chrisvfritz** [comment]
Thanks for bringing this up. The legibility of our docs is definitely important to us! 😃  @yyx990803 How would you feel about switching the body text to use to the system font stack a la Github and Bootstrap v4?

**Comment by sqal** [comment]
I am on Windows 10 and looks fine to me (http://prnt.sc/cdy7ly). Do you perhaps have this font installed in your system? Becouse I think it may interfere with displaying the font in the browser

**Comment by simshaun** [comment]
I'll have to check again on Tuesday. I've got it installed on my PC here at home and it looks fine. Maybe I've only got a lighter weight on my work PC?

**Comment by chrisvfritz** [comment]
OK, I'll close this for now then, as it's sounding more like a local problem.

**Comment by sqal** [comment]
Yeah it might be.. I just installed SSP Extra Light and that's how the site looks like http://prntscr.com/ce14hb
