### ISSUE TITLE
Pressing 'return' on Smart Keyboard for iPad Pro does not add a new to-do item

### ISSUE THREAD

**Issue by garrytaulu** [vuejs/vuejs.org#394]
On the 'Getting Started' page under the 'All Together Now' sub-heading, adding a new to-do item using the return key on a Smart Keyboard for iPad Pro does not work. This may also be an issue with any external keyboard (not tested).

Currently running iOS 10 with Beta 8.

**Comment by chrisvfritz** [comment]
This sounds like it's probably a bug in Smart Keyboard integration in iOS 10 beta 8. Vue's key detection is a very thin layer that just checks event.keyCode. Have you tested other inputs with behavior on enter?

**Comment by garrytaulu** [comment]
I doubt it is a bug as I've used this keyboard extensively with other web apps (as well as our own). I checked out the vue.js implementation on http://todomvc.com/ and the issue also exists there, other frameworks work fine.

**Comment by chrisvfritz** [comment]
Interesting. And you've confirmed the bug does __not__ exist with the native iOS keyboard? And other controls on page still work (e.g. the `X` button to remove a todo)?

**Comment by garrytaulu** [comment]
When you say 'native' keyboard do you mean the software keyboard? If so then yes, it does **not** happen with the software keyboard, I am able to add items to the to-do list. The x button works fine.

**Comment by chrisvfritz** [comment]
Thanks for helping narrow it down. The only difference I can see is that our examples use `keyup` events, whereas some of the other TodoMVC implementations use `keydown` events. My best guess is still a bug with Smart Keyboard integration - possibly only with the the convergence of the  return key, `keyup` event, and maybe some other factor(s).

Either way, it's definitely not a bug in Vue or the code examples. If the software keyboard is working, then Vue is correctly detecting the event and key code. The external keyboard should trigger identical events and key codes, but it doesn't seem to be. I hope Apple fixes it soon!

**Comment by garrytaulu** [comment]
Hey there,

Just letting you know this still only happens with Vue.js and iOS is now up to 10.3, still doesn't seem like it's a bug with iOS but rather with Vue. It has been discussed here too https://github.com/tastejs/todomvc/issues/1717

**Comment by erik127** [comment]
Hi all,
The issue still exists on iOS 11.3. Keyup.enter doesn't get detected with the smart keyboard. I logged out the keyup events to the console and the differences between the smart keyboard and other keyboards are:
- code = "Unidentified" (vs "Enter")
- keyCode = 0 (vs 13 on other keyboards)
- keyIdentifier= "Unidentified" (vs "Enter")
- which = 0 (vs 13 on other keyboards)

The only property that shows which key is pressed is 'key'. So I guess you can workaround it like this:

In index.html change @keyup.enter to just @keyup:
```HTML
<!-- change
<input class="new-todo" autofocus autocomplete="off" placeholder="What needs to be done?" v-model="newTodo" @keyup.enter="addTodo">  -->

<input class="new-todo" autofocus autocomplete="off" placeholder="What needs to be done?" v-model="newTodo" @keyup="addTodo">
```

In app.js, add a conditional:
```javascript
addTodo: function (event) {  //add the key-event to the method
  if  (event.key === 'Enter') {  //check if enter is pressed
    var value = this.newTodo && this.newTodo.trim();
    if (!value) {
      return;
    }
    this.todos.push({ title: value, completed: false });
    this.newTodo = '';
  }
},
```
Note: if, in this case for example, the addTodo also could be triggered by clicking an 'Add Todo' button, then the above will not work. Instead I would change the keyup listener to something like @keyup='keyupListener' and a new method

```javascript
keyupListener: function(event) {
  if (event.key === 'Enter') {
    this.addTodo()
  }
}
```

Hmm, let's see if apple fixes this as this won't improve maintainability.

Smart keyboard:
![smart-keyboard](https://user-images.githubusercontent.com/10899468/39244910-6ff7c96e-4892-11e8-94fd-095b7aefcb5a.png)

Soft keyboard:
![software-keyboard](https://user-images.githubusercontent.com/10899468/39244898-64d7541e-4892-11e8-8dd9-12dccb5a7da5.png)

**Comment by chrisvfritz** [comment]
It looks like the correct `keyCode` isn't being triggered then. It should work with @keyup.Enter though and since `keyCode` is starting to be phased out, maybe aliases like `@keyup.enter` should alias to their corresponding `key` instead of `keyCode`. I think it's worth opening up an issue on [the main repo](https://github.com/vuejs/vue) for.
