### ISSUE TITLE
Github users and e-mail confirmation

### ISSUE THREAD

**Issue by Y-Less** [vuejs/vuejs.org#398]
# Issue

Hello.

I tried to sign up to the forums using the github oauth system.  I allowed the site access to my profile, but I can't post anything.  Your forums keep trying to send a confirmation e-mail to check that my e-mail is valid, despite the fact that surely linking to a github account should be sufficient.  Regardless, even if that's not sufficient, the e-mail will never succede because I am using github's e-mail hiding options, which means that all the confirmation e-mails are going to:

`Y-Less@users.noreply.github.com`

# Original Post

So I don't loose the post I was trying to make when signing up, I'm leaving it here until I can get on.  It was a reply to this topic, and given my concerns with the code I was potentially going to post it as a new topic as well for wider feedback:

http://forum.vuejs.org/topic/5088/is-there-a-way-to-directly-pass-props-to-dynamic-components-as-a-whole-object

> I wanted to do the exact same thing, came here to ask if there was a better way to do it than the one I came up with, but the only references to doing this seemed to be the same question and no answer.  So this is the solution I came up with - I'd appreciate feedbackas I know the implementation is a bit ugly (although I'm happy with the API it exposes).
>
>In short, I added a `v-this` directive to essentially allow you to set the `this` of a component to some specified existing object.  For the example in the first post this would result in (made up half the example):

```html
<template>
<div>
    <div v-for='control in controls' track-by='$index'>
        <component :is='control.type' v-this="control.config"></component>
    </div>
</div>
</template>
```
```js
new Vue({
	controls: [
		{
			type: 'component-input',
			config: { name: 'foo', value: 'bar', other: 'baz' }
		},
		{
			type: 'component-list',
			config: { length: 100, gen: '+1', skip: [5, 7, 10] }
		},
	]
})

Vue.component('component-input', {
	props: [ 'name', 'value', 'default' ]
});

Vue.component('component-list', {
	props: [ 'length', 'gen', 'skip' ]
});
```
>
>Any propety specified by `props` and present in `control.config`, but NOT explicitly given by `v-bind` will be bound to the Vue model.  `v-this.once` works, as do `.twoWay` prop options.
>
>The code is:

```js
Vue.directive('this', {
	// "v-this" allows you to specify a complete model to inherit properties
	// from.  Only those specified in "props" will be inherited, and also only
	// those not explicitly listed by other "v-bind" directives.  Will bind so
	// that assigning the complete object, and members, will update the
	// component.
	bind: function () {
		var prop, desc;
		var vue = this.el.__vue__;
		// Build up an optimised function to do the replacements quickly.
		this.rebindProps = [];
		//console.log(this.rebindProps);
		for (var name in vue._props) {
			// Extract the propery options, and the old handlers.
			prop = vue._props[name];
			desc = Object.getOwnPropertyDescriptor(vue, name);
			// If something doesn't exist, skip this one.  Also skip this if
			// "raw" is not null - that means that the prop was given
			// explicitly.
			if (!prop || !desc || !desc.configurable || prop.raw !== null)
				continue;
			// If this is one-way, use the existing set (to not propagate).
			this.rebindProps.push({
				name: name,
				enumerable: desc.enumerable,
				set: prop.options.twoWay ? undefined : desc.set
			});
		}
		this.rebindLen = this.rebindProps.length;
		this.modifyOnce = true;
	},
	
	update: function (value) {
		if (this.modifiers.once) {
			// Only doing this once - easy.
			if (this.modifyOnce) {
				this.modifyOnce = false;
				var prop, name;
				var vue = this.el.__vue__;
				for (var i = 0; i != this.rebindLen; ++i) {
					prop = this.rebindProps[i];
					name = prop.name;
					vue[name] = value[name];
				}
				// Clean up a bit.
				delete this.rebindProps;
				delete this.rebindLen;
			}
		} else {
			var prop, desc, name;
			var vue = this.el.__vue__;
			for (var i = 0; i != this.rebindLen; ++i) {
				prop = this.rebindProps[i];
				name = prop.name;
				desc = Object.getOwnPropertyDescriptor(value, name);
				if (!desc)
					continue;
				// Copy in the new value before replacing the (s|g)etters.
				vue[name] = value[name];
				Object.defineProperty(vue, name, {
					enumerable: true,
					configurable: true,
					get: desc.get,
					set: prop.set || desc.set
				});
			}
			// Clean up a bit.
			delete this.modifyOnce;
		}
	},
});
```
>
>As I said - the code is ugly, as evidenced by the fact that I directly access `__` and `_` internal members.  One down-side is that currently `.required` props may be given by `v-this`, but because they are not explicitly given by `v-bind`, there will be a console error at the minimum.

**Comment by chrisvfritz** [comment]
The Github Social Sign On plugin has a bug where it doesn't work with a hidden email. There's unfortunately nothing we can do on our end to fix that. 😕

**Comment by Y-Less** [comment]
I'm more slightly confused why you need to verify an e-mail at all when you already have a verified github account.  Isn't the point to verify that sign-ups are real people?  If anything the github account seems more secure - I can make thousands of unique e-mail addresses instantly, register under one, then discard it.  My github profile is far more permanent.

**Comment by chrisvfritz** [comment]
@Y-Less Yes, I agree it doesn't make sense. 😕  The behavior is the result of a bug in a 3rd party plugin, for which there's an [open issue here](https://github.com/julianlam/nodebb-plugin-sso-github/issues/4). You could try submitting a pull request to get it fixed sooner.

**Comment by Y-Less** [comment]
That doesn't really answer the question of why you are trying to send e-mails in the first place, only why you can't.

Is there a way to get manually verified instead - since this is clearly my real account...

**Comment by chrisvfritz** [comment]
To be notified of replies, mentions, etc, a real email address must be supplied. Unless you'd like to update your GitHub settings, I recommend simply signing up with an email and password instead.

**Comment by Y-Less** [comment]
I don't even know HOW to register with an e-mail.  Clicking on "login" only accepts existing accounts, and there is no obvious "register" link anywhere.  I don't even WANT notifications...

**Comment by Y-Less** [comment]
http://stackoverflow.com/questions/39079695/how-to-register-or-signup-in-vuejs-discussion-forum

:/

**Comment by chrisvfritz** [comment]
Please remember that you are receiving free support, for free software, from mostly volunteers. It does indeed look like we've disabled local registration - probably because there were too many spam users signing up. In that case, we may look into forking and patching the GitHub SSO plugin ourselves eventually. There may not be an optimal solution however. If it ends up not being possible to access the user's email in these cases, we may have to choose between users not receiving notifications (and not understanding why) or having to change that privacy setting.

In the meantime, my recommendation would be to either not hide your email (there is, after all, still an email attached to your commit messages and even more sensitive information available with a `whois` check on `y-less.com`), or instead post your issue on [the Gitter chat](https://gitter.im/vuejs/vue).

**Comment by Y-Less** [comment]
I'm not entirely sure why that's relevant.  Obviously I am aware of that and appreciate it, but that seems an odd thing to bing up to a person reporting bugs encountered while trying to answer questions by other people.

I'll look in to removing e-mail protection, but given your interest in free support, raising the barrier to entry for those willing to give said help still seems an odd move.
