### ISSUE TITLE
Add more unit testing examples to guide 

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vuejs.org#401]
These aren't really Vue-specific testing tips, but I think they could still be helpful for people. This is a list that will probably grow as I (or others) think of more things.
- [ ] Using spies to ensure something happens in a lifecycle hook
- [ ] Mocking Ajax requests
- [ ] Mocking external dependencies

**Vuex stores/modules**
- [ ] Testing initial state
- [ ] Testing actions
- [ ] Testing mutations
- [ ] Testing getters

**Comment by LinusBorg** [comment]
Shouldn't the vuex-related example go to the vuex docs?

**Comment by chrisvfritz** [comment]
Yeah, that's a good idea. I'd like to link to it though.

**Comment by adiakritos** [comment]
+10,000 for Mocking external dependencies there is 1 example and it's so brief I'm left to experimenting and searching for guides to really get it.

**Comment by sdras** [comment]
What do we think of this now that we have linked up vue-test-utils and have made a cookbook recipe? Does that close out this issue?

https://github.com/vuejs/vuejs.org/pull/1470

**Comment by sdras** [comment]
Gonna close this out since we now point to vue-test-utils, but feel free to reopen
