### ISSUE TITLE
Broken links in comparison.md and possible elsewhere

### ISSUE THREAD

**Issue by milimetric** [vuejs/vuejs.org#405]
links in https://github.com/vuejs/vuejs.org/blob/2.0/src/guide/comparison.md#knockout are to html pages, such as components.html, but those seem to have been replaced by md pages, such as components.md.  So all the links appear broken when browsing this page on github.  Sorry no time to send a PR, but I'm interested in Vue and might in the future.

**Comment by chrisvfritz** [comment]
The links are only meant to work in the live site, where the markdown is compiled to HTML.
