### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Devinsuit** [vuejs/vuejs.org#407]
http://vuejs.org/2014/03/22/vuejs-010-release/ - _with v-component="{{type}}"._ [Doc.](http://vuejs.org/guide/directives.html#Literal_Directives) **&** _string as the component ID._ [Doc.](http://vuejs.org/api/directives.html#v-view) **&** _filters for v-repeat._  [Doc.](http://vuejs.org/api/filters.html#filterBy)

**Comment by chrisvfritz** [comment]
This version of Vue is no longer supported, so the docs are no longer hosted. If you're just learning about Vue, I recommend checking out the [upcoming 2.0 docs](http://rc.vuejs.org/).
