### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by hayeah** [vuejs/vuejs.org#416]
We are organizing a Chinese translation effort here:

https://github.com/hayeah/vuejs.org/tree/lang-zh-2.0

We'll prioritize the API doc translation, then move on to the guide.

欢迎各路神仙加入 Vue2 中文翻译组。我们会准备 vue 周边送给贡献者 🎁

**Comment by dingyiming** [comment]
@hayeah 目前我们也进行了一些翻译工作，基本完成，校对工作还需要进一步进行，不知道我们能否一起协助做点什么？

- 翻译仓库与进度汇总 https://github.com/vuefe/vuejs.org 
- 翻译 issue https://github.com/vuefe/vuejs.org/issues
- 翻译情况 http://vuefe.cn/about/

**Comment by sdras** [comment]
My apologies, but I can't tell if this is done or not. Are you still in progress with this or has it been added to the site? If it's been abandoned or it has already been added I'd love to close out this issue. Thanks!

**Comment by Jinjiang** [comment]
@sdras yes It is done. We used @dingyiming 's version. Now the Chinese translation work has all been pushed into vuejs/vue.vuejs.org and maintained there as the README wrote. So it could be closed. Let me finish it 😏
Thanks.

**Comment by sdras** [comment]
🎉 thanks
