### ISSUE TITLE
Similar variable names in Guide are confusing to new learners

### ISSUE THREAD

**Issue by jsejcksn** [vuejs/vuejs.org#424]
Hi 👋

I'm just getting started trying to learn Vue for the first time, and I'm finding that the guide often uses the same name for several different data types, which is confusing me. Below is an example from the section entitled [Composing with Components](http://rc.vuejs.org/guide/#Composing-with-Components) on the front page of the guide. It uses `todo` in almost every location possible. Perhaps someone can take a look at the examples in the guide and try to use unique names for different types of data. I'm sure I'm not the only person who would find it easier to understand the examples. Thanks!

> ... We should be able to pass data from the parent scope into child components. Let’s modify the component definition to make it accept a [prop](http://rc.vuejs.org/guide/components.html#Props):
> ```
> Vue.component('todo', {
>   props: ['todo'],
>   template: '<li>{{ todo.text }}</li>'
> })
> ```
> Now we can pass the todo into each repeated component using `v-bind`:
> ```
> <div id="app-7">
>   <ol>
>     <todo v-for="todo in todos" v-bind:todo="todo"></todo>
>   </ol>
> </div>
> ```
> ```
> var app7 = new Vue({
>   el: '#app-7',
>   data: {
>   todos: [{ /* ... */}]
>   }
> })
> ```

**Comment by chrisvfritz** [comment]
Hi @jsedlacek - could you explain a little more about what you mean by different types of data? In the examples above, the only type of data `todo` is used to represent is a todo object. For example:

``` js
{ text: 'Build something awesome' }
```

**Comment by jsejcksn** [comment]
@chrisvfritz Here is a screenshot to show what's confusing:

<img width="496" alt="screenshot" src="https://cloud.githubusercontent.com/assets/868251/19009205/dd926926-8736-11e6-8a32-2a3de79638dd.png">

See the word `todo` used so many times? It's hard for me to explain because of the fact that I don't yet understand Vue, but here are some examples I made on JSFiddle to try to show what I mean:

Here is the [original example](https://jsfiddle.net/jsejcksn/pser3abr/). It uses the word `todo` in as many places as possible. After experimenting with replacing variables' names for a while, I came up with [this version](https://jsfiddle.net/jsejcksn/pser3abr/3/), in which I've attempted to use as many uinque names as possible to help identify different types of data (different variables). See how this shows which names map to the `component` vs. which names map to the `props` key?

I still don't understand anything about binding or props or why the same word is used after the colon in `v-bind:` and also in the following quotes, but at least this helps me understand that not everything is linked to the word `todo`.

**Comment by chrisvfritz** [comment]
Hmm, I'll think about this a bit more. I don't think I like the rename to `task`, as I think `todo in todos` is more natural, but I may rename the component to `todo-item`. It's also worth mentioning that this section is not meant to show you how components actually work - just introduce you to the basic concept. The deeper dive and real explanation is on the [components page](http://vuejs.org/guide/components.html).

**Comment by jsejcksn** [comment]
@chrisvfritz That sounds good. I wasn't suggesting a specific name for any of them, but just showing you how it could be made more clear that they are not the same thing and that to new learners like me, it can cause unnecessary confusion if they all share the same name.

Thanks for taking a look!

**Comment by chrisvfritz** [comment]
@jsejcksn What do you think about [this revised copy](https://github.com/vuejs/vuejs.org/commit/61589d47b20261515d178305c3cdeb84cbd4d768)?

**Comment by jsejcksn** [comment]
@chrisvfritz I still don't know enough about Vue to give proper feedback, but I think that's helpful. Especially when seeing examples early on, I think making things as unambiguous as possible is great. I'll reach out again if I find something particularly confusing having to do with examples. Thanks, again, for taking a look at this and the other examples.

**Comment by chrisvfritz** [comment]
Sounds great! Thanks for bringing this up.
