### ISSUE TITLE
New site looks buggy

### ISSUE THREAD

**Issue by YerkoPalma** [vuejs/vuejs.org#426]
Please tell me this is a bug and not the new design :(

![image](https://cloud.githubusercontent.com/assets/5105812/19004175/eed4717c-872a-11e6-9b0e-fbbfd602a6b5.png)

**Comment by cannap** [comment]
looks like some styles are not loading for you 

here works fine just hit ctrl + f5 or clear cache

**Comment by chrisvfritz** [comment]
@YerkoPalma Try again - this should be working now.

**Comment by YerkoPalma** [comment]
It looks awesome again ;D
