### ISSUE TITLE
Bad layout

### ISSUE THREAD

**Issue by octref** [vuejs/vuejs.org#431]
![image](https://cloud.githubusercontent.com/assets/4033249/19016145/1976ae30-87c7-11e6-8e9b-a7f3652648a6.png)

**Comment by chrisvfritz** [comment]
Can you provide more information please? I'm not able to replicate this.

**Comment by octref** [comment]
Open https://vuejs.org/2016/04/27/announcing-2.0/ and resize it to around 900px wide.

I'm using Chrome on Mac.

**Comment by chrisvfritz** [comment]
Thanks! @yyx990803 With the new design, is this page meant to always have the sidebar hidden or is it meant to act like the guide sidebar?

**Comment by octref** [comment]
Can confirm it works. Thanks!

**Comment by chrisvfritz** [comment]
@octref Thanks for reporting it!
