### ISSUE TITLE
Add Aurelia to "Comparison with Other Frameworks"

### ISSUE THREAD

**Issue by atsu85** [vuejs/vuejs.org#432]
It would be nice, if the comparison also contained smth about [Aurelia](http://aurelia.io/) - I really enjoy using it myself.

**Comment by chrisvfritz** [comment]
A pull request and collaboration would definitely be welcome. My experience with Aurelia is quite limited, but I'd be especially curious to hear where Aurelia shines over Vue (even if it's subjective).

**Comment by atsu85** [comment]
I have (almost) no experience with Vue and I'm still reading the docs to find out more, but probably @EisenbergEffect and @jdanyow can introduce some strengths of Aurelia to figure it out.

**Comment by atsu85** [comment]
@chrisvfritz, here is link to the ["Vue vs Aurelia"](https://www.slant.co/versus/11378/37/~vue-js_vs_aurelia) (that came out on top of the search results for me). It is a bit outdated for both frameworks, but probably outlines some good points (even if the first PRO of Aurelia made me laugh a bit regarding the gulpfile ;) )

**Comment by chrisvfritz** [comment]
Thanks. With that alone, I don't yet feel confident that I can make a good comparison between modern Aurelia and modern Vue, but I'd love for people to list differences they've experienced here.

**Comment by atsu85** [comment]
I [asked from Aurelia chat](https://gitter.im/aurelia/Discuss?at=57f035b934a8d5681cd3f134) about Aurelia vs Vue. I didn't get many replies, but one thing that couple of people outlined, was 

* the lack of ES6/ES7 support. 

From my own side, I'd add couple of things for Aurelia that came to my mind right now:

* Related to "ES6/7 support", for me TypeScript is very important because of compile-time checks and IDE support (refactoring and autocomplete).

* Aurelia has [linter](https://github.com/MeirionHughes/aurelia-template-lint/) for detecting issues at compile time from templates (in addition to generic html syntax checks, aurelia specific html elements checks, binding syntax checks, static type checking and many more).

* Convention over configuration, but convention defaults can be altered case-by-case with decorators or replace default conventions with Your own. Aurelia custom element code looks a lot like Angular2 without the bloat.

* Easy to learn or even understand the code without knowing anything about Aurelia. You rarely need to open the documentation to look smth up even if IDE wouldn't help You in any way. This applies for both ES/TS and template code. My teammate once said (shortly after first contact with Aurelia), that he is surprised that things work just exactly how he thought they should without even reading the documentation).

For Vue I'd add 

* server side rendering *([corresponding feature for Aurelia](https://github.com/aurelia/pal-nodejs/) is "nearly ready" based on the quote from main contributor)*

**Comment by EisenbergEffect** [comment]
@atsu85 Do you use VS Code? We've got a cool plugin coming for that :)

**Comment by atsu85** [comment]
@EisenbergEffect, 
> Do you use VS Code?

No, I'm using IDEA, and while I'm grateful to @denofevil for an [unofficial Aurelia plugin for IDEA](https://github.com/denofevil/AureliaStorm/), it could use [much more love](https://github.com/denofevil/AureliaStorm/issues) (from JetBrains).

**Comment by atsu85** [comment]
@EisenbergEffect, could You add some comments here regarding strengths of Aurelia?

**Comment by EisenbergEffect** [comment]
I'll start working on an official document.

**Comment by chrisvfritz** [comment]
@EisenbergEffect Excellent! If there's anything I can answer from the Vue end, please don't hesitate to let me know.

**Comment by Haeresis** [comment]
Just from my experience :
- Aurelia is really a hugh library difficult to understand and apply without knowledge in MVVM.
- Vue is really simple to understand and the learning curve is really awesome !

So I prefer Vue.js because a lot of difficult things with Aurelia seems simple with Vue. 

I don't know for a big application usage but for a everyday or simple / modest application usage, Vue is better than Aurelia.

But Aurelia have a nice name ;)

**Comment by ferrygr** [comment]
Comparing cross platform support and portability between Vue and Aurelia is very welcome. Can it run on iOS / Android? For instance, from what I've gathered, React is the most portable currently - web and mobile devices run the the same code more or less.

**Comment by chrisvfritz** [comment]
@ferrygr Just FYI, Vue's definitely not a one-man effort these days. 🙂  The core team includes 21 members as of writing. Many of the official repos are mostly maintained by people other than Evan and even in core, commits now tend to range between 20% to 60% from other people.

If Evan got hit by a bus, it'd definitely be a very sad day and an incredible loss for the community. Vue wouldn't be the same without his vision, but it would go on.

**Comment by 20zinnm** [comment]
I would definitely add "Official Jetbrains plugin" as a plus for Vue, as well as community. However, I do like the naming conventions Aurelia adopts--`value.bind`--but I still think Vue is an overall cleaner framework or library.

**Comment by marccollin** [comment]
@chrisvfritz 

when you check contributor, second after evan have less then 4000 line of code...

**Comment by sdras** [comment]
As Chris and I have limited experience with Aurelia and no PR was submitted despite the issue being most active about a year ago, I'm going to close out this issue. Please feel free to reopen it! Especially if someone would like to take the charge of creating the initial PR that we could work off of. We appreciate your time thus far in this consideration.
