### ISSUE TITLE
1.0 -> 2.0 Transition Guide suggested addition - events option removed

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vuejs.org#436]
I just upgraded an app from 1.0 to 2.0 and a mention that the events option is gone would have helped. It's implied but not obvious.

**Comment by davidkhess** [comment]
I don't see it pushed to the live site but the commit looks spot on.

**Comment by chrisvfritz** [comment]
Good to hear! It should now be updated btw. I redeploy the site several times per day, but usually only after a batch of changes rather than after each individual commit, as I sometimes like to make further changes after a PR is merged.

**Comment by davidkhess** [comment]
Yes, I see it there now.

BTW, thanks for the great work you and the rest of the team are doing on Vue.js!

**Comment by chrisvfritz** [comment]
@davidkhess It's made easier with lots of help. 😃  Thanks for contributing!
