### ISSUE TITLE
1.0 -> 2.0 Transition Guide suggested addition - `twoWay` directives and filters

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vuejs.org#438]
I just upgraded an app from 1.0 to 2.0 and a mention that `twoWay` directives and filters should be converted to `v-model` on a component wrapping an `input` (at least that seems the case) would be helpful.

**Comment by LinusBorg** [comment]
@chrisvfritz just updated the guide: http://vuejs.org/guide/migration.html#Two-Way-Filters-deprecated

Does that cover the points you feel were missimg?

**Comment by davidkhess** [comment]
Wow, that's a great new section! Two things:

1. There's some occasional weirdness with the JSFiddle embeds where they don't seem to load properly sometimes. Safari 9.1.3 on El Capitan.
2. For those who don't want to go through all of the examples, perhaps this sentence:

> Instead, components are recommended as a more explicit and feature-rich way of creating custom inputs.

could say something like:

> Instead, components wrapping an input are recommended as a more explicit and feature-rich way of creating custom inputs.

Thanks!

**Comment by davidkhess** [comment]
Also, it might be worth it to have a blurb elsewhere like "Two-Way Directives ^ deprecated" that points to this section.

**Comment by davidkhess** [comment]
Oh, and some of the examples say they select the text on focus - but on Safari, if I click them with the mouse you can see the text get selected and then it unselects.

**Comment by LinusBorg** [comment]
Thanks for the feedback! 

/ping @chrisvfritz

**Comment by chrisvfritz** [comment]
@davidkhess I just pushed up a couple updates that I think should resolve all of these. Let me know what you think!

**Comment by davidkhess** [comment]
Looks great!

**Comment by chrisvfritz** [comment]
Fantastic. 😄  Thanks for your help!
