### ISSUE TITLE
Custom Filters section appears to be missing in 2.0 docs

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vuejs.org#439]
Not quite sure what's going on but both the internal links for Custom Filters and the search results seem to jump to the 1.0 version of custom filters.

**Comment by chrisvfritz** [comment]
I think Algolia is still indexing the new site. @posva Can you confirm?

**Comment by davidkhess** [comment]
Note that "Custom Filters" also doesn't show up in the table of contents to the left under 2.0.

**Comment by chrisvfritz** [comment]
Filters have been intentionally left out of the guide, as we don't recommend using them. It's [covered in the API](http://vuejs.org/api/#Vue-filter) though.

**Comment by davidkhess** [comment]
Is the "Custom Filters" link under the "filters" option supposed to link back to 1.0? Or should that link be removed?

**Comment by davidkhess** [comment]
And I saw the `deprecated` notice but its on the "Filters Outside Text Interpolations" title so when I read the next two paragraphs it seemed like filters were not deprecated, just their use outside of Text Interpolations.

If they are indeed deprecated completely, it might help to make that more explicit.

**Comment by chrisvfritz** [comment]
I just updated the links in the filters API. The migration guide is correct though - they're not deprecated completely, as they can indeed still be used inside text interpolations.

**Comment by davidkhess** [comment]
Sounds good. The errant link and 1.0 search results while viewing 2.0 docs are the primary source of confusion.

**Comment by chrisvfritz** [comment]
Good to hear. Hopefully that indexing will finish soon!

**Comment by posva** [comment]
The indexing is finishing. I believe that previous index has not been emptied before populating the new one. What's weird is that the pages in the guide still exist! Those pages are pointing at vuejs.org but are for vue 1.
I'm sending an email to get this fixed. It'll probably get fixed in less than an hour or tomorrow. People at Algolia are very responsive and has always provided a very good support, so I'm closing this.

**Comment by posva** [comment]
It looks like a cache error on our end.
@davidkhess Thank you for reporting that 😄 . We're working on fixing it

**Comment by davidkhess** [comment]
FYI, search hits for "filter" under 2.0 docs look correct now.

**Comment by chrisvfritz** [comment]
Excellent!
