### ISSUE TITLE
The result of  the "app-4" example in guide index page should be wrong 

### ISSUE THREAD

**Issue by theseawolves** [vuejs/vuejs.org#441]
https://github.com/vuejs/vuejs.org/blob/master/src/guide/index.md

```
<div id="app-4">
  <ol>
    <li v-for="todo in todos">
      {{ todo.text }}
    </li>
  </ol>
</div>

var app4 = new Vue({
  el: '#app-4',
  data: {
    todos: [
      { text: 'Learn JavaScript' },
      { text: 'Learn Vue' },
      { text: 'Build something awesome' }
    ]
  }
})

```
**The  website shows the result :**
```
1. Learn JavaScript
2. Learn Vue
3. Build something awesome

```

**but the correct should be:**  : 
(without the index number in the template)
```
Learn JavaScript
Learn Vue
Build something awesome
```

**Comment by chrisvfritz** [comment]
I'm sorry, I'm not sure what you mean by this. 😕  Would you mind providing more details or rephrasing?

**Comment by theseawolves** [comment]
@chrisvfritz  sorry! I was updated more details.

**Comment by chrisvfritz** [comment]
Ah, I see. The numbers are created by the ordered list (`<ol>`), so it is actually rendering correctly.
