### ISSUE TITLE
2.0 docs - better "dynamic attributes" example in Introduction

### ISSUE THREAD

**Issue by davestewart** [vuejs/vuejs.org#449]
I just checked out the new v2.0 Introduction, and thought I would comment on the dynamic attribute:

<img src="http://forum.vuejs.org/uploads/default/original/1X/43a25de513723fa6abc9809e3cadb18ee423547b.png" width="630" height="414">

The entire example feels really contrived in my opinion:

- I can't think of an everyday situation where I would want a dynamic id
- I can't think of a single time I've used the more verbose 'v-bind' syntax; it looks kludgy in its longhand form, and the shorthand version would look more accessible for new users
- I had no idea what "Inspect me" meant for a good 20 - 30 seconds
- When I did, you have to use the Developer Tools to work out what's changed

Anything other than `id` would be more intuitive as the 3rd example on the page, such as `class`, `title`, `href` or `src` - all immediately visible on the page!

- title: https://jsfiddle.net/ft1u4ptq/
- href: https://jsfiddle.net/h4f9z6t1/
- img: https://jsfiddle.net/ygk08ed9/

Just my 2c; `id` is just a recipe for confusion.

**Comment by chrisvfritz** [comment]
> I can't think of an everyday situation where I would want a dynamic id

Dynamic id bindings are commonly used to mount 3rd party libraries to a container (e.g. Google Maps), but I agree the `title` attribute might be better and have updated the example.

> I can't think of a single time I've used the more verbose 'v-bind' syntax; it looks kludgy in its longhand form, and the shorthand version would look more accessible for new users

I always use the shorthand for `v-bind` in my personal code too, but our rule is we _always_ use the more verbose form in the guide. The shorthand version might seem cooler/cleaner, but when first learning, a word is easier to remember than a symbol and it's also easy to miss a colon when skimming an example.

> I had no idea what "Inspect me" meant for a good 20 - 30 seconds; When I did, you have to use the Developer Tools to work out what's changed

For those not as familiar with their browser's devtools, the `title` attribute can be inspected on hover, so I've updated the instructions. I don't think it's a problem though that developers sometimes have to use the developer tools. It's a bit like a carpenter complaining that they had to use a hammer. Opening them is very simple and familiarity is absolutely essential for any frontend developer.

**Comment by davestewart** [comment]
Good stuff Chris, and thanks responding :)
