### ISSUE TITLE
2.0 docs-- missing "slot" option on render function's data object

### ISSUE THREAD

**Issue by asselin** [vuejs/vuejs.org#450]
Reopening issue https://github.com/vuejs/vue/issues/3841 against the vuejs.org repo per Evan.

Referring to this part of the doc: http://vuejs.org/guide/render-function.html#The-Data-Object-In-Depth

When writing a render function, if you want to pass something in a named slot to a component, you have to write something like this:

````
createElement(component, { }, 
  createElement('div', {
    slot: 'some-named-slot'
  }, [ <some content> ])
);
````

Currently, the documentation for `createElement`'s data object doesn't mention the `slot` field.

**Comment by chrisvfritz** [comment]
Thanks! Fixed in 26ac8a92b84b27f2a5fd8b7c9c36b7b411004f24.
