### ISSUE TITLE
br.vuejs.org - Portuguese Brazilian translation 

### ISSUE THREAD

**Issue by danielschmitz** [vuejs/vuejs.org#456]
Hi,

I just started translating the website in Portuguese Brazilian Language (br) . 

fork @ [vuejs-br/br.vuejs.org](https://github.com/vuejs-br/br.vuejs.org)

Team:
 @danielschmitz
 @vedovelli
 @vitorarjol
 @jbruni
 @ErickPetru
 @natanaelphp
 @gidenilson
 @nicholaspedroso

Status:

**Website**
- [x] Entry Page

**Guide**
- [x] Installation
- [x] Introduction
- [x] The Vue Instance
- [x] Template Syntax
- [x] Computed Properties and Watchers
- [x] Class and Style Bindings
- [x] Conditional Rendering
- [x] List Rendering
- [x] Event Handling
- [x] Form Input Bindings
- [x] Components
- [x] Advanced
- [x] Transitions: Entering, Leaving, and Lists
- [x] Transitioning State
- [x] Render Functions
- [x] Reactivity in Depth
- [x] Custom Directives
- [x] Mixins
- [x] Plugins
- [x] Single File Components
- [x] Routing
- [x] State Management
- [x] Unit Testing
- [x] Server-Side Rendering
- [x] Migration from Vue 1.x
- [x] Migration from Vue Router 0.7.x
- [x] Migration from Vuex 0.6.x to 1.0 
- [x] Comparison with Other Frameworks
- [x] Deployment

**Examples**
- [x] Markdown Editor
- [x] GitHub Commits
- [x] Firebase + Validation
- [x] Grid Component
- [x] Tree View
- [x] SVG Graph
- [x] Modal Component
- [x] Elastic Header
- [x] Wrapper Component
- [x] TodoMVC
- [x] HackerNews Clone

ps: if you need use this list in your translation issue, get [here](https://gist.github.com/danielschmitz/dcc81c08b32c30d2a2edf76ec4e2dbfd)

**Comment by jbruni** [comment]
Pretendo contribuir. Acabei de entrar no Slack.

I wish to contribute. Just joined Slack.

**Comment by ErickPetru** [comment]
I wish to contribute too. I joined Slack and started translating *Guide/Introduction* (**index.md**).

**Comment by gilvaju** [comment]
I wish to contribute too, started translating Single File Components.

**Comment by NicholasPedroso** [comment]
I'm on it :)

**Comment by danielschmitz** [comment]
Hello DEVS, we are 99% with guide, how to publish to oficial rep?

**Comment by chrisvfritz** [comment]
@danielschmitz Just seeing your comment now. [Here's are the steps](https://github.com/vuejs/vuejs.org/issues/271#issuecomment-266476746) to get this translation official.

**Comment by ErickPetru** [comment]
@chrisvfritz, I just followed [all the steps](https://github.com/vuejs/vuejs.org/issues/271#issuecomment-266476746) right now, but [br.vuejs.org](br.vuejs.org) isn't working yet. I believe the last step Evan [did here](https://github.com/vuejs/vuejs.org/issues/271#issuecomment-268624151) is still needed. Can you do it, please?

**Comment by danielschmitz** [comment]
@yyx990803 
Any news about br.vuejs.org ?

**Comment by yyx990803** [comment]
Sorry for letting this sit - it's up now! 🎉 

https://br.vuejs.org

Closing this one - now we need a PR to add Portuguese to the main language dropdown :)

**Comment by vitorarjol** [comment]
Portuguese add to the dropdown at #872
