### ISSUE TITLE
An error in an example about the Filtered and Sorted 

### ISSUE THREAD

**Issue by ricardocanelas** [vuejs/vuejs.org#463]
In https://github.com/vuejs/vuejs.org/blob/master/src/guide/list.md#displaying-filteredsorted-results
the last example isn't working. Showed me this message: 'Uncaught TypeError: numbers.filter is not a function'. You can test here: https://jsfiddle.net/9qnugcfc/

**Comment by chrisvfritz** [comment]
You forgot to change `computed` to `methods` in your fiddle. The actual example works:

https://jsfiddle.net/chrisvfritz/nfym3byf/
