### ISSUE TITLE
vuejs2.0 v-focus demo code does not work in the document

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vuejs.org#465]
Vue.js version

2.0.0-rc.3

Reproduction Link

[https://jsfiddle.net/matiascx/tdhzjavg/1/](https://jsfiddle.net/matiascx/tdhzjavg/1/)

Steps to reproduce

run

What is Expected?

input focused

What is actually happening?

No focus happen on input element

**Comment by chrisvfritz** [comment]
Why use `rc3`? The final version is out. 😃  If you update your version of Vue, [it works](https://jsfiddle.net/chrisvfritz/6g735ogy/).

**Comment by cnweibo** [comment]
great, i'd like to update it.
@chrisvfritz , by the way, i use npm install vue@next to fetch the package in my node_modules.
Should I now use that command again or something different since vuejs2.0 stable is available now?

thanks~!

**Comment by chrisvfritz** [comment]
Since 2.0 is out now, you can just use `npm install vue`.
