### ISSUE TITLE
Bug in Firefox?

### ISSUE THREAD

**Issue by jallander** [vuejs/vuejs.org#467]
OS: LinuxMint 18 (64-bit)
Firefox 49
Chromium 52
There are a data variable 'paradas[]'. The paradas['lineas'] is a array variable. 
The code is:
`computed: {
      lineas: function () {
        let lineas = []
        this.paradas.forEach(function(current,index) {
          lineas.push(current['lineas'])
        })
        console.log(lineas)
        return lineas
      }
    },`
This code compile correctly into Chromium:
![chromium-1](https://cloud.githubusercontent.com/assets/3317821/19103389/d4e766e8-8ad6-11e6-8325-98b741e617af.png)
and in the browser, for lineas[0]:
![chromium-2](https://cloud.githubusercontent.com/assets/3317821/19103432/0cbd8804-8ad7-11e6-8d9c-81520faf1616.png)
In Firefox:
![firefox-1](https://cloud.githubusercontent.com/assets/3317821/19103483/5f70ac2a-8ad7-11e6-95e9-a2b25c73a74f.png)
![firefox-2](https://cloud.githubusercontent.com/assets/3317821/19103488/63e2a8ee-8ad7-11e6-8194-251ddb3ee40b.png)

**Comment by jallander** [comment]
I am use vue.js 1.0.27

**Comment by chrisvfritz** [comment]
This is the documentation repository. You're probably looking for [vuejs/vue](https://github.com/vuejs/vue)? Either way though, this requires a bit more independent troubleshooting before an issue is open. For example, does this even have anything to do with Vue or do you notice the problem outside of Vue as well? Can you replicate the problem in a simple jsfiddle?
