### ISSUE TITLE
[Suggestion] Make the search bar accessible from anywhere on the page

### ISSUE THREAD

**Issue by SoullessWaffle** [vuejs/vuejs.org#475]
You guys have really user-friendly documentation and search, but at the moment the user needs to scroll to the top of the page every time they want to search for something.
I believe it would be a meaningful UX improvement if the user could search from anywhere on the page.
Making the header fixed so it always stays in view is one possible solution.

**Comment by chrisvfritz** [comment]
I think this could be a good change. 👍  I may not have time to implement it right away, but a PR would be welcome and I can check it out.

**Comment by LinusBorg** [comment]
This is live now :+1:
