### ISSUE TITLE
About  eventHub 

### ISSUE THREAD

**Issue by woshihaoren** [vuejs/vuejs.org#498]
http://vuejs.org/guide/migration.html#dispatch-and-broadcast-deprecated
about this guide,I have some question.
where to wirte "var eventHub = new Vue() ", and how to import eventHub in NewTodoInput or DeleteTodoButton component?

**Comment by chrisvfritz** [comment]
You don't have to do anything specific to the event bus. If you're using a module system, you can export/import it just like any other object:

``` js
// event-bus.js
export default new Vue()
```

``` js
// some other file
import eventBus from './event-bus'
```

**Comment by woshihaoren** [comment]
I got it ,Thank you ~
