### ISSUE TITLE
Make the sortable grid component example use a stable sort

### ISSUE THREAD

**Issue by JobLeonard** [vuejs/vuejs.org#500]
This grid component: https://vuejs.org/examples/grid-component.html

In my experience, almost all sortable table components on the internet use unstable sorting, which I find mildly infuriating. This is more than just a little pet peeve, it's a usability issue! Especially with larger tables with many equal keys per column, this becomes important. It would be really cool if vue gets this right by default.

EDIT: just checked the JS of the example; it does not use a stable sort. There's quite a simple trick to fix that here:

http://stackoverflow.com/a/2085225

But this won't work here, since the data isn't sorted in-place but through a copy. Another option would be to keep track of the clicked sort keys, use the second-most-recent key as a secondary key, third-most-recent as tertiary key, etc (up to at most the number of possible keys). That would achieve the same effect.

I can see if I can find the time for this later tonight.

**Comment by chrisvfritz** [comment]
Note that we'd only accept a pull request for this only if it has a very minor effect on the example. If it would require significant changes, like using a watcher instead (which I suspect it would), then I'd prefer to keep it the way it is. An example implementing stable sort could be interesting in the Vue Cookbook that we'd like to develop however, so you'd still be welcome to post your solution here.

**Comment by JobLeonard** [comment]
Check, I can imagine you don't want too much complexity here. I'll just link the JSFiddle here when I'm done.

**Comment by chrisvfritz** [comment]
Still open to the example, but closing for now as there's nothing more that's actionable on our part.

**Comment by JobLeonard** [comment]
I understand; and my apologies, I haven't gotten around to working on this just yet.

**Comment by chrisvfritz** [comment]
No worries. 🙂
