### ISSUE TITLE
v-for (val, key, index) object documentation incorrect

### ISSUE THREAD

**Issue by g-liu** [vuejs/vuejs.org#517]
In the [documentation for v-for](http://vuejs.org/api/#v-for), it states that we can use the following syntax to iterate over an object:

```html
<div v-for="(val, key, index) in object"></div>
```

However, I have found that this is not the case. `val` and `key` are both `undefined`, and `index` turns out to be a value in the `object`. I can, however, still use `{{$key}}` and `{{$index}}` in the `v-for`.

I am using vue 1.0.28.

**Comment by chrisvfritz** [comment]
You're experiencing discrepancies because you're reading the 2.0 documentation while working with 1.0. You want [these docs](http://v1.vuejs.org/api/) instead.
