### ISSUE TITLE
Recursive compoment in Tree-view emxaple

### ISSUE THREAD

**Issue by rookiezmh** [vuejs/vuejs.org#518]
In the guide parts, it says "Components can recursively invoke themselves in their own template. However, they can only do so with the name option", however in the tree-view example, the recursive component item doesn't have a name option.Below is the code.
**template**
<script type="text/x-template" id="item-template">
      <li>
        <div
          :class="{bold: isFolder}"
          @click="toggle"
          @dblclick="changeType">
          {{model.name}}
          <span v-if="isFolder">[{{open ? '-' : '+'}}]</span>
        </div>
        <ul v-show="open" v-if="isFolder">
          <item
            class="item"
            v-for="model in model.children"
            :model="model">
          </item>
          <li class="add" @click="addChild">+</li>
        </ul>
      </li>
    </script>
**js**
Vue.component('item', {
  template: '#item-template',
  props: {
    model: Object
  },
  data: function () {
    return {
      open: false
    }
  },
  computed: {
    isFolder: function () {
      return this.model.children &&
        this.model.children.length
    }
  },
  methods: {
    toggle: function () {
      if (this.isFolder) {
        this.open = !this.open
      }
    },
    changeType: function () {
      if (!this.isFolder) {
        Vue.set(this.model, 'children', [])
        this.addChild()
        this.open = true
      }
    },
    addChild: function () {
      this.model.children.push({
        name: 'new stuff'
      })
    }
  }
})
Does it mean it's ok to use a recursive component without a name option or what?

**Comment by chrisvfritz** [comment]
`Vue.component` takes the name as the first argument, so a `name` _is_ being set. I'll update the explanation and API doc to make that clearer.

**Comment by chrisvfritz** [comment]
Just updated the docs to make this clearer.
