### ISSUE TITLE
ru.vuejs.org — Russian Translation

### ISSUE THREAD

**Issue by gbezyuk** [vuejs/vuejs.org#527]
[current fork here](http://github.com/translation-gang/ru.vuejs.org)
[current demo site here](http://ruvuejsorg.surge.sh/)

## Team:

@gbezyuk (general translation)
@kojoru (proof-reading and styling)
@moonlik (proof-reading)
more contributors are welcome

### Website
- [x] Entry Page
- [x] Other Layout Elements
### Guide

Essentials
- [x] Installation
- [x] Introduction
- [x] The Vue Instance
- [x] Template Syntax
- [x] Computed Properties and Watchers
- [x] Class and Style Bindings
- [x] Conditional Rendering
- [x] List Rendering
- [x] Event Handling
- [x] Form Input Bindings
- [x] Components

Advanced
- [x] Reactivity in Depth
- [x] Transition Effects
- [x] Transitioning State
- [x] Render Functions
- [x] Custom Directives
- [x] Mixins
- [x] Plugins
- [x] Single File Components
- [x] Deploying For Production
- [x] Routing
- [x] State Management
- [x] Unit Testing
- [x] Server-Side Rendering

Migrating
- [ ] Migration from Vue 1.x `translation in progress by @gbezyuk`
- [ ] Migration from Vue Router 0.7.x
- [x] Migration from Vuex 0.6.x to 1.0

Meta
- [x] Comparison with Other Frameworks
- [x] Join the Vue.js Community!
### API
- [x] Global Config
- [x] Global API
- [x] Options / Data
- [x] Options / DOM
- [x] Options / Lifecycle Hooks
- [x] Options / Misc
- [x] Instance Properties
- [x] Instance Methods / Data
- [x] Instance Methods / Events
- [x] Instance Methods / Lifecycle
- [x] Directives
- [x] Special Attributes
- [x] Built-In Components
- [x] VNode Interface
- [x] Server-Side Rendering
### Examples
- [x] Markdown Editor
- [x] GitHub Commits
- [x] Firebase + Validation
- [x] Grid Component
- [x] Tree View
- [x] SVG Graph
- [x] Modal Component
- [x] Elastic Header
- [x] Wrapper Component
- [x] TodoMVC
- [x] HackerNews Clone
- [x] Markdown Editor
### Blog
?

### Website
- [x] Entry Page
- [x] Other Layout Elements
### Guide

Essentials
- [x] Installation
- [x] Introduction
- [x] The Vue Instance
- [x] Template Syntax
- [x] Computed Properties and Watchers
- [x] Class and Style Bindings
- [x] Conditional Rendering
- [x] List Rendering
- [x] Event Handling
- [x] Form Input Bindings
- [x] Components

Advanced
- [x] Reactivity in Depth
- [x] Transition Effects
- [x] Transitioning State
- [x] Render Functions
- [x] Custom Directives
- [x] Mixins
- [x] Plugins
- [x] Single File Components
- [x] Deploying For Production
- [x] Routing
- [x] State Management
- [x] Unit Testing
- [x] Server-Side Rendering

Migrating
- [ ] Migration from Vue 1.x
- [ ] Migration from Vue Router 0.7.x
- [x] Migration from Vuex 0.6.x to 1.0

Meta
- [x] Comparison with Other Frameworks
- [x] Join the Vue.js Community!
### API
`proof-reading and styling in progress by @kojoru`
- [x] Global Config
- [x] Global API
- [x] Options / Data
- [x] Options / DOM
- [x] Options / Lifecycle Hooks
- [x] Options / Misc
- [x] Instance Properties
- [x] Instance Methods / Data
- [x] Instance Methods / Events
- [x] Instance Methods / Lifecycle
- [x] Directives
- [x] Special Attributes
- [x] Built-In Components
- [x] VNode Interface
- [x] Server-Side Rendering
### Examples
- [x] Markdown Editor
- [x] GitHub Commits
- [x] Firebase + Validation
- [x] Grid Component
- [x] Tree View
- [x] SVG Graph
- [x] Modal Component
- [x] Elastic Header
- [x] Wrapper Component
- [x] TodoMVC
- [x] HackerNews Clone
- [x] Markdown Editor
### Blog
?

## Glossary (or current doubtful term translation conventions):

(currently for uniformity only, a subject to change in the future, not a complete list yet)
- `instance` — инстанс
- `props` — входные параметры
- `calculated props` — вычисляемые свойства
- `native` — нативный
- `callback` — ~~функция обратного вызова~~ коллбэк

// this thread was originally started with:

> Being a native speaker and an amateur linguist, I would be more than happy to help with Russian translation. Is it, by any chance, already in progress?

**Comment by gbezyuk** [comment]
The translation is started at https://github.com/gbezyuk/ru.vuejs.org

**Comment by chrisvfritz** [comment]
@simplesmiler might know better, but there's none that I know of.

**Comment by simplesmiler** [comment]
There was an initiative around the time of transition 0.x -> 1.x (https://github.com/vuejs-ru/vuejs.org). But it didn't finish, and most likely is unusable now, because 2.0 were rewritten pretty much from scratch.

**Comment by gbezyuk** [comment]
I am close to finishing the API translation now, as well as first parts of the Guide. Should we move the repo under vuejs?

**Comment by gbezyuk** [comment]
UPD. Guide's `Essentials` section is almost finished. Guys, let's move the repo to vuejs and start proofreading. Anybody? )

**Comment by chrisvfritz** [comment]
We'll move this to its own repository under the `vuejs` organization once it's done, but in the meantime, it's generally easier to just manage the translation in a personal repo, where you'll have full control over collaborators.

**Comment by gbezyuk** [comment]
API docs proofreading started by @kojoru.

**Comment by gbezyuk** [comment]
Guide's Essentials section initial translation is completed.

**Comment by gbezyuk** [comment]
"Reactivity in Depth" section from Guide/Advanced is translated.

**Comment by gbezyuk** [comment]
"Plugins", "Mixins", "Join Vue.j Comminity", "Custom Directives" and "Deployment" sections of the Guide are translated.

**Comment by gbezyuk** [comment]
"Render Functions", "Routing" and "Single File Components" sections of the Guide are translated.

**Comment by gbezyuk** [comment]
"Server-Side Rendering" and "State Management" sections of the Guide are translated.

**Comment by gbezyuk** [comment]
"Transitioning State" section of the Guide is translated.

**Comment by gbezyuk** [comment]
"Transition Effects" section of the Guide is translated. My gosh, we don't seem to have a proper translation for "transition" in Russian =(

**Comment by gbezyuk** [comment]
"Unit testing" section of the Guide is translated. Thus, the Guide translation seems to be complete now.

**Comment by gbezyuk** [comment]
@chrisvfritz, maybe it's time to move the repo under vuejs now? It's certainly not the end of the work, as there should be more proof-reading and styling, as well as "migrations", "comparison with other frameworks" and "examples" sections translation, but I guess the translation is already useful for Russian developers not having enough skill in English to read the original documentation.

**Comment by gbezyuk** [comment]
@kojoru, would you please mark the checkboxes indicating the sections you've already proof-read?

**Comment by chrisvfritz** [comment]
> maybe it's time to move the repo under vuejs now? It's certainly not the end of the work, as there should be more proof-reading and styling, as well as "migrations", "comparison with other frameworks" and "examples" sections translation, but I guess the translation is already useful for Russian developers not having enough skill in English to read the original documentation.

@yyx990803 What do you think?

**Comment by gbezyuk** [comment]
"Comparison with Other Frameworks" chapter is translated. That was a big one =)

**Comment by kojoru** [comment]
# Proofreading / Styling Status

## Website

- [ ] Entry Page (?)

## Guide

- [ ] Essentials

### Installation
- [ ] Introduction
- [ ] The Vue Instance
- [ ] Template Syntax
- [ ] Computed Properties and Watchers
- [ ] Class and Style Bindings
- [ ] Conditional Rendering
- [ ] List Rendering
- [ ] Event Handling
- [ ] Form Input Bindings
- [ ] Components

### Advanced
- [ ] Reactivity in Depth
- [ ] Transition Effects
- [ ] Transitioning State
- [ ] Render Functions
- [ ] Custom Directives
- [ ] Mixins
- [ ] Plugins
- [ ] Single File Components
- [ ] Deploying For Production
- [ ] Routing
- [ ] State Management
- [ ] Unit Testing
- [ ] Server-Side Rendering

### Migrating
- [ ] Migration from Vue 1.x
- [ ] Migration from Vue Router 0.7.x
- [ ] Migration from Vuex 0.6.x to 1.0

### Meta
- [ ] Comparison with Other Frameworks
- [ ] Join the Vue.js Community!

## API

- [ ] Global Config
- [ ] Global API
- [ ] Options / Data
- [ ] Options / DOM
- [ ] Options / Lifecycle Hooks
- [ ] Options / Misc
- [ ] Instance Properties
- [ ] Instance Methods / Data
- [ ] Instance Methods / Events
- [ ] Instance Methods / Lifecycle
- [ ] Directives
- [ ] Special Attributes
- [ ] Built-In Components
- [ ] VNode Interface
- [ ] Server-Side Rendering

## Examples
- [ ] Markdown Editor
- [ ] GitHub Commits
- [ ] Firebase + Validation
- [ ] Grid Component
- [ ] Tree View
- [ ] SVG Graph
- [ ] Modal Component
- [ ] Elastic Header
- [ ] Wrapper Component
- [ ] TodoMVC
- [ ] HackerNews Clone
- [ ] Markdown Editor

**Comment by gbezyuk** [comment]
Translation was updated to v.2.0.5 via an upstream merge in order to reflect the changes of the original documentation.

**Comment by gbezyuk** [comment]
layout elements translated

**Comment by gbezyuk** [comment]
@moonlik has joined the team, providing his first PR with typo fixes

**Comment by gbezyuk** [comment]
Self-proff-read "comparison", "class-and-style-conventions" and "components"; disabled 'Source Sans Pro' font which doesn't seem to play nice with Cyrillic text at the moment (see _settings.styl for details).

**Comment by gbezyuk** [comment]
@yyx990803, how about moving the repo to **vuejs** team?

**Comment by kojoru** [comment]
We've returned Source Sans Pro as a locally hosted font since Google Fonts does not support Cyrillic for it.

**Comment by gbezyuk** [comment]
There was a massive proof-reading / styling work done today. Also, the examples section was translated. So now, basically, we have only the migrations docs left to be translated, and just a few sections of the guide to be proof-readed.

Which returns me to the original question about the repository position. @chrisvfritz, @yyx990803 — what do you think, guys?

**Comment by timefordroids** [comment]
I have translated migrations docs for Vuex.

**Comment by gbezyuk** [comment]
Vuex migration docs were proof-read.

**Comment by timefordroids** [comment]
Translated migrations docs for Vue Router.

**Comment by gbezyuk** [comment]
Merged upstream to reflect 2.1.x version docs update; thus some new parts of docs are not yet translated. @chrisvfritz, what about finally creating a Russian version docs repo under @vuejs?

**Comment by chrisvfritz** [comment]
@gbezyuk Sounds great! I don't have access to create new repos, but I think this should now be ready @yyx990803.

**Comment by gbezyuk** [comment]
2.1.x stuff is also translated.

**Comment by parotikov** [comment]
look forward to official Russian docs at ru.vuejs.org

**Comment by grigoriygithub** [comment]
+1

**Comment by yyx990803** [comment]
Awesome, in Paris with shitty wifi right now, will setup the logistics once I get back to US.

**Comment by yyx990803** [comment]
Btw is the demo site up to date? Seems it doesn't have the new ecosystem dropdown.

**Comment by malitov** [comment]
+1 official Russian docs

**Comment by gbezyuk** [comment]
@yyx990803 sorry, the demo site isn't up-to-date. @kojoru, could you please fix it?

**Comment by kojoru** [comment]
@gbezyuk done

**Comment by victorpetryk** [comment]
+1 for official Russian docs

**Comment by yyx990803** [comment]
Looks good! So, for the deployment logistics:

- You can deploy via either surge or GitHub pages. For either you need to update the `src/CNAME` file to `ru.vuejs.org` - I will add a DNS record and update the languages dropdown on the main site once that's done.

- We will likely not be pulling translation repos into the `vuejs` organization in the future, as it just adds admin complexity for little benefits. I'd recommend continuing to work in your current fork and update the contribution link at the bottom of each page.

**Comment by yyx990803** [comment]
Nvm! I looks like you already did.

**Comment by yyx990803** [comment]
It seems Surge does not support subdomain CNAME? Maybe we need to use GitHub pages instead.

**Comment by gbezyuk** [comment]
@yyx990803 I guess it already works somehow with Japanese and Mandarin? Shouldn't we just use the same approach?

**Comment by yyx990803** [comment]
@gbezyuk my experience is that moving them into the organization didn't provide any practical benefits except that it is now "part of the organization", and adding contributors etc. became more complex because it now has to go through the organization instead.

**Comment by gbezyuk** [comment]
@yyx990803 I got it and I don't insist. I was addressing the issue of CNAME.

**Comment by yyx990803** [comment]
@gbezyuk ah, ok. Both the Chinese and Japanese versions are using GitHub pages. I tried pointing the CNAME to surge but it doesn't seem to work: https://ru.vuejs.org/

**Comment by gbezyuk** [comment]
what does the original site use?

**Comment by yyx990803** [comment]
Also GitHub pages. I've already pointed the domain to GitHub now, but it seems the gh-pages of translation-gang/ru.vuejs.org is out of date.

Since you've already edited [this line](https://github.com/translation-gang/ru.vuejs.org/blob/master/_config.yml#L100), you should be able to just run `hexo deploy` to deploy to GitHub pages.

**Comment by gbezyuk** [comment]
oh, the line is outdates as I've moved the repo to @translation-gang. Seems like it's my fault in the end of the day. Let me fix it.

**Comment by gbezyuk** [comment]
finally, it seems to work now! hooray!

**Comment by gbezyuk** [comment]
once again, Evan, thank you very much for everything you've done!

**Comment by yyx990803** [comment]
Yay! Do you want to make a PR to the main repo to add Russian under the translations dropdown?

**Comment by gbezyuk** [comment]
Sure, in a minute.

**Comment by gbezyuk** [comment]
#637 — here you go

**Comment by gbezyuk** [comment]
I've also created a PR for Japanese translation (https://github.com/vuejs/jp.vuejs.org/pull/195)
Can't find a way trough Chinese characters, unfortunately. 对不起.

**Comment by gbezyuk** [comment]
And BTW, there's vue-router's translation awaiting a merge, too.

**Comment by gbezyuk** [comment]
@chrisvfritz thank you too :) I think it's okay to close this issue now, as all further work could be coordinated under @translation-gang.
Could you please deploy vue-router's up-to-date version as well? Russian docs are merged in, but not yet deployed, which makes me feel a bit incomplete )

**Comment by sdras** [comment]
Reading through this thread, this looks like it was good to close about a year ago. I'm closing it out but feel free to reopen if I misunderstood. Thanks!
