### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by paul-go** [vuejs/vuejs.org#531]
RiotJS has an animation plugin: https://github.com/sartaj/riot-animate

(Although I can't vouch for it's quality)

**Comment by LinusBorg** [comment]
This does not seem to be an officially supported plugin, though, does it?

In the comparisons section, we compare what the official libaries are offering. If we would take into account every library's plugin contributed by its community (which would naturally differ wildly in quality), the comparison would simply become impossible.

**Comment by chrisvfritz** [comment]
If it was a robust and well-supported animation solution with broad adoption in the ecosystem, I'd likely remove this line altogether, but this doesn't seem to be the case unfortunately. 

- Hasn't been touched in 4 months (and no new version has been published in a year) 
- No tests
- Documentation consists of a single example
- With only 19 downloads in the last month on NPM, I don't get the impression people are using and enjoying it
