### ISSUE TITLE
Remove vendor prefixes in markdown editor example

### ISSUE THREAD

**Issue by adamzap** [vuejs/vuejs.org#535]
The vendor prefixes in the Markdown Editor example are not needed: http://caniuse.com/#feat=css3-boxsizing

- Example page: https://vuejs.org/examples/
- JSFiddle Source: https://jsfiddle.net/yyx990803/v368d4g3/

Thanks!

**Comment by chrisvfritz** [comment]
You're right, thanks! Fixed now.
