### ISSUE TITLE
Extract code fragments in order to avoid duplication

### ISSUE THREAD

**Issue by gbezyuk** [vuejs/vuejs.org#546]
Currently there's often this situation in the text:

``` js
// some code
```

Result

{% raw %}

<script>
// same code once again
</script>

{% endraw %}

Which looks like the code should be extracted to a variable of some sort. Is it possible to do this extraction via pre-processing of some sort?

**Comment by chrisvfritz** [comment]
Yes, there are ways, but all of the solutions I've come up with so far have their own disadvantages. 😕  It remains something I'm thinking about in the back of my mind, so I'm very open to discussion/suggestions here.

**Comment by chrisvfritz** [comment]
Closing this for now, as there doesn't seem to be an obvious solution. Still something I'll be keeping in the back of my mind though and I'm always open to ideas. 🙂
