### ISSUE TITLE
hexo server: Docs don't work

### ISSUE THREAD

**Issue by thewhitetulip** [vuejs/vuejs.org#551]
I want a local version of vue.js and that's why I tried to build this repo, but I get this error.

npm install
npm WARN no-skeleton.docpad@0.1.0 No repository field.
npm WARN no-skeleton.docpad@0.1.0 No license field.

$ hexo server
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

Cant' start the docs!!

**Comment by chrisvfritz** [comment]
Are you sure you didn't make a typo? `hexo server` shoud work.

**Comment by thewhitetulip** [comment]
No, I installed hexo last night and it doesn't work. There is no option as server for hexo.

Can you please try that out with a fresh pull? I followed the steps given in the manual, I first installed hexo using the npm then I went to the folder where I had cloned the vuejs.org repository and there, I ran npm install, there I got this message, I have no clue what it means in npm context

`npm WARN no-skeleton.docpad@0.1.0 No repository field.`
`npm WARN no-skeleton.docpad@0.1.0 No license field.`

Then I did hexo server.

**Comment by thewhitetulip** [comment]
Was an npm install issue
