### ISSUE TITLE
Wrong link on Comparison page

### ISSUE THREAD

**Issue by Francisc** [vuejs/vuejs.org#556]
Hello,

Under [Angular 2, Learning Curve](https://github.com/vuejs/vuejs.org/blob/master/src/guide/comparison.md#learning-curve), there's a link to a Vue.js "Hello World" app which is broken.

It points to:
https://vuejs.org/guide/index.html#Hello-World
which redirects to:
https://vuejs.org/guide/index.html#mobile-bar

I'd send a PR, but I'm unsure what the correct location is.
Perhaps:
https://jsfiddle.net/chrisvfritz/4tpzm3e1/
?

**Comment by chrisvfritz** [comment]
Thanks! I just updated the links. 🙂

**Comment by Francisc** [comment]
Thank you.
