### ISSUE TITLE
v-html problem with load more

### ISSUE THREAD

**Issue by prakasa1904** [vuejs/vuejs.org#558]
Sorry im new in vue, maybe its my fault but im really dont know why my v-html not working at loadmore click. My code not use component or template, just in line HTML format and Vue object app : 

`li class="media" v-for="(event, index) in events">
                        <div class="media-left">
                            <a v-bind:href="event.url">
                                <img style="height:150px;" v-bind:src="event.cover" class="media-object lazy" v-bind:alt="event.content_name">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><a v-bind:href="event.url" v-html="event.content_name"></a></h4>
                            <p v-html="event.content_excerpt"></p>
                        </div>
                    </li>`

the problem is here : v-html="event.content_excerpt" ... When use load more click, there not working well.. Whats wrong with that. Thanx

**Comment by chrisvfritz** [comment]
Hi @prakasa1904 - we actually reserve the issues for bugs and feature requests. For general usage questions, I recommend [the forum](http://forum.vuejs.org/) or [Gitter chat](https://gitter.im/vuejs/vue).
