### ISSUE TITLE
Tool for drawing VUE official diagram

### ISSUE THREAD

**Issue by henryhuang** [vuejs/vuejs.org#559]
Sorry for I ask this question on this area.

Could u tell me that what's the tool for VUE drawing official diagram like http://vuejs.org/guide/instance.html#Lifecycle-Diagram ?

**Comment by simplesmiler** [comment]
Illustrator. Reference: https://twitter.com/vuejs/status/650963538727567361

**Comment by henryhuang** [comment]
@simplesmiler Thanks

**Comment by chrisvfritz** [comment]
Some prototypes also built with Google Slides I believe, so that may be worth looking into as an alternative.
