### ISSUE TITLE
Example creating an extendable custom input component

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vuejs.org#563]
Sometimes users want to have complicated custom behavior for `v-model`, or simply 2-way filter like type casting similar to the built-in modifiers.

The custom input component pattern I demonstrated earlier (as mentioned [here](https://github.com/vuejs/vue/issues/3666#issuecomment-249583603)) is very powerful and can handle all those needs, but it isn't mentioned in the docs.

I think we should either add a paragraph on this at the end of Form Input Bindings (with a tip like "comeback after you understand how components work"), OR add a chapter in the Advanced section of the guide.

**Comment by chrisvfritz** [comment]
I have an example for transitioning from 2-way filters to a custom input component [in the migration guide](http://vuejs.org/guide/migration.html#Two-Way-Filters-replaced). @yyx990803 Is that the kind of thing you're thinking of? Either way, I agree it should also be featured elsewhere in the guide.

**Comment by yyx990803** [comment]
@chrisvfritz ah yeah, that's already very detailed. Maybe an adapted version of that, without assuming a 1.x background.
