### ISSUE TITLE
The menu button doesn't work in some browsers?

### ISSUE THREAD

**Issue by writeee** [vuejs/vuejs.org#564]
Tested Safari and Chrome at iOS9, not working.
But Chrome for Android is OK...

**Comment by chrisvfritz** [comment]
I don't have access to iOS9, but iOS10 seems to be working fine for me. Can you clarify what you're seeing that's different from what you expect?

**Comment by writeee** [comment]
@chrisvfritz  Thanks so much. 
The menu icon at left top does not 
respond my clicks (phones), it works fine days ago.

So sorry for wasting your time, I will try to use some dev tools for debuging later and back with useful messages.
