### ISSUE TITLE
Difficulties in understanding vue inner workings

### ISSUE THREAD

**Issue by thewhitetulip** [vuejs/vuejs.org#565]
Note: this might sound arrogant, but this is a real issue, don't mean to to arrogant!

I have 0 experience in front end dev. There are a host of issues I have for getting started with Vue, despite the detailed and otherwise wonderful docs. I think Vue should have a "tutorial" like the Python tutorial, if you guys are busy to write it, I'll write it (on the lines of this https://github.com/thewhitetulip/web-dev-golang-anti-textbook/), I want a document which teaches vue.js with example. It is one thing to tell `how to bind a JS variable to a <p>` and how to use vue in general and how it works.

The docs just skip the essential "getting started with vue" part and go ahead teaching the basics, there are 0 docs about how to set up & explain the setup, the docs have the `npm install` thing, but npm is like magic to me, don't understand a thing about it. I would like to know what that npm does, or what the vue cli does, how things work, I read the docs for three days and yet I can't understand _how_ vue works, do I import it? do I have it in a `<script>` tag? how do things work?

How exactly is the project run? what if I do not want to have a JS based server? how do I do that in vue? (I think this is an advanced topic, but since the docs don't tell about how to get started, it is difficult for newbies to front end dev like me to understand how to use vue and get started with the front end world which is full of js frameworks)

**Comment by writeee** [comment]
<script> works.
"Simply download and include with a script tag. Vue will be registered as a global variable." (http://vuejs.org/guide/installation.html)

You can write your vue code inside another script tag (or include).

-----

Npm is a tool for managing packages, docs: https://docs.npmjs.com

**Comment by writeee** [comment]
Script tag example:
```
<body>
  <script src="vue.js"></script>
  <div id="app">
    {{ message }}
  </div>
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue!'
      }
    })
  </script>
</body>
```


Npm is needed if you want to build more complex web (front-end) apps.
See https://docs.npmjs.com/

And this: https://github.com/lukehoban/es6features
(How the "import" works in JavaScript.)

Then: https://github.com/vuejs/vuex

More: http://webpack.github.io/

**Comment by thewhitetulip** [comment]
@writeee This might suffice if I go ahead and dive deep into the things, but don't you think we need a chapter to explain this in the bare minimum essentials in the docs itself?

You linked to the TODOmvc project, it doesn't have a  `<script>` tag where vue.js is placed as src

**Comment by writeee** [comment]
@thewhitetulip 

About the error, try delete the "var app =", should be like this:
```
<body>
  <script src="vue.js"></script>
  <div id="app">
    {{ message }}
  </div>
  <script>
    new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue!'
      }
    })
  </script>
</body>
```

TODOmvc? Do you mean the vuex?
uh......It needs more understandings of ES6, npm and a little basics of webpack.

And I commented earlier because I was confused, too.
I thought maybe helpful someway.

For the dosc thing, I don't know, not a contributor......

**Comment by chrisvfritz** [comment]
@thewhitetulip Thanks for bringing this to our attention and sorry to hear you've been having issues getting set up with Vue. We try to help people get set up in the [Getting Started section](http://vuejs.org/guide/index.html#Getting-Started) of the Introduction. What do you think went wrong in your case? Did you try the fiddle and it didn't work or some part of it didn't make sense to you?

**Comment by yyx990803** [comment]
The installation page states:

> Simply download and include with a script tag. Vue will be registered as a global variable.

The most basic working example is linked right at the beginning of the Introduction: https://jsfiddle.net/chrisvfritz/50wL7mdz/

**Comment by thewhitetulip** [comment]
That example is abstract! We need an example which we can download via npm and make changes to it and figure out what's up with the code. Jsfiddle is not helpful because it excludes most important aspects of npm and the backend setting up process it is just like an interpreter session and we are left wondering how to trigger the interpreter

**Comment by thewhitetulip** [comment]
> We try to help people get set up in the Getting Started section of the Introduction. 

This is what the intro tells me:

```
# install vue-cli
$ npm install --global vue-cli
# create a new project using the "webpack" template
$ vue init webpack my-project
# install dependencies and go!
$ cd my-project
$ npm install
$ npm run dev
```

What it does not tell me is, what happens after I run each command, what does `npm run dev`  mean, what does webpack mean, what folders are created after the init, what is the significance of the files/folders

>What do you think went wrong in your case? 

I started off reading the docs for almost a week to get a hang of vue, I understood few concepts and the syntax is clean. but the problem starts when I have to `run` any example. The only live example is on jsfiddle. A jsfiddle example isn't that great, we need some example which we can download and install(and edit) on our local machines. This is because I still don't understand how to use vuejs, I know the syntax but no clue about how to realistically use it in building an app. from jquery I know that jquery is to be included in `<script>` tag but there is no documentation where that is explained.


>Did you try the fiddle and it didn't work or some part of it didn't make sense to you?

I wasn't able to get a sample vue project working, I cloned it and it worked, but when I edited it, it said `app declared but not used` and then the docs had taught me nothing related to that, so I wasn't able to figure that out, hence I came to raise this issue!

**Comment by simplesmiler** [comment]
@thewhitetulip give a look to ["The Majesty of Vue.js 2"](https://leanpub.com/vuejs2), it appears to provide the kind of content you desire. Also feel free to ask questions on our [chat](https://gitter.im/vuejs/vue) and [forum](https://forum.vuejs.org/).

**Comment by thewhitetulip** [comment]
@simplesmiler I'll take a look, but don't you think that content like that should be a part of the docs? I know Angular has a nice getting started page where they explain the nuts and bolts starting with the import statements

**Comment by simplesmiler** [comment]
@thewhitetulip maybe "Installation" page could use more love, but I don't think it is Vue's job to explain what npm and webpack are and how do they work, especially that they are not necessary to get you started.

**Comment by LinusBorg** [comment]
It would be a bit repetitive if every frontend framework explained Javascript modules and all that stuff, even though those things are not specific to the framework at all. That would be a huge wast eof resources to duplicate these explanations in every framework's documentation.

Angular2 might have to provide this because 1. they use typescript and 2. you can't even really use Angular without such a setup.

**Comment by thewhitetulip** [comment]
@linusborg I am sorry if I was not clear about my question. I do not want the npm details! I understand npm. My concern is about an easy way to getting started with vue.

When I said nuts and bolts I didn't mean that I expect basics of JS! I want to understand in the docs something like this.

vue init webpack

This initates a blank project. Go ahead and run npm dev run; it starts a server

Now edot the src/main.js and read it. The first linr is the import which'll define the namespace for Vue. We will use that class.

This is the template in index.html, we include vue.js etc
I don't want a jsfiddle example, I want to download and edit that example offline.

**Comment by thewhitetulip** [comment]
@smilesimpler the book is costly, minimum is 24$. I think that the non should really be free to download considering it give a considerable boost for newbies who want to run away from angular.

**Comment by LinusBorg** [comment]
So essentially your only problem is that this section should be a bit more verbose?

**https://vuejs.org/guide/installation.html#CLI**

**Comment by chrisvfritz** [comment]
@thewhitetulip I think you may be making things more complicated than they need to be, possibly stemming from an assumption that for a real use case, Vue has to be "installed" somehow. This isn't true. You don't need vue-cli, NPM, or Webpack. These are only for an advanced workflow. Vue can just be included in a script tag, like jQuery - as is pointed out on the installation page. There's no magic hidden behind the JSFiddle examples.

If you want do download and edit an example offline, I'd start with `vue init simple my-project`, rather than going straight to the `webpack` template.

**Comment by yyx990803** [comment]
There is absolutely no need for npm/webpack/vue-cli to "get started" with Vue, in fact, none of the examples in the entire guide requires any of that. "The way to start with Vue" is exactly what is demonstrated in the linked jsfiddle - you can literally just copy and paste that fiddle into an HTML file with `<script>` and `<style>` tags and get it working. So your complaint that "jsfiddle is not helpful" seems to be a misunderstanding of how it works.

Vue docs are written with the assumption that the user has basic experience in frontend development. It is not our responsibility to thoroughly explain and teach the entire modern frontend development stack. We **do** briefly introduce npm/webpack/build systems in the [later section of the guide](https://vuejs.org/guide/single-file-components.html), but it is the users' own responsiblity to familiarize themselves with these additional technologies (they have their own docs for a reason).

@chrisvfritz What we can probably do is more explicitly suggesting a proper learning path for absolute beginners at the start of the guide. ("Don't start with vue-cli, copy and paste this HTML and follow the guide...")

**Comment by chrisvfritz** [comment]
@yyx990803 Sounds good.

**Comment by thewhitetulip** [comment]
>If you want to download and edit an example offline, I'd start with vue init simple my-project, rather than going straight to the webpack template. This will just generate an index.html file for you

@chrisvfritz Bingo.

had no way of knowing that from the docs!!

>So your complaint that "jsfiddle is not helpful" seems to be a misunderstanding of how it works.
@yyx990803 

Yep that'sliterally the title of this issue :-D, difficulties in understanding vue fundamentals from the docs.

>Vue docs are written with the assumption that the user has basic experience in frontend development

I do not know about that, I heard of vue because of Gitlab and the first thing I heard was the documentation, that vue has excellent docs. Now, the thing is, when a newbie(to frontend) like me is going to start front end dev, it'd be like React vs angular vs what not vs vue. from HN we hear that Vue has excellent docs and we start reading the docs and there is nothing in the docs which explains getting started, yes the jsfiddle is fine, but how'd I get started with building an app out of vue? From the installation page I felt that the vue init webpack was the _only_ way to use vue and I was confused because of that.

>There is absolutely no need for npm/webpack/vue-cli to "get started" with Vue, in fact, none of the examples in the entire guide requires any of that. 

And neither does the guide explain that include vue.js in the `<script>` tag

@LinusBorg 

I do understand the lack of resources, if you want me to do that I'll be happy to contribute, we can create a new repo under vuejs if you want

**Comment by yyx990803** [comment]
> Now, the thing is, when a newbie(to frontend) like me is going to start front end dev, it'd be like React vs angular vs what not vs vue.

I think that's exactly what is causing your frustration. Jumping directly into a framework is definitely the wrong way to start learning frontend stuff. You should start with the basics, understand how HTML, CSS and JavaScript work together **without** a framework before attempting other things.

The claim about "excellent docs" is also based on the assumption of prior frontend experience. The doc is about explaining Vue itself, not about frontend development in general.

**Comment by thewhitetulip** [comment]
>Simply download and include with a script tag. Vue will be registered as a global variable.

I think it'd be great if we have an example, a very small one for this. I am not blaming anyone, my apologies if I was sounding like that!

I'll get started with the download and let you know. I just want to clear a doubt, if I write a tutorial, would you be interested in hosting it as a part of the official repository?

**Comment by thewhitetulip** [comment]
Take a look at this guys https://news.ycombinator.com/item?id=12882816

This is the reason the vue book should be a part of documentation! This guy to, is facing issues getting started. Not blaming, just pointing out :) 
I'm happy to see that commits are being made!

**Comment by thewhitetulip** [comment]
https://scotch.io/tutorials/build-a-single-page-time-tracking-app-with-vue-js-introduction

This seems like a true resolution of this issue, I wonder how come nothing in the docs point to these wonderful tutorials. @yyx990803
