### ISSUE TITLE
Is Modal example oudated?

### ISSUE THREAD

**Issue by randohinn** [vuejs/vuejs.org#566]
It seems like the modal example, located at https://vuejs.org/examples/modal.html is outdated for 2.0 or just broken. I could not find a way to make the close event work as is, and had to resort to setting the `showModal` to false in the button click.

**Comment by chrisvfritz** [comment]
It didn't close when you pressed the `OK` button?

**Comment by randohinn** [comment]
yup

**Comment by chrisvfritz** [comment]
Could you share more information please? For example, what browser and operating system are you using? Are you seeing errors on the JavaScript console?

**Comment by LinusBorg** [comment]
PS: Works fine here on Chrome, FF & IE 11

**Comment by chrisvfritz** [comment]
Closing due to lack of response.
