### ISSUE TITLE
Nested version search index problem

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vuejs.org#575]
@maxiloc sorry to bother again, but as we are planning to merge multiple major versions of the docs under one domain (from `vuejs.org`+`v1.vuejs.org` to `vuejs.org/v2` and `vuejs.org/v1`), we realized that Algalia may end up including both versions under the same index, and the search results can be confusing.

Basically, our question is - is it possible to make one index only crawl pages under `vuejs.org/v1`, while the other `vuejs.org/v2`?

**Comment by maxiloc** [comment]
Yes we do have a multi version capabilities. I updated the `vuejs` config to prepare for multiversion
(https://github.com/algolia/docsearch-configs/commit/4b816ab9660c818ecb23bea97870cd0d58dcf52a)

You just need to update the snippet

```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '85cc3221c9f23bfbaa4e3913dd7625ea',
  indexName: 'vuejs',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["version:$VERSION"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

$VERSION being `v2`.

When you'll have v1  ready, we'll add it to the config. And you can change the $VERSION to `v1` for the v1 part of the website

Does that makes sense ?

**Comment by yyx990803** [comment]
@maxiloc awesome, thanks again!

**Comment by kazupon** [comment]
@maxiloc 
Does this support for japanese translation?

**Comment by maxiloc** [comment]
Yes we can support it as well but right now http://jp.vuejs.org/v2/api/ does not exist so I can not move it to the new config.

**Comment by kazupon** [comment]
@maxiloc 
thanks!
I don't deploy the latest version (2.0 japanese translation) yet.
already, I have been set the new configration.
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja-2.0/themes/vue/layout/layout.ejs#L78-L84

Are we ok with new configration?

**Comment by maxiloc** [comment]
Yes as soon as you deploy ping me and I'll update the config

**Comment by kazupon** [comment]
@maxiloc thanks!

**Comment by kazupon** [comment]
@maxiloc 
deploy done.

search configuration is the following:

- configration for v2 japanese translation
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/themes/vue/layout/layout.ejs#L78-L84

- configration for v1 japanese translation
https://github.com/vuejs/v1-jp.vuejs.org/blob/master/themes/vue/source/js/common.js#L20-L25

**Comment by maxiloc** [comment]
Ok it's deployed on our side. You just need to update the v1 by this one:

```
 docsearch({
            apiKey: '0a75952972806d9ad07e387d08e9cc4c',
            indexName: 'vuejs_jp',
            inputSelector: selector,
            algoliaOptions: { facetFilters: ["version:v1"] }
          })
```

**Comment by kazupon** [comment]
@maxiloc 
thanks quick reply!
I' fixed configuration.
https://github.com/vuejs/v1-jp.vuejs.org/commit/267b40f9cdddd6846798f089f908f3b4daee1134

**Comment by kazupon** [comment]
@maxiloc 
I think that algolia docsearch does not indexed for vuejs japanese translation.
I checked docsearch config of vuejs_jp.
https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs_jp.json#L21-L37

It's is not  `"url": "http://(?P<version>.*?).vuejs.org/guide/"`, but  `"url": "http://(?P<version>.*?)-jp.vuejs.org/guide/"`, Isn't it?

**Comment by maxiloc** [comment]
@kazupon My bad, it should be fixed now

**Comment by kazupon** [comment]
@maxiloc Thank you very much! 😺

**Comment by gbezyuk** [comment]
@maxiloc, @yyx990803 — could you please give me a hint on how to update Algolia config for Russian translation? Comparing Japanese and English versions I've realized I need to provide different `apiKey` and `indexName`, but I don't seem to understand where could I get 'em.

**Comment by maxiloc** [comment]
I need to configure it. What is the url ?

**Comment by gbezyuk** [comment]
https://ru.vuejs.org/

**Comment by maxiloc** [comment]
Here you go:
index_name: vuejs_ru
api_key: c6f9366f6f7fe057ee3e01747b603d9f

**Comment by gbezyuk** [comment]
@maxiloc awesome! Thank you!

**Comment by chrisvfritz** [comment]
I believe this is all resolved now, so closing. 🙂
