### ISSUE TITLE
in 2.0 `el` can not be used in `Vue.extend`

### ISSUE THREAD

**Issue by gebilaoxiong** [vuejs/vuejs.org#578]
There is a small problem...

The document does not specify that `el` can not be used in `Vue.extend`

[source code](https://github.com/vuejs/vue/blob/dev/src/core/util/options.js#L28)

[Vue.extend:document](https://github.com/vuejs/vuejs.org/blob/master/src/v2/api/index.md#vueextend-options-)

Can I submit a pr？

**Comment by yyx990803** [comment]
See http://vuejs.org/v2/api/#el

**Comment by gebilaoxiong** [comment]
Well, here I only see the data prompt.
