### ISSUE TITLE
Clicking above headline scrolls to headline

### ISSUE THREAD

**Issue by dpschen** [vuejs/vuejs.org#584]
While reading documentation I sometimes mark important words for me with the cursor.
If I try to mark some words in the last line before a headline I always click on the invisible anchor of that headline.

Why does the anchor of the headlines overlap the last line of previous text?
Is this the intended behaviour?

The problem is [here](https://github.com/vuejs/vuejs.org/blob/36772a7b7c0bb93350245900a3c782a463a00c4e/themes/vue/source/css/page.styl#L48)

**Comment by chrisvfritz** [comment]
It's intended that those anchors overlap, so that hash scrolling still works with the sticky header. The previous text should be the top layer though. Can you share more about the OS and browser you're seeing this on?

**Comment by dpschen** [comment]
Ok. I see. OS is macOS Sierra and browser Chrome 54.0.2840.98.
But I saw this issue on Firefox and Safari as well.

Maybe it's just me. But I think marking text while reading it is a common behavior.
It's somehow like reading with the finger under the current line.

As you said the text is indeed the top layer. But if I start marking from below (e.g. [here](https://vuejs.org/v2/guide/#What-is-Vue-js) from under the link "Comparison with Other Frameworks" in the last line) I click on the link and intentionally the content jumps.

I really wouldn't bother, but it happens to me all the time.
I have a similar issue while reading articles on [medium.com](https://medium.com/) where I mark the text and click on the share popup sometimes. But the click area for the share links there is compared to the text anchors in the docs very small so a not intended click doesn't happen so often.

**Comment by chrisvfritz** [comment]
@dpschen OK, I've kept this in the back of my mind and just deployed a tiny hack that should add a bottom margin to paragraphs and lists, making them easier to select. Would love to hear how it helps!

**Comment by dpschen** [comment]
Awesome works! =) thx
