### ISSUE TITLE
Explain Usage of the special "key" attribute outside of v-for more throughly.

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vuejs.org#587]
While the docs state that the use of `key` is not limited to the context of `v-for`, it is never prominently explained what those other usecases really are (except briefly  in the Advanced Section about Transitioning Components).

Issues like vuejs/vue#4216 and questions on the forum show that people often see "strange" behaviour where all that's missing is a `key` to keep Vue from re-using an element where it shouldn't.

So we need to find a good place (or maybe multiple places) to explain this more thoroughly.

**Comment by yyx990803** [comment]
@LinusBorg do you have links to forum posts that have to do with this? Would like to see a few to help pick example code to use.

**Comment by LinusBorg** [comment]
Will have to look for some, don't have them bookmarked I think.

**Comment by LinusBorg** [comment]
This one, for example:

https://forum.vuejs.org/t/vnodes-produced-by-createelement-in-render-function-shares-same-data-object/3013

Will post more (older ones) when I find them.

**Comment by chrisvfritz** [comment]
@LinusBorg I'll close this for now, in the hope that this change resolves the confusion. If you find that we still need to include info in more parts of the guide, please don't hesitate to open another issue. 🙂

**Comment by LinusBorg** [comment]
@chrisvfritz Yeah that's ok. I will come back to this if I find additional pain points from my experience on the forum etc.
