### ISSUE TITLE
Migrate to hexo 3.0？

### ISSUE THREAD

**Issue by hanfeisun** [vuejs/vuejs.org#59]
I found hexo 3.0 is not compatible with hexo 2.x..

 https://github.com/hexojs/hexo/wiki/Migrating-from-2.x-to-3.0

The new version use `npm install hexo-cli -g` instead of `npm install hexo -g` for installation.

I was wondering whether this site is planning to migrate to hexo 3.0. If so, maybe there is something I could help..

**Comment by yyx990803** [comment]
Done :)
