### ISSUE TITLE
API documentation index missing

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vuejs.org#595]
The index on the left side of the API documentation is missing. Is this intentional?

https://vuejs.org/v2/api/

Viewing in Safari 9.1.3.

**Comment by davidkhess** [comment]
Seeing this error in the console.

> [Error] SyntaxError: Unexpected identifier 'i'. Expected either 'in' or 'of' in enumeration syntax.
> 	(anonymous function) (common.js:61)

**Comment by yyx990803** [comment]
Should be fixed now!

**Comment by davidkhess** [comment]
Looks good - thanks!
