### ISSUE TITLE
No documentation about optional script tag in .vue file

### ISSUE THREAD

**Issue by e-cloud** [vuejs/vuejs.org#609]
New to Vue.js.

When I try to figure out the structure of vue-hacker-news-2.0, I find out there is no script inside `App.vue`. However, `App.vue` is imported in `app.js`. I search through the official website and the [vue component spec](http://vue-loader.vuejs.org/en/start/spec.html). Neither of them contains documentation of that behavior.

It prevents newbies to gain deeper understanding with the official demo.

**Comment by e-cloud** [comment]
And, there is no document showing:
```
import App from './App.vue'
```
What is the `App` imported? Although i could guess it might be the export of the script inside `.vue`.

It's confusing when script is missing.

**Comment by yyx990803** [comment]
The spec says:

> vue-loader will parse the file, extract each language block, pipe them through other loaders if necessary, and finally assemble them back into a CommonJS module whose `module.exports` is a Vue.js component options object.

That what you get from `import App from './App.vue'`.

The spec also says:

> Each *.vue file can contain at most one <script> block at a time.

"at most one" means it's optional. When there is no `<script>` tag, a plain object will be created for you.

**Comment by e-cloud** [comment]
Sorry for my less careful. But

> a plain object will be created for you.

is implicit.

And it's still a bit less direct for `at most one`, IMHO.
