### ISSUE TITLE
Document using vue-server-renderer in detail

### ISSUE THREAD

**Issue by defcc** [vuejs/vuejs.org#615]
ref: https://github.com/vuejs/vue/issues/4331

Maybe we need more explanation on SSR,  like best practice with vue-router.

**Comment by chrisvfritz** [comment]
Yeah, this is definitely something we need to do. I've updated the title of [this issue](https://github.com/vuejs/vuejs.org/issues/406) to be slightly more encompassing, as I think we'll want to cover both routing and SEO together.
