### ISSUE TITLE
typo in vuejs.org/src/v2/guide/class-and-style.md

### ISSUE THREAD

**Issue by freenice12** [vuejs/vuejs.org#623]
``` html
<div class="static"
     v-bind:class="{ active: isActive, 'text-danger': hasError }">
</div>
```
is 'text-danger' right?
I think remove `'` it.

**Comment by simplesmiler** [comment]
JavaScript identifiers (and thus literal property names) can not contain dashes, so to make a property name with dashes (e.g. `text-danger`) you have to wrap it in quotes.
