### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by KingMario** [vuejs/vuejs.org#629]
*another key code* in [Render Functions](http://vuejs.org/v2/guide/render-function.html#Event-amp-Key-Modifiers) page has a 404 status. And I have no idea how to correct it.

Should it be *events.html#Key-Modifiers*?

**Comment by chrisvfritz** [comment]
Hmm, it _seems_ to be working for me. When I click on the link, it takes me to the correct page and section. `curl` also returns `200 OK`. Could you try again? It may have just been a temporary issue as GitHub Pages was transitioning to the new content.

**Comment by KingMario** [comment]
What I'm talking about is the link `[another key code](keycode.info)`. Seems that `http://vuejs.org/v2/guide/keycode.info` is not in the site.

**Comment by chrisvfritz** [comment]
Got it! Thanks for the clarification. Just fixed it. 😃
