### ISSUE TITLE
Translations maintenance

### ISSUE THREAD

**Issue by andreipfeiffer** [vuejs/vuejs.org#639]
Hey guys,

I was wondering what is the process of updating the docs translations?
Let's say you have translations in N languages, and you need to update (add/edit) something in the "original (english)" docs. How would the translation maintainers get notified of this, and how would they know what exactly was updated (added/edited)?

I would like to contribute with the Romanian translation, but before that, I would like to know the long-term process.

Thanks in advance,
Andrei

**Comment by chrisvfritz** [comment]
I would probably look at the maintainers of other translations and ping them here.

**Comment by andreipfeiffer** [comment]
I'm asking this because I'm maintaining the Babel + Babel plugin Romanian translations for almost 1 year. They use Crowdin to manage them, which is very handy.

Without a service like Crowdin, you would have to manually notify the translators about updates. That's easy.

The difficult part (as far as I see it) is for the translators to spot the "diff" (additions/edits/deletions). Crowdin makes this very easy to deal with. I'm just curious how do you currently handle this. Would they have to do through each individual commit (since their last revision) to spot the diffs?

**Comment by gbezyuk** [comment]
With Russian translation we currently simply merge upstream and compare changes.

**Comment by kazupon** [comment]
In Japanese translation, simply, we check upstream(vuejs/vuejs.org) commit histories, and if there is diff, we  are pick up it, translation.

**Comment by andreipfeiffer** [comment]
Got it. Thanks guys.

**Comment by chrisvfritz** [comment]
I'll close this for now, as it seems the conversation has resolved. 🙂
