### ISSUE TITLE
Header Translation Links

### ISSUE THREAD

**Issue by gbezyuk** [vuejs/vuejs.org#640]
Hi there. I think there is a need to unify the approach to language selection dropdown in site header. Currently Japanese version offers Japanese names of languages (which makes it literally impossible for a random non-Japanese speaker to find his way to English or other version), Chinese doesn't seem to offer any link at all, while Russian spells the very "Translations" menu element in English. That being said, I guess we should find some universal solution and apply it to all translation sites in order to achieve cross-language uniformity.

I propose to:
- use both current document's language and English spellings of the word "Translations" for the caption
- use both endonym and current document's language name versions

So it will be like that for Japanese:

Translations (言語)
- English (英語)
- 普通话 (中文)
- Русский (ロシア語)

**Comment by chrisvfritz** [comment]
Before investing too much energy into this, are we sure it would be solving a real problem? Are there currently users finding themselves in Japanese/Chinese/Russian translations without understanding the language?

**Comment by gbezyuk** [comment]
People can survive without it, it's for sure. But there's not just bread but also beauty in this world, right?

Also, I don't see if it really requires too much time or energy. Just approve the approach, so I'll spend another 15 minutes on actual PRs, and it's pretty much done.

**Comment by kazupon** [comment]
I think there is not especially a need to unify the approach to language selection dropdown in site header. In translation for japanese users, the reason why not "translations (翻訳)" but "languages (言語)", it easily understand as japanese users.

**Comment by gbezyuk** [comment]
"Translations" vs. "Languages" isn't important. "I can't read Japanese" vs. "I can't read Japanese, but there's some English" is.

**Comment by chrisvfritz** [comment]
I can understand the desire and I appreciate you bringing it up, but I'm OK with translation maintainers making different decisions here. There may even be reasons to maintain different styles for different cultures. Since it sounds like users are not negatively affected by the differences, I think I just have to veto this.
