### ISSUE TITLE
2.0 docs: Source links not pointing to actual source

### ISSUE THREAD

**Issue by bdno86** [vuejs/vuejs.org#643]
In many cases the source links don't actually point to the source of the described functionality, but to a search query on github that only rarely points to the relevant code.

It would be very helpful for learners who want to study the code behind functionality to be able to quickly access the source without having to search manually.

**Comment by chrisvfritz** [comment]
I'd be open to a PR with a better solution, but I'd like to keep these links automatically generated somehow, as I fear it would slow down Vue development having to manually update line numbers whenever making a change to a file. Do you have any ideas?

**Comment by GuiDevloper** [comment]
I didn't exactly understand this one.
What is the "source links" pointed?

If it's docs sources, the links are currently auto-generated.
Being source code links, never seen one in docs.

**Comment by phanan** [comment]
Actually, I was about to close this due to inactivity.
