### ISSUE TITLE
ko.vuejs.org - Korean Translation

### ISSUE THREAD

**Issue by kciter** [vuejs/vuejs.org#648]
[current fork here](https://github.com/kciter/ko.vuejs.org)

We have just started so the amount of translation is small. We are going to continue. :)

## Team
@kciter
@mastrayer
@mgcation

More contributors are welcome!

### Website
- [x] Entry Page
- [ ] Other Layout Elements

#### Essentials
- [ ] Installation
- [ ] Introduction
- [ ] The Vue Instance
- [ ] Template Syntax
- [ ] Computed Properties and Watchers
- [ ] Class and Style Bindings
- [ ] Conditional Rendering
- [ ] List Rendering
- [ ] Event Handling
- [ ] Form Input Bindings
- [ ] Components

#### Advanced
- [ ] Reactivity in Depth
- [ ] Transition Effects
- [ ] Transitioning State
- [ ] Render Functions
- [ ] Custom Directives
- [ ] Mixins
- [ ] Plugins
- [ ] Single File Components
- [ ] Deploying For Production
- [ ] Routing
- [ ] State Management
- [ ] Unit Testing
- [ ] Server-Side Rendering

#### Migrating
- [ ] Migration from Vue 1.x translation in progress by @gbezyuk
- [ ] Migration from Vue Router 0.7.x
- [ ] Migration from Vuex 0.6.x to 1.0

#### Meta
- [ ] Comparison with Other Frameworks
- [ ] Join the Vue.js Community!

#### API
- [ ] Global Config
- [ ] Global API
- [ ] Options / Data
- [ ] Options / DOM
- [ ] Options / Lifecycle Hooks
- [ ] Options / Misc
- [ ] Instance Properties
- [ ] Instance Methods / Data
- [ ] Instance Methods / Events
- [ ] Instance Methods / Lifecycle
- [ ] Directives
- [ ] Special Attributes
- [ ] Built-In Components
- [ ] VNode Interface
- [ ] Server-Side Rendering

#### Examples
- [ ] Markdown Editor
- [ ] GitHub Commits
- [ ] Firebase + Validation
- [ ] Grid Component
- [ ] Tree View
- [ ] SVG Graph
- [ ] Modal Component
- [ ] Elastic Header
- [ ] Wrapper Component
- [ ] TodoMVC
- [ ] HackerNews Clone
- [ ] Markdown Editor

**Comment by kciter** [comment]
Oh, It is duplicated.
https://github.com/ChangJoo-Park/vuejs.org
This issue is closed. Sorry

**Comment by ChangJoo-Park** [comment]
@kciter 안녕하세요 
[저장소](https://github.com/ChangJoo-Park/vuejs.org)에서  보시다가 문제가 있는 부분은 언제든지 PR 해주세요

**Comment by kciter** [comment]
@ChangJoo-Park 안녕하세요 :)
몇달 전부터 관심있게 보다가 이번에 회사 프로젝트에 적용하면서 번역 자료가 없었던걸 아쉬워했는데 친구와 작업하기 위해서 오늘 올리고보니 이미 있었더라구요 ^^;; 앞으로 공부하면서 자주 이용하겠습니다. 좋은 번역 감사합니다 :)
