### ISSUE TITLE
Text size, weight and contrast ratio

### ISSUE THREAD

**Issue by alligatorio** [vuejs/vuejs.org#660]
I'm finding the text on vuejs.org very hard on the eyes, and wondering if others have that issue too.

The combination of small text size, very thin font and low contrast ratio make it hard to read even if I increase the font size.

I hope it's appropriate to classify this as a potential issue.

**Comment by chrisvfritz** [comment]
This is definitely something that's appropriate to bring up here! We care deeply about the readability of the docs and at least in Chrome on macOS, the site does meet AAA accessibility standards for text size and exceeds them for contrast ratio.

Can you share more about the browser and OS you're using? It sounds like something may be going wrong with the combination you're on. Or sometimes browser extensions can change the styles on some pages in undesirable ways.

**Comment by alligatorio** [comment]
Thanks so much @chrisvfritz! You're absolutely right. Something prevented Source Sans Pro from properly loading and the second font in the stack was being used instead (Helvetica Neue, a very thin font).

I've now installed Source Sans Pro locally on my machine and everything is looking much better. Weird that Source Sans wasn't loaded properly, maybe something going on with my Chrome setup.

**Comment by chrisvfritz** [comment]
Glad to hear it! We'll keep an ear out for others with this problem.
