### ISSUE TITLE
algolia docsearch for kr.vuejs.org

### ISSUE THREAD

**Issue by kciter** [vuejs/vuejs.org#661]
Hello, I'm Korean vuejs user. 😄
Recently, very helpful to me the Korean translation site has been created by @ChangJoo-Park.
Can we support docsearch to [the Korean translation site](https://kr.vuejs.org)?
Here [Korean repo](https://github.com/vuejs-kr/kr.vuejs.org).

Regards,

**Comment by ChangJoo-Park** [comment]
+1

**Comment by chrisvfritz** [comment]
When you get a chance @maxiloc, we'll need a config for one more translation here. Our community's been busy!

**Comment by kazupon** [comment]
ref: https://github.com/vuejs/vuejs.org/issues/575

**Comment by maxiloc** [comment]
Sure, here you go:
indexName: vuejs_kr
apiKey: 6d4ed4990adfc74c08d2f69f21c000d6

**Comment by ChangJoo-Park** [comment]
Thanks everyone! kr.vuejs.org got algolia docsearch!  

https://github.com/vuejs-kr/kr.vuejs.org/blob/master/themes/vue/layout/layout.ejs#L80
