### ISSUE TITLE
More information about list render 

### ISSUE THREAD

**Issue by defcc** [vuejs/vuejs.org#665]
refer: https://github.com/vuejs/vue/issues/4512

1. v-for has higher priority
2. additional note with v-for and v-if api

**Comment by ChangJoo-Park** [comment]
**2. additional note with v-for and v-if api** +1

**Comment by ChangJoo-Park** [comment]
Add this to [Korean docs](https://kr.vuejs.org/v2/guide/list.html#v-for와-v-if)
