### ISSUE TITLE
Clarify "no doubt" reference in "The Vue Instance"

### ISSUE THREAD

**Issue by jkshapiro** [vuejs/vuejs.org#666]
In the page https://vuejs.org/v2/guide/instance.html, the following statement is made:

> Although not strictly associated with the MVVM pattern, Vue’s design was no doubt inspired by it.

This is confusing, since it's in the official Vue.js documentation: was Vue's design inspired by MVVM or wasn't it?

We should either remove "no doubt" or remove the entire statement, as appropriate.

**Comment by LinusBorg** [comment]
I don't find this confusing at all: Even though it does not fully follow MVVM, it was, without a doubt, inspired by it.

Yes, the "doubt" part is not nessessary, but a common figure of speech, isn't it?

**Comment by jkshapiro** [comment]
Yes it's a common figure of speech, when used by a third-party observer. If two people see a chicken crossing a road, one might ask the other why, and the first might answer "no doubt to get to the other side". However, if they asked the chicken instead, she would be able to tell them definitively. Assuming the observers spoke the language of chickens of course.

In this context, on the official Vue.js website, we are expecting definitive answers. Was Vue.js inspired by MVVM? Well, the programmers who created it will know. It either was or it wasn't; we do not need to surmise.

**Comment by chrisvfritz** [comment]
Just updated the wording there.

**Comment by hax** [comment]
It seems current document does not discuss any difference with Vue and "real MVVM", so it's still confusing to say "not strictly associated with the MVVM pattern".
