### ISSUE TITLE
Older link under download button

### ISSUE THREAD

**Issue by in-in** [vuejs/vuejs.org#675]
On the page is downloaded older version (2.1.6) of Vue
https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/installation.md
![a0c52](https://cloud.githubusercontent.com/assets/8797432/21550312/bfd9f826-ce09-11e6-992f-7928035637fb.png)

**Comment by chrisvfritz** [comment]
Just updated! Thanks.
