### ISSUE TITLE
How to test component

### ISSUE THREAD

**Issue by pavel123123** [vuejs/vuejs.org#68]
Hi 
I don't understand one moment in your example for testing http://vuejs.org/guide/application.html#Unit_Testing

//----------------return only object 
var myComponent = require('../src/my-component')
//----------------why the myComponent  contain function "data" ?
expect(typeof myComponent.data).toBe('function')

Thank you for advance.

**Comment by yyx990803** [comment]
My bad, I forgot to update the first snippet! (Fixed now)
