### ISSUE TITLE
multiple select appears abnormal in mobile

### ISSUE THREAD

**Issue by STayinloves** [vuejs/vuejs.org#683]
Multiple select example in this [page](https://vuejs.org/v2/guide/forms.html) appears abnormal when I use chrome or safari on my iOS device.
When you touch the drop down button, it will automatic toggle the first item(A).
I don't know whether it's the WebKit's bug.

**Comment by chrisvfritz** [comment]
This is indeed [a bug on iOS](http://stackoverflow.com/questions/34660500/mobile-safari-multi-select-bug). There are some hacky work-arounds, but I'd rather complicate the examples with them. Hopefully, they'll fix the bug soon.
