### ISSUE TITLE
《对比其他框架》页面的几处小错误

### ISSUE THREAD

**Issue by grandsong** [vuejs/vuejs.org#686]
https://cn.vuejs.org/v2/guide/comparison.html

### “表现在开发中仍然很重要,因为它是与开发相关经验”
之后显然应该还有话吧。
另外，逗号应为中文全角的。

### “这可以让你围绕设计为中心展开工作，,比如您的构建过程中颜色操作”
多了一个西文逗号。

### “如果阅读更多关于不同的设计理念。”
“如果”之后应该有半句话吧。后文也怪怪的，似乎是从英文生硬地翻译成中文。

### “-功能更加强大的路由机制，Riot 的路由功能的 API 是极少的。”
“-”？似乎是markdown的序号“- ”少了空格？
而且，这句话也不是很通顺。

**Comment by chrisvfritz** [comment]
@grandsong Thanks for the comments! Can you post it [here instead](https://github.com/vuejs/cn.vuejs.org)?

**Comment by grandsong** [comment]
OK.

2017-01-07 

GrandSong 



发件人：Chris Fritz <notifications@github.com>
发送时间：2017-01-07 13:33
主题：Re: [vuejs/vuejs.org] 《对比其他框架》页面的几处小错误 (#686)
收件人："vuejs/vuejs.org"<vuejs.org@noreply.github.com>
抄送："GrandSong"<grandsong@163.com>,"Mention"<mention@noreply.github.com>

@grandsong Thanks for the comments! Can you post it here instead?
