### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by tscanlin** [vuejs/vuejs.org#69]
Hey, I'm working on some documentation and I really love the way you've done the navigation with the sidebar on vuejs.org. I also really love the fact that you're using native APIs rather than jquery. Would you mind if I based the navigation I'm building off of yours? Although it would look different and probably work a bit differently too.

**Comment by yyx990803** [comment]
Feel free to do so!

**Comment by tscanlin** [comment]
Thank you! :)
