### ISSUE TITLE
Grid component example: Show "no values" when table is empty ?

### ISSUE THREAD

**Issue by kaihendry** [vuejs/vuejs.org#693]
Suggestion for improvement:

https://jsfiddle.net/kaihendry/xkkbfL3L/361/

Or is there a better suggestion?

**Comment by kazupon** [comment]
Thank you for your commenting!

Grid component is demonstration that using `Component`, `v-for` and `filter`.
In the example, I think that don't need to include about `no values` to make it simple.

**Comment by chrisvfritz** [comment]
Yeah, I agree with @kazupon that this is fine the way it is. All these examples could have more features added to them, but then it would be more difficult to see the _specific features_ being highlighted.
