### ISSUE TITLE
vue1里面的this.$compile 在vue2里面怎么用啊

### ISSUE THREAD

**Issue by fengxiaotx** [vuejs/vuejs.org#699]
vue1里面的this.$compile 在vue2里面怎么用啊

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. 

The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). 

BTW, You can use the `Vue.compile` in Vue 2.x later.

Thanks.
