### ISSUE TITLE
Computed Properties incorrect about "pure" functions

### ISSUE THREAD

**Issue by McNathan321** [vuejs/vuejs.org#710]
The _Computed Properties_ section of the Guide says that "the computed getter function is pure and has no side effects", but that's not true: the example function `reversedMessage()` isn't pure because its return value depends on `this.message` (which is defined outside the function, not passed in as an argument).

**Comment by znck** [comment]
IMO "pure" function as it has no side effects (Which, I guess, is to stress that it should not mutate anything). I know it not 100% true to the definition but (just for our use case) assume all the reactive properties used by a computed function be the parameters of the function, no for a given state of reactive properties, the computed function would produce same output (IMO it makes the computed function almost **pure**).

**Comment by McNathan321** [comment]
A function that depends on program state is [by definition](https://en.wikipedia.org/wiki/Pure_function) not pure. Also, the next part of the sentence I quoted above says that it being pure "makes it easy to test", but of course this isn't true because it's _not_ pure - to test it you have to make sure the state is set correctly, so the function can't be tested in isolation. (Not that that's necessarily a big deal, but it's not as easy to test as a genuinely pure function.)

Note that I'm not saying that it is a bad thing that such functions aren't pure, I'm just saying that we should not call them pure when they aren't.

**Comment by znck** [comment]
/ping @yyx990803 What's your take on this?

**Comment by yyx990803** [comment]
Yeah, I'd say they are not pure by definition. The only thing I actually wanted to emphasize was that users should avoid producing side effects in computed getters. Open to PRs on revising the  sentence.

**Comment by chrisvfritz** [comment]
I just removed the words `is pure and`. I think the message stands without it.
