### ISSUE TITLE
Incorrect Example in "Method Event Handlers"

### ISSUE THREAD

**Issue by KingPixil** [vuejs/vuejs.org#713]
In `example2` in the [Method Event Handlers](https://vuejs.org/v2/guide/events.html#Method-Event-Handlers) portion of the website, it shows an example of calling the method programmatically.

Like this:

```js
// you can invoke methods in JavaScript too
example2.greet() // -> 'Hello Vue.js!'
```

If this is actually run, an error is thrown, because the 'greet' method takes an event object as a parameter, and accesses them to create an alert popup with the contents: `alert(event.target.tagName)`

**Comment by chrisvfritz** [comment]
Thanks! Just fixed this.

**Comment by KingPixil** [comment]
No problem 👍
