### ISSUE TITLE
Transitioning State requestAnimationFrame() usage

### ISSUE THREAD

**Issue by McNathan321** [vuejs/vuejs.org#715]
The [Transitioning State page](https://vuejs.org/v2/guide/transitioning-state.html) has three examples that have an `animate()` function that calls `requestAnimationFrame(animate)` unconditionally, creating an endless animation loop that keeps running even after the tweening is completed. Which means if the user changes the value multiple times there will be multiple parallel `requestAnimationFrame`-based loops running, all continuing to call `TWEEN.update()` even after reaching the target value. The `requestAnimationFrame()` call should be made only if the `TWEEN` process is incomplete. (I'm not familiar with the Tween.js library, so I'm not sure how to test that.)

**Comment by chrisvfritz** [comment]
Good catch!
