### ISSUE TITLE
Docs error in Chrome

### ISSUE THREAD

**Issue by PascalPixel** [vuejs/vuejs.org#716]
```carbon.js?zoneid=1673&serve=C6AILKT&placement=vuejs:1 GET https://fallbacks.carbonads.com/home/e99a260b94849497ea962f674f0aebd9//vuejs/8/ net::ERR_BLOCKED_BY_CLIENT```

I get this in my console on https://vuejs.org/v2/guide/ and the mouse-over demo is not working for me 😓

**Comment by chrisvfritz** [comment]
I don't think the error is related to any problems you're encountering, as it just means you're blocking the very non-intrusive ads we use to fund hosting for free community services, as well as further development to Vue. 😢  Could you add an exception to your adblocker for our docs please?

Depending on your browser, you may need to move your mouse over the text, then keep it still for several seconds (it's a browser feature, not a Vue feature you're having trouble with).

**Comment by PascalPixel** [comment]
You are so right, I disabled my ad blocker and made a donation through Paypal for wasting your time @chrisvfritz. Keep up the hard work.

**Comment by chrisvfritz** [comment]
Wow, thank you @PascalPixel! Have a great day. 😃
