### ISSUE TITLE
Possible bug with dynamic (bind) select multiple.

### ISSUE THREAD

**Issue by 34x** [vuejs/vuejs.org#719]
Hello! First of all thank you for the great framework and your work.

I faced possible issue when tried to use select html tag with binded multiple attribute.
I have example on jsfiddle: https://jsfiddle.net/jqybwngo/

Partially copy bellow:
```
<div id="app">
  <select v-model="option" v-bind:multiple="isMultiple">
    <option value="1">item 1</option>
    <option value="2">item 2</option>
  </select>
</div>
```

And here is the error log from Safari (same for Firefox):
![screen_2017_01_18_19_52_16](https://cloud.githubusercontent.com/assets/60165/22078489/65fddf66-ddb8-11e6-8b5c-28787bf5c3c8.jpg)

```[Error] [Vue warn]: <select multiple v-model="option"> expects an Array value for its binding, but got String 
(found in root instance)
	warn (vue.js:525)
	setSelected (vue.js:5691)
	componentUpdated (vue.js:5672)
	callHook$1 (vue.js:4746)
	(anonymous function) (vue.js:4702)
	patchVnode (vue.js:4461)
	updateChildren (vue.js:4364)
	patchVnode (vue.js:4448)
	patch (vue.js:4572)
	_update (vue.js:2646)
	updateComponent (vue.js:2613)
	get (vue.js:2936)
	run (vue.js:3005)
	flushSchedulerQueue (vue.js:2811)
	(anonymous function) (vue.js:477)
	nextTickHandler (vue.js:426)
	promiseReactionJob
[Error] TypeError: binding.value.some is not a function. (In 'binding.value.some(function (v) { return hasNoMatchingOption(v, el.options); })', 'binding.value.some' is undefined)
componentUpdated — vue.js:5678
callHook$1 — vue.js:4746
https://unpkg.com/vue
patchVnode — vue.js:4461
updateChildren — vue.js:4364
patchVnode — vue.js:4448
patch — vue.js:4572
_update — vue.js:2646
updateComponent — vue.js:2613
get — vue.js:2936
run — vue.js:3005
flushSchedulerQueue — vue.js:2811
https://unpkg.com/vue
nextTickHandler — vue.js:426
promiseReactionJob

	logError (vue.js:439)
	promiseReactionJob
```

Maybe I used bind in a wrong way then please show me the correct way to do this.

**Comment by chrisvfritz** [comment]
Glad you're enjoying Vue! We try to reserve these issues for bugs or requests regarding the documentation, but you can post usage questions to [the official forums](https://forum.vuejs.org/). Can you please post there instead?

**Comment by LinusBorg** [comment]
@chrisvfritz I think this is a bug. The fiddle that OP provided works if you set the `multiple` attribute on the `<select>` statically:

https://jsfiddle.net/Linusborg/jqybwngo/1/

But it throws the error shown above if we bind it dynamically with `v-bind:multiple`:

https://jsfiddle.net/Linusborg/jqybwngo/

**Comment by LinusBorg** [comment]
Oh, Just seeing that we are in the wrong repository...

**Comment by chrisvfritz** [comment]
@34x Now that @LinusBorg has confirmed this as a probable bug, I'd report it on the `vuejs/vue` repo.
