### ISSUE TITLE
Two-ways data-binding on non-form elements?

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [vuejs/vuejs.org#72]
Hey,

Is there any way to initialise data from rendered HTML content instead of the ````$data```` property?

##### Use Case

I have a list of elements rendered from server-side,
And I want to set-up an "external" form to filter it.

    <form id='filter-form' action='#' method='get'>
        <input type='search' name='filter' placeholder='Filter' v-model='query' />
    </form>

    
    <ul id='characters'>
        
        
        <li class='static character'>Marty McFly</li>
        <li class='static character'>Jennifer Parker</li>
        <li class='static character'>Emmet Brown</li>
        <li class='static character'>Biff Tannen</li>
        <li class='static character'>Einstein</li>
    </ul>

    var filtrableList = new Vue({
        el: '#filtrable-list',
        data: {
            characters: [],
            query: ''
        }
    });

##### Workaround

To make it work "as I want", I wait for the list to be loaded, then parse the rendered items, push them to the list, then delete their rendered DOM element...

As in the following: http://jsfiddle.net/FloSchieldBobby/avr8ccus/

    <ul id='characters'>
        <li v-repeat='character: characters | filterBy query' class='rendered character'>{{ character.name }}</li>
        
    </ul>

    var charactersList = document.querySelector('#characters');
    var characters = charactersList.querySelectorAll('.character.static');
    var charactersLength = characters.length;
    var index;

    for (index = 0; index < charactersLength; index++) {
        var character = characters[index];
        
        filtrableList.characters.$set(index, {
            name: character.innerHTML
        });
        
        character.remove();
    }

But it is very hacky (dirty) IMO.

Do you have an idea?

**Comment by yyx990803** [comment]
Why do you render the list from the server in the first place though? Why not just render JSON?
If you have no control over what the server renders, then I think this is the only way to do it.

BTW, please only submit documentation-related issues here. General questions should be posted here: https://github.com/vuejs/Discussion/issues

**Comment by Flo-Schield-Bobby** [comment]
Aps, sorry yeah, didn't notice I was not on the good place. Possible to move it ?!

You would suggest to render a JSON object in a ````<script></script>```` directly, in order to pass data to JS ?
I just dislike this way, I personally find it hacky too...
And I don't really want to build an asynchronous stuff, at this step.

**Comment by yyx990803** [comment]
I don't think rendering to JSON is dirty, it's more like embedding JSON data in your HTML so that it can be sent down to the client within a single request, and is in fact cleaner than initializing data in the vue template.

**Comment by Flo-Schield-Bobby** [comment]
Okay, thanks for your feedback :)
I guess we can close the issue, at this point!

**Comment by azamat-sharapov** [comment]
It's era of rendering things on client side, mate :) I also recommend not doing almost any kind of rendering on server side.

**Comment by Flo-Schield-Bobby** [comment]
Not sure to get what you mean by server-side rendering?
I just do not especially like to expose JSON data globally on client-side, but nvm, I just remove this exposition once the Vue parsed it.

**Comment by azamat-sharapov** [comment]
I meant rendering *HTML* on server side, but just return data like JSON. But yeah, it's everybody's preference.
