### ISSUE TITLE
A issue about integer iteration.

### ISSUE THREAD

**Issue by superhos** [vuejs/vuejs.org#730]
Take a simple example.
`<span v-for="n in Num">{{ n }},</span>`
As above source code. Where Num as a integer value. In this case I set it to 5. 
```
export default {
  name: 'exampleComponent',
  data () {
    return {
      Num: 5
    }
  },
 //...
```
At the first time, the result is correct. 
` 1 , 2 , 3 , 4, 5, 6 ,`
But when I change the Num value , template will treat this value as a array.  For example, when I changed it to 18. the result as following:
`1 , 8 ,`

And I have tried add tag like  `type="number"` , still not working.
It's this a bug or I did something wrong? Please give me some advice.

Thanks a lot.

**Comment by LinusBorg** [comment]
1 Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.

2. If what you claim is true, this is a bug in Vue, not a problem with the documentation. In that case, please report it in the Vue repository (with a reproduction).

Thank you.

**Comment by superhos** [comment]
@LinusBorg Thanks for your information. I will follow your advice to modify my issue and provide an example on jsfiddle in this night.
And thanks for your attention again.

**Comment by LinusBorg** [comment]
Hint: if you use v-model on an input that is supposed to be a number, use `v-model.number="..."`

**Comment by superhos** [comment]
@LinusBorg  Yeah it works.  Thanks for your help.
