### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by entaku19890818** [vuejs/vuejs.org#734]
I am interested in the javascript framework and I want to use vue.js.
I attempted to set up referring to the official site.
There was a confusing point in the document.
https://vuejs.org/v2/guide/index.html

# Procedure

1. I installed vue.js by following the instructions on the ["Installation" page](https://vuejs.org/v2/guide/installation.html)

```
npm install vue
````

2. I attempted to move the installed vue.js in the procedure written on the  ["Introduction" page](https://vuejs.org/v2/guide/index.html#Getting-Started) .

3. However, since the ["Introduction" page](https://vuejs.org/v2/guide/index.html#Getting-Started) was a procedure to designate and use vue.js on the web,
I did not use vue.js that I dropped by installation.

# Expected behavior

I wanted it to be a procedure to use the installed vue.js.

# Possible remedy

Write code example of script tag when installing on "Introduction" page

What do you think?

**Comment by kazupon** [comment]
Thank you for your feedback! 
I think we should only need to improve about phrases at the introduction page, due to already mention about the installation as follows.

```
... Or you can simply create an .html file and include Vue with:

<script src="https://unpkg.com/vue/dist/vue.js"></script>
```

**Comment by chrisvfritz** [comment]
As @kazupon mentioned, we _do_ mention how to include Vue the way you're hoping on the introduction and installation pages (it even appears in a separate section, before the separate instructions to use via NPM). I haven't encountered anyone having this particular problem before, so I'm going to close for now, but am happy to reopen if this appears to be a recurring problem with multiple people.
