### ISSUE TITLE
Contributing Guide Link broken on production site.

### ISSUE THREAD

**Issue by CollinRea** [vuejs/vuejs.org#736]
[Link](http://rc.vuejs.org/guide/join.html)

> Contribute Code
>As with any project, there are rules to contributing. To ensure that we can help you or accept your pull request as quickly as possible, please read [the contributing guide](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md).

the contributing guide takes you to:
https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md
instead of:
https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md

However the code is correct in the source code:

`As with any project, there are rules to contributing. To ensure that we can help you or accept your pull request as quickly as possible, please read [the contributing guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md).`

**Comment by chrisvfritz** [comment]
Ah, you're looking at the old in-progress docs for the release candidate. The up-to-date version of the page is at (notice no `rc` subdomain):

> https://vuejs.org/v2/guide/join.html

@yyx990803 I'm thinking we should probably redirect `rc.vuejs.org` to `vuejs.org`.

**Comment by yyx990803** [comment]
I added redirect but it may take a while to take effect. Hopefully the rc links will die off soon...
