### ISSUE TITLE
hello-world JSFiddle sample doesn't work with guide instructions

### ISSUE THREAD

**Issue by jonbri** [vuejs/vuejs.org#737]
At the very beginning of the [guide](https://vuejs.org/v2/guide/) it links to a hello-world example on [JSFiddle](https://jsfiddle.net/chrisvfritz/50wL7mdz/) with the text:

> The easiest way to try out Vue.js is using the JSFiddle Hello World example. Feel free to open it in another tab and follow along as we go through some basic examples. Or, you can simply create an .html file and include Vue with...

So, I took that wording to mean I could continue on with the guide using the provided sample in the JSFiddle environment, and not necessarily needing to create my own `.html` file just yet.

Then, in the next section it says:

> Just open up your browser’s JavaScript console and set app.message to a different value. You should see the rendered example above update accordingly.

But, when I do that nothing happens, which was confusing.

I suppose the reason it didn't work is that JSFiddle will sandbox the sample code, so "app" won't be accessible from the browser console.

Perhaps either the JSFiddle or the wording of the guide could be made more clear? I know this is probably a very trivial thing, but I spent a good 15 minutes or so confused...

**Comment by chrisvfritz** [comment]
Ah, slight misunderstanding. When we say open up your browser's JavaScript console, we mean _in this current tab_ (the same pages as the docs). I'll update to make this more clear. 👍

**Comment by chrisvfritz** [comment]
I just updated the docs, with new wording bolded below:

> Just open your browser's JavaScript console __(right now, on this page)__ and set `app.message` to a different value.

Do you think that makes it more clear?

**Comment by jonbri** [comment]
Thanks for the quick response!

Yes, I see the updated wording, and it's much more clear now.
