### ISSUE TITLE
Spanish (CO) Translation "work-in-progress"

### ISSUE THREAD

**Issue by yeisonvargasf** [vuejs/vuejs.org#753]
I've just started the translation of https://vuejs.org

I created the organization and forked the vuejs.org repo.

Organization: [https://github.com/vuejs-co](https://github.com/vuejs-co)
Repo: [https://github.com/vuejs-co/vuejs.org](https://github.com/vuejs-co/vuejs.org)

Contributors are welcome!

Thank you.

**Comment by kazupon** [comment]
Welcome!

**Comment by PierBover** [comment]
I was just going to do this myself. I'll start contributing in my spare time.

**Comment by zeratulmdq** [comment]
@PierBover @yeisonvargasf there is already an ongoing spanish translation. Truth is, they started half a year ago and I saw no progress so I began doing it on my own. In two weeks I've already translated vue-router's docs and vuex's docs. The docs for Vue are a bit larger, but I have completed the entire _Advanced_ and _Migrating_ sections  but haven't pushed that yet. If you wanna do it on your own it's ok, but it'd be nicer to do it together.

**Comment by PierBover** [comment]
Hey @zeratulmdq please tell me the repo you are using and I'll contribute there.

**Comment by zeratulmdq** [comment]
@PierBover this is the organization: [es-vuejs](https://github.com/es-vuejs)

I've already created PRs for vue-router and vuex, but feel free to read through the translation and point out any errors you find. On monday I'll push all my work to the main Vue doc repo (I'm @ home right now), you can start from there if you want.

**Comment by PierBover** [comment]
Thanks.

Maybe I'm missing something but I don't see any `docs/es` folder in `vue-router` or `vuex`.

https://github.com/es-vuejs/vue-router/tree/dev/docs
https://github.com/es-vuejs/vuex/tree/dev/docs

**Comment by zeratulmdq** [comment]
PRs are pending. [vue-router](https://github.com/vuejs/vue-router/pull/1150) and [vuex](https://github.com/vuejs/vuex/pull/623). Both repos were forked in the organization above, as the main Vue repo.

**Comment by PierBover** [comment]
> but feel free to read through the translation and point out any errors you find

Where can I see those translations?

**Comment by zeratulmdq** [comment]
The PRs I pointed out earlier have all the file changes i've made. But if you prefer to read them locally, just clone the [organization's repos](https://github.com/es-vuejs).

**Comment by PierBover** [comment]
> But if you prefer to read them locally, just clone the organization's repos.

I'd like to fork but the repos on that organisation have no Spanish translations that I can see.

![image](https://cloud.githubusercontent.com/assets/226483/22859576/43af7ace-f0ae-11e6-93cb-8d857c56e6e9.png)

**Comment by PierBover** [comment]
I just saw from your PRs that you are working on a different branch. D'oh.

**Comment by yeisonvargasf** [comment]
@zeratulmdq @PierBover I'll contribute on es-vuejs, let's do this together. :+1:

**Comment by zeratulmdq** [comment]
I'll be making "nightly builds" with the progress. You'll see the [ongoing translation here](https://es-vuejs.github.io/vuejs.org/). Guide, examples and the site structure are already translated, but **it's not production ready** it has to be revised yet. I'm starting API tomorrow.

**Comment by chrisvfritz** [comment]
Closing this in favor of the more recently active #1004.
