### ISSUE TITLE
Hexo structure

### ISSUE THREAD

**Issue by zeratulmdq** [vuejs/vuejs.org#761]
Hi there:

I'm almost finishing the spanish translation and I came across a tiny problem when trying to deploy. Most of the structure under the theme folder is not prepared to be used with GitHub pages directly. Let's say i have the following **_config.yml** configuration:

>url: https://zeratulmdq.github.com
root: /v/

Once you render:

```
...
<a href="https://jsfiddle.net/" target="_blank">
  <img src="/images/jsfiddle.png">
</a>
...
```

The image link will be broken because it'll point to: 

> https://zeratulmdq.github.com/images/jsfiddle.png

Shoudn't you use the [url_for](https://hexo.io/docs/helpers.html#url-for) helper function? If you change the above to: 

```
...
<a href="https://jsfiddle.net/" target="_blank">
  <img src="<%- url_for("/images/jsfiddle.png") %>">
</a>
...
```

It'll render the right link for both github personal pages and custom domain names. I can create a PR changing every link but maybe there's a reason behind this (and I'm no hexo expert BTW).

Thanks in advance.

**Comment by chrisvfritz** [comment]
This sounds good to me. I'm also not a hexo expert either and I actually didn't know about the `url_for` helper function. 😅

**Comment by zeratulmdq** [comment]
PR #774
