### ISSUE TITLE
a little mistake about the directive demo

### ISSUE THREAD

**Issue by syaka-yin** [vuejs/vuejs.org#763]
Maybe i find a little mistake when i reading the section about [directive](https://vuejs.org/v2/guide/custom-directive.html)

I make a screenshot like below
![image](https://cloud.githubusercontent.com/assets/4370991/23006844/491e9e6a-f43f-11e6-8248-9b15842603f2.png)

The value of expression `binding.arg` is not "hello" but "foo"

**Comment by chrisvfritz** [comment]
This should be fixed now! Thanks for reporting it. 😄
