### ISSUE TITLE
Tree table by vue.js

### ISSUE THREAD

**Issue by linhluud3v** [vuejs/vuejs.org#775]
I want to build treetable by vue.js, i have idea merge treeview and grid component but i don't know how to do it. Can you help me. it show look like this URL http://webix.com/widget/treetable/
Thanks you very much!

**Comment by morigs** [comment]
Hi @linhluud3v 
This is repository of vuejs.org site
May be you wanted to create an issue in repository of [Vue](https://github.com/vuejs/vue)?

**Comment by linhluud3v** [comment]
Dear @morigs 
Sorry about my question, i will ask some people at Vue's community. Do you know good community?  can you let me know!

**Comment by morigs** [comment]
@linhluud3v I think you should open issue [here](https://github.com/vuejs/vue/issues) or create new topic on [official forum](https://forum.vuejs.org)
I hope I understood you correctly. 😉

**Comment by simplesmiler** [comment]
A good place to ask for something you want to exist is [vue-requests](https://github.com/vuejs/vue-requests). And if you want guidance and/or help, a good place for that is [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). Unlike @morigs said, the issue list of main repo is not a good place for neither.
