### ISSUE TITLE
Comparison to Avalon.js

### ISSUE THREAD

**Issue by ibufu** [vuejs/vuejs.org#776]
avalon

**Comment by chrisvfritz** [comment]
Are you referring to [this project](https://github.com/RubyLouvre/avalon)?

**Comment by ibufu** [comment]
@chrisvfritz yes, of course :)

**Comment by chrisvfritz** [comment]
Seeing as this project only seems to have grown popular in China, I think I'm going to close this for now - at least for the English version of the docs. The maintainers of [the Mandarin version](https://github.com/vuejs/cn.vuejs.org/issues/new) might find it appropriate to include a comparison then, so you're welcome to open a new issue there.
