### ISSUE TITLE
Special key filter presets require quotes

### ISSUE THREAD

**Issue by dpass** [vuejs/vuejs.org#78]
The docs (http://vuejs.org/guide/events.html#The_Special_key_Filter) say you can specify a key filter like this:
```
<input v-on="keyup:submit | key enter">`
```
However, as per the filter syntax change in v0.12.0 (https://github.com/yyx990803/vue/releases/tag/0.12.0) the key specifier must be surrounded in quotes like this:
```
<input v-on="keyup:submit | key 'enter'">
```
The docs should be changed to reflect this necessity

**Comment by yyx990803** [comment]
Thanks for catching this!
