### ISSUE TITLE
Event Handling bug

### ISSUE THREAD

**Issue by FatimahSanni** [vuejs/vuejs.org#782]
:keyup.tab doesn't work. The other modifiers work fine except the tab

**Comment by LinusBorg** [comment]
1. this is the website repository. you are looking for github.com/vuejs/vue
2. You have to provide a reproduction for us so we can follow exactly what you did to get your error.

**Comment by chrisvfritz** [comment]
Yes, as @LinusBorg said, please open an issue on the repository for the core library (vuejs/vue).
