### ISSUE TITLE
Grid Example - show sort arrows only if sorted

### ISSUE THREAD

**Issue by wilga** [vuejs/vuejs.org#783]
Sort arrows in the example grid show whether or not the column is sorted.

Please add `v-show="sortKey == key"` to the `span` of the component template like this:

`<span class="arrow" :class="sortOrders[key] > 0 ? 'asc' : 'dsc'" v-show="sortKey == key">`

Here is a fiddle with the update:
https://jsfiddle.net/wilga/myeu0sL3/

**Comment by wilga** [comment]
Another suggestion, please set the initial sortOrders to minus one:
`set sortOrders[key] = -1`

That way the first click of sort is in ascending order, the way westerners think in english.

**Comment by phanan** [comment]
I'm closing this in an effort to clean up the issue list. If you think this is worth considering, please open a PR. Cheers!
