### ISSUE TITLE
Tables don't scroll horizontally when they're too big for the screen

### ISSUE THREAD

**Issue by jacobmischka** [vuejs/vuejs.org#785]
![c5nxjnivaaix_dr](https://cloud.githubusercontent.com/assets/3939997/23352589/c3db18e4-fc8d-11e6-85e4-4888ed0326fc.jpg)

Related tweet: https://twitter.com/jacobmischka/status/835936216088526850

**Comment by ruskakimov** [comment]
`div#main` has an `overflow-x: hidden` on it
The issue can be solved by adding the following styles to the tables:
```css
    display: block;
    max-width: 100%;
    overflow-x: scroll;
```
but I am not sure if overriding the display property is a good idea. The other way I can think of is adding a wrapper with the above properties to each table.

**Comment by ruskakimov** [comment]
Setting:
```css
table td,
table th {
    word-break: break-word;
}
````
would fit the entire table to the available width. But the result is not very pretty:
![image](https://cloud.githubusercontent.com/assets/5536948/23455818/0024e1e8-feac-11e6-9570-1c4d516afad9.png)

**Comment by kazupon** [comment]
Close

**Comment by jacobmischka** [comment]
Interestingly the rightmost border on the table doesn't display when scrolled all the way right, but this is much better!
