### ISSUE TITLE
Add "is" to list of special attributes in API docs.

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vuejs.org#804]
The "is" attribute, used for/with dynamic components, is currently missing in the list of special attributes.

It's documented indirectly in the Guide's section about "Dynamic components", and in the API docs about `<component>`, but I think that can be easy to miss if somebody is looking for it when he/she finds something like `<tbody :is="whatever">` in some code and want to look it up.

**Comment by chrisvfritz** [comment]
Done!
