### ISSUE TITLE
The live compilation demo of render function is unselectable

### ISSUE THREAD

**Issue by CodinCat** [vuejs/vuejs.org#821]
Hi, please see:  
https://vuejs.org/v2/guide/render-function.html#Template-Compilation

I noticed the demo here is unselectable, because the `user-select: none`. Is it intended? 

I wrote a small template and want to copy the snippet from the compiled render function. It's a little bit inconvenient. Even if this is intended, anyone can just open devtools and remove the `user-select` style, so I would say adding this style is unnecessary.

thanks

**Comment by chrisvfritz** [comment]
@CodinCat One reason we have `user-select: none` on the demo results is because when copying a chunk of text, it's usually not desired to also copy the contents of a demo. I just made an exception for this one though.
