### ISSUE TITLE
Make 'createElement' more discoverable in the documentation

### ISSUE THREAD

**Issue by StachuDotNet** [vuejs/vuejs.org#824]
Greetings,

I recently had a scenario in which this:
```
var vm = new Vue({
    el: document.getElementById("app"),
    render: createElement =>
        createElement(app, {
            props: {
                viewMode: FinancialPlanViewMode.Advisor
            }
        })
});
```

was the solution.

There seems to be little documentation of this 'createElement' bit in 'render' when creating a new Vue instance. I think I eventually found some sample around this on StackOverflow on somewhere, but I would have loved to find something here.

Any thoughts on what would make the most sense to make this more discoverable? Namely, which page?

**Comment by simplesmiler** [comment]
Well, if you know that you need to write a `render`, you would probably check the [docs on render function](https://vuejs.org/v2/guide/render-function.html), and the first example of render function contains the `createElement` argument.

What was your path to discover the `render` and `createElement`?

**Comment by StachuDotNet** [comment]
I guess the confusion, on my part, was assuming 'render' was somehow
different between a component and a full vue instantiation.

**Comment by chrisvfritz** [comment]
The page on the template syntax now links to render function near the beginning and I think it's made more clear that wherever a template can be used, a render function could be used instead, so closing this for now.
