### ISSUE TITLE
Guide and API translations

### ISSUE THREAD

**Issue by flyingP0tat0** [vuejs/vuejs.org#829]
I only see translations for router and vuex (in their repos). Is there any possibility to get a system working to also make translations of the guides and API description possible? Would be great, I'd like to contribute by translating some of this stuff.

**Comment by kazupon** [comment]
You can fork this repository, and can translation. 😉 

The German translation project is already here, and currently I seem it is WIP.
https://github.com/vuejs/vuejs.org/issues/260

You should ask the people of this German translation project.

**Comment by flyingP0tat0** [comment]
What you referenced is a dutch translation. I set up a german translation organization and began to translate little parts.

**Comment by kazupon** [comment]
sorry, I mistaken.  🙇 

I hope that the translation succeeds :)

**Comment by flyingP0tat0** [comment]
That's what I hope aswell!
