### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by flyingP0tat0** [vuejs/vuejs.org#832]
Organization: [vuejs-de](https://github.com/vuejs-de)
Repository: [vuejs-de/de.vuejs.org](https://github.com/vuejs-de/de.vuejs.org)

- [ ] Essentials
  - [ ] Guide
    - [ ] Introduction
    - [ ] The Vue Instance
    - [ ] Template Syntax
    - [ ] Computed Properties and Watchers
    - [ ] Class and Style Bindings
    - [ ] Conditional Rendering
    - [ ] List Rendering
    - [ ] Event Handling
    - [ ] Form Input Bindings
    - [ ] Components

**Comment by flyingP0tat0** [comment]
#829

**Comment by LinusBorg** [comment]
Greetings, fellow German!

When you are done, I'm happy to review.

**Comment by kristinruben** [comment]
Would love to help with this! Let me know.

**Comment by flyingP0tat0** [comment]
Well, you could just clone the repo at vuejs-de/de.vuejs.org and start translating.
