### ISSUE TITLE
Description of ref behavior with v-for is inconsistent

### ISSUE THREAD

**Issue by jamesref** [vuejs/vuejs.org#843]
Hello,
the description of the behavior of `ref` with `v-for` in the Guide is different than the description in the API docs. The API docs seem with correspond to the actual behavior of Vue 2.0 as the reference is an array - not an object.

**Guide**
https://vuejs.org/v2/guide/components.html#Child-Component-Refs
> When ref is used together with v-for, the ref you get will be an array **or an object** containing the child components mirroring the data source.

**API docs**
https://vuejs.org/v2/api/#ref

> When used on elements/components with v-for, the registered reference will be an Array containing DOM nodes or component instances.

**Comment by LinusBorg** [comment]
Thanks!
