### ISSUE TITLE
Broken examples - mixed content

### ISSUE THREAD

**Issue by greenify** [vuejs/vuejs.org#85]
Hey I was just digging through your examples and you might be interesting that I the vue.min.js isn't loaded. Do you have a CDN with SSL where you can link it to?

"Mixed Content: The page at 'https://fiddle.jshell.net/yyx990803/wy2qf6yx/show/light/' was loaded over HTTPS, but requested an insecure script 'http://vuejs.org/js/vue.min.js'. This request has been blocked; the content must be served over HTTPS."

**Comment by yyx990803** [comment]
Fixed, they now load from cdnjs based on the protocol you are using.
