### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by chadidi** [vuejs/vuejs.org#863]
We've just started the translation of `vuejs.org`

https://github.com/LaravelArab (Laravel Framework Arab Community)
https://github.com/LaravelArab/vuejs.org (VueJs Repo)
We'll keep you up-to-date when the project has more updates.

Thank you. (contributors are always welcome).
contact : @chadidi

**Comment by kazupon** [comment]
Welcome!

**Comment by phanan** [comment]
I'm closing this issue as an effort to tidy our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
