### ISSUE TITLE
Vue.JS Component Marketplace

### ISSUE THREAD

**Issue by mrinc** [vuejs/vuejs.org#868]
Hey guys,

I haven't seen much of guaranteed place where all shared components are hosted.

Is there one hosted somewhere?

If not, would it be something you guys would see value in?

Thanks

**Comment by LinusBorg** [comment]
Well, a "guaranteed" marketplace would be hard to do since there's no guaranteed way to find all plublic vue components.

But so far, we have github.com/vuejs/awesome-vue which was recently overhauled and should include only quality contributions.

We also work on a curated list of "top of class" components/libraries, but are not ready to go public yet. All free and OS, of course.

What would you expect from such a public "marketplace".

**Comment by mrinc** [comment]
Hey,

So basically what I was visualizing was something similar to npmjs.org but shifted a little.

So you would publish your components to the so called store.
You would have verified or 'starred' components - checked out and guaranteed by you guys like you said above.

So the cool part now:
There are 2 ways to use a component.
1 - You install the component 'package' into your project and its literally exactly like an npm package.
2 - You reference the component via a js link (CDN like when you reference vue.min.js)

So of course you'd be able to lock a version or use the latest - or have it like nuget and allow all minors but not a major change.


It would be awesomely easy to add components to websites and also being cdn, you'd get quicker response time globally for your site.

Comments?

**Comment by simplesmiler** [comment]
@mrinc why no unpkg? E.g. `<script src="https://unpkg.com/portal-vue@^1.0.0-beta"></script>`

**Comment by chrisvfritz** [comment]
@mrinc I recommend checking out the new [Vue Curated](https://curated.vuejs.org/) page, developed by the wonderful and talented @Akryum. New resources can be [suggested here](https://github.com/vuejs/vue-curated/blob/master/PACKAGES.md) with a PR, but as I understand, this will only include what you referred to as "verified"/"starred" components and other vue-related libraries.

**Comment by mrinc** [comment]
@chrisvfritz @Akryum 
It doesn't work :D - I'll wait for it to be finalized, but it seems to be what I was talking about.
Basically, it'll give you a url to be able to embed a component into your app.
