### ISSUE TITLE
vuejs/vue and this repository links to unencrypted vuejs.org site

### ISSUE THREAD

**Issue by Serkan-devel** [vuejs/vuejs.org#869]
You probably have https implemented but not linked

**Comment by LinusBorg** [comment]
Good catch

**Comment by Serkan-devel** [comment]
It might not take too long to fix the descriptions, just add an 's' to every protocol there.

**Comment by LinusBorg** [comment]
Obviously. I personally just don't have the privileges for those repositories.

**Comment by ShashankaNataraj** [comment]
@LinusBorg Are PR's encouraged for this?

**Comment by chrisvfritz** [comment]
It's probably easier to just force SSL. I believe @yyx990803 has access to do this.

**Comment by chrisvfritz** [comment]
SSL appears to be forced now, so closing.
