### ISSUE TITLE
Bootstrap Tooltips fail when using v-repeat with AJAX data

### ISSUE THREAD

**Issue by hotrodfl** [vuejs/vuejs.org#87]
I'm having trouble with tooltips for elements inside a v-repeat loop, whenever the loop is based on data received by an AJAX callback.

Here is a jsfiddle with the issue.
http://jsfiddle.net/hotrod/526e6qwv/

Any idea on what am I doing wrong here?
Thank you.

**Comment by azamat-sharapov** [comment]
http://jsfiddle.net/526e6qwv/1/

http://vuejs.org/guide/best-practices.html#Understanding_Async_Updates
https://github.com/vuejs/Discussion
https://gitter.im/yyx990803/vue

**Comment by hotrodfl** [comment]
Thank you @azamat-sharapov
