### ISSUE TITLE
Is “Init Events” in lifecycle diagram incorrect? 

### ISSUE THREAD

**Issue by dotneet** [vuejs/vuejs.org#871]
Moved from this topic: https://forum.vuejs.org/t/is-init-events-in-lifecycle-diagram-incorrect/9421

In vue guide "Init Events" in lifecycle diagram is described after 'beforeCreate' hook.

https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks

But Vue seems to call 'beforeCreate' hook after "Init Events".

"vue/src/core/instance/init.js".

```javascript
initLifecycle(vm)
initEvents(vm)
initRender(vm)
callHook(vm, 'beforeCreate')
initInjections(vm) // resolve injections before data/props
initState(vm)
initProvide(vm) // resolve provide after data/props
callHook(vm, 'created')
```

Actually, $emit() is available in beforeCreate().

https://jsfiddle.net/z114vzyk/

Is this a bug of Vue runtime or mistake of diagram?

**Comment by LinusBorg** [comment]
It seems that this is indeed an inaccuracy. Will take some work to correct the image though.

Thanks for the report!

**Comment by thandonguocmo2020** [comment]
init event in a component. 

beforeCreate(){
          this.$on('name_event',function(params1,params2){
              console.log(params1);
              console.log(params2);
          });
        },
created(){
            this.$emit('name_event','event 1', 'event 2');
},

**Comment by chrisvfritz** [comment]
@yyx990803 I've assigned you, as I believe you made the diagram in Illustrator.
