### ISSUE TITLE
Vue Style Guide

### ISSUE THREAD

**Issue by dwiyatci** [vuejs/vuejs.org#875]
### What problem does this feature solve?
Providing an opinionated style guide and/or best practices for syntax, conventions, and structuring Vue applications.

### What does the proposed API look like?
Should be something similar to:
- https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md
- https://angular.io/docs/ts/latest/guide/style-guide.html

**Comment by cannap** [comment]
Here is something https://pablohpsilva.github.io/vuejs-component-style-guide

**Comment by chrisvfritz** [comment]
I can definitely see the value in something like this, but for nearly every rule, I find occasions to break them. I also find it useful to use different conventions in different kinds of projects and with different kinds of teams. So I _personally_ am not that interested in creating/supporting a resource like this.

However, the cookbook (which I will finally have more time to _really_ develop this summer!) I do think it would be good to address many concerns in a more exploratory format, e.g. weighing pros and cons of various architectures around a specific problem.

**Comment by chrisvfritz** [comment]
OK, I've _finally_ been convinced to start work on an official Vue style guide. 😄  Many of these rules will even be [enforceable through `eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue/issues/10), thanks to hard work from members of the community!

**Comment by sdras** [comment]
This is in! 🎉 Hooray

**Comment by dwiyatci** [comment]
❤️
