### ISSUE TITLE
manual insertions with instance methods samples needed

### ISSUE THREAD

**Issue by KingMario** [vuejs/vuejs.org#879]
For V1, http://v1.vuejs.org/guide/components.html#activate-Hook
> Note the activate hook is only respected during dynamic component swapping or the initial render for static components - it does not affect manual insertions with instance methods.

What does *manual insertions with instance methods* mean? Any samples?

**Comment by chrisvfritz** [comment]
I just [clarified this sentence](https://github.com/vuejs/vuejs.org/commit/fc0ea53d17a0fa04e3d6e434309ce6e75e154e86) and it will be pushed live soon.
