### ISSUE TITLE
the default value of the 'replace' option should be true in Chinese API Doc

### ISSUE THREAD

**Issue by panteng** [vuejs/vuejs.org#88]
Please see this.
https://github.com/yyx990803/vue/issues/1051#issuecomment-121574359

The Chinese version of vue.js documention should be updated to v0.12.7. Now it's still v0.11.5.

**Comment by yyx990803** [comment]
Translation is in progress, but slow because 1. I don't have time; 2. It's all done by volunteers.
If you have time please contribute to the translation: https://github.com/Jinjiang/vuejs.org/tree/0.12-zh

**Comment by panteng** [comment]
Ok, I will consider helping the translation. Thx for your reply.
