### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by lukaszkups** [vuejs/vuejs.org#884]
Hello, I'm starting to translate the website to Polish. I'll update the status once I've push something to forked repo.

**Comment by kazupon** [comment]
welcome! 🎉

**Comment by sdras** [comment]
Hey there! It's been about six months so I'm going to consider this lost in translation. Haha get it? Ok aaannnyways, please feel free to reopen this at any time if you'd like to start up the effort again, or let us know your progress. Thank you!
