### ISSUE TITLE
forum.vuejs.org down the the US West for a few days

### ISSUE THREAD

**Issue by aldencolerain** [vuejs/vuejs.org#886]
Hate to put this on github, but not sure how else to communicate it to the maintainers.  The forum has been down for a few days in US West.  Chatted with some people in gitter and seems to be up in some locations and down in others, but checked downforjustme and similar sites and it said it was down as well.

![vue forum](https://cloud.githubusercontent.com/assets/16270737/25408270/ade8501e-29ca-11e7-9171-5dd1c8f76e00.png)
![vue forum down](https://cloud.githubusercontent.com/assets/16270737/25408333/de11ae66-29ca-11e7-94a2-e48d3296755f.png)

**Comment by kazupon** [comment]
Thank you for your reporting!
`forum.vuejs.org` is live now.
