### ISSUE TITLE
Indonesian (ID, Bahasa Indonesia) Translation

### ISSUE THREAD

**Issue by kokizzu** [vuejs/vuejs.org#891]
work started an hour ago, currently only `guide/index.md` translated.. 

repo: http://github.com/kokizzu/id.vuejs.org

**Comment by kazupon** [comment]
welcome 🎉

**Comment by dikiaap** [comment]
I'll help this though.
I think we already have documentation​ for Indonesian with our domain .id and not really active yet.
[vuejs-id/docs](https://github.com/vuejs-id/docs)

But if we need the official domain, like, id.vuejs.org that would be great idea. 

cc: @mul14 from @vuejs-id org

**Comment by sdras** [comment]
Hi All, it's been about 6 months. Has there been any progress here? If not, I'll close this out. Thanks!

**Comment by kokizzu** [comment]
I'm no longer using vue, you can remove the listing to my partial translation.. '__')

**Comment by sdras** [comment]
OK thank you for the update! Much appreciated.

**Comment by kokizzu** [comment]
My friend will continue the translation: https://github.com/jefrydco/id.vuejs.org
