### ISSUE TITLE
Filter 'source' link is outdated

### ISSUE THREAD

**Issue by rpkilby** [vuejs/vuejs.org#894]
From vuejs/vue#5569, the `source` link for filters is oudated, and returns no results.

https://github.com/search?utf8=%E2%9C%93&q=repo%3Avuejs%2Fvue+extension%3Ajs+%22Vue.filter%22&type=Code

**Comment by chrisvfritz** [comment]
Just pushed out a fix for this. For future reference though, it wasn't a case of the source link being "outdated", but rather the generated source search not being helpful in this case.
