### ISSUE TITLE
Donations via liberapay

### ISSUE THREAD

**Issue by oliverpool** [vuejs/vuejs.org#900]
Hi,

There is a nice (french) open-source platform for recurring micro-donations: [Liberapay.com](https://liberapay.com/).
It allows you to create a team and the members of the team decide how they split the donations (one can also give directly to one person).

They eat there own food, since they don't get money on the transactions (the fees are for the Mango costs), but also have a page to receive donations https://liberapay.com/Liberapay/.

I created a (small) pledge for the vuejs team: https://liberapay.com/on/github/vuejs/.
To receive it, you only have to signup and link your github account (to prove that you belong to the vuejs team :-).

All the best and thanks again for this great software !

PS: there are a bit different from Patreon, as mentioned in their [FAQ](https://liberapay.com/about/faq)

**Comment by chrisvfritz** [comment]
Thank you for your commitment to supporting Open Source! 😄 This is something @yyx990803 will decide, though I believe he's working reduced hours the next couple weeks, so it may take a little time to get his thoughts.

**Comment by sdras** [comment]
We're on both [Patreon](https://www.patreon.com/evanyou) and [Open Collective](https://opencollective.com/vuejs) now, my feeling is that another platform might be confusing for people. Would you mind applying the donation to Open Collective? That would consolidate efforts for us. Thank you!

Closing this out, but if I'm mistaken @chrisvfritz or @yyx990803 please feel free to reopen.
