### ISSUE TITLE
Typo in comparisons guide

### ISSUE THREAD

**Issue by joshlbaker** [vuejs/vuejs.org#911]
In the "Performance" subsection, comparing Vue to React, it seems like there might be a typo: `Both React and Vue offer comparable performance in most commonly seen use cases, with Vue usually slightly head due to its lighter-weight Virtual DOM implementation` Seems like head should be ahead? Not a huge deal but figured I'd let you know! Cheers.

**Comment by chrisvfritz** [comment]
Looks like someone just submitted a PR to fix this! Thanks. 😄
