### ISSUE TITLE
Inaccuracy in comparisons guide (Ember)

### ISSUE THREAD

**Issue by miguelcobain** [vuejs/vuejs.org#912]
In https://vuejs.org/v2/guide/comparison.html we can read:

> Performance-wise, Vue outperforms Ember by a fair margin, even after the latest Glimmer engine update in Ember 2.0.

This is no longer the case with Glimmer 2 which landed in Ember 2.10. I'm not sure what the figures are now, but I'm pretty sure that "outperforms Ember by a fair margin" is an inaccuracy.

**Comment by chrisvfritz** [comment]
It's still true, unfortunately. According to [this 3rd-party benchmark](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html), Ember is still more than 40% slower overall and some operations, such as element creation, are even twice as slow. Startup time is even more than 400% slower. The Glimmer update has improved things, but not significantly enough and Vue has also continued to improve.

**Comment by chrisvfritz** [comment]
I just added a link to that benchmark in the ember section of the comparisons page.

**Comment by miguelcobain** [comment]
Thanks.

**Comment by chrisvfritz** [comment]
@miguelcobain Thanks for helping us keep the docs up-to-date! The JavaScript world moves fast, so we do sometimes miss things - and this page is especially important to keep an eye on, to avoid accidentally starting a flame war!

**Comment by miguelcobain** [comment]
@chrisvfritz no problem! :)
I'm pretty sure this sentence will become inaccurate when glimmer.js components land in ember. But we're not there yet.
I'll try to remember to revisit this issue when that time comes. Thanks!
