### ISSUE TITLE
Greek Translation In Progress

### ISSUE THREAD

**Issue by vzuburlis** [vuejs/vuejs.org#925]
Hello, made a translation repo  in Greek
Starting from Guide

**Comment by chrisvfritz** [comment]
Sounds great! 😄  If you have any questions about organizing the translation work, @gbezyuk is a great resource.

**Comment by phanan** [comment]
I'm closing this issue as an effort to tidy our issue list. Feel free to open another if you think it's a mistake (and sorry for that 🙂).
