### ISSUE TITLE
Looking for 0.10 docs?

### ISSUE THREAD

**Issue by Nirazul** [vuejs/vuejs.org#93]
http://legacy.vuejs.org/guide/ links to itself when clicking the link to the previous version.
It's debatable if the 1.10 docs are still necessary or useful at this point of time (I doubt it). But it's a bit misleading to leave the link on the page, even if it's legacy ^^

For further versions however, I'd prefer an absolute naming convention. The meaning changes for the term `legacy`, `0.11` is unambiguous.

You could do something like bootstrap:
- http://vuejs.org/0.11/docs
- http://vuejs.org/0.12/docs

**Comment by yyx990803** [comment]
yeah, it's probably necessary in the long term, but for now I've just removed the 0.10 link.
