### ISSUE TITLE
Clarity in the docs if Vue 2.*.* is following semver strictly.

### ISSUE THREAD

**Issue by daymos** [vuejs/vuejs.org#930]
Looking at the issues on github, it seems it might, but I couldn't find a specific statement in the docs that Vue 2.. is strictly semver, and therefore offer full backward compatibility. Have I missed it or is not stated anywhere ?

**Comment by chrisvfritz** [comment]
No, I don't believe we do state it, but Vue does try to follow semver in all its projects - at least for documented features and behavior. For undocumented behavior or exposed internals, we describe changes in release notes.

What would you think about a note on the installation page?

**Comment by daymos** [comment]
I just need to know if its semver before updating to a new version. I dont mind where its stated, but it should be stated somewere.

**Comment by mbraint** [comment]
Maybe add labels for new api properties. Small green image with text about version. And show this label in navigation menu.

**Comment by chrisvfritz** [comment]
I like that idea too. Will try to add it this week, but a PR is also welcome if someone wants to jump on it immediately. We note when items were introduced in the guide.
