### ISSUE TITLE
Unit test example needs a dom element

### ISSUE THREAD

**Issue by Cortrah** [vuejs/vuejs.org#931]
Hi Folk,

The unit test example here doesn't work out of the box with either the browserify or webpack templates.
https://vuejs.org/v2/guide/unit-testing.html#Writing-Testable-Components

The container needs to be passed in with the propsData or they are not used
function getRenderedText (Component, propsData) {
    const container = document.createElement('div');
    const Ctor = Vue.extend(Component);
    const vm = new Ctor({
        el: container,
        propsData: propsData
    });
    return vm.$el.textContent
}

if you want a repository to look at it easily it is [here](https://github.com/Cortrah/test-monkey)

Thanks for all you are doing. It's making being a js developer more pleasant than it was by far.

**Comment by chrisvfritz** [comment]
Thanks for reporting this! I'll go through all the examples soon and do a little revamp.

**Comment by sarahdayan** [comment]
@sdras Would it be okay to refactor this example using Vue Test Utils? Since this is the official Vue testing library, and it has new maintainers, this would probably be a better experience for users to have an example that matches what they'll learn afterward on the Vue Test Utils documentation.
