### ISSUE TITLE
Specifically mention illegality of circular references

### ISSUE THREAD

**Issue by bencooper222** [vuejs/vuejs.org#938]
I recently tried to store a Leaflet.js marker in the data object of a Vue component. It did not work. I'm fairly certain this is because a Leaflet marker recursively stores itself for draggability purposes (if I'm wrong, sorry for wasting your time). 

As seen below, the Vue 0.12 docs specifically call this out as illegal behavior. The new docs don't but kind of imply it. I would like to include a specific warning in the docs against circular references.
![image](https://user-images.githubusercontent.com/9143563/26841958-c9aa228a-4ab0-11e7-89c2-fe0d5473561c.png)

Additionally, it'd be nice if an error was thrown to console when this behavior occurs. Should I open an issue in the main Vue repository for this?

**Comment by chrisvfritz** [comment]
Hmm, I'm not noticing any problems with circular references [in the data object](https://jsfiddle.net/z4drvft8/) or [_of_ the data object itself](https://jsfiddle.net/y6xz42d7/), so I think you're probably experiencing some other issue. I recommend creating a minimal reproduction of the behavior you're seeing in JSFiddle, which should help you identify the source of the problem. If it ends up being a bug in Vue, you can create an issue on the main repo, including that minimal reproduction.
