### ISSUE TITLE
Update "watch" component option description

### ISSUE THREAD

**Issue by Darkside73** [vuejs/vuejs.org#94]
1. At current time we also have alternative syntax (with options object: https://github.com/yyx990803/vue/commit/47c52d6bfc59bd17a0f0f1ebc8c77730f9716685).
2. Please add an example describing option usage for object case:
```javascript
data: {
  some: {property: 1}
},
watch: {
  'some.property': 'handler'
}
```

**Comment by yyx990803** [comment]
It's already in the doc: http://localhost:4000/api/options.html#watch
