### ISSUE TITLE
Content Distribution with slots

### ISSUE THREAD

**Issue by CalamarBicefalo** [vuejs/vuejs.org#940]
Up to this point we found vue docs extremely clear. But we cannot understand what this statement means under the section [content distribution with slots](https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots):

> The <app> component does not know what content may be present inside its mount target. It is decided by whatever parent component that is using <app>.

I tried to reason about this with my colleague but we didn't get to a sensible conclusion. We would love to pull request a clarification, but unfortunately we don't really know what it is supposed to communicate.

**Comment by chrisvfritz** [comment]
Thanks for reporting this! 🙂  Would this be clearer?

> The `<app>` component does not know what content it will receive. It is decided by the component using `<app>`.

**Comment by CalamarBicefalo** [comment]
That sounds crystal clear to me!

Thanks for taking that into consideration. ;)
