### ISSUE TITLE
Explicitly Create index.html File

### ISSUE THREAD

**Issue by alexfinnarn** [vuejs/vuejs.org#941]
In the https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/index.md#declarative-rendering example, I only saw `{{message}}` until I added a document ready function wrapper...something like 

```
document.addEventListener('DOMContentLoaded', function(){
  var app = new Vue({
    el: '#app',
    data: {
      message: 'Hello Vue!'
    }
  });
}, false);
```

I'm not sure if I'm just doing something wrong, but whatever the case, more notes need to be added for my failure or the code example needs to check if the DOM is fully loaded.

**Comment by alexfinnarn** [comment]
I basically just told them explicitly what .html file to make and what they could copy/paste into that to follow along.

**Comment by chrisvfritz** [comment]
As stated in #943, I made a compromise with a download link for `index.html`. I think that should resolve the problem. 🙂
