### ISSUE TITLE
Add .github/ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by alexfinnarn** [vuejs/vuejs.org#942]
Where I work, we use https://github.com/CuBoulder/express/blob/dev/.github/ISSUE_TEMPLATE.md, and that has helped make our issues much more complete and standardized.

...and that is in a team where we are in the same location most of the time, lol, and still write crappy tickets. So, for an open source project with the potential for many "It's broken" issues, I think adding an issue template would be a good idea.

**Comment by chrisvfritz** [comment]
We do use issue templates for many other Vue repos and I've thought about adding one for this one as well, but despite the fact that we get some poor descriptions occasionally, it's not actually too often. I'd also rather get someone's poorly described feedback that I can follow up on and ask questions about, than risk losing potentially valuable feedback with too much bureaucracy.

Does that make sense?

**Comment by alexsales** [comment]
Just my 2 cents ..
If the members (i.e. powers that be) comments on an issue with some finality, should probably close it. Might also want to close dormant issues and where a response isn't heard from the OP or others in several months.

**Comment by alexfinnarn** [comment]
Agreed. 

We often times delete all of the template's sections when submitting issues anyway so requiring an issue template for people to fill out could de-motivate them from submitting an issue.
