### ISSUE TITLE
High CPU usage on "Transition Effects" page

### ISSUE THREAD

**Issue by fenivana** [vuejs/vuejs.org#945]
![image](https://user-images.githubusercontent.com/11750532/26941887-b128a764-4cb2-11e7-9384-02a2fba5ed4e.png)

![image](https://user-images.githubusercontent.com/11750532/26942228-d3962e6a-4cb3-11e7-941c-d05630781dd8.png)

It seems Velocity is running forever in the background.

**Comment by chrisvfritz** [comment]
Investigating. 👍
