### ISSUE TITLE
Replace Gitter chat with Discord server

### ISSUE THREAD

**Issue by egoist** [vuejs/vuejs.org#959]
Gitter is horrible for a large group of people, there're 10k users on gitter.im/vuejs/vue and they can easily get lost in the replies for different topics from different people.

btw, the search and mobile/desktop app etc of Gitter are not as powerful as Discord's either.

Our goal for [Vue Land](https://vue-land.js.org) is to have the whole Vue community fit in a single place. Would love to hear your thoughts! 

/cc @yyx990803 @vuejs/collaborators

**Comment by sylvainpolletvillard** [comment]
If you want to have the whole Vue community on your Discord, please add channels for other languages.  This is something we have currently with Gitter:
https://gitter.im/vuejs-jp/discussion
https://gitter.im/vuejs-fr/vue
https://gitter.im/vuejs-ru/Discussion

**Comment by egoist** [comment]
@sylvainpolletvillard For language-specific chat you can still use whichever you prefer, like gitter. This is more like a replacement for the main one.

**Comment by jerakode** [comment]
Discord is much, much better Gitter.

**Comment by yyx990803** [comment]
I just tried Discord and it is indeed a much more polished product. I agree that we should switch, but it needs some coordination. Let's do this after VueConf :)

**Comment by gustojs** [comment]
Discord server grows rapidly - over 500 users, with a peak of 95 online users so far. As a regular Gitter answer-person I'd more than welcome an official switch to Vue-Land.

**Comment by chrisvfritz** [comment]
@gustojs It's in the works. 🙂  We won't be shutting down the Gitter (at least for now), in case some people really prefer it or want to refer to past messages, but we'll no longer be linking to it or promoting it.

**Comment by gustojs** [comment]
Thanks, good to hear. :)

I know for a fact there is few people there who prefer Gitter, with main reason being an IRC bridge setup on Gitter channel (which is easier to do as there's only one channel on Gitter but multiple channels on Discord). 

But as to "refer to past messages", the Gitter search feature is so terrible that sadly looking up past messages is not an option, it brings up totally random messages.

**Comment by acidjazz** [comment]
+1 for discord from gitter, much better web client, desktop client, and mobile client.

the vue channel is the only reason I still use gitter

**Comment by nickmessing** [comment]
@acidjazz in gitter suggested adding link to vue-land in gitter topic, do you think this is a valid idea?

**Comment by acidjazz** [comment]
@nickmessing absolutely that would help cover all the existing people in the channel as well

**Comment by chrisvfritz** [comment]
OK, I've now:

- [x] Aliased chat.vuejs.org to the new Discourse server
- [x] Replaced references to Gitter on vuejs.org
- [x] Opened a PR to replace references to Gitter in Vue's README
- [x] Updated the Gitter description to encourage people to move to Discourse

Have I missed anything?

**Comment by egoist** [comment]
@chrisvfritz Looks good to me

**Comment by chrisvfritz** [comment]
Excellent! @egoist Thanks for creating Vue Land. 🎉  Everyone seems much happier with it. 😄

**Comment by ericbehughes** [comment]
is there a channel on discord for vuejs?
i used it for my work and its way better than gitter

**Comment by LinusBorg** [comment]
See chat.vuejs.org

**Comment by posva** [comment]
Locking just in case, so people can easily find the link at the end of this issue (https://chat.vuejs.org)
