### ISSUE TITLE
Single-file component syntax is not covered well enough in docs in multiple places.

### ISSUE THREAD

**Issue by bmarkovic** [vuejs/vuejs.org#962]
Most advanced topics are covered with imperative syntax and significant ambiguity or mental friction exists when one has to translate it to the declarative i.e. `.vue` syntax. I have had numerous problems with this previously which I have solved by trial-and-error. 

But now I need to import and use a directive available as a npm module [(this)](https://github.com/Akryum/v-tooltip) which was written with this kind of use in mind:

```javascript
Vue.directive('tooltip', VTooltip)
```

And I haven't got the faintest idea how to use it inside a single-file component constructor options, because the only documented way is populating `directives` property of configuration object with an array of directive classes i.e.:

```javascript
  directives: [ VTooltip ]
```

Since the declaratvie, `.vue` style is the preffered style, why does documentation not reflect that better?

As I remember or run into more uncovered examples I will add to this issue.

**Comment by LinusBorg** [comment]
I am under the impression that you think about this too hard/complicated.

SFCs work 100% extactly like "normal" components, the only difference is the file format with the `<template>` tags and so forth - the whole options object looks just the same. For Components, we have *extensive* documentation [here](https://vuejs.org/v2/guide/components.html), but are, of course, always open for suggestions on which sections to improve).

In the example about the directive, my impression is that your problem isn'T so much with Single-File-components as it is with custom directives and the different ways they can be registered, which is covered [here](https://vuejs.org/v2/guide/custom-directive.html) and/or with Vue Plugins and/or ES6 modules. You seem to wonder hwo to install a custom directive in a Single-File-Component... The answer is: like in a regular component. Using your example about v-tooltip:
`
```javascript
// my-component.vue
import { VTooltip } from 'v-tooltip'

export default {
  directives: {
    tooltip: VTooltip,
  }
}

// or for a "normal" component:
Vue.component('my-component', {
  directives: {
    tooltip: VTooltip,
  }
}
```

Could you explain a bit more precisely what is unclear with regards to how to add a directive to a component?

**Comment by chrisvfritz** [comment]
Closing this for now, as it may just have been the case of overthinking a problem. @bmarkovic If you think of something (e.g. a piece of missing information that could have prevented the confusion), please do let us know and I'll reopen.

**Comment by bmarkovic** [comment]
The documentation has changed significantly from the time I reported this. As you can see from my example, there were places where the syntax has been stated in documentation as:

```javascript
    components: [  Pass, Me, An, Array, Of, Objects ]
```

whereas what really works is

```javascript
   components: { Pass: Me, A: Hashtable, Of, Objects }
```

for both directives and components.

This has been rectified in the docs.

**Comment by chrisvfritz** [comment]
@bmarkovic Great to hear it's been rectified! Sorry about the initial confusion. 😅
