### ISSUE TITLE
Could we put vuejs logo on our website?

### ISSUE THREAD

**Issue by sotayamashita** [vuejs/vuejs.org#968]
We would like to put your logo on an "Active Projects". Could we do that?
Thanks in advance 🙇

cc:/ @kazupon @yyx990803

**Comment by chrisvfritz** [comment]
@sotayamashita Judging from precedent, I think as long as you're using the logo to reference Vue (e.g. the way blogs might use the logo when mentioning Vue), then you're fine. If the logo were used outside the context of Vue, or implied ownership of / endorsement from Vue, then it might be problematic. Does that make sense?

**Comment by sotayamashita** [comment]
@chrisvfritz I got it. I appreciate your kind reply. We will share how Vue.js logo looks like on our website later. I close it
