### ISSUE TITLE
use className in v-bind:class=[...]  is wrong

### ISSUE THREAD

**Issue by JaneRui** [vuejs/vuejs.org#969]
error has been found in page: **https://cn.vuejs.org/v2/guide/class-and-style.html**
![image](https://user-images.githubusercontent.com/16890543/27376042-8fe8cf5c-56a3-11e7-9c32-f07dfef83f0c.png)

just as cut above: 
When we use array in v-bind:class, item in array **should be variable of className, not the className directly**.

so right answer is:
**&lt;div v-bind:class="[{ activeClass : isActive }, errorClass]"&gt;**
it equals to:
**&lt;div v-bind:class="[isActive ? activeClass : '', errorClass]"&gt;**

**Comment by codexp** [comment]
it actually equals to:
```html
<div v-bind:class="[ (isActive ? 'activeClass' : ''), errorClass]">
```
the first one is handled as string, the second one is a property of the vue instance.

see JSFiddle: https://jsfiddle.net/uptzn9v0/

**Comment by javoski** [comment]
Seems you have misunderstood object syntax class binding, the object syntax will take object keys as class value.
In this demo, the value of variable `activeCalss` is just `'active'`, so:
```html
<div v-bind:class="[{ active: isActive }, errorClass]">
```
when `isActive` equals `true`, template above will render:
```html
<div class="active text-danger">
```
it's actually equals to:
```html
<div v-bind:class="[isActive ? activeClass : '', errorClass]">
```
If change it to:
```html
<div v-bind:class="[{ activeClass : isActive }, errorClass]">
```
will get:
```html
<div class="activeClass text-danger">
```
that's not what we want.

**Comment by pawr** [comment]
The confusion is with the data object defined in the #Array Syntax section:
 `data: {
    activeClass: 'active',
    errorClass: 'text-danger'
}`

The first example works as expected: 
`<div v-bind:class="[activeClass, errorClass]"></div>`

However, the examples thereafter using `isActive`, will throw the following: 
>Property or method "isActive" is not defined on the instance but referenced during render.

Add `isActive: true` to the data object and that will eliminate the errors: 
 `data: {
    isActive: true,
    activeClass: 'active',
    errorClass: 'text-danger'
}`
