### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by andrewshevtsov** [vuejs/vuejs.org#972]
Наконец, хотя Vue и не так глубо**к**о интегрирован с TypeScript как Angular, **он** предоставляет

**Comment by chrisvfritz** [comment]
This doesn't seem like a question - perhaps even a mistake, so closing.

**Comment by andrewshevtsov** [comment]
Sorry, I just followed the instructions on what to do if I found inaccuracy in describing the comparison of frameworks.
I just started to study it.

**Comment by chrisvfritz** [comment]
Ah, I just noticed the bolded word, which indicates you may have found a typo in the Russian documentation. I think you're looking for [this repo](https://github.com/translation-gang/ru.vuejs.org) then.
