### ISSUE TITLE
Clarify that prop default() cannot call a method or access a computed property

### ISSUE THREAD

**Issue by richardtallent** [vuejs/vuejs.org#984]
See issue:
https://github.com/vuejs/vue/issues/6013

Documentation for `props` does not mention that computed properties and methods are not accessible when the prop `default()` is called. While it makes reasonable sense that this should be limited, the documentation should at least mention this limitation.

I'll take a stab at creating some new language for this and submit the PR.

**Comment by chrisvfritz** [comment]
Just merged this! Thanks. 🙂
