### ISSUE TITLE
How to make?

### ISSUE THREAD

**Issue by simonsharry** [vuejs/vuejs.org#989]
Hello,

I'm trying to build an offline version of Vue.js documentation using the project `Makefile`, but cannot.

Is the `Makefile` broken by any chance...? as there's no `../vue` directory relative to `Makefile`. If I `mkdir ../vue` myself, then the `git checkout ...` etc commands fail because obviously the `.git` directory doesn't exist in `../vue`.

Is the entire Vue.js documentation available as a pdf or as an html bundle for offline reading?

Regards,
/HS

**Comment by znck** [comment]
Clone `vue` repository in `../vue`.
```
git clone https://github.com/vuejs/vue vuejs/vue
git clone https://github.com/vuejs/vuejs.org vuejs/vuejs.org
```
